== Chapter VII

After my service on Long island, I had great sweetness upon my spirit for some time,
which sometimes caused my heart to sing for joy;
and yet I rejoiced in a trembling frame of spirit,
and had the true sense of what is written in the holy Scriptures, where it is said,
"`Serve the Lord with fear,`" I take it to be filial fear,
"`and rejoice with trembling,`" for fear of losing that
precious sense of the love of God which is in Christ.

On the 20th of the twelfth month, the first-day of the week, I was at Abington meeting,
in which the love of Christ was manifested to us, in the opening of his saying,
"`If I be lifted up, I will draw all men unto me,`" The next day I was at Germantown,
at the burial of a son of Dennis Conrad, at which also was our friend Abigail Bowles.
On the sixth-day following,
I went to the general meeting of ministers and elders at Burlington,
where I again met with our said friend and several others.
The first-day meeting was large;
and on second-day was the quarterly meeting for the county;
and on third-day was their youths`' meeting, where many weighty truths were delivered.
On fourth-day we were at a meeting at Springfield; the house was pretty much thronged,
and Friends were exhorted thankfully to commemorate
the mercies and favours of the Almighty to them,
and desired to enlarge their meeting houses as their number increased;
for in those parts there was such an openness in
the hearts of the people and increase of their number,
that Friends had already agreed on building two meeting
houses between Crosswicks and Burlington;
their zeal and unanimity therein, were worthy of commendation.

Fifth-day being the week-day meeting at Burlington,
Friends of the town desired I would stay at it.
I thought we had just before had several good opportunities,
and my own inclination seemed to lead to my family;
but Friends being desirous of my staying, I did so, and we had a good meeting.
After it, a solid Friend said,
"`he thought we had the best wine at last;`" and indeed the love of God, through Christ,
is so sweet to his people, that the last often seems the best,
when it is only a renewed visitation of the same love to his children.
I went home rejoicing that I was in some measure accounted
worthy to serve so good and so gracious a Master.

On the 6th day of the first month, being the first of the week,
I was at the morning and afternoon meetings in Philadelphia,
wherein those who call themselves freethinkers,
were exhorted to be careful of drinking too freely,
lest they might justly be called free-drinkers; for many times such,
when they drink too freely of strong liquor,
think and speak too freely their own corrupt notions to the dishonour of God,
and to the scandal of religion in general.

In this month I went to the Jerseys,
and was at three large meetings in company with Abigail Bowles,
in which our said friend had good service, to the comfort of Friends,
convincing of gainsayers, and confirming the weak, and the people were glad of our visit.

The 15th day of this month I was at Burlington,
at the burial of my good friend and old acquaintance, Abraham Bickley,
at whose funeral were great numbers of people, he being well beloved of his neighbours.
Christ`'s raising Lazarus out of the grave, and his tenderness and weeping there,
were spoken of, in order to stir people up to a tender, religious exercise of mind,
which is much lacking among many of the professors of his holy name,
who have too little sense of that which should bring true tenderness over their minds,
being more in earth than heaven; so that they are dry and barren,
as to the things of God.
The meeting ended to satisfaction, with supplications to the Almighty.

A few days after I was at our general spring meeting in Philadelphia, which was large;
where our friends Robert Jordan and Abigail Bowles, had good service.

This week I was at four very large meetings at Philadelphia, Frankford and Abington,
much to my satisfaction, though I had no vocal service therein;
yet my heart was broken into tenderness and tears, under several weighty,
solid testimonies, that wore borne by living ministers,
qualified to preach the gospel in the demonstration of the spirit, and with power.

The 26th of the first month, 1726, I went to Germantown meeting, which was large,
and I was opened therein to speak of the vision of the prophet Ezekiel,
of the holy waters, which proceeded from under the threshold of the sanctuary,
which the angel measuring, they grew deeper and deeper,
until they became a river to swim in.
Which shows the work of grace, conversion, and regeneration;
and that these holy waters of which the soul must drink and be washed, and baptized in,
are spiritual and supernatural,
and therefore not to be measured by the spirit and will of man, in his natural state,
according to the prophet Isaiah.
Man, before he can swim therein,
must be stripped of all his self-righteousness and artificial religion,
though as splendid and beautiful as a gallant ship, or galley with oars,
in which respect it is agreeable to the state of men swimming in elementary water,
where the most skillful have sometimes lost their lives, for lack of being unclothed.
Those who had not yet attained much experience,
were advised not to go out of their depth, but to wait in patience and humility,
to enjoy the medicinal virtue of the trees growing by the side of this river,
whose fruit is for food, and its leaves for medicine.
The people of this meeting were generally Germans,
several of whom stayed in the house after it was over, and were broken into tenderness,
in a sense of the presence and love of God unto us,
for which I was also humbly thankful and bowed in spirit.

I was at the third-day weekly meeting in Philadelphia, which was but small,
considering the large number of those professing to be of our Society in this city;
those present were closely and tenderly exhorted to be zealous for good works,
and against bad works; not respecting the person of any man.
The abominations committed by some under our profession in this city and province,
call for humiliation;
and as the promise of God`'s favour was to those who mourned with
sighs and cries for the abominations among his people formerly,
so now, as many as are under the same concern, may hope for preservation and salvation,
if he should in like manner visit us, as at this time he does some of our neighbours;
there being a great sickness and mortality in some of the adjacent places.

In the second month I visited the meetings of Friends at Haverford, Newtown, Radnor,
and Merion; which meetings consist chiefly of ancient Britons, who are a religious,
industrious, and increasing people; among whom my service was, as they expressed,
to our mutual satisfaction.
After my return home, I went to visit Friends at the falls of Delaware,
and was at a large meeting; in their new meetinghouse.
After a satisfactory meeting at Frankford,
on the fifth-day of the same week I went with Ennion Williams to his son`'s marriage;
next day he and several other Friends accompanied me to Woodbury creek, and had a good,
open meeting, and that night went to James Lord`'s, and next morning towards Salem,
and lodged at Isaac Sharp`'s; where I was informed of a great mortality at Cohansey.
The 24th of the second month was the general meeting at Salem,
which was a large gathering of people of different persuasions,
from many parts of the country,
where the doctrine of the gospel was preached in great love to the people,
which they heard with solid attention.
From Salem I went to Alloway`'s creek and Cohansey, and had meetings there.
I was informed that more than seventy persons had lately died here of a malignant distemper,
though it seemed to abate, none dying while we were there.
At Cohansey the meeting was large and solid, though but few of our Society reside there;
and they were earnestly admonished to a proper disposition of mind,
to fit them either for life or death,
and reminded of the regard of the Almighty to such as live in his fear,
who will have peace in their death, and their change will be glorious,
when they are taken out of this life; but with the wicked it is not so.

From Cohansey I went through the wilderness over Maurice`'s river,
accompanied by James Daniel, through a miry, boggy way,
in which we saw no house for about forty miles, except, at the ferry,
and that night we got to Richard Townsend`'s, at Cape May, where we were kindly received.
Next day we had a meeting at Rebecca Garrison`'s,
and the day after a pretty large one at Richard Townsend`'s,
and then went down to the Cape, and had a meeting at John Page`'s,
and next day another at Aaron Leaming`'s;
several expressed their satisfaction with those meetings.
I lodged two nights at Jacob Spicer`'s, my wife`'s brother.

From Cape May we travelled along the sea coast to Great Egg Harbour,
had another meeting much larger than the first, at Rebecca Garrison`'s,
and here I was much concerned to promote the settlement of a monthly meeting,
for the well ordering of the affairs of our Society.

We swam our horses over Egg Harbour river, and went over ourselves in canoes,
and afterwards had a meeting at Richard Summers`',
which was as large as could be expected,
considering the people live at such a distance from each other.

The next meeting we had at John Scull`'s;
on first-day we had a large one at Peter White`'s; on second-day at Japhet Leeds`';
and then we went five miles through a marsh to Little Egg Harbour river,
and had a meeting in their meetinghouse on the fourth-day of the week,
and 11th day of the month, which was larger by the addition of the owners, masters,
and mariners, of two sloops from New York, who, hearing of the meeting, came to it.
Next day we had another meeting at the same place,
and lodged at Jarvis Faro`'s. After these two meetings I left Egg Harbour,
accompanied by several Friends,
and travelled about forty miles before we came to any house.
In the evening we reached a Friend`'s house, where we were kindly entertained,
and next morning got to Burlington, and so home, where I found all well,
and was thankful therefor to the Almighty.

In this journey I travelled about three hundred miles, had twenty-one meetings,
and was from home about three weeks.

In the third month I stayed at and about home, visiting the meetings at Philadelphia,
Germantown, Abington, and Frankford.

In the fourth month I left my family, and went back in the woods as far as Oley.
I was from home nine days, travelled about one hundred and fifty miles,
and had six meetings at Oley, Perkiomen, and many other places,
chiefly in barns and open places, there being large companies of people,
and few meeting houses yet built in those parts of the country.
In this journey I suffered much through the heat.
The first meeting was at the iron works settled a
little beyond a place called Mount Misery.
I was concerned for those people,
having heard of their rude doings before I left my habitation;
and although some were rude, others behaved themselves soberly,
and expressed their thankfulness for that visitation,
as I do for the opportunity I had of clearing myself to them.

On my return homewards, I crossed Schuylkill, and went to Samuel Nutt`'s iron works,
where I had a large, quiet, solid meeting;
and the next day called to see my old friend David Meredith,
who being about eighty-nine years of age,
I thought it probable I might not have another opportunity of seeing.
He met me with gladness, and told me it was their meeting day; so I stayed,
and was much comforted and tendered by the power of Christ;
after which I came home that night.

On the next first-day after my return I went to Philadelphia,
and then to a yearly meeting in Chester county, held at Goshen;
though the season was wet, this was a large, good meeting;
at which there were three young men,
who had lately been called to the work of the ministry,
whom I was glad to hear declare the truth in the
power and simplicity of the gospel of Christ,
being of the mind of Moses, when he said, in answer to Joshua,
"`Would God that all the Lord`'s people were prophets,
and that the Lord would put of his spirit upon them.`"
After this meeting I went to Springfield, and the next day returned home.

On the 22nd of the fourth month I went to the marriage of John Lee`'s daughter,
at Springfield, in Chester county.
I was concerned to speak mostly to the young people,
advising them to seek the Lord in that great affair of marriage,
that they be careful on whom they set their affections,
and not to draw out one another`'s minds, if they did not intend an honourable marriage;
reminding them of the ill tendency of courting several at a time,
or allowing several to court at once,
and that they be chaste and true in their proceedings,
duly regarding the advice of the apostle,
"`Be not unequally yoked;`" for all such marriages are unequal,
when those who marry are of different principles of religion.
The meeting ended with tender supplication for preservation through whatever exercises,
further troubles or trials, temptations or afflictions, we might meet with in the world,
that so we might end well at last,
and live forever to praise and glorify God and the Lamb, who, through the holy,
eternal Spirit, is worthy forever.

On the receipt of the last letter from my dear father, which I some time since mentioned,
I was apprehensive it might be his last, which it proved to be;
for the next letter from my dear brother gave me intelligence of his death,
which I received the 25th of the fourth month this year.
The news of my dear father`'s decease took such hold of my mind,
though I daily expected it, that for some time I was hardly sociable.
Oh! how have I been sometimes comforted in his loving and tender
epistles! at the receipt of which I have cried to the Lord,
that if it pleased him,
I might have a double portion of the spirit which he gave to my father.
But now I must never hear more from him in this world;
yet in this I have some inward comfort,
that I hope we shall meet where we shall never part.
Here follows a part of my affectionate brother`'s
account of my father`'s death and burial.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Edmonton, 25th of the First month, 1726.

[.salutation]
Dear brother,

This comes with the sorrowful account of our dear father`'s decease,
who departed this life the 7th instant, after having been indisposed about a fortnight.
I have herewith sent a particular account of some remarkable passages,
and his last expressions in his sickness; that part relating to his convincement,
he desired should be committed to writing, which I have done, and sent it to you.

I was with him several times in his last illness,
and most of the last two days of his life, as you may perceive by the contents.
Our worthy father was honourably buried on the 11th instant,
being carried from his own house to the meetinghouse at Horsleydown,
accompanied by his relations,
where was a large meeting of as many people as the meetinghouse could well contain,
and many testimonies were borne to the innocent, exemplary life, integrity,
and honest zeal of our dear father, so concurrent and unanimous,
that I have hardly known any such occasion more remarkable:
he was accompanied from there to the grave very solemnly,
and there in like manner interred,
where a further testimony was given to his honest life and conduct,
and lively zeal for the holy truth, whereof he made profession.

Dear brother, though it be a sorrowful occasion of writing,
yet herein we may be comforted in consideration that our
father went to his grave in peace in a good old age:
he had his understanding and memory to the last.
I believe, as I have sometimes said,
that he embraced death as joyfully as ever he did any happy accident of his life.
I remember one passage of his cheerful resignation;
finding him fine and cheery when I came to see him, a week before his decease,
and he showing me how well he could walk about the room, and would have gone out of it,
though he was very bad the day before, I said, "`Father,
I hope you will get over this illness;`" but he answered me pretty quick and loud, "`No,
but I don`'t though.`" It is not long since he was at my house,
and was cheerful and well, but spoke as if he thought it would be the last time.
My wife said, "`Father, you may live some years;`" but he replied,
"`Is it not better for me to die, and go to Christ?`" So dear brother,
with dear love to you, my sister, and your dear children and our relations,
I conclude with earnest desires for your health and welfare,

[.signed-section-closing]
Your affectionate brother,

[.signed-section-signature]
George Chalkley.

[.blurb]
=== An Account of My Father`'s Convincement, and of His Last Sickness and Dying Words.

My father was born of religious parents at Kempton, near Hitching, in Hertfordshire,
the 1st of the ninth month, 1642; his father`'s name was Thomas Chalkley, by trade,
a dealer in meal; by profession, of the church of England, and zealous in his way,
as was also his wife.

They had four sons and three daughters, John, George, Thomas, and Robert; Elizabeth,
Sarah, and Mary.
My father being the third son,
was convinced very young at a meeting by Enfiel-Chace-Side, near Winchmore-hill,
through the powerful ministry of William Brend,
who was an eminent minister in the Lord`'s hand in that day,
and had been a great sufferer for his testimony in New England.
He was preaching, as I heard my father several times say, upon the words of the preacher,
"`Rejoice, O young man, in your youth,
and let your heart cheer you in the days of your youth,
and walk in the ways of your heart, and in the sight of your eyes;
but know that for all these things God will bring you into judgment.`"
Upon this subject he spoke so home to my father`'s state and condition,
that he was convinced,
and two others of his companions were reached and affected
with the testimony of Christ`'s truth and gospel.
My father and two young men had been walking in the fields,
having religious conversation together, and were providentially directed to the meeting,
by observing some Friends going to it, whom they followed there:
one of his companions was Samuel Hodges, who lived and died a faithful Friend,
at whose house in succeeding times, a meeting was settled, and is there continued,
and a meetinghouse built at this day at Mims, in Hertfordshire.

My father was the first of the family who received
the testimony of truth as it is in Jesus,
after which his father and mother were convinced, and all his brothers and sisters,
who lived and died honest Friends; except one who died young,
continuing in the church of England persuasion.
Soon after the convincement of my father and his two companions aforesaid,
they met with a trial of their faith and patience;
for being taken at a religious meeting of Friends,
they were all three committed to the new prison in Whitechapel,
where having continued prisoners for some time,
the magistrates observing their Christian courage, boldness, and innocency,
and being touched with tenderness towards them, considering their youth, discharged them.

My father about the twenty-fifth year of his age, married my mother,
a virtuous young woman, who was the widow of Nathaniel Harding,
a Friend who died under the sentence of banishment for his profession of Christ;
the above account I had from my father`'s own mouth;
what follows fell within my own observation.

My dear father met with great exercises and disappointments in his early days; he,
dealing in his father`'s business, sold meal to some who broke in his debt,
which brought him low in the world,
in which low state he was an eminent example of patience, resignation, and industry,
labouring with his hands for the support of his family,
and conscientiously answering all his engagements; so that it may be justly said of him,
he was careful that he might owe nothing to any man but love.
He was very constant in keeping to meetings, being a good example therein,
though in very hot times of persecution;
for when Friends were sorely and severely persecuted
on account of keeping their religious meetings,
and the prisons filled with them through the nation, and their goods taken away,
and much spoil and havoc made about the years 1680 to 1684,
my father constantly attended meetings, and never missed, as I remember, when well.
He was sometimes concerned to speak by way of exhortation
to Friends in their public meetings,
when they were kept out of their meeting houses, by the then powers,
to stand faithful to the truth and testifying of the solid comfort
and satisfaction those had who truly waited on the Lord,
which the faithful enjoyed,
notwithstanding their deep and many sufferings for Christ`'s sake and his gospel;
and it pleased the Lord to preserve him by his divine providence,
that he did not suffer imprisonment,
though the wicked informers were very busy in that time of severe persecution.
I may further add, that when my father was about sixty years of age,
he had a concern to visit Friends in the north of England,
and some other parts of the nation;
and in the seventy-fifth year of his age he travelled to Chester, and from there,
in company with James Bates, a public Friend of Virginia, went over for Ireland;
in all which services he had good satisfaction, and was well received of Friends:
many other journeys and travels he performed, not here noted;
but this journey into another nation at seventy-five years of age,
shows that age had not quenched his love and zeal for his Lord`'s work and service.

Our father`'s old age was attended with very great exercises:
about his seventy-seventh year, as he was assisting his men in the dusk of the evening,
he missed his footing, fell down and broke his leg; and soon after his leg was well,
he met with another accident by a fall, which disabled him,
and made him lame to his death, never recovering the hurt, which was after this manner;
he was sitting in a chair by his door, on a plank, which not being set fast, it fell,
and he, to save himself from the stroke of the plank, fell with his hip on the stones,
and got hurt exceedingly.
Notwithstanding this, he was remarkable for his activity; he would walk, though so aged,
and also lame, as far as the work house, Devonshire house, and Bull and Mouth meetings,
two or three miles from home.
The last bad accident that befell him was about three weeks before his death, when,
being walking in the timber yard, a single plank which stood against a pile, fell down,
and striking him on his side, threw him down.
He complained not much of the blow till about a week after,
when he was taken with a violent pain in his side,
on the place where he received the stroke, and when his cough took him,
with which he was often troubled, the pain was very great.
Through the means used for his relief, he received some ease,
the pain of his side abated, and the cough went off; but a violent flux followed,
and brought him very low, so that it was thought he could not continue long;
but he revived.

He continued all the time of his illness in a patient and resigned frame of mind;
on first-day, in the afternoon, he took his bed, being the 6th of the first month,
and in the evening, after the afternoon meeting,
which was the first-day before his death, several Friends came to visit him,
who finding him very weak, after a little stay went to take their leave of him,
whom he desired to sit down, and after some time of silence,
he broke forth in declaration in an intelligible and lively manner, to this effect,
saying, "`We have no continuing city here, but seek one to come, which has foundations,
whose builder and maker is God: Friends,
may we all labour to be prepared for our last and great change,
that when this earthly tabernacle shall be dissolved,
we may have a habitation with the Lord, a building not made with hands,
eternal in the heavens.
And that it might be thus, the Lord has showed you, Oh! man, what is good, namely:
To do justly, love mercy, and walk humbly with your God.
I do not expect but that this will be the last night I shall have in this world,
and I desire these things may be remembered, as the words of a dying man;
Oh! that we may labour to be clothed upon with our house that is from heaven,
so that when the finishing hour comes, we may have nothing to do but to die.`"

About one or two o`'clock the next morning, he began to change, and desired to see me;
I came to him and found him very sensible, but expected his end quickly to approach;
he saying he was waiting for his change.
About the fourth hour in the morning he prayed fervently after this manner: "`Lord,
now let your servant depart in peace, for my eyes have seen your salvation,
which you have prepared before the face of all people.
You have given your Son, a light to enlighten the gentiles,
and to be the glory of your people Israel; and now,
Lord be with your people and servants, and preserve my near and dear relations,
and keep them from the snares and temptations of the enemy,
that in your truth they may fear your great name.`"

After a little time of silence he desired me to remember his dear love,
in the life of Christ Jesus, to my dear brother, Thomas Chalkley, in Pennsylvania,
and to all his old friends and acquaintance.
After some time he spoke cheerfully out aloud, so that all in the room might hear him,
"`I shall go off about five;`" his man said, "`Master, how do you know?`"
To which he answered, "`I do not know, but I believe it,`" About noon, the apothecary,
one of his neighbours, among whom he was well beloved, came to see him,
and asked him how he was?
Father answered, that for three or four hours in the night he thought he should have gone.
Why, said he, it will be no surprise to you, I hope.
No, no, said my father, very cheerfully.
He taking leave of father, said, the Lord be with you.
To whom he answered, and with you also.
The doctor having ordered him a cordial to drink, he drank it willingly, and then said,
I do not think to drink any more in this world;
but I hope I shall drink plentifully of the river of life.
Finding his strength fail, there being a cord at the bed`'s feet,
he raised himself up thereby as long as he had strength; when last lifted up,
he spoke very low and faultering, and said, now I am going, and about an hour after,
laying all the while without sigh or groan, departed this life, as in a slumber,
in sweet peace, just as the clock struck five,
in the enjoyment of that legacy which our Saviour left his followers;
"`My peace I leave with you,`" etc., leaving us, of the succeeding generation,
a good example to follow.
He died like a lamb, in the eighty-fourth year of his age,
the 7th day of the first month, 1725-6,

[.signed-section-signature]
George Chalkley.

--

To which account I shall add the following short testimony
concerning my dear and greatly beloved father,
George Chalkley:

[.embedded-content-document.testimony]
--

I have a great deal in my heart, more than I can write concerning my dear father`'s life,
it having been a remarkable life to me from my youth up.
His early care of me, and counsel to me, when I was too thoughtless and wild,
melts me into tears now in the remembrance of it;
and my tender mother was a partner with him in the same exercise,
and she died in like peace.
The last words I heard her speak were, I long to be dissolved.
And as to my tender father, I would record a little briefly in memory of him,
that he was a true and faithful servant of Christ, and a tender and affectionate husband,
I lived at home with my parents about twenty years:
their life was a life of peace and love,
and they were an excellent example to us their children.
Oh! may we follow them therein to the end!

He had a fatherly care for his children, in tender prayers for us,
and in good advice to us, and in giving us learning according to his ability,
and teaching us by his example, as well as precept, industry, humility,
and the true religion of our blessed Saviour, endeavouring to plant it in us betimes,
and to destroy the evil root of sin in us, while young.
I was his servant as well as his son, and I can truly say his service was delightful,
and his company pleasing and profitable to me;
and he was also beloved much by his other servants.
He was universally beloved by his neighbours,
and I do not remember any difference between him and them,
in the many years I lived with him; but all was peace and love.

He was very loving to his relations, and true to his friends,
and a hearty well wisher and lover of his king and country.

[.signed-section-signature]
Thomas Chalkley.

--

Our general meeting held at Frankford the 30th of fourth month, was large,
our friend William Pigot, from London, being there,
in the course of his visit to Friends in America, and had close work and good service.

In the fifth month, 1726, I visited the meetings of Friends at Philadelphia, Germantown,
Byberry and Frankford, and had very comfortable satisfaction.
My testimony was sometimes pretty sharp to transgressors,
and therefore some of them hate me, as the Jews did my great Master;
because I was concerned to testify, that their deeds were evil,
and to excite my friends to manifest a Christian zeal, by openly denying ungodly men,
while they continue in their ungodly works; but when they become truly penitent,
and reform their lives, the arms of Christ and his church, will be open to receive them.

Being under some melancholy thoughts, because some persons for whom I wished well,
and to whom I had been of service,
were so envious and malicious as to tell false stories of me, tending to defame me;
as I was riding to our meeting, it opened with satisfaction to my mind,
the more my enemies hate me, the more I will love, if that can be.
I had hearty desires to come up in the practice of this resolution;
and I then thought I should come up with them all,
for if a man loves and prays for his enemies, if they are gained,
he is instrumental to their good, and so has cause of rejoicing;
and if they are not gained, he heaps coals of fire upon their heads;
so that every true Christian, by keeping under the cross of Christ,
and in the practice of his doctrine, gets the better of his enemies.

In the beginning of the sixth month, I was at the burial of Robert Fletcher,
a worthy man, and one universally beloved by all sorts of people, as far as ever I heard.
There was a large meeting at his funeral,
wherein several testimonies suitable to the occasion were borne:
some of his last words were mentioned, which were,
that he had lived according to the measure of grace given him.
The doctrine of the resurrection was maintained according to the Scripture,
and the people were exhorted to prepare for their final change.
The death of this Friend was a loss to the country, to our Society,
and to his neighbours, as well as to his family and friends.

After meeting I travelled towards Uwchland, had a meeting there on first-day;
on second-day, one at Lewis Walker`'s,
and on third-day was at the general meeting at Haverford.
Friends were exhorted to dwell in the love of God, one towards another;
for if they lost their love they would lose their religion, their peace, and their God;
for "`God is love, and those that dwell in God, dwell in love.`"

My neighbour, Daniel Worthington, accompanied me in this rough travel,
some part of the way being hilly, and very stony and bushy, and the weather wet.
We had four meetings, and rode about fourscore miles;
and though I had travelled much in this province,
I had never been at some of those places before.
A few nights before I set out, I had a plain prospect of them in a dream,
as I saw them afterwards, which I thought somewhat remarkable.

The people inhabiting this province are now become numerous,
and make many settlements in the woods,
more than I have observed in my travels in any other of the British plantations;
and there has long been a desire in my mind that they might
prosper in the work of true and thorough reformation.
A godly fear and concern being upon me,
I have sometimes put them in mind of the state of this land,
when their fathers first came and settled in it;
and cautioned them against growing careless, and forgetting the Lord,
lest he should forsake them,
and turn their now "`fruitful fields into a barren wilderness,`" as this was so lately;
which it is easy with him to do, if he pleases, for the sins of the people.

After my return home, I visited Abington youths`' meeting,
and the meetings at Philadelphia and Chester.
At Chester I was concerned to direct the people to that power in themselves,
which is the life of religion,
and exhorted them to be careful not to rest in the best forms without it;
for if we had only the form of godliness, and had not the life and power of it,
it might be as reasonable for people to turn away from us,
as it was for our forefathers to turn away from other societies.

In the seventh month I was at our yearly meeting held at Burlington,
for the provinces of New Jersey and Pennsylvania, which was a very large meeting,
there being Friends from New England, Rhode Island, and Europe.

First-day morning I went to Evesham,
to the burial of our serviceable friend Jervice Stockdale; he being in good esteem,
there was much people.
The meeting was in a good, tender frame, and continued several hours,
in which several testimonies were delivered,
in order to stir up people to truth and righteousness, and godly living,
that they might die well.
I lodged the night before at Peter Fearon`'s,
and in the morning I was awaked out of my sleep, as it were by a voice,
expressing these words: "`He that lives and believes in me shall never die.`"
This I took to be the voice of Christ; I do not know that it was vocal,
but it was as plain as if it were.
From these expressions I had to observe to the people,
the happy state and privilege of those who live and believe in Christ,
and that such must not live in sin.

During the time of our yearly meeting,
some rude people came up the river in a small sloop, provided by them for that purpose,
and spent their time in drinking, carousing, and firing of guns,
to the grief and concern of Friends, who were religiously discharging their duty,
in serving and worshipping the Almighty.
It is observable,
that one of these disorderly persons had his hand shot off at that time,
and that the chief promoters and actors in this riotous
company were soon after cut off by death,
in the prime of their days.

After the general meeting was over, which ended well,
Friends, in the love of God, departed in peace for their several habitations,
praising and glorifying God.

In the beginning of the eighth month, having some business at Cape May,
I ferried over to Gloucester, and went the first night to James Lord`'s, lodged there,
got up before day, it being first-day morning, and rode near thirty miles to Salem,
where we had a good meeting, and so went to Alloway`'s creek, Cohansey,
and through a barren wilderness to Cape May, where we had one meeting,
and returned home by way of Egg Harbour; travelling upwards of two hundred miles.
At Cape May I was concerned to write a few lines concerning swearing, as follows:

[.embedded-content-document]
--

[.numbered-group]
====

[.numbered]
Christians ought not to swear in any case, for these reasons: _First,_ because Christ,
their Lord, forbade it; unto whom the angels in heaven must be subject, and doubtless,
so must mortal man, to whom he gave the precept.
We must and ought to be subject to Christ, who is Lord of lords, and King of kings,
and the Judge of quick and the dead:
to him all mortals must be accountable for their disobedience.
He says, in his sermon on the mount, "`I say unto you swear not at all:`" therefore,
how can Christians, or such who are his friends, swear, since he says also,
"`You are my friends, if you do whatsoever I command you;`" consequently,
those who disobey his commands must be his enemies.
To this command it is objected,
that Christ only spoke against common or profane swearing:
but this must needs be a great mistake, because Christ says, "`It was said in old time,
you shall perform unto the Lord your oaths,`" alluding to the law of Moses,
which oaths were solemn and religious;
therefore Christ did not only prohibit vain and profane swearing, but all swearing.
If we understand the word all, and what all signifies,
then all and any swearing whatsoever, is not lawful for a Christian,
according to Christ`'s law and command, which is positive to his followers.

[.numbered]
_Second;_ James, the holy apostle of Christ, our lawgiver and our king, says,
"`Above all things, my brethren, swear not, neither by heaven, neither by the earth,
neither by any other oath.`" Christ says,
"`Swear not at all;`" and James his disciple and apostle, says,
"`Swear not by any oath;`" therefore, if swearing on the Bible be an oath,
or is swearing at all, it is contrary to the express doctrine of Christ,
and his apostle James, as is plain from the above cited texts.

[.numbered]
_Third;_ the primitive Christians did not swear at all, in the first ages of Christianity.
Query, whether our modern swearing Christians are better than the primitive ones, who,
for Christ and conscience sake, could not swear at all, even before a magistrate,
though legally called?

[.numbered]
_Fourth;_ many Christians have suffered death, because for conscience sake,
they could not swear, and so break the command of Christ their Lord;
and do not our modern Christians trample upon their testimony and sufferings?
some of whom suffered death for not swearing before the heathen magistrates,
and some were martyred by the Papists;
judge then whether the persecuted or persecutors were in the right.

[.numbered]
_Fifth;_ many of our worthy friends and forefathers, since the former,
have suffered to death in jails, for not swearing,
when required by persecuting Protestants, because for Christ`'s sake and sayings,
as above, they could not swear at all:
and this is a testimony which our Society has constantly
borne ever since we have been a people,
for the reasons above, and more also, which, if there were occasion, might be given.

====

--

The 23rd of the eighth month I was at the morning meeting at Philadelphia,
on a first-day of the week, which was large,
and I was concerned therein to exhort Friends to labour to purge and cleanse
our Society of those under our profession who live in open profaneness,
and are riotous in their conducts.
I was at the Bank meetings in the afternoon, where we had a comfortable time:
and the next sixth-day of the week, I was at our monthly meeting,
where it was unanimously agreed,
in consideration of some late indecent conduct of
some persons pretending to be of our profession,
that a testimony from that meeting should go forth against such disorderly doings,
and unchristian practices; and that all such persons,
who were irregular in their conducts, be disowned to be of our community, until they,
by repentance, manifest their reformation; which was accordingly soon after published,
and read in our first-day morning meeting, and in our youths`' meeting.

About this time our governor issued a seasonable proclamation against drinking to excess,
gaming, swearing profanely, revelling, night walking, and disturbing the peace,
and other immoralities;
which afforded some satisfaction to sober and well inclined Friends and others:
yet there remained a great exercise and concern upon my mind, that some young people,
whose parents had been careful in training them up, were grown so wicked,
that by their extravagant conduct, they not only disturbed our religious meetings,
but likewise became obnoxious to the peaceable government we live under.

In the ninth month I was at meetings at Merion, Germantown, Fairhill, Abington,
and Philadelphia, in which were several marriages solemnized in a religious manner.
In the tenth month I went into the county of Salem, about my affairs:
it happened to be the time of the quarterly meeting for Salem and Gloucester counties;
but I did not know it, until I came to Salem, where Friends were glad to see me,
as I also was to see them;
there were some of us whose hearts were knit together as Jonathan`'s and David`'s,
the love of God being much shed abroad in our hearts at that meeting.
When it was over, and I had finished my business,
I could not be clear in my mind without having some meetings;
and though it was a sickly time,
and people died pretty much in those parts where we were going, James Lord and I,
in the love of Christ, visited the meetings at Alloway`'s creek, Cohansey, Pilesgrove,
Woodbury, Newton, and Haddonfield, having meetings every day in the week,
except the last, and sometimes riding nearly twenty miles after meeting,
the days being at the shortest, and the weather very cold; but the Lord was with us,
which made amends for all the bodily hardships we met with.

I got home well, but weary; and was joyfully received by my loving spouse, children,
and servants; and I was truly thankful to the Most High,
for his presence and goodness continued to me; so that,
though I perceived my bodily strength to decline quickly, my sight, hearing, and voice,
failing much, I have occasion to believe,
at times I was helped even beyond nature in the work of Christ, my dear Lord and Master.

The 27th of the tenth month, I heard the news of the death of my dear friend John Lee,
by one sent to desire my company at his burial; it affected me with sorrow,
he being an old acquaintance and friend of mine, with whom I had travelled many miles.
He was a living, serviceable minister of the gospel of Christ,
and instrumental to convince many of that principle
of divine light and truth which we profess.
I could not be at his burial, because of my indisposition,
and the unseasonableness of the weather;
yet I think it my duty to say this concerning him;
that our love and friendship were constant and entire unto the end,
having been acquainted about thirty-five years, as near as I can remember.

In the eleventh month, as I was meditating in my closet,
on the duty and beauty of that great virtue of temperance,
it appeared very bright to the view of my mind,
and the great benefit of it to those who loved and lived in it.
First, as to religion, it tends to keep the mind in an even temper,
which is a help to devotion, and the practice of religious duties.
Second, it is a great preservative to health and a good constitution.
Third, it is a blessing to posterity, in many considerations.
Whereas, intemperance destroys the health, stains the reputation, hurts posterity,
in respect to a healthy constitution of body and state, ruins many families,
brings to poverty and disgrace, and what is yet worst of all,
is a great hinderance to religion and the true fear of God,
and is a great scandal to any who make profession of the Christian religion.

In this month I accompanied William Pigot, who lately arrived from London,
on a religious visit to the meetings of Friends in America.
From Philadelphia we went to my house at Frankford, and from there to North Wales,
and had two large satisfactory meetings on the first-day;
next day were at the monthly meeting at Abington, third-day at Frankford,
and fourth-day at Germantown.
Fifth-day I went to Philadelphia week-day meeting,
and the said Friend to Abington general meeting,
and a few days after we met again at the quarterly
meeting of ministers and elders at Philadelphia.

The 8th of the twelfth month was our youths`' meeting at Frankford;
and many persons dying about this time,
I was concerned in the meeting to put Friends in mind of their mortality;
and that I had told Friends lately, at their meetings at Abington and Philadelphia,
that as I was riding from my house to Philadelphia, about a mile from the city,
I saw in the vision of life, the hand of the Lord stretched over the city and province,
with a rod in it, in order to correct the inhabitants for their sins and iniquities.
This sight affected my mind greatly, and although I did not hear any vocal voice,
nor see any visible hand, yet it was as plainly revealed to me as though I had.
I understood some slighted that testimony, yet I observed to them, that since that time,
more people were taken away than common, as they now might see;
and indeed that inward sight and sense I had of the displeasure of God,
for the sins of the times, made great impression on my mind;
and that no flesh might glory, the Lord took, from the evil to come, several sober,
well inclined young people,
as well as others whose lives and conducts were evil and vicious;
so that all had need to be watchful and turn to the Lord, lest he come unaware,
and call us suddenly out of the world unprepared.

In the twelfth and first months many died, of all ages and professions; and now some,
who would hardly give credit to what I had delivered in several meetings,
began to see the fulfilling of it, and great talk there was about it:
and many solid and large meetings we had with the
people at several funerals about this time,
exhorting them not to slight the present visitation of the Almighty,
but to prepare for eternity, to meet the Judge of quick and dead, who stands at the door.
Among many that were taken away by death, were some few of my particular friends;
and first, dear Hannah Hill, who was a bright example of piety and charity;
she was like a nursing mother to me in my afflictions,
and her husband was more like a brother than one not related,
whose generous entertainment I may not forget.
Thomas Griffith, and Elizabeth his wife, died also about this time.
Thomas was a serviceable man, and well esteemed in our Society; and his wife,
a noted woman for being helpful to, and visiting the sick:
she chose the house of mourning, rather than the house of mirth.
These were worthy ancients, who made peaceful and good ends,
and to whom may be properly applied that remarkable text of Scripture,
"`Mark the perfect man, and behold the upright, for the end of that man is peace.`"

In the second month, 1727, I proceeded on a voyage to Barbados, on account of business,
for the support of my family, and in order to discharge my just debts,
which were occasioned by great losses by sea and land.
Many of my friends were kind to me, and sent a cargo of goods, in the sloop _John,_
Anthony Peel, master, consigned to me for sales and returns.
When the vessel was loaded, she proceeded down the river, and I went by land to Salem,
and was at meeting there on first-day,
and on third-day went on board the sloop at Elsenborough.
On the 8th of the second month, we took in our boats and anchors, and proceeded to sea.
From Elsenborough and the Capes, I wrote to my wife,
giving her an account how it was with me,
and encouraged her to bear my absence with patience:
it was indeed very hard for us to part.

I may not omit taking notice of an exercise which
I felt one night as I lay on my bed in Philadelphia,
on the 21st of the first month, my sleep being taken from me,
which I recollected and wrote down on board the aforesaid vessel, and was in this manner:

"`That the Lord was angry with the people of Philadelphia and Pennsylvania,
because of the great sins and wickedness which were
committed by the inhabitants in public houses,
and elsewhere.
That the Lord was angry with the magistrates also,
because they use not their power as they might do, in order to suppress wickedness;
and do not, so much as they ought, put the laws already made,
into execution against profaneness and immorality:
and the Lord is angry with the representatives of the people of the land,
because they take not so much care as they ought to do to suppress vice and wickedness,
and wicked houses, in which our youth are grossly corrupted:
and also the Lord is angry with many of the better sort of the people,
because they seek after and love the things of this world,
more than the things of his kingdom.
It was showed me that the anger of the Most High would still be against us,
until there was a greater reformation in these things.`"

It is worthy of commendation, that our governor, Thomas Lloyd, sometimes in the evening,
before he went to rest, used to go in person to public houses,
and order the people he found there to their own houses, till at length,
he was instrumental to promote better order, and did, in a great measure,
suppress vice and immorality in the city.

For some days after we were at sea, the weather was pleasant, and we had our health,
for which my heart was truly thankful.
I exhorted the sailors against swearing; and though they had been much used to it,
they left it off, so that it was rare to hear any of them swear; for which reformation,
so far, I was glad.
I lent and gave them several good books, which they read, and showed much respect to me;
but soon after the wind was contrary for some days,
and some in the vessel were quarrelsome.
I asked them what they thought of the saying of Christ,
"`If a man smite you on one cheek,
turn to him the other also;`" at which they were silent,
and of a better disposition to one another afterwards,
and we had some reformation both from fighting and swearing.
During this voyage I was not so sea sick as I formerly had been,
which I took as a peculiar favour from heaven.
About the latitude of twenty degrees north, we met with calms and contrary winds,
which were very hard for some in the vessel to bear,
they putting themselves much out of temper about it.
For my part, I had been used to disappointments, and therefore did not so much mind it,
I spent pretty much of my time in reading and writing, and God being gracious, it was,
in the main, a comfortable time to me;
and I enjoyed my health as well as ever I did at sea in my life,
for which I often breathed forth inward thanks to the Almighty.
On the fifth of the third month we arrived at Barbados,
and I was lovingly received by our friends, but came to a very low market for my goods.

I visited Friends`' meetings on the island, and had several open meetings at Bridgetown,
and Speight`'s-town, and likewise at Pumpkinhill, and the Spring.
On the day of Pentecost, so called, we had a meeting at Bridgetown,
in which was shown the work and operation of God`'s spirit on the old world,
and under the law;
and the everlasting duration and operation of the
same holy Spirit under the gospel dispensation,
which Christ said should abide forever.
At the quarterly meeting at Speight`'s-town, were Judge Allen,
and the captain of a man-of-war stationed there, with several others, not of our Society.
I was much drawn forth in this meeting to speak of the power of the Father, Son,
and the Spirit,
opening to the people how we had been misrepresented
in respect to our belief in the trinity,
or the holy Three, which bear record in heaven, the Father, Word, and Spirit,
which three are one;
for that it was clear and plain we are more orthodox in our belief in the Deity,
than those who do not believe in the operation of the Holy Spirit;
as also that none could be true Christians without it.
It was queried, how could they be clear in their belief in the holy trinity,
or the three that bear record in heaven,
who believe the holy Spirit has ceased his operations, gifts, or immediate revelations,
and if ceased, when, and where, to whom, and how?
The people were very sober and attentive, and stayed sometime after the meeting was done,
and several expressed their satisfaction with what was said.
My good friend Peter Sharp, of Maryland, was with me at this meeting,
on whose account some of the people came.
He had good service in the meeting, and I was glad of his company in this island,
where we joyfully met and parted in the love of Christ.

At this meeting we had each of us a certificate from Friends,
signifying their unity with our conduct and services.
The last meeting I had at Barbados was at Speight`'s-town, on a first-day.
It was a solid, good meeting, in which I took my leave of Friends there,
and exhorted them to believe in and hear Christ,
he being a teacher that could not be removed from them, as men often were;
and though they were but few, they were desired to meet in Christ`'s name;
and I had to show them the difference between us and other Christian professors,
who hold no public worship, if there be no outward teacher: whereas,
if but two or three meet in the name of Christ,
he has promised to be in the midst of them; and he is the best teacher we can have.

On the 14th of the fourth month we set sail from this island, and for the most part,
had fair weather and fair winds, and saw several ships, but spoke with none.

I was one evening leaning over the side of the vessel, being very lonesome,
and having little conversation with any in the vessel, for several reasons,
I turned from all outward things to the Lord,
and was glad to feel his presence and goodness,
which was a comfort to me in my lonesome state;
and as my travels and concerns had called and caused me to be much on the seas,
it also pleased my good and gracious God, to support me thereon many times, in trials,
temptations, and exercises; for all which, I bow in awful reverence before him,
and return thanksgiving and praise to his great name.

The 1st of the fifth month, about noon, we came to the Capes of Delaware,
and sailed up the bay; but in a little time,
we touched the ground with our vessel several times;
there being little wind we got no harm; but two hours after, or thereabouts, a gust,
or storm of wind took us, which, if it had met with us on the shoals where we struck,
in all likelihood we must have perished; which I took to be a remarkable deliverance.
Next tide we got to Newcastle, and it being first-day,
I had a meeting with Friends there, with which we were greatly refreshed in the Lord,
and in one another.
After meeting I went on board the sloop, and having a fair wind,
we sailed for Philadelphia, where we arrived about the eleventh hour,
lodged that night at Paul Preston`'s, and next day went home to my family at Frankford,
where my wife, children, and servants, received me with much rejoicing.

While I was in Barbados, P. M., who accompanied me from Bridgetown to counsellor Weeks`',
told me, that when I was in the island before,
he and I had some discourse concerning the use of the sword;
he then not being of our Society, wore a sword, but now had left it off,
and his business also, which was worth some hundreds a year.
I had reminded him of Christ`'s words, that "`Those who take the sword,
shall perish with the sword.`"
"`Resist not evil, and if a man smite you on one cheek, turn the other also:
love your enemies, do good to them that hate you, pray for them who despitefully use you,
and persecute you.`"
After I had used these arguments, he asked me, if one came to kill me,
would I not rather kill than be killed?
I told him, no; so far as I knew my own heart, I had rather be killed than kill.
He said that was strange, and desired to know what reason I could give for it.
I told him, that I being innocent, if I were killed in my body, my soul might be happy;
but if I killed him, he dying in his wickedness, would consequently be unhappy;
and if I were killed, he might live to repent; but if I killed him,
he would have no time to repent; so that if he killed me, I should have much the better,
both in respect to myself and to him.
This discourse had made so much impression, and so affected him,
that he said he could not but often remember it.
And when we parted at Bridgetown, we embraced each other in open arms of Christian love,
far from that which would hurt or destroy.
