== Chapter X

When I came home from this voyage, which was the 30th of the second month,
I met with the sorrowful news of the death of my only son, George, a dear youth,
who was but ten years and seven days old when he died,
and as he was much beloved for the sweetness of his nature and disposition,
so he was greatly lamented by many who were acquainted with him.
I have this account to leave concerning him, not so much that he was my son,
as to excite other youths to serve and fear the Lord, and to love him above all,
and that they may remember their Creator in their youthful days,
that it may be well with them in this world, and when time here to them shall be no more.

He was a lad much inclined to read the holy Scriptures, and other good books,
especially religious ones; and was always obliging, obedient and loving to his parents,
and ready and willing to do any service he could to his friends;
any little services in his power he cheerfully performed, and took delight in;
he was very diligent and ready to go to religious meetings,
and an entire lover of religious people.
In his sickness he behaved himself more like a wise man, than a youth of that age,
bearing his pain and sickness with a great deal of patience.
I being in another part of the world, he would gladly have seen me,
but said he should never see me any more,
and therefore desired his mother to remember his dear love to his father,
and tell him he was gone to his heavenly Father.
He was very fervent in prayer in the time of his sickness,
and prayed that God would preserve his people all the world over.
One time, when in great misery and pain, he prayed to Christ, saying.
Sweet Jesus! blessed Jesus! give me patience to bear my misery and pain,
for my misery is greater than I can well bear!
Oh! come, sweet Jesus, why are you so long coming?
I had rather be with you than in the finest place in all the world.
Many other religious expressions he spoke on his deathbed,
greatly to the satisfaction and melting of his friends and relations who came to see him.
One day he said.
My misery and pain is very great, but what would it be if the wrath of God was in my soul?
He believing in the love of God in Christ, made him desirous of being with him,
and seeing the joy that was set before him, thought the time long to be with Jesus,
as knowing that then he would be out of all misery and pain.
His heart was full of love to his relations, acquaintance and friends,
who came to see him in his illness; and full of tender sweetness and divine love,
he took his last leave of them, which greatly affected many.
This was one of the most pinching exercises I ever met with;
but as he said in his illness, so I now write: The wisdom of the Lord is wonderful.
One time in this dear child`'s sickness he said.
Oh! the good hand of the Lord help me, give me ease, and conduct me safely, i. e.,
to God`'s kingdom, uttering this verse:

[verse]
____
Sweet Jesus give me ease, for mercy I do crave;
And if thou`'lt give me ease, then mercy I shall have.
____

Although this was a great exercise and deep affliction to me,
in losing this promising youth, and my only son;
yet considering that he went off the stage of life like a solid, good Christian,
it was made tolerably easy to me for he departed this life in much brightness and sweetness,
and more like an old Christian than a youth of ten years of age.

It was usual for me to advise his mother not to set her affections too much upon him,
thinking he was too good to live long in this world, and too ripe for heaven,
to stay long on earth, in this world of sorrow and misery.
This dear and tender youth, when reading, to which he was much inclined,
if he met with anything that affected him,
either in the Sacred Writings or other good authors, would write it down,
and get it by heart.
He was more than common affectionately concerned for his mother,
doing whatever he could freely and cheerfully to serve her,
and told her not to do some things which he thought too much for her, saying.
Mother, let me do it, if I were a man you should not do anything at all,
meaning as to labour.
She being affected with his filial love and care for her in his father`'s absence,
it caused her sometimes to turn about and weep.
I thought a little memorandum of the life and death
of this religious lad was worthy of recording,
in order to stir up other youth to obedience and love to their parents,
who carefully and tenderly nourished and brought them up; and also to love and obey God,
from whom they have their life, breath and being, and to believe in Christ,
who died for them; who is the glorious light of all the nations of them that are saved,
and walk therein, according to Sacred Writ.

He got several pieces by heart out of the Bible and other religious writings,
first writing them with his pen.

One which much affected my mind,
was the fifteenth verse of the fifty-seventh chapter of that evangelical prophet, Isaiah:
"`For thus says the high and lofty One, that inhabits eternity, whose name is holy,
I dwell in the high and holy place;
with him also that is of a contrite and humble spirit,
to revive the spirit of the humble, and to revive the heart of the contrite ones.`"

I have now one only daughter, Rebecca, left me, out of twelve children,
except my wife`'s son and daughter.

After this long and tedious voyage, which ended in the second month,
I stayed but a few weeks at home, and loaded with wheat and flour for Dublin, in Ireland;
Alice Alderson, my kinswoman, and Margaret Coupland, were passengers.
We had a very comfortable, pleasant passage, fair winds and weather,
and good religious meetings.
I think it was the most pleasant time that ever I crossed the seas.
About Nantucket we saw several sloops whaling, and spoke with one,
by which opportunity we inquired of the welfare of our friends on that island,
and sent our loves to them.
Not many miles from the sloops we saw a shoal of whales;
I counted eight in a row lying side by side in the water.

We were four weeks and six days from our Capes to Cape Clear, in Ireland:
coming near the land, we met with fishing boats and got plenty of choice fresh fish;
in the evening we got into Kinsale, took in a pilot for Dublin,
and sailed next day from Kinsale, and were out one night at sea,
got next day to Dublin bay, where we went ashore,
and were kindly entertained by our friends.
We were at several large meetings in that great city, which some of us, while we live,
at times I believe, shall remember.
My stay in Ireland was about seven weeks,
in which time I visited several meetings in the country, and at Edenderry,
the Moate of Greenough, Carlow, Ballytore, etc.

We set sail from Dublin with a fair wind, in company with the ship Neptune,
and our friends sent many prayers and good wishes after us.
We were about forty persons, sailors, passengers and servants, on board,
and had a good passage, all things considered.

We had religious meetings on board, and were on our passage, from the sight of Ireland,
to the sight of our land, five weeks and six days:
it was the quickest voyage I ever made to Europe and back again to Philadelphia.

When I came home, finding all well, I was thankful to God, in the name of Christ,
for all his mercies and the many preservations wherewithal he had favoured me.

After being a little at home and at several meetings, and not being clear of the world,
in order to it, I undertook another voyage to Barbados,
and from there intending for London, in order to settle my affairs there,
which I intended some years before, but losses and disappointments hindered me.
On the 7th of the tenth month, I proceeded on a fifth voyage in the Barbados packet,
and left Philadelphia, and was at a meeting the next day at Chester, being first-day,
and in the evening we had a large meeting at Grace Lloyd`'s,
where I met with my dear friend Joseph Gill, who had good service in said meeting;
we rejoiced in Christ to see each other.
We left Chester the 9th, and got that tide down the river to Newcastle,
and after visiting the few Friends there, we set sail the 12th in the morning;
the wind being high, and the weather very sharp, freezing hard, our sails were so frozen,
that we had hard work to get the vessel under sail.
The 13th day, weighed anchor and sailed down the bay,
and the 14th were clear of the Capes.
The first-day following we had a good, seasonable meeting,
for the worship and service of God; in which,
as I was treating of disobedience to parents, and disobedience to Almighty God,
our great Parent and heavenly Father, a youth who was a passenger in the vessel,
went out hastily and abruptly, as I was showing the ungratefulness of the first,
much more of the last.
When I asked the reason of his going out,
he said it was because he could not forbear crying;
and thinking I spoke so because of him, he said he could not hear me any more.
Afterwards I understood that he was a youth who was
very ungrateful and disobedient to his parents;
the which I knew not of, for his mother told me, and himself also,
that he went to sea on account of his health.
I thought his going out so hastily was occasioned by some indisposition of body;
but it was as he gave us to understand, through resenting illy what was spoken,
and by taking it to himself.
I have sometimes observed,
that persons have shown a restlessness and uneasiness in public assemblies for worship,
sometimes going out, etc.,
so that they have thereby exposed themselves to the notice of the people,
as persons guilty of the matter publicly reprehended, or spoken against;
just as though they were the only persons in the assembly
who were guilty of the evil then taken notice of:
such public restlessness is a great folly and weakness,
besides so openly and publicly exposing themselves.

After we left our Capes, we had hard gales of wind, which lasted several days.
The 28th being first-day, we had a meeting for divine worship,
in which God was praised and his holy name exalted, for his unspeakable grace,
in sending his only begotten Son,
a divine light to enlighten the inhabitants of the world.
We had stormy weather and contrary winds for some weeks, so that our passage was tedious;
and of fifteen times going to Barbados, I found this the most difficult;
and the prospect was very discouraging of making a losing voyage,
by the great expense I expected for repairing and refitting the vessel, etc.,
so that I began to despair of accomplishing my design
of discharging my debts in Great Britain,
and the thoughts and consideration of losing so much
of the company and conversation of my wife,
relations and friends, and spending so much precious time, which cannot be recalled,
to so little purpose, lay heavy on my mind;
yet by the grace of God my mind was supported,
and my resolutions confirmed to praise the Almighty for every dispensation of his providence.

The 23rd of the eleventh month we saw the island of Barbados at the breaking of the day,
having been from the Capes of Delaware forty days and one night; and were truly thankful,
that at last, we, through divine favour, got to our desired port;
where we were lovingly received by our friends at Speight`'s-town,
who were joyful at our arrival.
From there I went to Bridgetown, and to the governor`'s, in order to enter our vessel;
but staying a little too late, the governor, who was the lord Howe,
was come from his house on his way to Bridgetown, with his coach and six,
and his attendants; but seeing me, he courteously stopped his coach,
and did my business as he sat therein; and though I made an essay towards an excuse,
he would not admit of it, saying.
There is no need of any excuse.
He was indeed an extraordinarily courteous man: he died soon after, much lamented,
as he was much beloved.

My stay at Barbados this time was the longest I ever made,
believing it to be the last time I should go there, and that I should see them no more.
My so saying troubled some of them; but growing in years,
being then turned of threescore,
I thought it would be too hard for me to undertake such another voyage;
therefore I was at all the meetings of our friends on the island.

Here I met with Moses Aldridge, a Friend from New England,
who came on a religious visit to Friends of this island,
with whom we had several good meetings,
his service in preaching the gospel being edifying and acceptable;
we were together at the marriage of Andrew Drury and Mary Lewis,
after which I was ill of a fever several days;
this distemper was very much among the people,
and nearly twenty masters of vessels and some hundreds of people died.
Though I had been at Barbados many times, I never had so much illness there before.
Moses Aldridge and several Friends of us, had a large meeting at John Gibson`'s,
where were many people not of our persuasion, who were generally sober.
I recommended charity to the people, according to the doctrine of the apostle Paul,
as the most excellent gift,
and advised them to show it forth to all people of all professions,
and also to their negroes,
telling them that some of the gentry of this island had observed to me,
that the more kind they were to their slaves, the better their business was done for it.
I observed also,
that I had been at some places where I had watched
to hear some expressions that might look like charity;
but in many houses, and '`some of note,
I could not hear any Christian like expressions to their slaves or negroes,
and that with sorrow I had seen a great deal of tyranny and cruelty,
the which I dissuaded them from.
This doctrine so exasperated some that they made a disturbance in the meeting:
one of the persons meeting me on the king`'s highway, shot off his fowling-piece at me,
being loaded with small shot, ten of which made marks on me, and several drew blood;
by which unfriendly action the man got a great deal of disgrace,
it being highly resented by all who were acquainted with me.
The president of the island looked on it as a very base action,
as did also some of the justices and the gentry,
also the vestry and several clergymen and lawyers.
One of the lawyers told me I should not be just to the country, myself, or the man,
if I did not prosecute him; another professing the law,
said he ought to be abandoned by all mankind, if he shot at me with design;
many were for prosecuting him,
for the people generally took notice of it with abhorrence; but he sending for me,
and signifying he would not do so again, I forgave him;
and I pray it may not be laid to his charge in the great day,
and that he may be forgiven,
he being ignorant of the love I had and have for him and all men,
even for those whom I know to be my enemies.
It would be too great a scandal and reproach, to expose his name and station in the world.
Some thought I did well in forgiving him, and some thought I did ill in it:
but I spoke my mind to him alone freely, in which I had satisfaction and peace.

Intending my vessel for London, I made my chief mate, Ralph Loftus, master of her,
not knowing whether I might proceed on the voyage, it being a very sickly time:
afterwards my mate had the distemper also, but I bless God,
we both recovered a good state of health.

It was during this voyage that my friends in Barbados
published a little piece I wrote at sea,
which I called "`Free thoughts communicated to freethinkers;`"
done in order to promote thinking on the name and works of God;
which had, as far as I understand, a good acceptance among the people.
The principal clergyman on the island thanked me for it,
and said "`There was need enough of it;`" but I could be glad another, or a better hand,
had done something of that nature, and more at large.
If this may be of any service, I shall be thankful.

I had a meeting at John Lewis`'s, in Joseph`'s parish,
at which were many not of our profession,
and some who were never at any of our religious meetings before;
who said they were glad they were there that day; it being a satisfactory open time.

After I had visited my friends and settled my affairs as well as I could,
and loaded our vessel with sugars for London,
being willing once more to see my native land,
and settle my affairs there and see my relations and friends,
on the 6th of the third month we set sail from Barbados for London,
and had pleasant weather.
The 16th being first-day, we had a religious meeting for the worship of God,
in which I was concerned to speak on the government of the tongue,
having on board several hands who did not sail with us before that voyage,
and were much used to swearing.
After that meeting we had not so many bad words and oaths as before.
I was thankful in my soul to the Lord, and blessed his holy name,
for his goodness to us that day;
and in the night my sleep was very sweet and comfortable,
being sensible of the love of God in the visions of the night;
so that I witnessed the fulfilling of the prophecy of Joel, chapter ii.
28.

The 23rd being the first-day of the week, we had a meeting,
in which the grace of God that comes by Jesus Christ, was magnified,
and a blessing begged for all who love and serve God, throughout the world,
on sea and land; also a tender petition was put up to Almighty God,
that as he was graciously pleased to look down on those eight persons in Noah`'s ark,
so he would please to look upon us in our vessel; and that as by his divine providence,
they safely landed on the earth, so we, if it were his will,
might safely land at our desired port, yet not that our wills,
but his will might be done: which supplication was put up with great submission.
Both day and night I often sought the Lord, and was much alone in this voyage.
I read the Old and New Testament almost through, and much of it several times over;
my time being mostly taken up in reading, writing and meditating, in which, at times,
my heart was broken into tenderness,
and I was humbly thankful to God that my heart was not hard
he having promised to visit the contrite ones;
which he sometimes fulfilled, to my unspeakable satisfaction;
glory to his holy name forever.
My heart was also thankful that God was pleased to
visit me in my watery travels and troubles,
and in my separation from my family and friends,
who are much nearer and more valuable to me than all riches,
and it was a great cross to my natural inclination to part with them.

The 8th of the fourth month being the first-day of the week, we had a meeting,
in which acquaintance with God was exhorted to, showing the benefit of it,
and of loving him above all things,
and delighting in his law and meditating therein day and night.
The 19th in the morning,
a strong northerly wind came up and blew so hard that we could not carry sail,
but lay to the wind, under our mizen,
which was split or torn with the violence of the wind, and the sea rose high,
so that it came into the windows of our great cabin.
It was very rugged for the time, and though it was mid-summer,
was so cold that we were obliged to clothe ourselves as in winter.
The 22nd being first-day, we had a comfortable meeting after the storm,
wherein the great benefit of true religion was a little opened to our small company,
and the Lord, Most High, was praised for our deliverance and preservation.
The 26th we sounded, and found about seventy fathom depth of water.
The 29th we were abreast the isle of Wight.
From the time we left the island of Barbados to the time we found ground, was seven weeks.
Thus through many perils and dangers we came to Great Britain;
for all which mercies and providences,
let my soul bless and praise the holy name and mighty power of the Most High.

It was now a time of a very great pressing for seamen,
and several men-of-war`'s boats came on board to press our sailors;
but they had prepared a place in the vessel to hide themselves,
and the men-of-war`'s people could not find them.
One lieutenant with his men came on board, and seeing us weak handed,
the best of our hands being hid, he asked me if I had any more hands on board?
I made him little answer.
He then said he was sure I could not bring the ship from Barbados without hands.
I told him sailors were hard to be got in Barbados, either for love or money,
to go for London, for fear of being pressed, and I was obliged to take any I could get.
He said it was in vain to talk much, but if I would say I had no more hands on board,
he would be satisfied; he having a belief that I would speak the truth,
though he never saw me before;
and he said if I would say there were no more men on board, he would go away,
for then he had no more business there: but I made him no answer,
not daring to tell a lie.
Now I know that there are men on board, said he;
so he commanded his men to search the ship to her keel.
So they stripped and made a narrow search, and sweated and fretted,
but could not find them.
He being civil, I made him when he went away, a small present.
He wished me well; and so I carried my people safely up to London.

In the beginning of the fifth month I came to London,
and lodged at the house of Simeon Warner, in Southwark,
and at several kind friends and relations in and about London.
The tender and brotherly respect which I received in some of those families,
in my sickness, will not, I believe, ever be forgotten while I am in this world;
and I hope that He whom I serve with my might and strength, will be their reward.
When in the country about London, my residence was mostly at Edmonton,
at my dear brother George Chalkley`'s, who, with my sister and cousins,
were a comfort to me both in health and sickness.
In London I was often sorely afflicted with the phthisic and asthma,
which sometimes made me very uneasy;
and though my affairs required me to be often in the city,
yet I was obliged to return to the country for air, and both in health and sickness,
was kindly and affectionately received and tended by my dear brother, sister,
and all my loving cousins.
The memory thereof is cordial to me in penning these lines.
It may be truly said, we were very joyful in meeting one another,
and our sorrow in parting is not easy to be expressed.

In London I sold my vessel, the Barbados packet,
and settled all my affairs to general satisfaction, so far as I know,
on which account I had laboured for several years,
and was joyful that Providence had favoured me so far as to see it accomplished:
so that now I wholly intend to leave trading by sea, which I never inclined to,
only on a principle of justice;
for I was fully resolved in my mind that my creditors should be paid their just debts,
though I might lose my life in the pursuit of it.
I never was extravagant or indolent, but met with many casualties by fire and water;
by the latter I lost many hundreds of pounds for several years together.
I would persuade all in their undertakings for a livelihood in this world,
to be sure to have an eye to divine Providence, who will not allow us, if we do well,
nor so much as a sparrow, to fall to the ground, without he think it best for us,
he knowing what is for our good better than we know ourselves.

When I had paid my debts and in a good degree settled my affairs,
I visited several of my relations at Kingsworth, Staines, Guilford, etc.;
had a meeting at Market street, and one at Guilford, another at Staines,
and one at Longford; in all which I had some service,
and my relations were joyful to see me once more, not having expected to see me again.
When I had visited meetings in and about London, I went towards the north,
in order to visit some places where I had never been, and some that I had been at.
The number of meetings and the names of the places where I had meetings,
while I was this time in England, are as follows.
While I was in and about London, I was at eighteen meetings in that great city,
at two of which I was with May Drummond, a virtuous young woman,
who has a good gift in the ministry,
and had a gracious opportunity of declaring her convincement to our noble Queen Caroline,
our great King George`'s royal consort.
The kind treatment and good reception she had with the queen,
spread so in city and country, that many thousands flocked to hear her,
and more of the gentry and nobility than ever were known before at our meetings.
I had some private conversation with her,
which put me in mind of the apostle`'s exhortation,
where he advises the primitive Christians, that their words be few and savoury,
and that they should be seasoned with grace, for this great reason,
that they might administer grace to the hearers;
and truly I thought there was the influence of grace in her conduct and conversation,
whom I pray God to preserve in Christ to the end.

I had a meeting at the house of my brother with his scholars at Edmonton,
and also with his family and others of our relations,
which some of VIS may have occasion to remember.
We had seven meetings at Tottenham at sundry times, and four at Hartford;
I travelled to Hitchin, from there to Baldock, and then to Stadtfold and Ashwell.
The 7th of the eighth month being the third-day of the week, to Royston, fourth to Ives,
fifth to Huntington, sixth to Ramsey.
First-day being the 12th of the month, we had a meeting at a small town named Finding,
and the same day in the evening, had a large meeting at Wellingborough,
in Northamptonshire.
The 14th being the third-day of the week, we had a meeting at Northampton,
fourth-day at Braybrook, fifth-day at Okeham, the county town of Rutland,
sixth-day at Long Clackson; and first-day being the 19th of the month,
I was at a large and open meeting at Nottingham,
where were many people not of our Society, who were very sober;
third-day had a meeting at Fairnsfield, fourth-day at Mansfield,
and fifth at Chesterfield, in Derbyshire;
from which we went over the moors and mountains.
Benjamin Bangs, the younger, accompanied me,
who came from Stockport to be my companion and guide there:
his company was pleasant and profitable to me in that hilly country,
through which we travelled to Stockport, where we had three meetings,
and where I met with my dear, worthy old friend, Benjamin Bangs.
When we met we embraced each other in Christian love,
having not seen one another for many years, with whom I stayed four days.
This worthy Friend, though upwards of fourscore years of age, went with me to Manchester,
where we had two meetings, and then I went back with him to his house.
He was a man of extraordinary character, and well beloved,
being a pillar in the church of Christ.

From Stockport I went to Macclesfield, to Joseph Hobson`'s,
where I met with Joshua Toft and his brother, two choice ministers of Jesus Christ,
of whose company I was glad, though at that time I was very low and poor in my spirit.
We had two meetings here on the 2nd of the ninth month, being first-day.
I was at a large meeting at Morley, and in the evening, at the meeting at John Leigh`'s,
at both which there were many people not of our Society, who were very still,
and some were broken into tenderness.
From Morley I went to Penketh, where we had a large, solid meeting,
and had an evening meeting at Warrington, where I met with many brethren and sisters,
who sincerely love our Lord Jesus Christ, with whom I was refreshed,
particularly at Gilbert Thompson`'s and Lawrence
Galen`'s. From Warrington I went to Lanotree,
Preston and Clifton, where I had meetings, and so went on to Lancaster.
I went to Wray, in order to visit my old ship-mate, Elizabeth Rawlinson, whose son,
Hutton Rawlinson, went with me.
When I came to Wray, they desired me to have a meeting with them;
and though there was little notice, yet we had a large meeting, the neighbours coming in,
and Christ was preached to them freely; this was the 10th in the evening,
and second-day of the week.

Third-day I went to Kendal, and in the evening, with very little notice,
we met with several hundreds of people, Friends and others.
It was a surprise to me, I expecting but a few, because of the shortness of time;
but I acknowledge it was a pleasant surprise,
to see the willingness and readiness of the people to hear the gospel preached.
Friends here are a great people, and well beloved and esteemed by their neighbours,
and live in much love and unity.
The fourth-day many Friends came to see me from various parts,
I giving them some notice that I designed to go no further northward,
and hastening to get ready to go to America, betimes in the spring;
having been from home nearly two years; therefore many of my friends,
some of whom had been at sea with me, met me here.
We rejoiced to see one another, and after a large and good meeting,
took a solemn farewell, many of us not expecting to see each other any more.

In this journey and travel I endeavoured to be, as much as I well could,
at such meetings as I had never been at before,
and because I was short in this visit to my friend, some were not so well pleased;
but my call was most to the American shore, where I thought my service mostly lay,
and in order to return, I set my face toward London,
and expected to meet with my friend and brother in Christ, Isaac Pickerell, in Cheshire,
who designed to accompany me towards the south.
I went from Kendal to Lancaster, and was at Penketh on a first-day,
being the 16th of the ninth month, which meeting was large and solid.

We then went to Sutton, where I met with Isaac Pickerell,
also with our ancient friend James Dickinson, and Christopher Wilson, a choice young man,
his fellow-labourer.
We had meetings at Sutton, Newtown, Chester and Shrewsbury.
James Dickinson was about fourscore years of age,
and yet held out in travel to admiration, and was lively in preaching the gospel:
he is a worthy elder, of whose company I was joyful; at Shrewsbury we parted,
and Isaac and I went to Colebrook, where, on a first-day, we had a solid, good meeting.
From there we went to Stourbridge, and after having a meeting there and at Broomsgrove,
went on to Worcester, where we had several large and solemn meetings:
we lodged at John Corbin`'s, who was very kind to us, as also were his hopeful children,
and in great love and unity we both met and parted.
From Worcester we went to Evesham, where we had two meetings,
and from there to Oddington, and had a large evening meeting; the people,
who were mostly of other societies, were very sober, and gave good attention.

On fifth-day we had a meeting at Chalbury,
and a tender time with a Friend at Wallingford who was very weak,
and expressed his satisfaction and thankfulness for the visit;
his children were very tenderly affected also.
The good Lord, the great physician of value was with us,
and his grace was at that time shed abroad in our hearts.
From Wallingford we went to Reading, where my good companion and fellow traveller,
Isaac Pickerell, dwelt; we were lovingly received by our friends.
I stayed here and rested several days, and had several satisfactory meetings with Friends,
they being a large people, living much in love and good will.
Here Samuel Thornton, of Edmonton, my kinsman, and Isaac Brown, my wife`'s son,
came from London to see me.
From Reading, Isaac Pickerell accompanied me to Maidenhead and to Jordan`'s,
at both which places we had meetings.
The house and burying ground at Jordan`'s,
are kept in the neatest order of any I ever saw,
in which ground lie the bones of our worthy Friends, Isaac Penington, William Penn,
Thomas Ellwood, George Bowles, and their wives, as I remember.
This meeting is often, if not mostly kept in silence;
yet several have been convinced there,
through the grace of God and the power of the Holy Spirit,
which Christ said he would send to the true believers,
and that should abide with the church forever:
here my beloved friend Isaac and I parted in much love,
having good desires for each other`'s welfare.
From Jordan`'s I went to my brother`'s, at Edmonton,
where I rested a few days from travelling.

Then a concern came upon me to visit Friends`' meetings in the county of Essex,
and I went from my brother`'s to Hartford, and had several meetings there,
and one at Ware, which was very large; after which I went to Hartford again,
having relations there.
From there I went to Bishopstafford and Stebbing, where I had meetings; and at Braintree,
Coggeshall and Halstead, and there were abundance of people at Colne,
at an evening meeting we had, where I met with my worthy friend Joshua Toft,
and his fellow traveller, Joseph Hobson, we rejoicing to see each other.
From Colne I went to Cockfield, which was a very small meeting; then to Colchester,
where I stayed several days and went to several meetings, as at Rockstead and Manningtree,
and then back to Colchester.
On first-day I had a large meeting in the afternoon,
and after it Friends were for appointing meetings for me to be at in the ensuing week,
and desired to know my mind therein.
After a little pause I told them I found a full stop
in my mind from going to any more meetings at present,
and that I would wait some days with them in the city, till I saw further.
While we were sitting together a letter came to me from London, that a Friend,
Stephen Payton, had set up my name on the Exchange, in London,
as master of the Barbados packet, which was the vessel bought of me by John Agar,
who sold her to said Stephen Payton, who intended her for Philadelphia,
and next morning a messenger was sent for me from London:
thus having such a favourable opportunity of returning home, I embraced it,
and went on second-day to Witham,
where I again met with Joshua Toft and Joseph Hobson at meeting; then to Plaistow,
where we had a meeting, and then to Bromley, near Bow, at Joseph Olive`'s,
where we had a meeting with his people and servants, who were many.
I thought it was a good time, a divine hand of love was reached out to the young people,
and they were advised to give up their hearts to their Creator in their youthful days;
several scores of people belong to this family.
After this meeting I went to London and prepared for the voyage.
When our vessel was loaded, which was chiefly by Israel Pemberton, the younger,
who went with us, as did our owner, Stephen Payton,
and Isaac Brown and four of my kinsfolks, whose names are Freeman,
with several other passengers;
in the latter end of the twelfth month my brother and his eldest daughter, Rebecca,
with her husband, Samuel Thornton, accompanied me to Gravesend,
where our parting with them was very solemn and sorrowful,
we not expecting to see one another more.

From Gravesend we sailed the 3rd of the first month to the Downs,
and from there down the British channel, and were at sea about nine weeks,
which we thought long, having many contrary winds; but after we came on shore,
we understood many vessels were much longer.
At sea we had meetings, some of which were to my satisfaction.
I came very unwell on board; but when at sea, I mended;
for which favour I am truly thankful.
We landed all well and in health at Philadelphia, in the third month, 1736,
where we were received with joy by our relations, friends and acquaintance;
it was much the more so, because they had heard I was likely to die.
At London I had a sore fit of the asthma or phthisic,
three persons sitting up with me for three nights, who I thought would see my end;
but the time was not yet come that I must die, though indeed death was no terror to me,
hoping my change would be much for the better; for then,
I hoped I should be forever with Him whom I loved better than life.

After I had been at home some time I went to Salem, and from there to Cohansey,
and in my return was at Woodbury creek, and had meetings at each place:
and soon after I visited the meetings of Friends at Bristol, Burlington,
Trenton and Bordentown, and in my return home, at Middletown.
By the way I called to see my ancient friends, Joseph Kirkbride and the widow Warder;
she was ninety-two years of age, and perfect in her understanding;
she said she did not know for what end the Almighty should prolong her days to that age;
but she was satisfied in his will.

In the fifth month I visited the meetings of Friends at Haddonfield, in West Jersey,
and at Newton, Haverford, Germantown, Abington, North Wales and Plymouth,
and was several times at Philadelphia and Frankford.

After many exercises and large travels by sea and land,
my brethren and others not of our Society, expressed their gladness to see me,
rejoicing that I was likely to spend my time more on the land,
hoping that I would go no more to sea; the which, God willing, I determined,
having so settled my affairs that I could stay on shore;
and am truly and humbly thankful to the Almighty, that he by his good hand of providence,
in his due time, had favoured and helped me so to do.

In the sixth and seventh months I again visited the meetings of Friends at Bristol,
Burlington, Byberry, Abington, Horsham, Germantown, Fairhill,
and many times at Frankford and Philadelphia.

In the eighth month I was at two meetings at Cohansey, and one at Alloway`'s creek,
where I met with Edward Tyler, a Friend on a religious visit from Europe, and John Sykes,
a Friend living near Crosswicks, in Jersey, where we had an open satisfactory meeting;
from which I went to Salem, it being their week-day meeting,
which was large and to the edification of many.
I was also at Pilesgrove on fifth-day, and at Woodbury creek on sixth-day:
in which last meeting the obedient son was encouraged,
and the disobedient earnestly called home to his heavenly Father`'s house.
In this journey I had John Bringhurst, the younger, for my fellow traveller;
his father being unwilling that I should go the journey alone.

After I had been at home some time, I, with some others,
went to the yearly meeting at Shrewsbury, in East Jersey,
which was on the 23rd of the eighth month; it was exceedingly large,
and the quietest and most settled meeting that ever I was at there;
and many divine truths were delivered therein.
From there I went to Manesquan, and had a meeting, then to Middletown,
where we had a meeting in the Baptist meetinghouse, several of whom were there,
and glad of the meeting; from there to Shrewsbury, and had a meeting on first-day,
being the 30th of the month: from which, on my return home,
had meetings at Moses Robin`'s, Allentown, Crosswicks, Bordentown, and Mansfield;
some of which were large, open, and satisfactory.
After the last meeting, we went to Burlington, and next day came home,
accompanied by Richard Smith, Jr. After being a few days at home,
I was sent for to Chester, to the marriage of John Lee,
(who had sailed several voyages with me,) next day
I went to the week-day meeting at Providence,
and on first-day was at Springfield; from which I returned home.

The 23rd of the ninth month, I left home again, and went to Philadelphia,
and from there with Daniel Stanton, John Easton, and John Proud, Jr.,
(the two latter of Rhode Island,) to Radnor and Goshen meetings,
and by the coldness of the weather, and crossing several creeks, I got a cold,
which settled on my lungs, so that, in conversation, I was hoarse;
but I was helped in meetings to admiration;
for which I was truly thankful to the Almighty,
the great helper of his servants and children.
We had a meeting with an ancient Friend,
who said she had above two hundred who called her mother,
being her children by blood and marriage to the fourth generation:
we took our leave of her, as not expecting to see each other more,
and parted in tenderness of heart.
One of this Friend`'s grandsons went with us to Concord, where, on a first-day,
we had a very large meeting, and an evening meeting at Moses Mendenhall`'s;
and the remainder of the week we had meetings at Birmingham, Kennet, New-Garden,
Marlborough, and the monthly meeting at Center, on the seventh-day following,
at which were many young people; for whose sakes I was drawn,
in my exercise of the ministry,
to show the rise and design of our meetings of discipline.

[.numbered-group]
====

[.numbered]
_First,_ That the same power which gathered us to be a people,
inclined our elders to establish those meetings,
and settle them in most parts where we were gathered
and had meetings for the worship of God.

[.numbered]
_Second,_ They were advised to do the business of them, and speak to their affairs,
in the sense of the same power, spirit, and wisdom of Christ, which, as it had raised us,
would, as we kept to it, preserve us to be a people to the praise of God`'s holy name.

[.numbered]
_Third,_ They were advised, in doing the business,
not to run out into many unnecessary words, which might lead to contention,
and spending much time to little purpose;
religious affairs being done best in a meek and quiet spirit,
which is of great price with the Lord; great evils having arisen in many ages,
through hot and long contentions about religion.
It is also good to avoid, in matters of difference, respect of persons,
on account of being acquainted or related, so as to be swayed thereby from justice.

[.numbered]
_Fourth;_
they were advised to be very careful of giving any just occasion of offence to any,
to Jew or Gentile, to Indian or Negro; for, "`Woe to them,`" says our Saviour,
"`by whom offences come;`" and if any will take offence when none is justly given,
it is the best way to be patient, and take our Saviour for our example,
who got the victory through suffering; a safe way, and glorious in the end.
And as to few words, the apostle says, "`Let your words be few and savoury,
seasoned with grace, that they may administer grace to the hearers.`"

[.numbered]
_Fifth;_ I was engaged for the sake of the youth of both sexes,
to show them that a material part of the service of these meetings,
is that care be taken therein,
to see that persons are clear of prior engagements or entanglements,
in relation to marriage, and that they have the consent of parents, or parties concerned,
as guardians, etc., and also, that they, and all who belong to our Society,
walk orderly in conduct; otherwise they could not be in unity with us, or owned by us,
as a Society of religious people.
We do not own scandalous persons, or admit them to be married among us,
without acknowledging their faults and promising amendment for the future,
through divine grace and assistance.
Also, in those meetings the widows and fatherless are taken care of,
that they may be supported and visited, and youths put out apprentices to learn trades, etc.

====

This meeting concluded with supplication for the rising generation,
and for the king and all his subjects,
and with thanksgiving and praises to the sacred name of Him who lives forever.

After the abovesaid meeting we went to Wilmington,
a newly settled town on Christiana creek, which I believe will be a flourishing place,
if the inhabitants take care to live in the fear of God,
and seek his glory and the riches of his kingdom, preferring it to anything of this world.
We had a pretty large meeting here, considering the season, for it was very cold,
which was held in a large house of William Shipley`'s;
but they are making provision for a meetinghouse.
From this town we went to Newark,
and had a comfortable meeting at George Robinson`'s in the evening,
and next morning set out for Philadelphia.

As it was now the winter season,
and having been several times at this season of the year in the warm climates,
it was harder for me to bear the cold than usual,
so that I stayed at and about home pretty much, being often at Philadelphia, Frankford,
Germantown and Abington meetings.

The latter end of the tenth month, on a first-day of the week, I was at a large,
open meeting at Darby, in Chester county.
After meeting I rode home, about fourteen miles;
but it was so cold that my limbs were much benumbed,
and were not fully recovered in more than a week.
Coming home, between Schuylkill river and Philadelphia,
we observed the largest meteor that ever I saw, though I had seen many by sea and land;
this was in sight almost a minute, as nearly as I could guess; it was a mighty stream,
like a flame of fire, leaving, as it were, sparks of fire behind it, as it went along,
and then settled like a star, and disappeared.
A few days after this meteor, there appeared in the sky an uncommon redness,
with streams like fire.

About this time was buried at Frankford, John Hurford, who was about ninety years of age;
at whose burial, the coldness of the season considered, were a pretty many friends,
neighbours and relations of the deceased; as also many from Philadelphia.
I was concerned to advise those present to prepare for their final change;
that being certain, though the time is uncertain; which, generally,
none knows but the Almighty;
therefore we ought always to be preparing for our dissolution,
and always watching and praying, lest we enter into temptation; as said our dear Lord,
"`If the good man of the house had known in what hour the thief would come,
he would have watched.`"
And we not knowing whether death will come in our youth, in middle, or old age,
ought therefore, earnestly to prepare our hearts to meet death,
so that we might dwell with God and Christ in his kingdom forever.
It was also observed, that though this Friend had lived to a great age,
yet that few lived so long, no, not one in a thousand, and many die very young.
They were earnestly entreated, in the love of God through Christ,
to prepare for their latter end,
and not to set their hearts and affections on things below; for,
by how much they set their hearts and affections on natural or outward objects,
by so much the harder it would be to part with them, when death should come.
This meeting ended with prayer for reformation and preservation to the end of life;
and praises, yes, high praises were given to Him who had given to all present life,
breath and being.

It being exceedingly severe weather, with much rain, wind and snow,
there were great floods, so that we could not get over Frankford creek to meeting;
therefore the Friends on the west side met together at my house,
and we had a satisfactory, good meeting,
in which we were exhorted to build our religion on the sure foundation;
that neither storms, rain, nor winds, might be able to shake us from this foundation,
which is Christ, the rock of ages.

This winter we were visited at Frankford with the smallpox,
of which many died at Philadelphia, and several in our neighbourhood.

Staying chiefly at home, I spent much of my time in reading and writing,
being often sensible of the love and goodness of God, my exceeding great reward;
he by the spirit of his Son comforting me,
and sometimes melting my heart into tenderness in consideration of his many mercies,
which caused me to praise his holy name, who is thereof worthy, beyond expression,
forever.

In the first month I went with my friend John Oxley, of Barbados, to Bristol,
where we had a large meeting;
and then over the river Delaware to Burlington quarterly meeting:
we were obliged to get to the Jersey shore on the ice,
laying boards thereon for about one hundred yards together;
and being long on the ice and poorly as to health,
I took such a cold that I could not get to meeting next day,
but was at the youths`' meeting on third-day following.
On fourth-day I went to Rancocas meeting, then to a large meeting at Mount Holly,
where was a marriage; afterwards to Evesham and Upper Springfield, or Hanover,
and then returned to Burlington, and next day was at the monthly meeting there, which,
to me, was a good open meeting, wherein church discipline was somewhat treated of,
and Friends advised to wait for that spirit which leads into all truth,
to guide them in the discipline.

In the second month, 1737, I went to Cohansey, in order to negociate some affairs,
and had three meetings at Greenwich and one at Alloway`'s creek;
and on the 9th of said month, being first-day, was at Salem meeting,
which was large and open:
and in the evening we had a heavenly meeting at Bartholomew Wyat`'s.

After my return from Salem,
on the 1st of the third month I took a journey to the eastward,
having a desire to see Friends in those parts,
whom I had several times visited in the service of the gospel, in my young years;
and though now upwards of threescore years of age,
was willing to visit them once more before I died, who,
in some places where I had formerly travelled, were grown very numerous.
I set out with Joseph Gilbert and several other Friends,
and we travelled together to Long island, where we parted, and I went to Newtown,
where I met with John Fothergill and Samuel Bowne; at which place we had a meeting,
which was appointed on John`'s account,
and his service therein was to the satisfaction and edification of Friends.
From there John went to West Chester, on the main, and I went to Flushing,
where we had a large, open meeting: it was a solid, good time,
and the sacred name of Him who lives forever, was praised.

From Flushing I went with my old friend and schoolfellow, Joseph Latham, to his house.
Our conversation was pleasant and comfortable to each other,
wherein we remembered our walking to and from school,
in the suburbs of that great and populous city, London when we were beaten,
stoned and abused, only for being the children of those called Quakers.
The priests, who had money for preaching,
had preached and printed so many lies against our friends,
that the common people were almost ready to make a sacrifice of us; they telling us,
when we pleaded our innocency by saying we went quietly along the streets to school,
that "`It was no more sin to kill us, than to kill a dog:`" but now,
through the grace and favour of the Almighty, we enjoy the exercise of our religion,
according to our consciences, free from jails and prisons,
in which our primitive friends suffered much;
for which we ought to be truly thankful to the God and Father of our Lord Jesus Christ.

From Joseph Latham`'s we went to Westbury and Matinicock, after a meeting at Cowneck,
and to New York, where I had also religious service and a meeting;
and from New York I took my passage in Robert Bowne`'s sloop, for Newport,
on Rhode Island, was two days and nights on the water, and on my arrival at Rhode Island,
the brethren lovingly received me, and we were joyful to see each other.

After having had several good meetings on Rhode Island, I went to Dartmouth,
where we had a large, serviceable meeting at a place called Aponyganset,
many hundreds being added to the church since I first visited those parts.
From this place I went to Holder Slocum`'s,
and he lent us his shallop to go over to Nantucket; but the wind not favouring,
we had a satisfactory meeting at a large farm of his on an island bearing his own name,
and after meeting set sail for Nantucket, had several large meetings there,
and I rejoiced to see the growth and increase of Friends on this island;
where God has greatly multiplied his people, and made them honourable;
glory to his name forever.

The priests, who have money for preaching; the lawyers, who have it for pleading;
and the physicians, who have money for giving receipts for health;
are poor trades on this island.

I had been at Nantucket about thirty-nine years before,
at which time there were only two men and one woman who joined with our friends in profession,
and now it was computed there were above a thousand who went to our meetings,
they being a sober, religious people;
and there is a great increase of Friends in various other places in New England;
and whereas formerly we were greatly persecuted for our religion,
now we are treated with more civility and respect in those parts.
