== Chapter XI

From Nantucket, Nathaniel Starbuck and Elijah Collins went with me,
with several other Friends, to the yearly meeting at Rhode Island;
which was so very large, that it was difficult to speak so as to be heard all over it;
but the last day our friend John Fothergill, who had a high voice,
being attended with the divine power, gave good satisfaction to the meeting,
and it ended well.
After this meeting was over, I went with Benjamin Bagnal, to Boston,
and from there to Lynn and Salem, and had several satisfactory meetings,
which tended to unite our hearts together in the love of Christ,
and the fellowship of his gospel.
From Salem I went with Zaccheus Collins and his wife to their house,
and lodged there three nights, and was lovingly entertained,
as I was also at many other Friends`' houses.
From Lynn Zaccheus Collins accompanied me to Boston,
where we had a meeting on a fourth-day of the week,
and the next day there was a very large meeting,
the greatest gathering of people which had been seen
at Friends`' meetinghouse for a long time,
occasioned by the marriage of John Mifflin, of Philadelphia,
to Benjamin Bagnal`'s eldest daughter.

From Boston I returned to Rhode Island,
and had several meetings at Newport and Portsmouth,
wherein our hearts were made glad in Christ,
and we were strengthened in our faith in him; blessed be his holy name forever.

From Rhode Island, I went to Conanicut, and to Kingston in the Narraganset country,
and had meetings, and then back to Rhode Island again,
and by water in company with several Friends to Greenwich,
where I was at two large meetings:
at this place they showed me the trees under which about forty years ago I had a meeting;
but now they have a pleasant meetinghouse.

The next first-day, I was at a large, solid, edifying meeting,
in a new meetinghouse at Tiverton.
From there I went to visit Joseph Wanton`'s wife, who had been long sick;
and in her chamber, with several of her friends and relations,
I had several religious seasons, with which she expressed much satisfaction;
she died of this sickness, and I was at her burial, which was large,
she being well known, and beloved.
Next day I was at an appointed meeting at Portsmouth, which was large,
and to satisfaction, for which we blessed the holy name of God.
I had many good opportunities on Rhode Island in private families,
and was at several meetings over the Beach, at John Easton`'s,
who was about ninety years of age; he had travelled with me when I was a young man;
we took leave of each other, not expecting to meet more in this world.

After many meetings on Rhode Island, I took my passage for Long island,
in my return homeward; and after a boisterous passage,
and being four nights on the water,
I got well again to my loving friend Joseph Latham`'s, where I had left my horse,
and on fifth-day had a meeting at Cowneck, where I met with Elijah Collins, Rose Tibbets,
and Patience Barker, we rejoicing to see each other, after their long journey by land,
and mine by water, they being likewise going for Pennsylvania.
These Friends went to Flushing first-day meeting, and I to Westbury,
where was a large meeting, in which there was a drunken schoolmaster, who disturbed us,
though at last it ended quietly, and I hope well also.
The next fourth-day I was at the monthly meeting at Westbury,
where many Friends met from various quarters, and it was a solid good time.
We had a meeting at Thomas Rodman`'s, who was unwell,
and had not been at a meeting for some months; he took our visit kindly,
expressing his love to us; we had also a meeting at Jeremiah Williams`',
to good satisfaction.

Fifth-day we had a large gathering at Matinicock,
and in the evening a tender broken meeting at Samuel Underbill`'s,
and sixth-day a good one at Newtown,
wherein primitive Christianity was opened and experimentally declared to the people;
and in the evening we had a good opportunity to declare
the truth of Christ at the house of Richard Hallet,
among several of his sober neighbours.
Next morning being the seventh of the week, we went to West Chester to a yearly meeting,
which was much crowded and the people very unsettled,
so that it was not so satisfactory as could have been desired.
After meeting we went over again to Long island, and then to New York,
where we had a large quiet meeting in the evening.
At New York on third-day morning, several dear friends accompanied us to the water side,
where we solemnly took leave of one another in the love of Christ,
and in the fellowship of his gospel; some of us not expecting to see each other any more.

Passing over Long and Staten islands to Elizabeth town, we travelled to Rahway,
and had a meeting on a fourth-day in the evening, where many neighbours came.
After meeting a certain person was dissatisfied about
women`'s public speaking in religious meetings;
Rose Tibbets having publicly exhorted them in this
meeting to be religious and to fear God,
and having prayed to God for us all, and praised his holy name,
the said person desired we would endeavour to satisfy him about it,
inasmuch as the apostle Paul forbade it, as he apprehended.
To which it was answered, that the apostle Paul only forbade,
or did not permit forward or busy women, to speak or ask questions in the church;
but advised them to ask their husbands at home,
and that doubtless he never intended to debar such godly women,
who had a real necessity laid on them, and were concerned by the Almighty,
to speak unto or pray for the people,
else he would not have showed them how they ought to behave themselves in the service.
For if he had any design to hinder such, whom the Almighty should call to this work,
then he must have contradicted himself,
where he shows how they must behave themselves in their duty of speaking or praying,
and he would likewise thereby have opposed the apostle Peter, who said,
Now is fulfilled the prophecy of the prophet Joel,
that in the latter days sons and daughters should prophesy.
So that it is clear and plain,
they who would limit or silence those who have a
gift from God to preach or pray in public,
from the words of the apostle Paul, oppose him to himself, and to the apostle Peter,
and also to the prophet Joel.

From Rahway we went to Woodbridge, where we had a meeting,
and there I parted with my fellow travellers, having a concern,
though much in the cross to my own will,
to go back in the woods to a meeting about eight or nine miles off;
which meeting was much to my own satisfaction, as well as of those present,
as many of them expressed.

From this place I went to Stonybrook, and had a pretty large meeting,
considering it was rainy, in the time of the meeting`'s gathering.
At this place, my son-in-law, Isaac Brown, with several Friends, came to meet me,
whom I was glad to see, and after meeting went with them to Trenton,
and next day to Bristol, it being their third-day meeting, which was large,
and after meeting went home to Frankford,
and there was lovingly received by my wife and family.
In this journey I was from home three months and nine days, had fifty-five meetings,
and travelled by land and water above a thousand miles.
I may truly say,
that therein I was favoured with the divine presence and grace of God by Christ,
in a good degree, and also with the fellowship of many sincere believers in him,
which in my return caused my soul to bless his holy name, who lives forever.

In the sixth month, after having had various meetings at and about home, I went to Darby,
Chester and Newcastle, having meetings in each place,
which were to the tendering of some mournful souls, and to their comfort and strength.
From Newcastle I ferried over Delaware river to Penn`'s-neck, where I had a meeting,
at which were several that had never been at any of our meetings before,
who went away well satisfied.
From there I went to Salem monthly meeting, which was very large,
and to Cohansey to the third-day meeting, and stayed till next first-day meeting,
which though small, by reason of rainy, stormy weather, was a very precious time.
After I had negotiated some affairs at Cohansey, I returned to Salem,
where I met with my fellow traveller, Elijah Collins, of Boston,
with whom I went on to Philadelphia, and from there home;
having much satisfaction in this journey, in which I had nine meetings,
and travelled about one hundred and fifty miles.
I cannot be clear in my mind without saying that I did not,
nor do I study what to preach to the people.
Nor did I, nor do I receive any pay or outward consideration for preaching, it being,
as I really believe, contrary to the doctrine of Christ, and his apostles and disciples.

This fall I visited several of the meetings of Friends in Bucks county,
and the meetings at and about home, as at Frankford, Philadelphia, Abington,
Byberry and Germantown.
In the ninth month I was appointed with several other Friends, by our monthly meeting,
to visit the families of Friends in Philadelphia.
My lot was to visit the upper part of the city, in company with Phebe Morris,
Hannah Parrock and Daniel Stanton; in which service we were of one heart and mind,
and performed it in pure self-denial, and in the cross of our holy Lord Jesus Christ.
And wonderful it was,
how the presence and goodness of God went with us from house to house,
and opened the states and conditions of the families to us,
to the tendering of many hearts, both of parents and children.
We visited about forty families of Friends, when the winter setting in,
and I being but weakly, having had a sharp spell of the fever, we by consent,
were willing to defer the conclusion of this work until longer days and warmer weather.

In this month I was sent to, in order to be at the burial of the wife of Richard Smith,
Jr. She was a virtuous woman, and well beloved,
at whose funeral were many of her neighbours and friends.
It was a very solemn time,
in which meeting it was desired that those who had lost their parents,
would live so that they might not be a dishonour to them;
for it was observed of some children, after their parents were dead,
they grew worse than when they were alive, taking undue liberties,
which their fathers and mothers could not have allowed of,
which was a sore grief and trouble to their friends, and such as wished them well.
Therefore they were exhorted not to do that when their parents were dead,
which they would not have done if they were living; which would be heavy on them,
and tend to bring a blast on them in this world;
and they were desired to consider how they would answer it in the world to come.

It was also observed,
that sometimes the death of parents had a good effect on sober young people,
they being thereby led more seriously to think on their own mortality,
and to consider the great loss of their careful and religious fathers and mothers,
and the good example and counsel they gave them.
This meeting concluded with a solid, weighty frame of mind in many.
From Burlington I went to Mount Holly, had a large meeting at the meetinghouse,
and another in the evening at Mount Holly town, at the house of Thomas Shinn;
both of which were open, and some people not of our profession were there,
who were well satisfied.
I then went to Evesham, Chester and Haddonfield,
at all which places I had large meetings, and back to Burlington,
and was at their fifth-day meeting.
From Burlington I went with Richard Smith, Caleb Raper and Jonathan Wright,
to visit a Friend who was sick, after which the said Friends accompanied me to the ferry;
and I rode home, where I found my family well, for which I was thankful.

In the forepart of the tenth month, our worthy friend John Fothergill,
sailed in the brigantine _Joseph,_ Ralph Loftus, master, for Barbados,
he having made a third visit to America from Europe, on a religious account.
His visit was acceptable and serviceable, and we parted in great love and tenderness.
The night before, about the eleventh hour, was an earthquake,
which was the greatest known in this province,
the whole city of Philadelphia being shaken, and most part of the adjacent provinces,
though little or no damage was done thereby,
which shows the abundant mercy of a merciful God; as also,
if it were the pleasure of his will,
how soon he can lay cities and countries waste and desolate,
and bury thousands in a moment.
But notwithstanding the mighty power of the eternal Jehovah,
Oh! how hard are the people`'s hearts, and how they hate to be reformed,
and how unconcerned are the inhabitants of the land about their eternal peace and well-being!
This is really lamentable.
Oh! how do earthly mindedness, pride, covetousness and drunkenness abound,
with many other evils,
which were scarcely known among the first settlers of this peaceful,
and now plentiful land of Pennsylvania.

The 26th of the twelfth month, being the first-day of the week, was buried at Merion,
Edward Jones, aged about ninety-two years.
He was one of the first settlers of Pennsylvania, a man much given to hospitality,
a lover of good and virtuous people, and was beloved by them.
There were many hundreds of people at his funeral.
I had a concern to be at this meeting before I left my place at Frankford,
and before I heard of this Friend`'s decease.

The beginning of the first month, being the fifth-day of the week, I was sent to,
in order to be at the burial of Hannah, the wife of John Mickle, at Newtown,
in West Jersey.
My kinsman, Daniel Stanton, was with me.
It was a solid, heart melting time; my heart was broken into tenderness with many others.
The deceased was much beloved by her friends and neighbours,
and there was much mourning among her relations, by whom she will be greatly missed.
The people were desired earnestly to prepare for their latter end and final change;
and that as we had all reason to hope it was well with our deceased friend,
we might likewise have a well grounded hope that it would be well with ourselves,
when we came to put off mortality and put on immortality.
The meeting ended with fervent supplication for our future well-doing and well-being,
both here and hereafter, and praise to the Most High, who is alone worthy forever more.

As soon as I returned to Philadelphia on the sixth-day of the week,
I heard of the death of Joseph Kirkbride, at Israel Pemberton`'s,
who told me I was desired to be at his burial.
He, his son and William Logan, accompanied me as far as Samuel Bunting`'s that afternoon,
with which journey I was exceedingly tired,
so that I could hardly stand or go when I alighted off my horse,
but being refreshed with a good night`'s rest,
I went in the morning to the house of my deceased friend.
There was a multitude of people at the burial,
among whom we had a good opportunity to invite them to lay hold on truth and righteousness,
and prepare for another world.
They were reminded that neither natural wisdom nor riches, youth nor strength,
crowns nor sceptres, could secure them from the stroke of death.
Robert Jordan was at this meeting and had good service therein;
it concluded in supplication for the widow and fatherless, and for mankind universally.
Fourth-day being the 4th of the first month,
I was at Middletown meeting in company with Thomas Brown,
wherein the divinity of Christ and his being made flesh, born of a virgin, crucified,
dead and buried, and his being raised from the dead by the divine power,
were largely opened to the people,
and that the same power must be witnessed to reform our lives,
and give us the true saving faith in, and knowledge of God the Father,
and Christ the Son, and of the Holy Spirit.

This month at our general spring meeting,
I acquainted Friends that I had a desire once more to see my friends in Virginia,
Maryland and North Carolina, if health and strength did permit,
and divine Providence favoured,
not having yet fully recovered my former health and strength:
the meeting consented to my request.

The latter end of the first month I was at the burial of Robert Evan, of North Wales;
he was upwards of fourscore years of age, and one of the first settlers there.
A man who lived and died in the love of God and his neighbours,
of whom I believe it might be truly said, as our Saviour said of Nathaniel:
"`Behold an Israelite indeed, in whom there is no guile.`"
He was a minister of Christ, full of divine and religious matter.
In this month I was at Fairhill,
at a meeting appointed for Ruth Courtney and Susannah Hudson,
who were on a religious visit from Ireland to Friends in this and the adjacent provinces.
It was a good meeting, the Friends speaking to the state thereof.

The beginning of the second month I went over the Delaware, and so to Cohansey,
intending home before I set out for my journey to the southward;
but my affairs not answering so as to come home,
and afterward to reach the yearly meeting of Friends at West river,
which I proposed to our general meeting;
I wrote to my wife and family that I intended to proceed to West river meeting,
it saving me much time and riding; and after having been at several meetings at Cohansey,
and at the yearly meeting at Salem, and at a meeting at Pilesgrove;
being accompanied by a Friend of Salem, I proceeded and went over Delaware river,
and first had a meeting at George`'s creek,
and from there to the head of Sassafras river, where we had a meeting,
but by reason of the wet weather it was small.
We travelled to Cecil meeting, and so on to Chester; then to Queen Ann`'s county,
and from there to Newtown, on Chester river, where we had a large satisfactory meeting;
in which it was shown that no Christian might or could break the moral part of the law;
for, said the apostle, it is a school master to bring to Christ,
and that those who come to the gospel of Christ,
can in no way break the least commandment of God.
For example; the law says, You shall not forswear yourself; but if a man,
according to Christ`'s gospel, swears not at all, then that man cannot forswear himself.
Again the law says, You shall love your neighbour and hate your enemy; but Christ says,
love your enemies; the which if we do,
there is no doubt but we shall love our neighbours.
Those things were largely spoken to and opened in the meeting, and the people,
many of whom were not of our Society, were very attentive and sober,
and the good hand of the Almighty was among us.

From Chester river we crossed Chesapeak bay to the yearly meeting at West river,
where we met with our friends Michael Lightfoot, Elizabeth Wyat and Grace Mason,
with several others;
Elizabeth and Grace being on their return home from
a religious visit to North Carolina and Virginia.
We all being far from home and well acquainted, were glad to see one another,
being thankful to the Almighty, who had been pleased to preserve us so far on our way.

After the meeting was ended at West river,
taking leave in the love of Christ of many Friends,
with hearts full of love and eyes full of tears,
as never expecting to see one another again, I with my companion and Armiger Trotter,
who came up with the Friends from Virginia to West river, set out for Virginia,
and having passed over Patuxent river, had a meeting among the family of the Plummers,
one of whom, with another Friend, accompanied us to the river Potomac;
we rode as nearly as we could compute sixty miles that day.
I being heavy and aged and the weather hot, was very much tired,
and laid down in my clothes all night,
and the next morning ferried over the river Potomac, computed about three miles,
and parted with our guides.
When over this river we travelled fifteen miles to William Duff`'s, had a meeting there,
and from there to a meeting of Friends at John Cheagle`'s, and so to Black creek,
had a meeting there,
and then went to the monthly meeting of Friends on the west side of James`' river,
and to the monthly meeting at Nansemond river, and from there to Carolina,
and on a first-day had a large meeting at a new
meetinghouse built to accommodate the yearly meeting;
it was a good, solid meeting, and there Friends appointed several meetings for us;
after attending which we went to the quarterly meeting for Friends in North Carolina,
which was very large.
The people were exhorted to overcome sin as Christ overcame,
that they might sit with him in his kingdom, as he overcame,
and is set down in the kingdom of God his Father: that subject was largely spoken to,
and we had a good opportunity with the people,
and the great name of God was exalted over all.

After this quarterly meeting we had a meeting at James Wilson`'s, in the barrens,
which was a large, good, and open meeting: in the conclusion thereof,
I told them that I came among them in great love, though in a cross to my own will,
with respect to my age and the heat of the weather,
being willing to see them in that province once more before I left this world;
and as I came in love, so I parted with them; desiring them to dwell in love and peace,
and then the God of love would be with them.

From Carolina we travelled into Virginia, Zachariah Nixon accompanying us,
and had a meeting at the widow Newby`'s, and then at Nansemond and the Branch;
many people were there not of our Society, and were very attentive and sober.
Next day being the second of the week, we had a satisfactory meeting at Bennet`'s creek;
then to Chuckatuck, Rasper-neck, Pagan creek, and into Surry county,
to Samuel Sebrell`'s; then to Robert Honicut`'s, had a meeting there; then to Curl`'s,
up James`' river; to Thomas and John Pleasants`', and then to the Swamp and Cedar creek;
and so on to John Cheagle`'s.

We came to his house on fifth-day, the 20th of the fifth month;
and being unwilling to be idle on sixth and seventh-days,
intending to have a meeting at his house on first-day,
we appointed one about three miles, and another about six miles off;
at which places we had good service: and then had a very large meeting at his house,
on first-day, which was, I hope, to pretty general satisfaction,
to the religious part of the people.
From there we travelled to William Duff`'s, and had a meeting at their meetinghouse;
and afterwards William went with us over Potomac river, as far as Piscataway,
in Maryland.
This river is computed to be nearly four miles over, and when we were about the middle,
there was a large swell, and the motion of the boat made our horses fall down,
and the boat having much water in it, being very leaky, was near oversetting.
Those in the boat were in some concern and consternation, saying,
when we came to the shore,
that they did not remember they were ever before in the like danger.
I apprehend we were in danger; and if the boat had overset, in all likelihood,
we might have been drowned.
And I then thought I was in the service of Christ, my great master,
and I also knew I must die, and I thought I might as well die in his service as my own;
so I gave up my life for Christ`'s sake, and he gave it to me again.
Oh! may I, with all those who sincerely love him, serve him truly all our days,
is my desire!

From Piscataway we travelled to Patuxent, to the family of the Plummers,
who were ten sons of one father and mother,
and were convinced about the time I first had meetings in those parts,
and so far as I know, they are all sober men.

After this meeting we went to Gerard Hopkins`', then to Patapsco,
and had a large meeting, the house being full before the Friends came,
so that they could hardly get in; to me it was a good, seasonable opportunity,
as was our next in the forest of Gunpowder river;
where Friends have built a new meetinghouse, which, at this time,
could not contain the people.
From Gunpowder river we went to Bush river, had a good, open meeting,
and one at Deer creek, and so over Susquehanna to Elihu Hall`'s.

At West Nottingham I parted with my companion, he having about a day`'s travel home.
I had two meetings on first-day at the great meetinghouse at West Nottingham,
which were very large, and Friends glad to see me once more.
After having meetings at Christiana bridge, Wilmington, Center and Kennet,
I went to the quarterly meeting of ministers at Concord,
and was there first and second-day, and third-day at Darby;
all which were very large meetings, and Friends were satisfied and comforted,
and I was encouraged in the work and service of the gospel of Christ.
From Darby I went home, having been abroad about four months, and rode, by computation,
above eleven hundred miles, and was at about seventy meetings.

While I was on this journey, I had an account of the death of my dear and only brother,
George Chalkley, a religious, prudent man; he died the 24th of the ninth month, 1737,
near the seventieth year of his age,
and left behind him a mournful widow and four daughters, all virtuous women.

When in Virginia, I wrote to those of our Society at Opeckon, Shenandoah, etc.,
many of whom went out of our province to settle in the government of Virginia;
to the following effect.

[.embedded-content-document.epistle]
--

[.letter-heading]
To Friends of the Monthly Meeting at Opeckon.

[.signed-section-context-open]
Virginia, at John Cheagle`'s, 21st of Fifth mo., 1738.

[.salutation]
Dear Friends, who inhabit Shenandoah and Opeckon,

[.numbered-group]
====

Having a concern for your welfare and prosperity, both now and hereafter,
and also the prosperity of your children, I had a desire to see you;
but being in years and heavy,
and much spent and fatigued with my long journeys in Virginia and Carolina,
it seems too hard for me to perform a visit in person to you;
therefore I take this way to discharge my mind of what lies weightily thereon: and,
_First;_ I desire that you be very careful, being far and back inhabitants,
to keep a friendly correspondence with the native Indians,
giving them no occasion of offence; they being a cruel and merciless enemy,
where they think they are wronged or defrauded of their right,
as woeful experience has taught, in Carolina, Virginia and Maryland,
and especially in New England, etc., and,

[.numbered]
_Second;_
As divine Providence has given them and their forefathers
the possession of this continent of America,
or this wilderness, they have a natural right thereto, in justice and equity;
and no people, according to the law of nature and justice, and our own principle,
which is according to the glorious gospel of our dear and holy Lord Jesus Christ,
ought to take away, or settle on other men`'s lands or rights, without consent,
or purchasing the same, by agreement of parties concerned;
which I suppose in your case is not yet done.

[.numbered]
_Third;_ Therefore my counsel and Christian advice to you, is, my dear friends,
that the most reputable among you, do, with speed,
endeavour to agree with and purchase your lands of the native Indians or inhabitants.
Take example of our worthy and honourable late proprietor, William Penn;
who by his wise and religious care in that relation,
has settled a lasting peace and commerce with the natives,
and through his prudent management therein,
has been instrumental to plant in peace one of the
most flourishing provinces in the world.

[.numbered]
_Fourth;_ Who would run the risk of the lives of their wives and children,
for the sparing a little cost and pains?
I am concerned to lay these things before you, under an uncommon exercise of mind,
that your new and flourishing little settlement may not be laid waste,
and if the providence of the Almighty does not intervene,
some of the blood of yourselves, wives or children, be spilled on the ground.

[.numbered]
_Fifth;_ Consider you are in the province of Virginia,
holding what rights you have under that government;
and the Virginians have made an agreement with the natives,
to go as far as the mountains, but no further; and you are over and beyond the mountains,
therefore out of that agreement;
by which you lie open to the insults and incursions of the southern Indians,
who have destroyed many of the inhabitants of Carolina and Virginia,
and even now have destroyed more on the like occasion.
The English going beyond the bounds of their agreement,
eleven of them were killed by the Indians while we were travelling in Virginia.

[.numbered]
_Sixth;_
If you believe yourselves to be within the bounds
of William Penn`'s patent from King Charles II.,
which will be hard for you to prove, you being far to the southward of his line; yet,
if done, that is of no consideration with the Indians, without a purchase of them;
except you will go about to convince them by fire and sword, contrary to our principles;
and if that were done, they would ever be implacable enemies,
and the land could never be enjoyed in peace.

[.numbered]
_Seventh;_ Please to note that in Pennsylvania no new settlements are made,
without an agreement with the natives; as witness Lancaster county, lately settled;
though that is far within the grant of William Penn`'s patent from King Charles II.,
therefore you lie open to insurrections of the northern as well as southern Indians.

[.numbered]
And _lastly,_ thus having shown my good will to you and to your new settlement,
that you might sit every one under your own shady tree, where none might make you afraid,
and that you might prosper naturally and spiritually, you and your children;
and having in some measure eased my mind of the weight and concern that lay upon me,
I subscribe in the love of our holy Lord Jesus Christ,

====

[.signed-section-closing]
Your real friend,

[.signed-section-signature]
Thomas Chalkley.

--

After my return from this journey, I stayed much at home that winter,
travelling being now hard for me, so that I could not perform long journeys as formerly,
being more broken in the long and hard travelling in this journey,
than in several years before.

In the year 1739, I took several short journeys, in Salem and Burlington counties,
in West Jersey, and in Philadelphia, Chester and Bucks counties, in Pennsylvania,
having many large and comfortable meetings,
and some satisfactory service in several of them.

This year the war broke out between Great Britain and Spain;
the Spaniards giving great occasion of offence to the British nation;
notwithstanding which, King George II sought to accommodate matters peaceably;
but the crown of Spain not complying with the terms agreed on for an accommodation,
war was proclaimed;
which occasioned much disturbance and distraction in our peaceable province and government.
War being destructive to life, health and trade, the peace and prosperity of the people,
and absolutely against the doctrine and practice of the Prince of life and peace,
our Lord and Saviour Jesus Christ;
a great concern came on my mind to promote his doctrine;
in order to which I was largely concerned to treat
thereof at the general spring meeting at Philadelphia;
with which service several wise and pious people were well satisfied,
though some were offended.

When the meeting was over,
having a desire and concern once more to visit Friends in the lower counties, Newcastle,
Kent, and Sussex, among whom I had not travelled for nearly twenty years,
and being now a little better in health than I had been, I set out from my home,
and went to Chester, and from there to Wilmington and Newcastle, where we had meetings;
William Hammond being with me.
We had meetings at George`'s creek, Duck creek, and Little creek,
and proceeded to Motherkill, where I had a large, open time,
in preaching the gospel to the people, which many of them received with gladness.
There were many, not of our Society, who were very sober and attentive,
a door being open among them; yet,
notwithstanding there may be much openness both in speakers and hearers,
I have observed with sorrow,
that there are but few who retain the truth so as to be really converted;
many are convinced, but few converted and come to be regenerated or born again,
as our Saviour taught.

From Motherkill I went back to Little creek and Duck creek,
and from there to Appoquinimink to the burial of a Friend`'s son,
who died of the smallpox; on which occasion we had a solid meeting,
the mournful relations being thankful for our company.
I then went to John M`'Cool`'s, and to Newcastle; where we had a large, open meeting,
to the satisfaction of many; though I was very weakly and poorly, as to my health,
so that it was hard for me to stoop to take anything from the ground,
and with difficulty I walked from the Friend`'s house to the meeting;
but being helped by grace and carried through the service of the meeting beyond my expectation,
was, with several others, truly thankful to God the Father, and Christ,
my Lord and Saviour.

From Newcastle I went to Wilmington, had a meeting there, and to Newark,
to the marriage of Alexander Seaton.
The meeting was uncommonly large, and to general satisfaction.

From Newark I went to Center monthly meeting, and to Kennet,
where was a very large meeting.
Here many who had professed among us,
refrained coming to the public meetings for divine worship; with whom,
next day we had a meeting,
wherein the evil consequence of forsaking the assembling
ourselves together was spoken to,
and that it would be a great hurt to the young and rising generation,
and themselves also; being a bad example to them,
and contrary to the advice and counsel of the holy apostle,
"`Not to forsake the assembling ourselves together, as the manner of some is.`"

From Kennet I went to Concord, to the burial of Benjamin Mendenhall,
where we had a large and solid meeting, several lively testimonies being borne therein.
This Friend was a worthy elder and a serviceable man in our Society,
and one of the early settlers in Pennsylvania; a man given to hospitality,
and a good example to his family, and has left several hopeful children surviving him.

The night before this meeting I lodged at the widow Gilpin`'s, whose husband,
Joseph Gilpin, was lately deceased.
There was true Christian love and friendship between us for above fifty years.
When first I saw Joseph in Pennsylvania, he lived in a cave in the earth,
where we enjoyed each other`'s company in the love and fear of God.
This Friend had fifteen children,
whom he lived to see brought up to the states of men and women,
and all but two married well, and to his mind.

From Concord I went to Wilmington, and after meeting to Newcastle,
where with George Hogg, I went over the river Delaware into Penn`'s-neck,
and had a meeting at James Wilson`'s. Then to Salem and Cohansey,
where I had several meetings at Greenwich, and at the head of Alloway`'s creek;
also at David Davis`'s,
where the people kindly lent us the benches of their meetinghouse,
and many of them came, and were very attentive; after which I went to Pilesgrove,
and had a meeting there, and to Woodbury creek, and from there home,
having travelled about five hundred miles in this journey.
I stayed at and about home for some time.

I was at the yearly meeting at Burlington in the seventh month;
in going to which my horse started and threw me, and hurt my shoulder and hip badly,
of which I did not recover for above half a year.
This meeting was very large, and though I was outwardly in pain,
yet in the sense of the love and goodness of God and grace of our Lord Jesus Christ,
I was, with many others, much comforted in spirit.

From Burlington I travelled to Shrewsbury, having several meetings by the way;
as at Bordentown, Crosswicks, Trenton, etc.
This journey I rode in much pain; but the satisfaction I had in meetings,
through the spirit and power of the Most High,
made amends for all the labour and pain I underwent.
I bless the sacred name of God, and may I do it forever!
I made what haste I could home, being in pain with my fall,
and tarried at home most of the winter,
which was one of the longest and hardest known in
these parts by some of the oldest livers;
people being frozen to death in several places, and many sheep and cattle perishing,
and much of the winter grain killed with the frost,
so that there was some apprehension of a lack of bread:
all which I took to be warnings of the just and righteous judgments of God for the ingratitude,
pride, and other sins and iniquities of the people,
of which I was at many times and places, concerned to put them in mind.
How well would it be if the people would lay the judgments of the Most High to heart;
and when they are abroad in the earth,
that the inhabitants thereof would learn righteousness!

After this winter I was at a general meeting at Germantown,
and at meetings at North Wales, Horsham and Byberry, and from there, with Joseph Gilbert,
went to Burlington, and was at a marriage, and then returned home.

In the second month I was under a religious engagement to visit
the meetings of Friends in Gloucester and Salem counties,
in West Jersey; and the 19th of said month I went over Delaware river,
and was at Haddonfield on a first-day, and third-day at Chester,
fourth-day had a meeting at the house of Josiah Foster, and fifth-day at Evesham;
from which meeting I went to John Estaugh`'s,
Ebenezer Large and Samuel Jordan being with me.
In the morning we went to Woodbury creek meeting, and next day down to Salem,
in order for the yearly meeting, which began on the 26th of the second month,
and was an extraordinarily solid meeting,
the divine presence and glory being richly manifested among us.

From Salem I went in company with John Evans and Elizabeth Stevens,
to Alloway`'s creek and Cohansey, where we had meetings,
I believe to the satisfaction of many.
Here I parted with said Friends, and not being well, I stayed at Greenwich,
and they went to David Davis`'s, in order for Pilesgrove meeting.

The 3rd of the third month, being the first of the week, I was at Cohansey meeting,
which was solid and weighty;
in which the mighty works of God and his wonderful
power were set forth to the people in several respects.

[.numbered-group]
====

[.numbered]
_First;_ As to the work of the creation of the heavens and the earth,
and of man to govern in the earth, reserving to himself the government of man,
to whom he gave a law, for the breach of which he was turned out of paradise,
and brought death into the world.

[.numbered]
_Second;_ Notwithstanding man`'s fall, God had love, mercy and compassion towards him,
and promised that the seed of the woman should bruise the head of the serpent,
who led them astray; which seed is Christ, whom all are commanded to hear,
believe and follow, in the practice of his holy doctrine,
which is contained in his words spoken to his immediate disciples and apostles,
and likewise made known and revealed in our hearts.

[.numbered]
_Third;_ That now in our day his righteous judgments are abroad in the earth, as the sword,
and a threatening of famine, or lack of bread:
all which was spoken in the tender love and fear of God and faith of Christ,
and all were entreated to lay these things to heart, and "`turn to the Lord,
and he will have mercy; and to our God, and he will abundantly pardon.`"
In this meeting God was glorified and his name magnified,
through the assistance of the spirit of his dear Son, our Lord.

====

From Cohansey I went to Salem, and to David Davis`'s, where we had a meeting,
at which were several people of various professions,
who were satisfied and edified therein; and from there we went to Pilesgrove meeting,
afterwards into Penn`'s-neck, and had a good open meeting at the widow Hugh`'s,
and so to Woodbury creek meeting, which I hope was serviceable.
After this I went home with my friend James Lord`'s widow, who,
with Joseph Clews and her sister Ann Cooper, went with me to Gloucester jail,
where we visited one under sentence of death for stealing.
I asked him if he truly repented of that sin of stealing,
of which he had been so often guilty?
He told me he hoped he had, and was willing to die.
He was recommended to the grace of God, and to keep in a humble frame of mind,
and beg mercy of the Almighty for the sake of Christ, for all his sins.
While a Friend was praying by him, he was broken into tenderness.

Here the aforesaid Friends parted from me; I crossing the river Delaware to Philadelphia,
and so home to Frankford.
I was at ten meetings in this journey, besides the yearly meeting at Salem,
and travelled about one hundred and fifty miles; but travelling was painful to my body:
for now I more and more felt the effects of many old falls and bruises,
which much disabled and hurt me in riding.

In the fourth month I was at several meetings about or near home, as at Fairhill,
Germantown, a meeting at Thomas Roberts`'; and also at Philadelphia.
In the beginning of the fifth month I visited Friends`' meetings at Darby,
Merion and Haverford; at the last place the meeting was large and very open;
wherein the mighty power of God was exalted over all, and it was plainly manifested,
that if there was any virtue, or any good gift; or genius in the creature,
it derived its excellency from the Creator; and that man, in his best capacity,
in either natural or spiritual attainments,
has no cause to boast or glory in anything which he, as an instrument in the divine hand,
might help to perform;
therefore we ought to humble ourselves under the mighty hand of God,
attributing no glory to self, or the creature; but all glory and praise to the Creator,
who is in and over all blessed forever.

The 20th of the fifth month, I set forward on a journey,
in order to visit Friends at and near Burlington,
and was next day at a meeting at Bristol, which was large,
considering the heat of the weather, and the shortness of the notice.
On fourth-day, the 22nd, I was at Mount Holly, at the burial of our ancient friend,
Restored Lippincot: he was, as I understood, nearly a hundred years of age,
and had upwards of two hundred children, grandchildren, and great-grandchildren,
many of whom were at his funeral; the meeting was large, and thought to be serviceable.
After this meeting, I went with a few choice Friends to visit Susanna Fearon,
who had been long ill;
in which visit we were favoured with the divine presence and goodness of the Most High;
for which we returned him thanks and praise we then went to Burlington,
and next day had a meeting, which was an acceptable opportunity to many.

Next first-day, being the 27th of the month, we had a good solid meeting at Trenton;
and I went, with several Friends, to Bristol, and so home to Frankford;
and was thankful to the Almighty for the grace which he was pleased to bestow upon me,
a poor worm; and that, considering the extreme heat, I had my health better than usual.
After coming home, I visited meetings at Philadelphia, Haddonfield, Frankford, etc.

In the sixth month there was a great mortality in Philadelphia, and many were taken away;
on a fifth-day I was concerned to put the people in mind of it,
and of their own mortality, and exhorted them to prepare for it,
they not knowing whose turn it might be next,
nor the hour when death might come to their own habitations;
and was concerned in the same way, at several large burials.
In the meeting at Philadelphia,
they were told it was better to fall into the hands
of the Lord than into the hands of men:
and that since we had been settled in this province of Pennsylvania,
we were preserved from the hands of men; there having never been an enemy in it,
in a warlike way; our dependence being in Providence,
and our principle against war and against spilling human blood by wars and fighting,
according to the doctrine of Christ, the peaceable Saviour;
therefore I believe the hand of God was manifested in preserving us in peace;
yet I would not be understood to be against the magistrates
exercising the power committed to them,
according to just law; but national wars, woeful experience teaches,
are destructive to the peaceable religion of Jesus, to trade, wealth,
health and happiness.
Our dear Lord preached peace to the people, and against wars; telling his followers,
That they must love and pray for their enemies, and rather take a stroke or a blow,
than give one; and that they should not resist evil; which peaceable doctrine of Christ,
the Jews could not away with; no, no, by no means: "`Oh!`" say they,
"`if we let this man alone,
the Romans will come and take away our place and
nation:`" just as the people now say in this province,
to those peaceable men, who, for the sake of Christ and his doctrine,
cannot use the sword; "`The Romans will come and take our country,
if we do not build forts and castles, and have military preparations.`"

I wish it were not true, that some who profess this peaceable principle,
too much endeavour to smother, stifle, and keep under this peaceable doctrine,
through a slavish fear and distrusting divine Providence,
which may cause his hand to deliver us to the Romans indeed;
at which I should not wonder, since we distrust Him who has hitherto preserved us,
without our preparing for war, for more than fifty years.
To which I know it is objected;
"`But now there are abundance of people who are not of that principle.`"
I answer, then why did they come among us,
if they could not trust themselves with our principles, which they knew,
or might have known, if they would?
The king gave the province, and the government of it, to our worthy proprietor,
William Penn; who was a man of this peaceable principle;
for which the heathens loved him and honour his name and memory to this day,
and those of his Society and principles; whereof I am a living witness.
The sense of the sweetness and social life that the first settlers of
the province of Pennsylvania and the city of Philadelphia lived in,
makes me express myself in this manner:
"`Oh! that the inhabitants of the city and country,
did but live and dwell in that first love, and hold it fast;
then I believe that the Almighty would not permit any to take our crown:
which crown is righteousness, peace and love, through true faith;
which true faith works by love in Christ Jesus.`"

On the last day of the fifth month,
I acquainted my friends of the monthly meeting of Philadelphia,
with a concern I had been some time under, to visit the people in the Virgin islands,
and more particularly in Anguilla and Tortola;
in order to preach the gospel of our Lord Jesus Christ freely,
to those who might have a desire to hear, as the Lord should be pleased to open my way.
My friends having unity with me therein,
at their next meeting gave me a certificate of their concurrence: soon after which,
having settled my affairs and taken leave of my dear wife and daughter,
and the rest of my family and friends,
on the 19th day of the seventh month I embarked at Philadelphia in the sloop _John,_
Peter Blunder, master, bound for the island of Tortola.

We sailed down the river and came to anchor near Christiana creek that night,
in which there was a violent storm, which drove several vessels on the marshes;
so that when the tide ebbed, one might walk round them.
Next day we sailed to Reedy island, where we waited for a fair wind:
we sailed down the bay in company with two sloops, one bound for Bermuda,
the other for the island of Christopher`'s;
and left the Capes on the 23rd day of the month,
and in eighteen days from that time fell in with the island of Thomas,
and in one day more turned up to Tortola.

In this voyage we saw nine sail of vessels; but spoke with none of them:
had a rough passage, the wind being high and contrary above a week, and much rain;
yet through the mercy and grace of God, I was preserved above all fear,
except the holy fear of the living Lord, in which I blessed his holy name.

On the 12th day of the eighth month, John Pickering, the owner of the sloop,
who was likewise governor of the island, with his spouse, met me at the water side,
and lovingly embraced me, and led me up to their house,
where we had a meeting the same evening; and on the 15th of the month,
being the fifth-day of the week, we had a large, satisfactory meeting,
at which were many people, several of them not of our profession;
and I think the good hand of the Lord was with us.
I was concerned in this meeting to show that the last dispensation of God to mankind,
in and through his dear Son, is a spiritual dispensation; a dispensation of pure,
divine love, which is to last and be with the true believers in Christ forever,
according to his own doctrine in the New Testament.

On the first-day of the week and the 18th of the month, we had another meeting,
larger than the former,
and the governor told me he had never seen so large a gathering on the island,
on any occasion.
My spirit was much set at liberty in this meeting,
and great openness and brokenness was among the people,
so that the gospel was freely and largely declared to them.
The case of Cornelius and of the apostle Peter going to his house, was treated of,
with other matters tending to edification.
I was so affected with the power, spirit and grace of our Lord Jesus Christ,
that when the meeting was over I withdrew,
and in private poured out my soul before the Lord,
and begged that he would be pleased to manifest his
power and glorious gospel more and more.
At this meeting there was a woman who had suffered much for going to meetings;
her husband being a proud, haughty man, had beaten her to the drawing of blood;
he also drew his sword and presented his pistol, with threatennigs to kill her;
but she thanked God that she was resigned to lose her life for Christ`'s sake.
She expressed some words in supplication in this meeting in a broken manner.
There was also a young woman,
whose father had turned her out of doors for coming to Friends`' meetings.

I went with the governor and his wife, to visit a few families up in the mountains,
and had a meeting, in which was great brokenness and tenderness in the time of prayer.

On second-day we visited several families in the division called the road,
to which we went by water in a coble, somewhat like our canoes;
there were four of these in company, five persons in two of them,
and seven in the other two.
In this visiting of families, the people came and filled the rooms,
and we had seasonable meetings, in which the people were so loving and well affected,
that we could seldom go in a friendly way to visit our friends,
but they would presently fill their rooms, and we scarcely could depart,
without having a time of worship.

Next day we went to visit a young man`'s habitation,
and the neighbours coming in as usual, we had a good meeting.

I cannot but note that the hand of the Lord God was with us,
and I felt his visitation as fresh and lively as ever; for which I was truly thankful,
and thought if I never saw my habitation again,
I was satisfied in this gospel call and religious visit; though being in years,
it was sometimes a little troublesome to the flesh;
being in the sixty-sixth year of my age,
and stiff in all my limbs from hurts with many falls and bruises.
As to my health, I had it better now than for several years past;
for which I am humbly thankful to Him, in whom we live and have our being;
glory to his name, through his dear Son.

Third and fourth-days, visited several families, and had several good opportunities:
in one of those meetings, a young man named Jeremiah Martin,
spoke a few words in prayer in which season we were, I think, all broken into tenderness;
so that in truth we might say, that the power and Spirit of Christ was with and among us,
and his great name was praised.

Fifth-day being the week-day meeting,
it was larger than was ever known on a weekday in that place;
there being many Friends who came from an island called Joseph Vandike`'s,
and many neighbours and sober people, who were very attentive.

Sixth-day was at several people`'s houses, and had religious meetings;
which we could not well avoid,
the people were so loving and desirous to hear what might be spoken to them;
many of them being like thirsty ground needing rain,
and our good and gracious Lord gave us celestial showers, which were refreshing to us,
and thankfully received.

Seventh-day I went with several Friends to the house of one who, with his wife,
had been at our meeting on fifth-day; he kindly invited me to his house;
his name was Blake; he and his wife were loving;
and though he had formerly written against Friends, he was now better informed.
From his house I went to Townsend Bishop`'s,
and there being many Friends from another island, we had a most comfortable,
tender evening meeting,
in which we offered up a sacrifice of praise and thanksgiving
to the holy name of the living eternal God,
and his dear Son our Lord and Saviour Jesus Christ,
through the influence of the holy Spirit, one God over all blessed forever.

On the first-day of the week, being the 25th of the month,
we had a larger meeting than ordinary; and in expectation of larger meetings than usual,
the governor, John Pickering,
had made several new forms to accommodate the people at his own house,
which he sent six miles on men`'s heads, the roads not being passable for carts, etc.
This I think worth noting, that their zeal may be had in remembrance,
and that others may be stirred up to more religious concern,
who will scarcely go six steps to a religious meeting, or will not go at all.
In this meeting I was concerned to speak of and set forth the doctrine of Christ,
which he preached on the mount, contained in the fifth,
sixth and seventh chapters of Matthew;
and to press the people to come to the practice of what is there
commanded by the great Author of the Christian religion;
and to show that the despised Quakers had learned, out of that excellent sermon,
much of their religion, which displeases many people,
and several of the great men of the world; and to urge them to regard the grace of God,
which brings salvation, and has appeared to all men.
In this meeting, Dorcas, the wife of John Pickering,
spoke to the people in public testimony, to which they gave good attention.

After meeting we returned by water from the Road Harbour to Fat Hog bay,
where John Pickering lives, being upwards of twenty of us in company, in three cobles.
These two weeks I spent in the island of Tortola, to my great satisfaction.

[.offset]
+++[+++The Journal of this worthy Friend ending here,
the following supplement is collected from some notes sent by a Friend of that island,
giving an account of his further services, sickness and death.]

[.old-style]
=== The Supplement: / Giving an Account of His Further Services, Last Illness, and Death.

On the second-day of the third week of his being among us,
he visited some Friends in the neighbourhood,
and likewise the man who had treated his wife so cruelly for coming to Friends`' meetings.

On third-day he was employed chiefly in writing to his family and friends in Philadelphia.

On fourth-day some Friends from the Road came to see him,
which prevented his going out to visit the neighbours as usual.

On fifth-day morning, being the 29th of the eighth month,
he found himself much indisposed; yet he went to our week-day meeting,
about a quarter of a mile.
When the meeting broke up, he had a hot fever upon him.
Doctor Turnbull, the chief physician in our island,
thought it proper to take some blood from him, and he being very willing,
it was done that afternoon, and the fever abated some time that night;
and next day he walked about,
and made no complaint until about eight o`'clock in the evening.
About this time the fever returned, and continued very severe till first-day morning,
when the doctor advised him to take a vomit, which he declined that day,
being desirous of attending the meeting which was held at my house, and was a large,
sweet, and tender meeting; in which he spoke to us concerning temptations,
and how Christ was tempted, and how to withstand them;
and afterwards on the parable of the great supper, and other subjects;
ending his testimony with the words of the apostle Paul, "`I have fought a good fight,
I have finished my course, I have kept the faith,
henceforth there is laid up for me a crown of righteousness:`" which words,
and most part of this last sermon, were delivered in great brokenness;
from which I judged he was sensible that he had not long to live,
though I believe he was not afraid to die.

On second-day morning the fever abated a little,
and he complied with the doctor`'s prescription of taking a vomit,
which seemed to have its proper effect; but that night the fever returned,
and continued on him until he died;
which was between two and three o`'clock on fourth-day morning,
the 4th day of the ninth month, being speechless about seven hours before.

A general invitation was given to Friends and others to his funeral;
where three testimonies were borne, all in great brokenness,
under a just sense of our great loss.
After which he was decently interred on the evening of the said day,
in a piece of ground which is since given to Friends for a burial place,
and on which a meetinghouse is built by John Pickering,
the governor of the island at that time.

It is said in the Scriptures, that the righteous are taken away,
and no man lays it to heart; but I hope it may be truly said,
this was not the case at this time; for Friends in general,
much lamented their great loss,
in being so soon deprived of so instructive a friend and elder,
whose care over us was very great; and who, by his loving and exemplary life,
and tenderness to people of all ranks and professions,
engaged the love and respect of almost all the people in the island.
We are fully assured that his labour among us was not in vain,
and that many have felt the good effects of it;
so that we believe some of the last words he spoke in public,
may justly be applied to him, and that he now enjoys a crown of righteousness.

[.asterism]
'''
