== God`'s Great Love Unto Mankind, / Through Jesus Christ, Our Lord.

"`And there came a voice out of the cloud, saying this (i. e. Christ) is my beloved Son,
hear him.`" Luke 9:35.

"`If you love me, keep my commandments.`" John 14:16.

"`For God so loved the world, that he gave his only begotten Son,
that whosoever believed in him might not perish, but have everlasting life.`" John 3:16.

=== PREFACE.

In sincerity and unfeigned love, both to God and man, were these lines penned.
I desire you to peruse them in the same love, and then, peradventure,
you may find some sweetness in them.
Expect not learned phrases or florid expressions;
for many times heavenly matter is hid in mean sentences,
or wrapped up in plain expressions.
It sometimes pleases God to reveal the mysteries of his kingdom,
through the grace of his Son our Lord Jesus Christ, to babes and sucklings;
and he often times ordains praise out of their mouths; one of which, reader,
I desire you may be.

My intent in writing these sheets, is, that they,
through the help of God`'s grace and the good Spirit of Christ,
may stir up true love in you; first to God and Christ, and then to man:
so you will be fit to be espoused to him, who is altogether lovely, that is Christ,
which is the desire of him who is your friend, more in heart than word,

Thomas Chalkley.

I HAVE been concerned for the good and welfare of
the children of men from my youthful days,
and tasted of the infinite love of God, in and through his dear Son, the holy Lamb Jesus,
who laid down his life for the sins of the world;
and in my tender years reaped great benefit, through faith in and obedience unto him.
And I have found by experience, that one without the other, that is, faith without works,
will not answer the end of the great love of Christ Jesus, our Lord,
who offered himself a sacrifice for all mankind; not for people to live in sin,
but to take away the sin of the world.
In a word, "`Faith without works is dead.`"
I found it so, and so must all true believers in the Son of God.

Christ first loved us and paid that debt for us, which, of ourselves,
we were not able to do.
Oh! his infinite love has often times melted my soul into tenderness.

I believe it is a great pity that the sons of men should requite evil for good,
or disobedience for such gracious obedience.
I would to God,
that all believers in Christ would live in that fear of God and that love to Christ,
which keep the heart clean; because nothing unclean can enter the kingdom of heaven,
I do not mean a slavish fear; but fear that is wrought by love:
for they who love the Lord, the great, everlasting God, will fear to offend him.

This is the matter that chiefly concerns my mind at this time;
the necessity of love to God and Christ, and one another.
"`Eye has not seen, nor ear heard,
neither have entered into the heart of man the things
that God has prepared for them that love him.`"
For my part I cannot pretend to tell you, Oh, man! to the full;
but only a little to hint at it: it is "`Joy unspeakable,
and full of glory:`" but then we must love him, so as to keep his commandments.
This is the work that I am very earnest in pressing people to, whether youth or aged:
it is not too soon for the young, nor too late for the aged,
to begin this work of obedience, through faith and love to God and Christ,
if his spirit is reproving or striving in them.
But it is more honourable and acceptable,
for a man to give up the strength of his days to serve the
Lord and to remember his Creator in the days of his youth,
before sin is rooted and grown in him;
for then it will be much more labour to get the root of unrighteousness plucked up.

In that ability which God has given me, I would endeavour to stir up all to serve him,
and to be in good earnest, and not to put the day of God, even the mighty Jehovah,
afar off; but to love the Lord unfeignedly, and with true obedience;
since that sacrifice only is acceptable to him; that is to say,
to love him in deed and in truth, more than in word and with tongue.
The Lord by his servant,
complained against a people in old time "`They draw nigh to me with their mouths,
and with their lips they do honour me:`" but their great misery was,
their hearts were far from him.
They did not love him with their whole hearts; this was their fault:
this thing is also a great evil in the sight of God, in our age;
and is too frequent in England, the land of my nativity,
as also in other islands and places beyond the seas.
What lamentation shall be taken up, for such as do so mock the Lord,
the great God of love?
Surely he will render vengeance, as in flames of fire, upon all the wicked and ungodly,
and those that forget him.
It is not by saying, but by doing, that we are justified, through faith in Christ;
not he that says, Lord, Lord, only, but he that does his will also,
shall enter the kingdom.

The will of God and of Christ his Son, is, that we should love him above all;
and in loving him, we shall love one another;
for Christ saw the great need there was of loving God above all,
and also of loving one another;
therefore he answered thus to him that asked which was the greatest commandment,
You shall love the Lord your God, with all your heart, and with all your soul,
and with all your mind.`"

"`This,`" says Christ, "`is the first and great commandment,
and the second is like unto it.
You shall love your neighbour as yourself:
on these two commandments hang all the law and the prophets.`"

If these two great commandments were obeyed, it would answer God`'s great love to us,
in sending his Son to bless us.
Oh! the glory of God,
how it would shine! it would make the young men as valiants of Israel,
and the old men as captains of thousands; then Christ would reign gloriously indeed,
in the hearts of the children of men; here the Lamb and his followers,
who walk in the light, and in that commandment, that burns as a lamp,
would get the victory over the devil and his followers.
But, on the contrary, the great error of mankind, is that they talk of God and Christ,
in words; but deny him in works: some will not stick to say,
it is impossible to keep the commands of Christ.
It is too commonly spoken, and also believed,
that there is no perfection on this side the grave; contrary to the saying of Christ,
"`Be perfect, even as your Father which is in heaven, is perfect.`"
Yet, say they, it is impossible; which is as much as to say, Christ is a hard master,
in commanding what cannot be done; consequently,
out of their own mouths they will be condemned; for Christ is not a hard master;
I testify it against all such unholy and imperfect believers,
in solid fear before the Lord; but according to such people`'s faith and belief,
he must needs be hard.

Oh that people would so love God and his dear Son, as to strive to do his commands;
for it is impossible they should obey if they neither believe nor endeavour.
Let such know, that "`Many shall seek,
and shall not enter;`" much less shall they enter if they do not seek.
But we must strive in obedience to his will, and by his assistance,
not in our own natural will,
"`to enter in at the strait gate:`" man would enter in with all his pleasant things,
and in all his bravery and gallantry; but God`'s will is, that he should be brought low,
that he might exalt him.
Oh this self is a great enemy to mankind.

My intention is, to awaken people out of the sleep of sin, which is death;
and to stir them up to righteousness, and love to the Lord and their neighbour,
even with their whole heart; for this my heart breathes to,
and supplicates the Lord of heaven; then would the end of my labour, in his love,
be answered.
Great is the love of God, in sending his Son, and also in sending his servants,
and stirring them up, to arouse people out of the sleep of security,
that they might see the danger they are in,
and how near they lie to the brink of the pit of burning.
Oh that people would but seriously consider that which is
showed and told them in the love of the Lord,
that it might be laid to heart.
Whether they will hear, or forbear, God will be clear,
and his servants also will be clear.
But if we not only hear, but also obey, that peace which passes the understanding of men,
and which our Lord gives to his followers, will be our portion,
and the lot of our inheritance forever; but this is on condition of our obedience,
and keeping the commands of God; "`If you love me, keep my commandments,`" says the Lord.

If people live in saying, and not in doing, in professing, and confessing,
yet still living in pride and high-mindedness and in sin,
it is apparent they do not love Christ Jesus, according to his own words,
neither does he justify them; for it is only the doers that he will justify.
The apostle John says, "`If a man says he loves God, and yet hates his brother,
he is a liar;`" and by plain Scripture testimony, such are not of God.
Moreover, if he says he loves Christ, yet keeps not his sayings, he is also a liar,
and the truth is not in him, or, Christ is not in him;
who said "`I am the truth;`" and thus man becomes reprobate.

Paul, writing to the brethren, says,
"`Examine yourselves as to whether you are in the faith.
Test yourselves.
Do you not know yourselves,
that Jesus Christ is in you?--unless indeed you are disqualified.`"
Which indwelling of Christ is a great mystery to many; although Christ within,
which the apostles preached, is the hope of the saints`' glory.
And how earnest was Christ in prayer to his Father,
that his followers might be one in him, and united together in one.
Such is the love of Christ to his church; and what remains on the church`'s part,
since Christ has done his part?
Surely is, that we love him again; for, says John, "`He that loves not, knows not God;
for God is love.`"
They that dwell in enmity, are not the children of God, but the children of Satan,
who always hated the appearance of Christ, the light of the world;
and still stirs up those who are led by his dark spirit,
to war against him and his seed in his children, who said,
"`I am the light of the world.`"

But it is as Christ has said,
"`Men love darkness rather than light;`" and how strange is it,
seeing the one is so glorious, and the other so miserable?
The reason is as Christ bath showed, "`because their deeds are evil.`"
This is indeed the very cause; for if their deeds were good, they would love the light,
Christ Jesus, the Lord of life and glory; and bring their deeds to him,
that he might judge them:
who will give righteous judgment to every man according to his works.
The righteous will have their portion in the resurrection of life,
joy and peace in the Holy Spirit; but the wicked in the resurrection of damnation.
Oh! that I might be instrumental in the hand of the Lord
to open the eyes of some who are spiritually blind,
that they might see the beauty and the great glory of the dear Son of God,
that most excellent light whom God has prepared,
according to good old Simeon`'s testimony of him.
"`You have, says he, prepared him a light to enlighten the gentiles,
and to be the glory of your people Israel.`"
A glorious light indeed!
Truly, I believe every body should be in love with him.
For my part, he is my chiefest joy.
I would not part with him for all the pomp and vain glory of the world;
neither would I have the shining beams and glorious rays,
which comfort me for well doing, and discover and reprove me for the contrary,
clouded from my sight and understanding, for the finest gold, or choicest rubies.
Such is my love to Christ, the bridegroom of souls; but by the way,
it has cost me many a tear, and many groanings in my spirit,
before I came thus to enjoy Christ, who is the beloved of all the redeemed.
May I never give him cause to withdraw himself from dwelling in me.

Oh! the universal love of Christ:
it is everlasting to them that are open-hearted unto him,
and to all that will hear his voice, so as to obey it; for, says he,
"`I stand at the door and knock,`" that is the door of the heart of man;
"`if any man hear my voice, and open the door, I will come in to him,
and will sup with him, and he with me.`"
And John says, "`And we have known and believed the love that God has to us: God is love,
and he that dwells in love, dwells in God, and God in him.`"
A heavenly habitation and glorious dwelling place!
Who would not endeavour to dwell in love, and forsake enmity,
that they might attain unto such eternal happiness,
as to have their abode with the Lord.

This fulfils the words of Christ: "`For he dwells with you, and shall be in you.`"
How was he to be in them?
A comforter for well-doing, that they might have the hope of glory;
and a reprover for sin, self-righteousness, and wrong judgment.
Indeed it was the great love of God in thus sending his beloved Son,
a light into this dark world, to show people their evil deeds,
and to condemn sin in the flesh: for he is the sinful world`'s condemnation,
as well as a Saviour and justifier of the righteous and holy believer.
The Jews of old hated him,
and many of them did intend to darken his bright and shining light;
but some of the Jews believed on him, and after they came truly to believe on his name,
spread his gospel of truth and glad tidings among the children of men,
and also suffered for his name`'s sake.
It is also said, "`He came unto his own, and his own received him not;
but as many as received him, to them gave he power to become the sons of God,
even to them that believe on his name.`"
But many of those that call themselves by his name,
trample upon his light and appearance, and despise the spirit of his grace,
which is a swift witness against evil, and lets men see what is good, and what is bad,
comforts for the one, and brings judgment and condemnation for the other.

I can truly say, I would with my whole heart, that God did dwell a comforter in all,
or Christ, or the Holy Spirit, or Holy Spirit, which are all one, but this can never be,
while sin remains and has an evil root in mankind.
"`An evil tree cannot bring forth good fruit.`"
By this we may know Christians from antichristians,
and lovers of Christ from them that love him not:
if we love him we become subjects to him, subject to do his will.
It is a dignified station to be subjects of the King of heaven,
and if we love him unfeignedly, with all our might and mind,
and our neighbours as ourselves,
and with the sword of the spirit valiantly encounter the devil,
then shall we be his subjects, and Christ will receive us into his warfare,
and through him we shall be victorious,
for the Lamb and his followers will have the victory.
I would press people in love into this warfare,
having commission from my Master and Lord,
by showing them what anxiety and distress of mind they will procure to themselves,
by living in enmity to the Lord and his saints.
Oh! my soul, I charge you, with all those that have any regard to the holy Jesus,
obey the commands of the Lord, and love his followers, or your neighbour as yourself.
Let his universal spirit of love to all dwell in you.

I would have all to cast down at his footstool, that which they glory in,
that is not right in his sight, and do like the poor penitent woman,
who lay and wept at his feet.
She thought all, little enough to part with to get into his favour.
Christ himself was meek and lowly; "`Learn of me,`" said he.
All power in heaven and earth was given unto him; "`Take me, said he,
for an example;`" when he washed his servants`' feet.
Seeing his love was so great to them, and is also to us, let us love him again,
not with feigned love, but with love that may manifest us to be his followers;
and in it let us love one another;
for this intent our Lord issued forth his royal command, which is this,
"`A new commandment give I unto you, that you love one another as I have loved you,
that you also love one another: by this shall all men know that you are my disciples,
if you have love for one another.`"
Christ`'s love was unfeigned to his disciples, yes, to all the world in general:
for what greater love can there be, than for a man to lay down his life for his friend;
and he not only laid down his life for his friends, but for his enemies also.
So that his love was great and unfeigned; we ought with the same love to love him again,
since he loved us first; and this cannot be without obedience to his commands.
Thus we should love him and one another with true love, which is exceedingly precious;
it thinks no evil, and we may be sure will not do any willingly or knowingly.
If a man sees his neighbour or brother in that which is not right,
he prays to the Lord to help him, and tenderly admonishes him; yes, if having this love,
he wounds, his wounds are faithful, for "`Faithful are the wounds of a friend.`"

He that is thus endued with love, is not hindered from reproving his brother,
but if there be a cause, it rather stirs him up to be faithful therein,
without respect of persons.
The love that is raised in them that love the Lord above all,
is great to the sons and daughters of men: it does wonderful things;
it is valiant for God; it overcomes its enemies: it is not overcome with evil,
but it often overcomes evil with good: it smites sin in the gate, that is,
in its first appearance, before it be entered into man, so as to subject him thereunto;
it gets victory over the devil; for he cannot stand before God`'s love.
I would to God that people did but know the virtue of love to Christ,
and one another in him; it would cause them, for the enjoyment thereof,
to forsake all manner of enmity one against another, and all things else,
how near or dear soever; yes, though they were as a right hand or a right eye,
they would be forsaken for its sake, and for the sake of him who first loved us.
Then we should strive, through the ability of his grace,
even the grace or spirit which he told Paul was sufficient for him, to love him again,
and our neighbour as ourself;
but this cursed self is loved too much and our neighbour too little.

Paul, the apostle of Christ, after his conversion, did not hate his neighbours,
nor was he in enmity with them.
When he was Saul, he oppressed and injured his nearest neighbours and chief friends;
for his blind zeal was part of that body of sin and death that was upon him,
and from which, by the help of Christ`'s grace, he was delivered,
and came to love his enemies, and for their good hazarded his life; and,
for his love to Christ, laid it down, as many holy martyrs have done since.
Surely they had not much regard for self, then!
It is a common expression now-a-days, "`Every one for himself,
and God for us all;`" but if every one were for his neighbour or his brother,
as much as for himself, God would be more for us all.
This self-love is an abomination in the sight of the Lord,
and the great eternal God abhors it;
therefore were the first and second commandments given forth,
and if all people would obey these, the whole law and the prophets, yes,
and the gospel too, would be fulfilled.

Self-love is a great enemy to man, and very much hinders his eternal happiness;
it shuts the ear from hearing the cause of the widow and fatherless, or of the needy,
and drowns the cry of the oppressed; to which we ought not only to lend an ear,
but also to administer relief according to their necessity, and our ability.
Mankind are too apt to join with that which is pleasant to the eye,
and agreeable to the lust of the heart; like Dives, the rich glutton of old,
who loved self better than poor Lazarus, but do not consider that which is lasting,
and would do them good forever.

How shall I express the excellent glory and eternal
sweetness of this love to the Lord and our neighbour?
Oh! how is my soul grieved, and how does my spirit mourn before the Lord,
when I see any walk contrary to the commands of Christ,
or who are in enmity to the truth, and in hatred one to another,
even from my tender years, ever since God Almighty opened my understanding,
and made known to me him that is true.
And my cry has been many times to him, to keep and preserve me in his true love and fear,
to the end of my days; in love both to him and to the brethren,
more especially to those that do his will,
although there is universal love in my heart to all.
Christ said, "`For whosoever shall do the will of my Father which is in heaven,
the same is my brother, and sister, and mother.`"
Therefore my love is more singly unto those.
The apostle also thus writes concerning love to the brethren:
"`We know that we have passed from death unto life, because we love the brethren;
he that loves not his brother, abides in death.`"
Are they then in death that are at enmity with the brethren?
Assuredly they are, for this enmity is sin;
"`And the wages of sin is death;`" and those that are therein, are dead while they live.
I wish and heartily pray to the God and Father of spirits,
that from the snares of death his people may forever be preserved.

Some people are too apt to judge one another, and to speak evil of things they know not,
except by report and supposition, which too often lets in enmity,
and is not according to the mind of Christ,
but is a snare of the enemy of man`'s salvation.
Surely if people were sensible thereof, they would not so hardly censure one another;
for indeed we ought to be well satisfied before we give judgment,
and then it ought to be in love, and not in enmity.
It is better to suffer, than to censure; to be judged, than to judge.
"`Judge not, that you be not judged,`" said the Judge of heaven and earth.
But people are too much possessed with uncharitableness and revenge one towards another,
and are not so ready to forgive one another their trespasses,
as the Almighty is to forgive them:
though to forgive one another their trespasses be every Christian`'s duty,
without which we cannot justly expect God to forgive us our trespasses, as Christ taught.

Persecution for righteousness sake, also is another branch of that corrupt tree,
which never did, and never will bring forth good fruit,
but must be cut down by the axe of God`'s power,
which is laid to the root of every corrupt tree, in order to cut it down;
and the Lord will burn it with unquenchable fire.
It is the true church`'s lot to be persecuted, but she never persecutes any:
for he that is her High Priest anyone, commanded quite the contrary: Love to enemies,
and to do good to them that hated them,
to pray for them that despitefully used and persecuted them.
They were also to rejoice,
and to be exceeding glad when all manner of evil was spoken falsely against
them for Christ`'s sake because great should be their reward in heaven;
and Christ observes, that so they persecuted the prophets.

Many are rebelling against God,
and doing despite to the spirit of grace in their own hearts,
and trespassing one against another, not living in love,
but in enmity against God and one another.
The judgment of man is terrible to the rebellious,
how much more if men rebel against God, our Saviour,
will his judgment be just and dreadful, as he has not only power to kill the body,
but can afterwards cast the soul into hell!
Oh! that the sons and daughters of men, would but fear to offend him,
the King of eternal glory.
Israel of old, his own peculiar people, did fear and tremble before him;
even all their host, his presence was so dreadful.
And a noble king made a decree, that men should fear and tremble before the living God.

Oh! that all would work out their salvation with fear and trembling,
according to Scripture testimony, and as people truly love the Lord,
they would fear exceedingly to offend him; also if one man did truly love another,
he would very unwillingly offend him.
So if we love Christ in deed and in truth, we should fear to offend him,
and must of necessity love one another also: so shall we fulfill the great commands,
that the whole law and the prophets hang on.

I have many times been grieved, when I have heard cursing and swearing,
and the Lord`'s name taken in vain, which too much abound;
and such too little consider that God will not hold them guiltless.
This is far from obeying him.
The deep sense of this great sin, is a deep concern on my mind: vengeance from heaven is,
and will be the portion of all such who thus violate the mind and will of God, Judgment,
judgment is the lot and inheritance of all the wicked, who remain and live in wickedness.
Although the Lord is slow to anger, and of great lovingkindness,
and his mercy endures forever, to them that truly repent of evil,
and do that which is good, yet he has also prepared weeping, wailing,
and gnashing of teeth, for them that continually live in sin.
There is a possibility of sinning, until there is no more mercy or grace for man:
witness the words of God; "`My spirit shall not always strive with man,
for that he also is flesh.`"
But those who are willing to put the day of God afar off, are ready to say,
Christ is our advocate with the Father; he makes intercession for our sins very well,
but it is conditionally, it is if you will repent and sin no more.
Mark that well repentance without sinning no more, will not do.
Confession is very good, but forsaking sin is abundantly better:
confession without forsaking, will stand in little stead in the day of account.

Drunkenness is a great sin, first against God, and secondly, the abuse of God`'s mercies,
and good creatures; and by it,
men are often fitted for any business their master the devil may call them to:
so that this great sin ought to be strictly watched against.
Surely if men had any good desires in their hearts, or any love to God,
they would refrain from such great wickedness.
I admire how people can expect mercy from God, or the intercession of Christ,
when by their sins they are piercing his sides, and putting him to open shame.
How can such expect he will intercede for them,
when they have dealt so shamefully with him, and grieved him,
and from time to time disobeyed his voice?
Suppose a man stood condemned before a judge,
and that at the judge`'s right hand there sat one in power,
whom this poor condemned person hopes will intercede for him;
and yet the poor wretch does to him as before mentioned.
What grounds can he have to hope for intercession, clemency, or lenity,
while he believes he can do no otherwise than sin against him all his days?
For my part, I think his faith, hope, and belief are but vain;
without any reason or ground.
But he that loves Christ Jesus, the Lord of life and glory,
so as to keep his commandments, the Lord will love him, and intercede for him,
and make himself known unto him; according to his words which he spoke,
"`He that has my commandments, and keeps them, he it is that loves me,
and he that loves me, shall be loved of my father; and I will love him,
and manifest myself unto him.`"

Covetousness, which is idolatry, is also another great snare of the enemy,
and many are caught therein.
It is in vain for the covetous to say, he has a share in the love of God;
for he has neither love to the Lord, nor to his neighbour,
A poor naked man might ask him long enough for relief, or for his coat,
before he would give him his hand to help, or coat either; or any manner of relief;
although Christ expressly commanded, "`Give to him that asks,
and from him that would borrow turn not away.`"
How can any be so hard-hearted, as to see his brother`'s or his neighbour`'s poverty,
and not administer of his ability to the necessity of the needy?
The covetous or miserable man may say, I have children, or a family to take care of;
yet too often covetousness brings a curse, and not a blessing,
upon family and children also.
Perhaps some may say, that charity begins at home.
But let him remember, that if it does begin there,
the consequence most commonly is very bad, when it ends there.
Every Christian has need to have charity in a two-fold sense,
or else there is no proper pretence to Christianity; in short,
covetousness is out of the love either to God or man.

All these, with abundance more, that I shall forbear to mention,
are eminent snares of the devil;
and he lays them according to the propensity of man or woman,
and suits them to their nature.
He colours them finely, and puts a pleasant gloss upon them, to betray your soul,
and keep it in bondage forever.

It is he that tells the murderer, the thief and the robber,
that it is better to live a merry life and short,
than to take pains and care all one`'s lifetime.

It is he also who tells the whoremongers and drunkards,
that so many people are in these practices,
because it is natural for people to be so overcome:
but he does not tell them that by nature all are children of wrath,
and that without this lustful nature be overcome, there is no salvation.

It is he that tells the swearers, they are so used to it,
that it is impossible for them to leave it off.
He never bids them repent and forsake,
that they might find mercy with God and Christ that died for them;
but died not that they should live in sin.

It is the devil tells the covetous it is good to be saving,
and not to spend all his substance in gluttony and pride; he will bid him hate pride,
and that he should not give much alms, though rich in this world,
for that proud people do it only in ambition, and to be seen of men:
but he will not tell him, it is a sin to be covetous.
He also tells the proud that they are counted happy,
and that pride is counted good for promoting the commonwealth,
and that it is as good to be out of the world as out of the fashion;
he tells them that pride is neatness; and it is admirable how many pretty excuses he has,
to keep people in pride.
He does not tell them that Christ the Lord, was meek and lowly,
and that they should take him for an example.
He, the Lord, did not come in splendor and glory, outwardly,
but plain in speech and also in apparel,
being clothed and adorned with the robes of righteousness and love.
This is my beloved! may he be yours also, gentle reader.
Oh! how lovely is he! he is the chiefest of tens of thousands.
Oh! you children of men, both sons and daughters! do not offend Christ,
by disobeying him, the bridegroom of the righteous; but I beseech you,
in his sweet and tender love, if you have offended him by sinning against him,
Oh! for the Lord`'s sake, and your own soul`'s sake, do so no more;
but unfeignedly repent; and then in his time, when he has tried you,
and found you faithful, he will embrace you with the sweet embraces of his love.

If the poor creature did but love the Lord its Maker above all,
and its fellow creature as itself, the enemy of mankind would be overcome,
and we be made more than conquerors, through him that loved us, even Christ Jesus,
our Lord; and man and woman would see all those evil things to be abominable,
and many more which I have not mentioned,
insomuch that self would be abhorred as in dust and ashes,
and the Lord would be loved and glorified above all, for which end he created mankind.
But certain it is, that this end cannot be answered, nor the Lord so loved,
without sin be forsaken, and hated; for the devil is the author of sin,
and Christ of righteousness.

Christ says, "`I am the way, the truth, and the life.`"
And again, "`I am the light of the world.`"
Oh! says my soul, in love and good will to the sons and daughters of men,
that they would but walk in the way of truth, and in the true light of the world;
then they would see clearly the snares of Satan; which that every one,
especially those that profess Christianity, may do, and escape the same,
is the very desire of my soul: even so prays he, who through the spirit of Jesus Christ,
and the ability of his grace, labours for the salvation of mankind;

Thomas Chalkley,
