[short="Observations on Christ`'s Sermon on the Mount"]
== Some Observations on Christ`'s Sermon on the Mount.

[.centered]
=== Preface.

Christ being the great author of the Christian religion,
some observations on the sermon which he preached on the mount,
may be acceptable to some of his followers;
especially such who desire to fulfill his holy will,
and not to rest satisfied in a mere form and show of religion.

And also considering that it is the greatest collection
of his words left us in the New Testament by the evangelists,
in any one place,
I was in hopes some observations thereon might tend
to promote the reading of it in the holy Scriptures.

But the great aim I had in this undertaking, was,
that the professors of the name of holy Jesus might live and walk in his truth,
and in the doctrine which he has there laid down for his followers to practise;
and that in so doing, they might have peace to their souls here,
and rest in the kingdom of glory forever.

It is by some accounted and looked upon in youth to be a
commendable and worthy practice to write down sermons,
and to copy and read them over; and I believe it will be generally acknowledged,
that there was never any sermon that can be compared with this preached in the mount,
and recorded by the evangelist Matthew, in the fifth, sixth and seventh chapters;
which if our young and rising generation would often read, and sometimes write down,
but be sure to practise; this would be truly noble in them.
If they find they lack inward strength to perform the duties it prescribes,
let them seek it in secret at the hand of the Almighty, in whom is everlasting strength;
and it is recorded in holy Scripture, "`That he gives liberally, and upbraids not.`"
He will not upbraid you, because you are but a child, or tender in years.
Oh, therefore, seek him betimes! for it is written,
"`They who seek him early shall find him.`"

If Christians would walk according to this holy sermon,
it would help to heal their differences,
and to soften them in their sentiments one to another.
All parties will confess that the doctrine in this sermon is good,
and ought to be promoted among all who profess the worthy name of the Lord Jesus;
and whoever walks contrary to this rule must needs be in the wrong.

The general end of preachers is, or should be, to have their doctrine taken notice of,
and put in practice; and this being counsel from the "`Wonderful, counsellor,
the mighty God and Saviour, the everlasting Father,
and Prince of Peace,`" we should take more than ordinary notice of it.

Considering also, that he not only spoke his doctrine, but lived in it;
and not only lived in, but died in it and for it,
and us also we are deeply engaged to hear him with an obedient heart and ear, "`This,
says the voice from the most excellent glory, is my beloved Son, hear him.`"
And Moses, the man of God, says, "`He that will not hear him,
shall be destroyed from among the people:`" that is,
from an inheritance with the saints in the kingdom of God, and his Christ.

I have carefully transcribed the sermon, verbatim,
and made some observations on it afterwards, I think on every verse a little,
as I found openness to it on my mind;
and it is recommended to the serious perusal and consideration of all
those who tenderly and unfeignedly love our Lord Jesus Christ.

[.signed-section-signature]
Thomas Chalkley.

[.offset]
_"`And seeing the multitudes, he went up into a mountain: and when he was set,
his disciples came unto him, and he opened his mouth, and taught them, saying, etc.`"_

Our Lord seeing the multitudes, for the advancing his Father`'s glory, his own kingdom,
and the good of souls, went up into the mountain, and sat in the power of the Father;
and when so sat down, his disciples came unto him;
which shows the necessity of coming to Christ, to hear his word,
and that Christians ought to assemble themselves before him,
that he may speak to them either immediately,
or by his ministers if he pleases to enlarge the
heart of any of them to declare his word;
and as his disciples then personally came unto him,
so now we ought to come to him in spirit; and when but two or three are so come to him,
he is as really present spiritually, as he was personally in the mount.
And as this meeting in the mount was powerful and glorious, so will all those be,
in measure, where Jesus is really present in spirit.

"`And he opened his mouth,
and taught them,`"
Thus when true believers meet before Christ, he teaches them,
and opens the mysteries of the kingdom of God,
and speaks truly to the state of the people, even now spiritually,
as he did then vocally; and his word is with power and great glory.
Oh! may all his servants and ministers, who are sensible of his divine call,
minister according to their several gifts and capacities, in his power,
and by his holy and divine authority.
This must change the hearts of poor mortals, and forward the work of reformation, which,
with godly sorrow it may be truly said, goes on but too slowly in this world.
Christ being thus set in the power of his Father,
opened his mouth and let fall a shower of blessings
on those hearts who were prepared to receive them.
For his great love and tender compassion are generally
manifested to poor souls when they,
with love and zeal to him, and for the honour of his great name, assemble before him.
He begins and says,

[.offset]
_"`Blessed are the poor in spirit, for theirs is the kingdom of heaven,`"_

It is a safe and blessed state, to be spiritually poor,
and to be rightly sensible of it before the Most High, For then we are nothing,
and have nothing, but from the Lord: and without him man sees himself undone:
his soul must starve, he must go naked, if the Almighty do not feed and clothe him.
When people see themselves poor and wretched, miserable, blind, and naked,
without Christ, notwithstanding all the fine things they may enjoy in this world,
which is of a fading nature; Oh! then how the soul cries and begs for mercy and grace.
A dry form of words will not satisfy it, but it begs with tears, "`Lord help me,
or I perish!
Save me, or I am undone forever!`"
Here the soul humbly approaches the throne of grace by prayer;
and if an answer is not quickly received, for such a soul is apt to think the time long,
it waits patiently with that servant of God, who said, "`Though he slay me,
yet will I trust in him:`" for I know there is no help for me but from you.
"`Oh! my God, and my Saviour,`" says the truly poor soul,
"`The food which must keep life in me, is your word: and the raiment which I need,
is your righteousness, as you wrought it for me, and work it in me also.`"
The Lord looks with a compassionate eye on such souls,
and does not use to turn them away empty; but as they abide in the patience,
waiting for his appearance in hope, he assures them of the kingdom;
and a great change is witnessed; for the blessing of Christ makes them rich,
which adds no sorrow with it.
Their greatest sorrow was, and is, for lack of it;
now their treasure and heart is in heaven,
and heavenly things are their chiefest delight;
now they are clothed with Christ`'s righteousness, he has put it upon them,
and they show it in the sight of men,
a thorough change being wrought both within and without also;
"`The holy Spirit bearing witness with their spirits,
that they are the children of God;`" and Christ says theirs is the kingdom of heaven.

[.offset]
_"`Blessed are they that mourn: for they shall be comforted.`"_

The mourning here spoken of, is of a godly sort, which may sometimes appear outwardly.
First, The soul may mourn for its own sins and iniquities.
Second, For need of a Saviour: and Third, For the iniquities of others.
"`All have sinned, and come short of the glory of God; and since we have all sinned,
we have all need to mourn before the Lord, and bow ourselves before the Most High;
and when he sees that we are humbled before him, he will comfort us.
Christ will send the Comforter, the Spirit of truth in his name, who will come unto us;
and when he is come, we may plainly know that it is he, by what he does,
according to Christ`'s own rule, which is infallible and certain.
He says, "`When he is come, he will reprove, or convince the world of sin,
of righteousness, and of judgment; of sin, because they believe not on me;
of righteousness, because I go to my Father, and you see me no more; and of judgment,
because the prince of this world is judged.`"

Thus, according to Christ, that which shows us our sins, which convinces us of them,
is the Spirit of truth, the Comforter;
and after we have mourned for the sins of which he convinces us,
then he comforts us with inward comfort and consolation.
This Comforter also convinces us of our formal righteousness, when it is only formal,
without the power of Christ;
and then the soul mourns after the life and power of godliness,
which indeed is great gain, with true contentment;
and has the promise of the things of this life, and of that also which is to come.
Here we are comforted by the Spirit in the promise,
in which we have faith to believe in Christ, that he will verily do as he has promised.
It also convinces us of judgment, when we judge with a wrong judgment;
and when we mourn for our mistake, he makes us sensible of his righteous judgment,
which judges the prince of this world, who is judged by Christ;
and then instead of mourning, we are ready to sing with the saints of old, "`Salvation,
and glory, and honour, and power, unto the Lord our God,
for true and righteous are his judgments,
for he has judged the beast which did corrupt the earth,
and has revenged the blood of his servants at her hands.`"

The soul being truly in love with Christ, and he being absent from it in some sense;
or if he seem to stay a great while from it, although it be only to prove it;
this makes it mourn like the spouse in the Canticles, who sets forth the beauty,
and excellent parts and comeliness of her beloved, and her sorrow is,
that he has withdrawn himself; and well may a soul be sorrowful,
when Christ spiritually withdraws himself.
The children of the bride chamber mourn in the bridegroom`'s absence,
but rejoice in his presence, who is the very perfection of beauty and holiness.
But the soul abiding in his love, seeking him and waiting for him,
in his own time he will certainly come to that soul; for he is the truth who said,
"`Blessed are they that mourn for they shall be comforted.`"

Again, pious souls cannot but mourn for the sins and abominations of the times,
which are a great exercise to them, and affect them with sorrow and mourning;
but they are comforted with blessed promises, which the Holy Spirit, at times,
immediately applies to their souls, as recorded in the holy Scripture;
and let it be remembered, that all our good times are in the hands of the Lord.
It is recorded in the holy Scripture,
that God would have his people comfortably spoken to;
and that he would "`give them beauty for ashes, the oil of joy for mourning,
and the garment of praise for the spirit of heaviness;
that they might be called trees of righteousness, the planting of the Lord,
that he might be glorified.`"

[.offset]
_"`Blessed are the meek: for they shall inherit the earth.`"_

Be not high-minded, says one of his servants; and another says, God resists the proud,
but gives grace to the humble.
Again, "`The meek will he teach his way, and the meek,
will he guide in judgment;`" as the holy Scripture witnesses.
Well said our holy Saviour, that the meek should be blessed: grace is given to them,
and God is their teacher and their guide in judgment; a most blessed gift, teacher,
and guide.
It is a great blessing indeed, to receive grace from Almighty God, to be taught his ways,
and to have the holy One to be our guide in judgment.
He who has all power in heaven and in earth committed into his hand,
says that the meek "`shall inherit the earth:`" they have
the truest enjoyment of all the things of this life;
whereas the proud and scornful are a burden to themselves and others,
and hardly anyone pleases them, or is good enough for them; when, on the other hand,
the meek and contented mind has a continual feast.

[.offset]
_"`Blessed are they who hunger and thirst after righteousness; for they shall be filled.`"_

Let it be remembered, that as our mortal bodies cannot enjoy health long,
without a natural appetite to food and drink,
so our souls cannot live unto holiness without a spiritual hunger and
an inward thirst after the righteousness which Christ puts upon his saints;
not by imputation only, but actually also.
Such souls he will fill, as Mary witnessed and bore her testimony to the truth thereof:
"`He has filled the hungry with good things, and the rich he has sent empty away.`"
When we are emptied of sin and self,
there is room for the Almighty to pour his spirit into us.
If we would fill anyone, it must first be emptied; so must we be empty,
if we hunger and thirst after righteousness:
then shall we truly pray to our heavenly Father for divine food,
and it will be our food and drink to do his will;
and we shall delight to feed upon his word; as Christ says,
"`Man shall not live by bread alone,
but by every word that proceeds out of the mouth of God.`"
This is holy food for the soul, which nourishes and keeps it alive unto God;
without this it is dead, notwithstanding it may have the name of a living soul.
As this hunger and thirst, or desire, must be spiritual, so must the food be also;
"`It being the spirit that quickens,`" and gives life;
therefore let a spiritual hunger and thirst after God and his righteousness,
be in the soul.
A righteous man being greatly athirst after the living Lord, cries out,
"`As the hart pants after the water brooks, so does my soul after the living God.`"
And this holy thirst was greatly satisfied,
so that his heart was many times sweetly opened to praise the Lord.

It is true we have an adversary, that would be filling us with many things, fleshly,
worldly, and satanical; but we are to shut our hearts against him,
to keep out all those things, and to stand open to Christ, empty before him.
If we find our adversary too hard for us,
we are to flee and cry to the Lord for succour and help, who is a God not only afar off,
but also near at hand, a present help in the needful time,
as many of his servants and children have experienced.
Therefore, to be hungry and thirsty after Christ and his righteousness,
entitles us to his gracious promise, who says they shall be filled.

[.offset]
_"`Blessed are the merciful, for they shall obtain mercy.`"_

It is highly necessary for mortals to show mercy
in all their words and actions one to another;
and also to the creatures which God has made for the use of man.
It is usually said, that a merciful man is merciful to his beast,
which generally is true; and if men are merciful to their beasts,
how much more ought they to be merciful one to another.

Where mercy is to be extended, it ought not to be done sparingly, since thereby,
according to Christ`'s blessed doctrine, we are to obtain mercy.
That servant who showed no mercy to his fellow, had no mercy showed to him from his lord.
It is also recorded, in the name of the Lord, "`He has shown unto you,
O man! what is good, and what does the Lord require of you, but to do justly, love mercy,
and walk humbly with your God.`"
By which it appears that we are not just in the sight of God,
if we are cruel and unmerciful one to another.
And we ought not only to be merciful, but to love it, which, if we are truly humble,
we shall certainly do.
Mercy will lessen, and not magnify weakness, failings, or small and trivial things,
one in another; and sometimes, as the case may require, larger things.
Yet there is room for seasonable reproof and correction;
but mercy must be mixed with justice, else the correction may end in tyranny.
We ought to be gentle to all men, which is a token of true gentility;
so to be truly merciful, is to be blessed, and to obtain mercy.

[.offset]
_"`Blessed are the pure in heart, for they shall see God.`"_

By which we may understand, that we are to take care of our hearts,
and to keep a strict watch over them; and not admit unclean or unchaste thoughts,
or sinful desires, to have an entrance therein.
And if unaware, they should at any time enter, we must not entertain or love them,
but turn them out; for we, in this, should be like our heavenly Father,
of purer eyes than to behold iniquity with any allowance or approbation:
otherwise it will hinder us from seeing God,
and from the sweet enjoyment of his most precious presence,
and from beholding the only begotten of the Father,
and the fulness of his grace and truth, which we cannot see if our hearts are impure.
We have an instance in the scribes and pharisees, who,
though they were outwardly righteous and clean, yet within were very impure,
so that they could not see God, though he was in Christ reconciling the world to himself:
notwithstanding their nice discerning eyes, yet they could not see him,
for the impurity of their hearts; which was so great, that they murdered the just One,
their hearts being full of deceit and hypocrisy.
"`Make clean the inside, and the outside will be clean also,`" says Christ:
from which it appears, that a true Christian must be clean both within and without.
The beginning of the work of purity and sanctity, must be within;
and being innocent and pure in heart, we shall then see the glory of the Father,
the lovely beauty of the Son, and the power of the Holy Spirit, or Spirit.

[.offset]
_"`Blessed are the peace makers, for they shall be called the children of God.`"_

This peacemaking is excellent work, and a blessed calling; what pity it is,
that there are not workmen in the world who would set themselves heartily to it,
which if they did, in a right spirit,
God would certainly prosper the work in their hands,
and plentifully reward them with his own peace,
which passes the understanding of the natural man.
If our ingenious men, our men and women of skill and good natural parts,
would take a little pains, or, when the case requires it, a great deal,
the Almighty would richly reward them.
This work is not too mean even for princes and nobles; no,
not even the greatest monarchs on earth,
unless it be too mean for them to be called the children of God.
And if the children of God are peace makers, what, and whose children are they,
who break the peace of nations, communities and families?
Therefore, we should seek peace with all men, and ensue it, or sue for it,
by our continual seeking of it, being a precious jewel, when found;
and though this office may seem a little unthankful at first,
yet in the end it brings forth the peaceable fruits of righteousness,
as many so labouring have witnessed.
And Christ, to encourage the work, says,
"`They shall be called the children of God;`" which are the words of the King of kings;
and if the princes of this world would promote this work among themselves,
it would save a vast expense of treasure and of blood;
and as these peace makers are to be called the children of God,
they who are truly concerned herein, are not only so called,
but are so in deed and in truth.

[.offset]
_`"Blessed are they who are persecuted for righteousness sake;
for theirs is the kingdom of heaven.`"_

Persecution may be considered in relation to calumny and reproach, and in imprisonments,
confinements, or the like, or taking away life or goods on a religious account,
for conscientious scruples, etc.
What sad work has there been on this account in the world, not among Turks and Jews only,
but among professors of Christianity, which is indeed a great reproach to that holy name.
Persecution for righteousness sake, is not fit for Turks or Jews,
much less for the professors of our meek Lord;
his dispensation and gospel being absolutely the reverse of it,
which is a shameful sin to all men, in all nations.
However, the persecuted have this comfort in the midst of all their sufferings,
they are blessed of Christ their Lord; who himself suffered for them,
and they are promised by him the kingdom of heaven.
By which doctrine it may be safely concluded,
that the members of his true church never persecuted any,
though they have been often persecuted;
but the eyes of many are now open to see the evil of it,
and a spirit of moderation begins to grow and spring in many parts of the earth.

It is to be desired, that the moderation of Christians might more and more increase,
and appear to all men; because God is at hand, who will justify the innocent,
whom he knows better than any man, because he sees their hearts,
and he will condemn none but the guilty.
How shall the Jews be converted,
or the Turks be convinced of the verity of the Christian religion,
while its professors are tearing; and rending one another:
had it not been for the immoderation and persecution among professors of Christ in Christendom,
so called,
it is probable Christianity would have made far greater progress
in the four quarters of the world long before this time,
than it has done.
Persecution has been proposed by the immoderate, to allay heats and divisions,
and cure breaches; but the ancient history of persecution, and the modern practice of it,
fully convince us, that it has always tended to make the hot, hotter,
the divisions greater, and the breach wider, and so the contention to grow endless;
which nothing will end, but a calm and quiet temper,
the mind being cooled by the gentle influences of the holy Spirit of Christ,
the immaculate Lamb; who came not to destroy, or devour,
but to seek and to save that which was lost and gone astray,
that he might bring them home to his fold of rest, in his Father`'s kingdom.

[.offset]
_"`Blessed are you when men shall revile you and persecute you,
and say all manner of evil against you falsely for my sake.
Rejoice and be exceeding glad: for great is your reward in heaven;
for so persecuted they the prophets, who were before you.`"_

There is a persecution as before hinted, by calumny and reproach, or reviling,
by evil speaking and falsities, which, for the most part,
it is better patiently and quietly to suffer for Christ`'s sake,
and if we are abused to appeal to him; for many times words beget words,
till at last it comes to prejudice,
and breaks the unity and peace of brethren and families.
So that in a general way one had better suffer the calumnies and reproaches of evil men,
with a tender concern for God`'s glory, resting in the blessing of Christ,
and that you will most surely feel if you can appeal to him in this way, "`Lord,
you know I suffer this wrong for your sake.`"
In such sufferings there is an inward joy, a spiritual rejoicing;
and the heart of the persecuted is abundantly more glad,
through the blessing and goodness of Christ, than the persecutor,
whose conscience accuses him in secret.
And as to personal persecution, it is no more than the prophets,
and our Lord suffered before us:
and with that consideration Christ comforts his suffering seed:
Those who suffer with him and his seed, these have the promise of reigning with him;
and himself has promised them a reward, no less than the kingdom of heaven.

[.offset]
_"`You are the salt of the earth: but if the salt has lost its savour,
how shall it be salted?
it is thenceforth good for nothing, but to be cast out,
and to be trodden under foot by men.`"_

Here Christ shows that his followers must season the earth, by living a savoury life,
and by walking according to his doctrine,
which is wonderfully set forth in this excellent sermon.
If we live up to those holy rules, we shall be serviceable in our generation,
and our lives will teach the people as well as our words, and better too,
by how much example is better than precept.
And indeed Christians ought to be careful in both; in life to live holy,
and in words to be sparing, observing to "`Let their words be few and savoury,
and seasoned with grace, that they may minister grace to the hearers.`"
Thus should we season the world, and salt it with the salt of the covenant;
but if we lose this savour of grace,
and take a liberty which Christ and his truth do not allow of, speaking things at random,
which are not convenient or edifying, but altogether unsavoury; then,
according to our Master who is in heaven, we are good for nothing but to be cast out,
i+++.+++ e+++.+++, out of the church, to be trampled upon by men, as in truth we deserve:
not that our bodies are to be killed or destroyed;
for the door of the church is always open to receive true penitents.
But for this end and good purpose we are chastened of the Lord,
that the soul may be saved in the day of the Lord.
And those who know godly sorrow for their sins,
and turn from the evil of their ways by amendment of life, those Christ forgives,
and advises his church to do the same, saying, "`If he repent,
forgive him;`" which repentance is best manifested
by a new life and a holy and blameless conduct.

[.offset]
_"`You are the light of the world: a city set on a hill cannot be hid.`"_

True and faithful Christians are indeed as stars in God`'s firmament,
which are of excellent use to people in the night,
and more especially when they are not clouded,
and in a particular manner to those who travel on the seas,
for when they have not seen the sun for a season,
then they are good guides to the seafaring man;
and likewise in the wilderness on the land.
This world is like a wilderness, and like the troubled sea, to some poor souls;
and good men and good women are serviceable, to reprove and instruct in righteousness:
"`Such, says Daniel the prophet, shall shine as the brightness of the firmament,
and as the stars, anyone and ever.`"
And these are like a city set upon a hill, which cannot be hid.

[.offset]
_"`Neither do men light a candle, and set it under a bushel; but on a candlestick,
and it gives light to all that are in the house.`"_

Men, when divinely enlightened by the grace and spirit of Christ,
ought to exert themselves to their Master`'s glory and excite others,
and stir them up to their duty; and to endeavour, as much as in them lies,
to promote the kingdom and interest of our dear Lord.
For men are God`'s candles, as the Scripture says,
"`The spirit of man is the candle of the Lord;`"
and this candle is often lighted by Christ,
who "`Lights every man that comes into the world,`"
and is the true light of the great Father of lights.
The great and good end of Christ`'s lighting man`'s spirit,
and illuminating him with divine light, is,
that he may shine out to others in a good conduct and a holy life,
which is serviceable to others and himself also,
and answers the end of Him who enlightened him by the fire of his word,
or with a coal from his holy altar; being thus lighted and walking in it,
as the nations of them that are saved, shall walk in the light of the Lamb.
Here all the house, or society, is truly lighted by such lights;
and those who have received greater gifts, or degrees of divine light from Christ,
than some others, and may have a larger share of natural or acquired parts,
ought not to hide it, as our Lord phrases it, under a bushel,
but put it in its proper place, on a candlestick;
and as the candle is of little use when it is put out,
therefore we ought to be very careful to keep to watchfulness and prayer,
that it be kept lighted in time of darkness;
for "`The candle of the wicked is often put out.`"

[.offset]
_"`Let your light so shine before men, that they may see your good works,
and glorify your Father which is in heaven.`"_

Since there is a bright and shining nature and quality
in the holy lives of Christ`'s servants,
and in the conduct of his faithful followers,
therefore it should be manifest and appear before men;
our lamp should be burning and our light shining;
and we should take care to keep holy oil in our vessels,
that therewith our lamps may be supplied,
otherwise folly instead of wisdom will appear in our conducts, which will be a hindrance,
when our great bridegroom comes, to our entrance into life, or God`'s kingdom,
and greatly hinders our Master`'s glory, of which we are by all means,
to endeavour the furtherance.
Men generally take more notice of our evil works, and when an evil eye is open,
will sooner see them, than our good ones; so that we had need to be very careful,
and keep a holy watch in our conducts, that our light may so shine,
that our Father who is in heaven may be glorified, in our bringing forth much good fruit.

[.offset]
_"`Think not that I am come to destroy the law or the prophets: I am not come to destroy,
but to fulfill.
For verily I say unto you, till heaven and earth pass, one jot,
or one tittle shall in no way pass from the law, till all be fulfilled.`"_

The excellency of the dispensation of the glorious gospel of Jesus Christ,
is wonderful! having no tendency to destroy the law of God given by Moses;
for Christ`'s doctrine comes up through it, fulfils it, and goes beyond it,
in perfection and in the beauty of holiness, and in the life and power of pure religion,

[.offset]
_"`For I say unto you,
except your righteousness shall exceed that of the scribes and pharisees,
you shall in no case enter the kingdom of heaven.`"_

Those scribes and pharisees had a righteousness, but it was one of their own making,
an outside one only; whereas, within they were full of deceit and hypocrisy;
they cried up righteousness in words,
and yet cried out against him who taught it in the greatest purity,
and sought his destruction; they were notable examples to all persecutors for religion.
Our Lord and his servants did not speak against outward holiness,
but that the inside should be the same;
for living righteousness leads to inward and outward purity,
which is manifest by its fruit; and those fruits are fruits of the spirit, which are.
Love, meekness, temperance, patience, experience, hope and charity, or brotherly love;
of which those people showed very little to Christ.
He was sensible of their envy and malice, which were very contrary fruits to holiness;
and therefore he tells them that hear him,
that their "`Righteousness must exceed that of the scribes and pharisees,
or they in no case shall enter the kingdom of heaven.`"

[.offset]
_"`You have heard that it was said by them of old time.
You shall not kill; and whosoever shall kill shall be in danger of the judgment.
But I say unto you, that whosoever is angry with his brother without a cause,
shall be in danger of the judgment; and whosoever shall say to his brother, Raca,
shall be in danger of the council; but whosoever shall say, You fool,
shall be in danger of hell fire.`"_

Here we may learn that the law provided nothing against anger, only in this case,
against shedding of blood,
and many times if anger is too much kindled it sets the soul on fire of hell,
if it be not timely quenched.
People, as it grows hotter, call one another out of their names,
and take the name of the Lord in vain, break the third commandment, swearing by him,
and cursing men.
We may plainly see by Christ`'s doctrine, that anger, without cause, is dangerous.
Soft words from a sedate mind will wonderfully help in this case:
it is not easily conceived what a mighty advantage
Satan has upon one that is angry without a cause:
and we are often apt to think we have cause when we have none at all;
and then we make work for repentance, without which we are in danger of hell fire.
Therefore every true Christian ought to watch against the evil of anger;
and yet there may be anger where there is real cause, without sin.

[.offset]
_"`Therefore if you bring your gift to the altar,
and there remember that your brother has aught against you;
Leave there your gift before the altar, and go your way;
first be reconciled to your brother, and then come and offer your gift.`"_

The Christian religion admits of no malice or guile;
the worship of it is in spirit and truth, and love, without hypocrisy,
without deceit or hatred: if we come with these to the altar,
they will hinder our acceptance.
Though we may indeed have a gift, we are to seek reconciliation, and not say,
let him come to me, I will not go to him; but Christ tells us we must go to him;
and if you go to the offended in a meek and Christian spirit, and seek reconciliation,
if your brother will not be reconciled, if the fault be in him, you have done your duty,
and your gift will be received,
and Christ will manifest himself to you by his grace and spirit.
But you are yet to seek for peace, he having ordained it,
and laid it as a duty incumbent on you.

[.offset]
_"`Agree with your adversary quickly, whiles you are in the way with him;
lest at any time the adversary deliver you to the judge,
and the judge deliver you to the officer, and you be cast into prison.
Verily I say unto you, you shall by no means come out of there,
till you have paid the uttermost farthing.`"_

It is plain from this passage, that Jesus is for a quick and speedy end to differences;
"`Agree with him quickly;`" for it is of dangerous
consequence to let disagreements lay long,
they eat like a canker, and they destroy the very nature of religion.
Personal differences are a great hurt to families, to churches,
and to nations and countries, especially when espoused by parties; then what rending,
tearing and devouring work it makes: therefore take Christ`'s counsel and agree quickly.
If the difference be on the account of debt, and the debt be just,
it is better to offer up one`'s self and all that he has in the world,
than to stand out with one`'s adversary, till it come to the utmost extremity;
and for Christians to go to law one with another, is contrary to the apostle`'s advice;
and often times the gainer of the cause loses by going to law;
so that it is good to agree quickly; it being profitable so to do,
both spiritually and naturally.

[.offset]
_"`You have heard that it was said by them of old time.
You shall not commit adultery.
But I say unto you, whosoever looks on a woman to lust after her,
has committed adultery with her already in his heart.`"_

The law was against adultery; but the gospel is against lust; and where there is no lust,
there can be no adultery; for then the occasion of adultery is taken away;
and the cause being taken away, the effect of course ceases.
Behold the chaste and pure doctrine of Christ, and his holy dispensation,
greatly excelling the law, or Mosaic dispensation!
Our blessed Saviour does not admit of an unchaste or lustful looking upon women;
much less of immodest salutations, touches, embraces, or discourses,
which all tend to beget lust in the hearts of men; and lust conceived, brings forth sin;
and sin when finished, brings forth death to the soul.

[.offset]
_"`And if your right eye offend you, pluck it out, and cast it from you;
for it is profitable for you that one of your members should perish,
and not that your whole body should be cast into hell.
And if your right hand offend you, cut it off, and cast it from you;
for it is profitable for you that one of your members should perish,
and not that your whole body should be cast into hell.`"_

Christ compares the sinful lusts and inclinations,
which are the cause of men`'s destruction, and their being cast into hell,
to a right eye, or a right hand,
two of the most useful and serviceable members of the body;
not that he intended that we should cut off our natural members,
but that we should cut off these sinful lusts, and cast them from us,
though they were as a right eye, or hand.
It is very much against nature, and very painful to pull out an eye, or cut off a hand;
so sin of many kinds, is very agreeable to the natural man,
and it is very hard for him to part with it; he pleads the use of it,
and when Christ the physician of the soul, comes to put his knife to it,
which is his word, poor man is too apt to fly from it,
and to shrink from under its stroke: the holy baptist, John,
understanding our Lord`'s doctrine,
and being sensible of the powerful working of Christ`'s word and spirit, says,
"`Now also the axe is laid to the root of the trees, every tree therefore,
which brings not forth good fruit, is hewn down and cast into the fire.`"

[.offset]
_"`Again you have heard, that it has been said by them of old time,
you shall not forswear yourself, but shall perform unto the Lord your oaths.
But I say unto you, swear not at all, neither by heaven, for it is God`'s throne:
Nor by the earth, for it is his footstool: neither by Jerusalem,
for it is the city of the great king.
Neither shall you swear by your head, because you can not make one hair white or black.
But let your communication be yes, yes; no, no; for whatsoever is more than these,
comes of evil.`"_

It was allowed to the Jews to vow to the Lord, and swear by his name,
provided they performed their vows and oaths.
But here our Lord prohibits and abolishes all swearing, with an "`I say unto you,
swear not at all.`"
Though swearing Christians will have it that he here prohibits only vain swearing,
or common swearing; this cannot be, because the oaths he here speaks of were solemn,
and to the Lord.
And the apostle James tells us, "`We must not swear by any oath.`"
Neither did the primitive Christians swear at all;
and Christians ought to be so just in their conversation,
as that their solemn words or promises would give them credit without any need of oaths.
If more than yes, yes, and no, no, be evil, it must also be evil to require more,
and that it is evil if it be more, as all vows and oaths are,
we have Christ for our author, a good foundation to build upon.

[.offset]
_"`You have heard that it has been said, an eye for an eye, and a tooth for a tooth.
But I say unto you, that you resist not evil:
but whosoever shall smite you on your right cheek, turn to him the other also.
And if any man will sue you at the law, and take away your coat,
let him have your cloak also.`"_

There was liberty by the law of Moses, for a man to revenge himself,
if he had an injury done to him; but Christ teaches patient suffering;
we are not to give any offence, but we are to take them quietly for his sake,
in which Jesus was an excellent example to us, whose sufferings were not for himself,
but for us; he turned his cheek to the smiter,
and his face to those that plucked off the hair.
To a man of courage and choler, this indeed is no small cross; but he must deny himself,
and take up Christ`'s cross daily, and follow him, if he will be his disciple:
and as for the law, it is better never to meddle with it, in a general way;
and if your coat by law is taken away, you had better give him your cloak,
than stand another trial with him: and it is much if you are not a gainer by so doing.
But the gain is not urged as the motive; but obedience to Christ,
our great Lord and good Master; who said, "`If you love me, keep my commandments.`"

[.offset]
_"`Give to him that asks you, and from him that would borrow of you, turn not away.`"_

We are here to suppose the asker to be in real need and necessity,
and the borrower also to stand in need,
and the asked to be in a capacity and of ability
to supply and assist the asker and borrower;
and in such case we are by no means to refuse to give him that asks,
nor turn away from him who would borrow of us.
If we are not in a capacity to supply, we are yet to use mild and friendly expressions;
for Christians should be courteous and kind to all, and particularly to the distressed.
And if we think the askers or borrowers are not worthy or deserving for their own sakes,
we should, if need be, give and lend for Christ`'s sake, and in obedience to him,
though it cross our own inclinations.

[.offset]
_"`You have heard that it has been said, you shall love your neighbour,
and hate your enemy.
But I say unto you, love your enemies, bless them that curse you,
do good to them that hate you, and pray for them who despitefully use you,
and persecute you.
That you may be the children of your Father who is in heaven,
for he makes his sun to rise upon the evil, and on the good, and sends rain on the just,
and on the unjust.`"_

The Hebrews had liberty to hate their enemies, but no people, by any dispensation,
had liberty to hate their neighbours or friends; so that those who are in that state,
are far beyond the line of truth.
But, says our holy Lawgiver, "`I say unto you, love your enemies.`"
If we love our enemies, we can in no way destroy them, although it were in our power.
Again, "`Bless them that curse you.`"
But, alas! how apt are men,
and even those who would think it hard to be told they are disobedient to Christ,
to render railing for railing, and cursing for cursing, instead of blessing.
Do good to them who hate you.
If we are sensible that anyone hates us, and have demonstration of it,
for sometimes we imagine it, when it is not so,
yet are we to do them all the good turns we can.
And pray for them who despitefully use you, and persecute you.
Thus we are not to render evil for evil, but to overcome the evil with that which is good.
Sweet was our Lord`'s example to us in this, when he said, "`Father, forgive them,
for they know not what they do.`"
If spiteful persecutors really know what they do, when they persecute the just,
their damnation must needs be very great; but if we do good for evil,
as Christ has taught, then are we the children of our heavenly Father,
"`Who makes his sun to rise on the evil, and on the good, and sends rain on the just,
and on the unjust.`"

[.offset]
_"`For if you love them who love you, what reward do you have?
do not even the publicans the same?
And if you salute your brethren only, what do you more than others?
do not even the publicans so?`"_

Our virtue is much more shining in loving those who do not love us,
than in loving those who do.
It is natural for us to love those who love us,
and we should be ungrateful if we did not; but the reward is greater,
if we love them who do not love us, which must be manifested in deeds, as well as words;
for saying and doing sometimes are two things, which made the apostle say,
"`Our love must not be with word, and with tongue only, but in deed and in truth.`"

As to friendly and hearty salutations, that may be necessary or needful,
we should not only manifest them to our brethren, but as occasion requires to all,
it being a shining virtue in Christians to be kind to strangers,
and to show forth a generous and loving temper and
deportment to such as may not be of us;
though not in a flattering, modish, or complimental way, but hearty and respectful,
according to the plainness of Christ and the simplicity of his gospel,
without respect of persons, respect being too generally, shown to high,
more than to them of low degree.
As we are not to refuse our friendly salutations to the great, or the rich,
so we are not to neglect the poor, for the publicans do so.

[.offset]
_"`Be therefore perfect, even as your Father which is in heaven is perfect.`"_

Christ would have us to be perfect in the practice of his doctrine,
and to live up to it in perfect obedience,
according to the best of our judgment and understanding,
and not to do his work by halves, but honestly and perfectly,
according to the measure of grace received.
Some have received twice, some thrice so much as some others,
as the parable of the talents plainly shows;
but whatever discoveries or manifestations of grace, light, or truth, we have received,
we ought to walk up to them perfectly;
"`Even as your Father which is in heaven is perfect.`"
As the Almighty is perfect in his love, justice, mercy, grace and truth,
unto poor mortals, in Christ Jesus, his only begotten, and in all his works;
so ought we to be perfect in our known duty: as it is written, "`You shall be holy,
for I the Lord your God am holy.`"
So must we be according to the degree of grace received.

It is supposed that no body will imagine that any
mortal can come up in degree with the Almighty,
but according to our measure, gift, and degree of grace received,
we are to be holy and perfect, as God, our heavenly Father, and Christ, our dear Lord,
are so in fulness.

[.offset]
_"`Take heed that you do not your alms before men, to be seen of them,
otherwise you have no reward of your Father which is in heaven.
Therefore when you do your alms, do not sound a trumpet before you,
as the hypocrites do, in the synagogues and in the streets,
that they may have glory of men: verily I say unto you, they have their reward.
But when you do alms, let not your left hand know what your right hand does:
"`That your alms may be in secret, and your Father which sees in secret,
himself shall reward you openly.`"_

The Christian religion, in its purity, according to the doctrine of the founder of it,
is a compassionate religion, and full of pity, as well as piety.
It is a holy composition of charity and goodness.
The apostle thus describes it: "`Pure religion, and undefiled before God and the Father,
is this, to visit the fatherless and widows, in their affliction;
and to keep himself unspotted from the world.`"

This is pure religion, and this is the Christian religion:
happy are those who walk up to it,
and live according to the precepts of Him who dictated them;
then the widows and the fatherless would not be neglected;
the poor would be very generously taken care of, and our garments kept clean,
and all done as secretly as may be.
For when we proclaim our alms-deeds and charity,
we lose our reward from our heavenly Father.
Also when alms are given, it ought to be done in the spirit of love and meekness,
and so received; else the receiver loses a second benefit,
and the giver his heavenly reward.
To give to the poor is to lend to Him that made us,
and we shall have good and greater measure returned us again.
If we hope to have the gates of Christ`'s kingdom opened to us at last,
our hearts must also be opened to the poor and needy, when in distress;
remembering the words of Christ, where he says to some who were waiting for,
and wanting an entrance into the kingdom, "`I was hungry, and you gave me no food;
I was naked, and you clothed me not.
I was sick and in prison, and you visited me not.`"
They answered, "`Lord, when saw we you hungry, naked, sick, or in prison,
and did not feed you, clothe you, and visit you?`"
He answers,
"`Inasmuch as you did it not to one of the least of these, my brethren, you did it not to me.`"
He sympathises with his poorest and meanest members, whatever others do,
and takes that which is done to them, as if done to himself, whether it be good or bad.
We should be good to all, but especially to Christ`'s members,
or the household of the faithful keepers of his commandments.
Our alms being thus distributed, according to our ability,
and the necessities of the object, without ostentation, and in secret,
our munificent Father, who sees in secret, will openly reward us.

How many rich men are there in the world,
who have made great and costly entertainments for their rich friends,
neighbours and relations; and if their substance be so great,
that it is not felt by them, they had the more need to remember the poor;
when they never so much as spare the tithe of it to them,
though the poor have ten times the need of it; and though Christ says,
"`When you make a feast, invite not your rich friends, for they will invite you again;
but call the poor, the lame, and the blind,`" etc.

[.offset]
_"`And when you pray, you shall not be as the hypocrites are,
for they love to pray standing in the synagogues, and in the corners of the streets,
that they may be seen of men; verily I say unto you, they have their reward.
But you, when you pray, enter into your closet, and when you have shut your door,
pray to your Father which is in secret, and your Father which sees in secret,
shall reward you openly.
But when you pray, use not vain repetitions, as the heathen do:
for they think they shall be heard for their much speaking.
Be not therefore like unto them;
for your Father knows what things you have need of before you ask him.`"_

Prayer is absolutely necessary for the being and well-being of a Christian;
an outside formal Christian may use the form, though unreformed;
but it avails little without reformation.
Private prayer, according to Christ`'s rule, is effectual and rewardable,
agreeable to his doctrine.
He also speaks against hypocrisy and loving to be seen of men,
with a command not to be like unto those who do so.
"`But you, when you pray, enter into your closet.`"
When we feel and are sensible of a divine call,
this must of course be the right and best time,
for Christ has not set us a distinct hour,
then we are to enter into the closet ofa humble heart or mind,
or some secret place in private.
This is Christ`'s order for particular persons in a general way;
but is not intended to prevent such who are rightly concerned
to pray in the public assemblies or gatherings of the church;
for we have Christ for our example, who prayed openly and publicly with his disciples.

"`But when you pray, use not vain repetitions, as the heathen do;
for they think to be heard for their much speaking,`" Formal repetitions of prayer,
repeated day by day, when they are not according, but contrary,
to the states of those by whom they are read or repeated, must needs be vain,
and people may vainly make use of the Lord`'s own form in that case,
though it is the best in the world, and to think to be heard for much speaking,
is to run into the error of the heathen.
"`Be not,`" says Christ, "`therefore like unto them;
for your Father knows what things you have need of, before you ask him.`"
Prayer is a gift from God and from Christ,
and as we wait on God in Christ`'s name and power, he will give us that gift,
when he sees we stand in need of it, or that it will be for our edification.
For he has promised to pour out the spirit of prayer and of supplication upon his people.
A great apostle said, "`If he prayed, he would pray with the spirit.`"
In another place he says, "`We know not what we should pray for, as we ought;
but the spirit itself makes intercession for us, with groanings that cannot be uttered.`"
Likewise, "`The spirit also helps our infirmities.`"
Since there is no form like that of Christ`'s, it is here set down,
that people might take diligent care to learn it, and to teach it to their children.
But if they learn it rightly, they must also learn to live in it: that is,
live according to it; otherwise they will mock, instead of serving Him,
who made both it and them for his own honour, and the glory of his name.

[.offset]
_"`After this manner therefore pray: Our Father who is in heaven, hallowed be your name:
Your kingdom come: your will be done in earth, as it is in heaven.
Give us this day our daily bread. And forgive us our debts, as we forgive our debtors.
And lead us not into temptation, but deliver us from evil; for yours is the kingdom,
and the power, and the glory, forever.
Amen. For if you forgive men their trespasses, your heavenly Father will also forgive you.
But if you forgive not men their trespasses,
neither will your Father forgive your trespasses.`"_

A short form and but few words, but of excellent composition.
And truly happy are those, who live so in their conversation, that they may,
when they use them, do it without falsehood, or deceit;
enjoying the answer of peace in the practice of it,
and the sense of grace influencing the soul.

[.numbered-group]
====

[.numbered]
_First;_ "`Our Father who is in heaven.`"
The great Creator, our universal Father, has made us and all nations, of one blood;
but there is another, and a nearer relation to him than this,
to be a child of God by regeneration.
If we live in an unregenerate state, in our sins and lusts, all which are of Satan,
then Christ says, "`You are of your father the devil;
and the lusts of your father you will do;`" and in another place, he says,
"`Whosoever shall do the will of my Father who is in heaven, the same is my brother,
and sister, and mother.`"
It is into this relation that the soul ought to come, who can truly and religiously say,
"`Our Father,`" etc.

[.numbered]
_Second;_ "`Hallowed be your name.`"
Do we sanctify the holy name of the God of the whole earth?
Do we religiously observe to fear and serve him?
Do we profane his awful name, by taking it in vain, and living in sin and vanity?
This instead of hallowing and sanctifying his name,
is to dishonour and reproach it on our part,
though he will hallow and honour his own name in justice and judgment,
on profane and ungodly livers, at the last day,
when he shall come to judge the quick and the dead by Jesus Christ.
God will not be mocked; such as every one sows, such shall they reap,
whether sin unto death, or righteousness unto life.

[.numbered]
_Third;_ "`Your kingdom come.`"
His kingdom is a kingdom of righteousness.
Happy souls! who seek the righteousness of it betimes and continue in it to the end.
If this kingdom come, Satan`'s, which is a kingdom of sin and unrighteousness,
must needs fall.

Oh! that the rising generation might be strong to overcome the wicked one,
and to be instruments to pull down his kingdom,
and promote the kingdom of God and his Christ.
If we do not believe that Satan`'s power and kingdom may and ought to be destroyed in us,
how can we pray without hypocrisy for the coming of God`'s holy kingdom?
Believing we must live and die in sin, is a great support to Satan`'s kingdom,
and a great hindrance of the coming of the kingdom of the dear Son of God.

[.numbered]
_Fourth;_ "`Your will be done in earth as it is in heaven.`"
Most certainly the will of God is punctually and perfectly done in heaven;
and hardly any who make use of this blessed form but believe it is so;
but it is the misery of many souls,
to believe it not possible for them to do God`'s will here on earth,
as it is done in heaven.
So that such pray in unbelief, or without a true faith; and the apostle says,
"`What is not of faith is sin.`"
Is it not also charging Christ with commanding that which cannot be done?
It is worthy our sedate consideration.
He has shown grace, and ought in justice to reap it from all mortals.
The great sower, Christ, sows in all sorts of men or grounds:
the grace of God appears to all men,
and teaches them to deny ungodliness and worldly lusts, to live soberly, and righteously,
and godly, in the present world.
But antichrist teaches that it cannot be done here on earth as in heaven.

[.numbered]
_Fifth;_ "`Give us this day our daily bread.`"
We not being capable, without his blessing, of procuring bread for our bodies or souls,
either natural or supernatural; and because our souls cannot live without the last,
no more than our bodies without the first,
therefore we ought to pray to our heavenly and most holy Father for both,
without doubting: and this should be done daily, either in words, holy sighing,
or spiritual groans, the Almighty knowing the language of the soul in the one,
as well as in the other.

[.numbered]
_Sixth;_ "`Forgive us our debts, as we forgive our debtors.`"
Or, as one of the evangelists has it, "`Our trespasses,
as we forgive them who trespass against us;`" which is to the same end and purpose.
If a debtor is indebted to us, and happens, through some accident or other,
to be insolvent, and has not enough to pay, we are to forgive him,
else how can we expect God to forgive us.
For we are all his debtors, and have nothing that we can call our own,
to pay that great debt which we owe to him, our mighty creditor;
who might lawfully cast us into an eternal jail.
But, Oh! his infinite mercy and love to us poor mortals: he would have us to imitate him,
and forgive one another, as we expect he should forgive us.
And since offences and trespasses will come, we must forgive, and the more freely,
when the person offending, sues for it, by humble petition, to the offended.
If we forgive not, neither will our heavenly Father forgive us our trespasses.

[.numbered]
_Seventh;_ "`And lead us not into temptation, but deliver us from evil;
for yours is the kingdom, the power, and the glory, anyone.
Amen.`"
That is, lead us into truth and righteousness,
which is the same with leading us out of sin, and out of temptation:
for we pray to be led out of it, by praying not to be led into it;
seeing we are not to understand that the Almighty will tempt any man to evil.
"`If,`" says the apostle, "`any man is tempted,
let him not say that he is tempted of God, for God tempts no man,
but he is tempted when he is drawn away of his own lust.`"
Though he does sometimes permit us to be tempted,
and when we fall into various temptations, and escape them, we have cause to be joyful,
and thankful that we are delivered out of them, and give the glory to God,
who is the great preserver of men: whose "`is the kingdom, and the power, and the glory,
anyone.
Amen,`"

====

[.offset]
_"`Moreover, when you fast, be not as the hypocrites, of a sad countenance,
for they disfigure their faces, that they may appear unto men to fast;
verily I say unto you, they have their reward.
But you, when you fastest, anoint your head and wash your face.
That you appear not unto men to fast, but unto your Father which is in secret,
and your Father which sees in secret shall reward you openly,`"_

Christ would have all our works of piety, virtue and charity,
all our religious duties done in the divine love and filial fear of God,
and not for vain glory, or ostentation.
And truly, without we expect our reward from men, there is no need of an outward,
hypocritical show, in such duties as that is of fasting, when truly called to it,
and truly performed.
This the Jews were much in the practice of;
but many of them being formal hypocrites in it, our Lord reprehends them,
and warns his hearers to shun the like deceit; and tells them, if they fast secretly,
their heavenly Father will reward them openly: yet we must not be open sinners,
or private ones either: for open or public sin is damning,
if not repented of and forsaken, as well as private deceit.

[.offset]
_"`Lay not up for yourselves treasure upon earth, where moth and rust does corrupt,
and where thieves break through and steal.
But lay up for yourselves treasure in heaven, where neither moth nor rust does corrupt,
and where thieves do not break through nor steal,
For where your treasure is, there will your heart be also.`"_

Earthly treasures are very apt to take up the mind and draw it from heaven,
and because Christ would have his children to be in heaven with him,
in tender love he advises them not to lay up for themselves riches or treasure on earth.
If it be said we lay it up for our children, it may be said also,
it is the same snare for them, as to the parents, and sometimes a greater;
and when it is gotten, it is liable to many casualties,
and creates a great deal of care and trouble.
Therefore Christ tenderly advises to seek after, and lay up treasure of another nature,
in a safer and better place, which will not be liable to the like casualties,
and urges us to it, with this great reason; "`For where your treasure is,
there will your hearts be also.`"
Oh! may every true Christian`'s treasure and heart be there forever.

[.offset]
_"`The light of the body is the eye, if therefore your eye be single,
your whole body shall be full of light.
But if your eye be evil, your whole body shall be full of darkness:
if therefore the light which is in you be darkness, how great is that darkness.`"_

It is not good to look on men or things with an evil eye;
but singly to look on one`'s self and others, in the fear of God,
having a single eye to his glory; and then being enlightened by his divine light,
we shall discern between good and evil.
Whereas if there be any double dealings, or looking or thinking;
or if ungodly self be in the bottom, and not the glory of God;
then our light will be darkness, and that darkness will be very great;
as it is said in the holy Scriptures, a double minded man is unstable in all his ways:
so that our Saviour`'s doctrine is good; to have a single eye,
and to avoid all double dealing.

[.offset]
_"`No man can serve two masters; for he will either hate the one and love the other;
or else he will hold to the one, and despise the other:
you cannot serve God and mammon.`"_

We cannot give our hearts to God and to this world, and the things of it also,
so as to set our affections on both, for the apostle says, "`If any man love the world,
the love of the Father is not in him.`"
And again, "`The love of money is the root of all evil;`" i. e.,
the inordinate love of it, and seeking after it, more than for our Maker and Saviour,
Then let us despise the world and the things of it,
in comparison of our God and our Saviour.
We do not understand by those words of Christ,
that he intended to debar us from seeking a comfortable
accommodation for ourselves and families in this world;
but that we should not set our hearts and affections upon it;
for we cannot equally affect both heaven and earth.

[.offset]
_"`Therefore I say unto you, take no thought for your life, what you shall eat,
or what you shall drink; nor yet for your body, what you shall put on:
is not the life more than food, and the body than raiment?
Behold the fowls of the air: for they sow not, neither do they reap,
nor gather into barns; yet your heavenly Father feeds them.
Are you not much better than they.`"_

Christ would have us without anxious thoughts about our living in this world, i. e.,
about our eating, drinking and clothing, and tells us, "`That the life is more than food,
and the body than clothing;`" by which he shows us, that he who gave the life, will,
by his providence, support it: and as he has formed the body,
he will form that which must feed it;
and that we might the more depend upon God`'s providence,
he teaches us by the fowls of the air, which neither sow nor reap, nor gather into barns,
and yet their great Creator feeds them; and asks, if we are not much better than they?
So that we being more noble creatures, need not doubt of the care and providence of God,
and his blessing on the labour of our hands;
though our hearts are not concerned unnecessarily about it,
but we have freely given them to God, and his Christ, our Saviour.

[.offset]
_"`Which of you by taking thought, can add one cubit to his stature.`"_

The farmers or planters, cannot by their thoughtfulness, cause their corn, fruits,
or cattle, to multiply or grow; nor the tradesman his custom, goods, or business,
without a proper application, which our Saviour is not against,
only he would have us without an encumbered and over-caring mind.
The merchant likewise, by all his thoughtfulness, cannot bring home his ship from afar,
nor carry her safe to her desired port.
All things of this kind are in the hands of Almighty God,
and it is our duty to trust in him, and to depend upon his divine providence, for food,
drink and clothing, for happiness here, and hereafter, forever.

[.offset]
_"`And why do you worry about clothing?
consider the lilies of the field how they grow; they toil not, neither do they spin.
And yet I say unto you, that even Solomon, in all his glory,
was not arrayed like one of these.
Therefore, if God so clothe the grass of the field, which today is,
and tomorrow is cast into the oven, shall he not much more clothe you,
Oh! you of little faith.
Therefore take no thought, saying, what shall we eat, or what shall we drink,
or wherewithal shall we be clothed?
For after all these things do the gentiles seek;
for your heavenly Father knows that you have need of all these things.`"_

Many people now, as well as then, are very fond of their clothing,
and love to be gay and fashionable therein;
and some are not a little proud of their clothes,
and are thoughtful how they may deck themselves to be admired.
Our Lord, who was meek and lowly of heart,
sends us to the lily to consider her beauty and glory and innocent thoughtlessness,
declaring that Solomon, in all his grandeur and splendour,
was not arrayed like one of these:
for this is a natural sweetness and gaiety the lily is clad with; but Solomon`'s,
as also most men`'s and women`'s, is generally but artificial.
If God so clothe the grass of the earth, will he not clothe us; if we believe not,
we must have but very little true faith.
So that it would be much better for us to consult how we shall please God and honour him,
and his holy Son and divine name, than to consult what we shall eat or drink,
or how we shall be clothed, which things the gentiles sought after, more than after God.
But we, knowing that our heavenly Father sees that we have need of all these things,
should chiefly leave it to him, and first seek his kingdom and righteousness.

[.offset]
_"`But seek first the kingdom of God and his righteousness,
and all these things shall be added unto you.
Take therefore no thought for the morrow:
for the morrow shall take thought for the things of itself:
sufficient unto the day is the evil thereof.`"_

Here is a glorious gospel promise;
upon seeking first the kingdom of God and his righteousness,
all these things shall be added to us, that is, food, drink and clothing,
the necessary things that we need to support us while we are in this world.
But let us remember it must be our first work, it must be the chief desire of our souls.
It must be first in several senses; first, as to our young and tender years; first,
in the morning of every day; first, in respect of all other things.

[.numbered-group]
====

[.numbered]
_First,_ as it has pleased God to give us a being in this world,
and being in the prime and flower of our years,
we should then devote our souls to God and his work and service,
and enter into covenant with him, with full purpose of heart,
to keep the same truly and inviolably; for it would be better not to make a covenant,
than to make it and break it.
Neither should we slight or put off the work of God till we are in our declining years,
as though we would give him only the refuse and broken end of our days,
and conclude it will better become us when we are old, to serve him.
Oh, no! learn the fear of God truly, and practise it when you are young,
and you will not easily depart from it when you are old.
You will find it hard to get into a holy life and conduct,
when you have been spending your youth in vanity and folly; therefore,
"`Remember now your Creator in the days of your youth, before the evil day come.`"
The autumn of man`'s years is in several respects called the evil day.
Oh! it is exceedingly sweet and precious to see an innocent life, and modest,
sober conduct in youth, when they are in their blooming years,
seasoned with grace and truth.
When youth is laden with the fruits of grace, and of the holy Spirit,
how pleasant is the taste of it; it relishes well with all men,
and naturally brings praise to God, as well as peace to the soul.
May the youth of this present generation, as also generations to come,
be such holy plants, that God`'s right hand may be seen in planting them:
when after being fruitful, and doing the work and service of their day,
and answering the noble end of God in making and planting them in this world,
they may be transplanted into the eternal kingdom of heaven; which, doubtless, they will,
who first seek his kingdom and the righteousness of it.

[.numbered]
_Second;_ If we consider that our life and being is daily granted to us,
and we are supported by the goodness and providence of Almighty God every day,
is it but just that he should have the first of our thoughts, in the morning of the day,
as well as the last in the evening.
The royal psalmist says, "`If I prefer not Jerusalem before my chiefest joy,
then let my right hand forget its cunning,
and my tongue cleave to the roof of my mouth;`" much
more ought we to prefer our Creator to all things,
and to have our thoughts on him, first in all things, and every day.

[.numbered]
_Third;_ What are the things of this world in comparison of those that are to come;
all these are fading and transitory; but the things of that which is to come,
are durable and permanent; and therefore ought to be first and chief in our minds.
That which is chief in our hearts, may be said to have the first place there.
"`One thing,`" says a servant of God, "`have I desired, and that will I seek after,
that I might dwell in the house of God all the days of my life.`"
This is the first thing we are to seek for.
As for the morrow, we need not to be too thoughtful or anxious concerning it,
for we know not whether we shall live to enjoy it, so that as Christ says,
"`Sufficient unto the day is the evil thereof.`"

====

[.offset]
_"`Judge not, that you be not judged:
For with what judgment you judge, you shall be judged; and with what measure you use,
it shall be measured to you again.`"_

A great and wise expression, from a righteous and just Judge;
the Judge of heaven and of earth, to whom all power in both is given;
by which we may easily perceive we are to be very
careful in our judgment and censure of others,
and that we be not rash and censorious therein;
considering that with what judgment we judge our fellow mortals,
with such shall we also be judged ourselves,
and that measure which we measure out to others, shall be filled to us again.
When it comes to our turn to be judged, or censured by others,
for anyone which we have done or said, we are ready then to cry out for charity;
are we so careful to be charitable in judging and censuring others!

It is better to suspend personal judgment, without we could see the hearts of men;
and if we think we do, then to imitate God and Christ,
and mix mercy and love with judgment; rashness and extremes in judgment,
being commonly hurtful.

[.offset]
_"`And why do you behold the mote that is in your brother`'s eye,
but consider not the beam that is in your own eye? Or how will you say to your brother,
let me pull out the mote that is in your eye,
and behold a beam is in your own eye.
You hypocrite, first cast out the beam out of your own eye,
and then shall you see clearly to cast out the mote out of your brother`'s eye.`"_

True it is, that the transgressions of others are very afflicting to those who fear God,
and this passage is not intended to hinder the good from reproving the evil;
but shows us that we must be clear of evil in ourselves when we reprove others,
else the guilt of hypocrisy will be laid at our door.
We are to look more at our own failings, than at the failings of others,
and to take special care that we are clear of that for which we reprove others;
and is it not deceit, to set up for reformers of others,
when there are great defects in ourselves?
It is too general a fault in poor mortals to be quicker
sighted to see the faults of others,
than their own.
Our Saviour`'s words to the Jews, who brought the woman to him, and told him,
by their law she ought to die, are worthy of notice; he answers,
"`He that is without sin, let him cast the first stone at her.`"
They being guilty, and convicted of sin in their own consciences, left her to Christ,
and went their way: and when we have done what we can to convince others of sin,
we must leave them to Christ at last; whether we are in sin or without it;
but we shall be the better able to help to reform others,
if we are clear from guilt in our own hearts.

[.offset]
_"`Give not that which is holy to dogs, neither cast your pearls before swine,
lest they trample them under their feet, and turn again and rend you.`"_

When we see the biting and persecuting nature, and dirty, selfish spirit of men,
it is to little purpose, generally, to cast before them the precious pearl of truth,
or to show unto them the deep mysteries of the kingdom of God, or the light of life,
they being in a brutish spirit; but when people are sober,
and show forth humanity and moderation, then are holy things valuable to them,
and the things of Christ`'s kingdom and his doctrine, precious in their eyes.
Therefore it greatly behooves Christ`'s ministers to minister
that to the people which is suitable for them,
and rightly to divide between the precious and the vile,
and to give to every one their portion, according to their deeds; mercy to whom mercy,
and judgment to whom judgment belongs; without partiality,
and without hypocrisy or deceit;
and not to flatter and daub those who are in the doggish and swinish nature.

[.offset]
_"`Ask, and it shall be given you; seek, and you shall find; knock,
and it shall be opened unto you.
For every one that asks, receives; and he that seeks, finds; and to him that knocks,
it shall be opened.
Or what man is there of you, whom if his son ask bread, will he give him a stone?
Or if he ask a fish, will he give him a serpent?
If you then, being evil, know how to give good gifts to your children,
how much more shall your Father who is in heaven give good things to them that ask him?`"_

Our kind and tender Redeemer would stir up and provoke souls to prayer and supplication;
he has been liberal in his holy advice; and to stir us up to it,
here are moving expressions, if your heart be open to receive them.
Could we have easier terms if we were to make them ourselves with the Lord, than to ask,
and have; seek, and find; knock, and the gates are opened; provided we ask in faith,
tenderly, and seek in humility, and knock with divine wisdom and submission?
Our Lord`'s own practice shows that we should be tender, submissive,
and fervent in prayer;
and then the fervent prayer of the righteous avails much with the Lord.
Christ urges us to it, and brings ourselves for example.
"`What man is there among you, who if his son ask bread, or a fish,
will he give him a stone, or a serpent?`"
Surely no: no father would deal thus with his child; but when his child is hungry,
and asks bread, he gives it to him: so when the Almighty sees our hunger,
and we tenderly seek divine assistance and refreshment from him, he, in his own time,
satisfies such souls with bread from above,
and the thirsty with living water out of the wells of salvation.
Oh! blessed be his holy name forevermore.
Evil men know how to give good things to their children,
therefore we may well conclude that our heavenly Father knows how to give
with much more discretion and understanding the good things of his kingdom,
to true asking, seeking, knocking, or praying souls.

[.offset]
_"`Therefore all things whatsoever you would that men should do unto you,
do you even so to them; for this is the law and the prophets.`"_

Well may this be called the golden rule; for if we square our lives and actions by it,
it will certainly lead us in the true way to happiness and glory.
We are generally apt to say, when anyone does ill to another,
"`Would he be willing to be served so himself?`"
And if we follow this rule in all our concerns, it will be well;
whether in relation to public or private business; whether in trade or religion,
or in our domestic affairs: the law and the prophets point at it,
and our Saviour plainly lays it down as a rule for us to walk by.

[.offset]
_"`Enter in at the strait gate; for wide is the gate,
and broad is the way that leads to destruction, and many there be who go in thereat.
Because strait is the gate, and narrow is the way that leads unto life,
and few there be who find it.`"_

It is afflicting to consider how natural it is for people to walk in this broad way,
and they who walk in it, are many; for here is room for people to walk if they are proud,
whoremongers, adulterers, thieves, swearers, liars, drunkards, covetous,
or in any other evil course of life; but let them know, it leads to destruction,
and the end is eternal misery,
and their many companions will administer no consolation to them,
when they lift up their eyes in hell.
And whereas the way that leads to life is called strait,
it is only strait to flesh and blood, or the will of unregenerate man.
Oh! it is a pleasant way, exceedingly pleasant,
when brethren walk together in love and unity.
The enemy of mankind would persuade souls, that it is narrower than it really is,
when they have some faint inclinations to make trial of it.
It may truly be said, "`Blessed are the undefiled in this way,
who walk in the law of the Lord:`" For, "`His ways are ways of pleasantness,
and all his paths are peace.`"
And although the way to the kingdom is strait and narrow,
yet there are hills and valleys therein as well as plains,
until we get through the gate of glory: there shall we know no more sorrow, nor pain;
but shall praise and glorify God and the Lamb forever.

[.offset]
_"`Beware of false prophets, who come to you in sheep`'s clothing;
but inwardly they are ravening wolves.
You shall know them by their fruits; do men gather grapes of thorns,
or figs of thistles?
Even so every good tree brings forth good fruit;
but a corrupt tree brings forth evil fruit.
A good tree cannot bring forth evil fruit,
neither can a corrupt tree bring forth good fruit.
Every tree that brings not forth good fruit, is hewn down, and cast into the fire.
Therefore by their fruits you shall know them.`"_

The great Shepherd and Bishop of souls, shows the care which he takes of his sheep,
and forewarns them to be careful of false prophets and deceivers; who,
though they may clothe themselves with words like the true ones,
yet inwardly they would destroy all who do not join with them, or receive them;
and they are for biting the poor harmless sheep of Christ, and if they could,
or it were in their power, would devour them, their minds being in the ravening nature.
But our holy and all-wise Bishop, that we might be preserved from them,
tells us how we may infallibly know them; saying, "`You shall know them by their fruits;
do men gather grapes of thorns, or figs of thistles?`"
says Christ: Surely no.
That is altogether unnatural, as well as unreasonable and impossible.
In the grape there is a sweet and pleasant nourishment,
those fruits being cordial and wholesome;
but it is bad meddling with thistles and thorns,
they being generally very unprofitable to mankind,
and hurt the good seed wherever they grow among it.
Well, where must we go for the grapes and the figs?
To be sure we must go to the vine, and the fig tree: Christ is this vine,
and his people are the branches, who bring forth such fruit,
according to the divine life or sap which they receive, as he taught,
and teaches to his followers.
So that if men`'s words be like the words of angels,
if they have never so great parts and endowments; yet if their fruit be evil,
if they live in sin and do iniquity, and bring forth the fruits of malice and rage,
or devouring persecution, they then are none of Christ`'s sheep,
though they may have their clothing: "`For every good tree brings forth good fruit;
and a corrupt tree brings forth evil fruit.`"
So if the fruit be evil, the tree is certainly corrupt.

Our Lord elsewhere says, "`Make the tree good, and the fruit will be good also:
and to be made truly good, since we are all corrupt by nature, and in the fall,
we must be cut off from that nature, and grafted into Christ, who said, "`I am the vine,
and you are the branches;`" and then our lives and fruits will be changed,
"`A good tree cannot bring forth evil fruit,
nor can a corrupt tree bring forth good fruit:
and every tree that brings not forth good fruit,
is hewn down and cast into the fire,`" That axe which John speaks of,
will be laid to the roots of the corrupt trees, and will hew them down,
and they will be cast into the fire, as Christ speaks.
It is not destroying the bodies of men that Christ speaks of,
but an inward work in the soul,
showing the powerful nature of the dispensation of the gospel of Christ,
which is not material cutting, or burning with material fire, or sword:
but Christ`'s word is a fire and sword to cut down and burn up the evil nature in man.
The apostle confirms this doctrine of his Master thus,
"`He that does righteousness is righteous, but he that sins is of the devil.`"
The apostle is plain and full, as is Christ, who repeats his doctrine over again, with,
"`Therefore by by their fruits you shall know them.`"

[.offset]
_"`Not every one that says unto me.
Lord!
Lord! shall enter into the kingdom of heaven;
but he that does the will of my Father who is in heaven.`"_

It is not our profession that will give us admittance into heaven, or a name of religion,
or religious performances, if we love sin and unrighteousness; nor is it our praying,
preaching, hearing, reading, or discoursing of, or arguing for Christ,
if we do the works of Satan; for there are many who may go further than this,
and yet not have admittance into the kingdom of God and our blessed Lord Jesus,
as is plainly manifest in the next verse.

[.offset]
_"`Many will say unto me in that day, Lord, Lord, have we not prophesied in your name,
and in your name have cast out devils, and in your name have done many wonderful works.
And then I will profess to them, I know you not; depart from me,
you workers of iniquity.`"_

So that professing Christ`'s own name, and prophesying therein,
without working the works of God, will not do.
No, though they may cast out devils, which indeed is a great work.

Christ speaks about the strong man armed,
who kept the house till a stronger than he came; who, when he came,
spoiled his goods and dispossessed him, but coming again, found the house, or heart,
swept and garnished: swept from many immoralities,
and garnished with self-righteousness and carnal security;
and the man off his watch and not at home with Christ, who is stronger than Satan:
he then reenters, and seven worse spirits with him.
So that we had need to be on our watch, and keep near to Christ,
lest after all our experience and wonderous works,
our last state be worse than our beginning, and we be shut out of the kingdom in the end.
For these say, that they have done many wonderful works in Christ`'s name:
so that we may work miraculous things,
and be sensible of wonderful power and strength from Christ; and yet,
without persevering in the way of holiness and self-denial, may fall short of heaven.
Therefore it is of dangerous consequence to live in sin and iniquity;
or to lean towards it, so as to plead for it,
or believe we cannot live without it while in this world.
For if we live and die in it, we may justly, according to the above doctrine of Christ,
expect that he will say unto us in the great day; "`Depart from me,
you that work iniquity.`"

[.offset]
_"`Therefore whosoever hears these sayings of mine, and does them,
I will liken him unto a wise man, who built his house upon a rock.
And the rains descended, and the floods came, and the winds blew,
and beat upon that house, and it fell not; for it was founded upon a rock.`"_

Oh! what excellent sayings and doctrine,
what holy precepts has Christ here recommended to the professors of his name,
and to them who believe in him and the Almighty Father and Maker of heaven and earth.
Surely we are greatly beholden to our Lord Jesus Christ for those divine sayings.
But to commend them or to read them, or hear them only, is doing but little;
the keeping and the doing of them is the main thing; the thing that is needful;
and to press the practice of them, Jesus has made this apt comparison.

[.numbered-group]
====

[.numbered]
_First;_ "`He who hears them, and does them, I will liken him unto a wise man.`"
And indeed it is great wisdom to keep them, that is, to practise them,
and as great folly to live contrary to them and plead against them.

[.numbered]
_Second;_ "`Who built his house upon a rock.`"
This rock is Christ, the rock of ages, and his Holy Spirit, or the Holy Spirit,
as Christ said to Peter, when Christ was revealed to him:
"`Flesh and blood has not revealed this unto you,
but my Father who is in heaven:`" "`You are Peter,`" or a stone or rock: you are a man,
though your name signifies a rock, and as your name signifies a rock,
so "`On this rock I will build my church; the gates of hell cannot prevail against it.`"
Peter was one who heard these sayings and did them, when he had received the Holy Spirit,
or Spirit; for which every true believer ought to pray continually, until he receive it;
through the help of which he may, without doubt, keep those holy sayings.
For of ourselves, without it, we cannot do any real good, either in speaking, thinking,
or acting.

[.numbered]
_Third;_ "`And the rain descended, and the floods came, and the winds blew,
and beat upon the house, and it fell not; because it was founded upon a rock.`"

====

If rain from above be poured out in wrath on man, for sin and iniquity,
and floods of persecution, or the windy words of men come upon this house, it will stand:
if sickness and death itself, and many other storms, that we may meet with in this world,
should beat against our building, we being built upon the Father, Son, and Holy Spirit,
shall surely stand them all, and live through all, if we hear or read Christ`'s sayings,
and practise the same; we are on the rock, and shall not fall for that reason.

[.offset]
_"`And every one who hears these sayings of mine, and does them not,
shall be likened unto a foolish man, who built his house upon the sand.
And the rains descended, and the floods came, and the winds blew,
and beat upon that house, and it fell; and great was the fall of it.`"_

If we read or hear these sayings, or doctrine of Christ,
and do not dwell in the life of it, nor practise the same, it were better we knew it not.
For our Saviour says, "`He who knows his master`'s will, and does it not,
shall be beaten with many stripes.`"
It is great folly to be sensible of Christ`'s holy will and doctrine, and not to do it:
if we profess Christianity, and build our profession on Christ,
and yet do not observe to keep his sayings,
the foundation of our building will be very loose and sandy: and when those rains,
and floods, and winds, which Christ speaks of,
shall descend and beat against this building, it must needs fall,
and the higher the building is, the greater will be the fall of it.

Thus ended the best sermon that ever was preached;
in which is set forth the great truths of God and our Lord Jesus Christ,
with blessings and rewards to the righteous, and holy believers in him,
who put in practice his precepts; and reproof to the disobedient and unfaithful;
with promises of the kingdom of heaven to one, and to the other, a being shut out of it.

[.offset]
_"`And it came to pass, when Jesus had ended these sayings,
that the people were astonished at his doctrine.
For he taught them as one having authority, and not as the scribes.`"_

They were astonished at his doctrine, and well they might be,
for it excelled even the law, and went beyond it, as when he tells them,
it was said of old time, or in the law,
"`You shall not kill:`" he taught that we must not be angry without a cause.
And whereas the law gives liberty to hate our enemies; he charges us to love them,
and pray for them, and do good to them; again the law prohibits adultery;
Christ prohibits lusts, both in the eye and in the heart.
And whereas the law commanded to perform their oaths to the Lord;
Christ commands not to swear at all.
Now those who are not angry, it is not likely should kill;
those who love their enemies cannot hate or destroy them;
those who have not lusts in their hearts or eyes, cannot commit adultery;
and those who never swear, cannot forswear themselves:
all which he taught with divine power and authority from above.
He was not dry and formal like the scribes: so likewise his ministers,
and the preachers of his gospel, should wait on him,
to be endued with a measure of his divine spirit and holy grace,
that the hearers might be edified, and the Father, Son, and Spirit, might have the glory,
who over all is worthy forever.
