== Christ`'s Kingdom Exalted;

[.blurb]
=== Being a Short Essay in Order to Promote Truth and Righteousness in the Earth, and to Discourage Unholiness, Ungodliness, and Unbelief.

[.centered]
=== Preface.

[.salutation]
Christian reader,

In order to promote and exalt the kingdom of the dear Son of God,
according to the gift and measure of grace received,
I was concerned to write the following tract at sea.
Considering the evil tendency of the belief and principle which
has overspread a great part of the professors of Christianity,
that we cannot be free from sin in this life,
which is contrary to the doctrine of the holy Scriptures of both the Old and New Testament,
I could not be easy in my mind, without opposing such a dangerous tenet.
For if we believe that we must always sin, this being a sinful faith,
"`according to our faith, so it will be unto us;`" and if we die in our sins,
Christ has told us, where he is gone, we cannot come.
And holy record informs us, that no unclean thing can enter God`'s kingdom.

I have, also, for the satisfaction of the true Christian believer,
collected the following texts of holy Scripture,
which maintain the doctrine of holiness and perfection;
and directly oppose that evil principle, that we can never be free from sin in this life.

[.offset]
"`Walk before me, and be perfect.`"

[.offset]
"`You shall be holy, for I the Lord your God am holy.`"

[.offset]
"`And you shall be holy men unto me.`"

[.offset]
"`Noah was a just man, and perfect in his generation.`"

[.offset]
"`Without holiness, no man shall see the Lord.`"

[.offset]
"`We should be holy, and without blame before him, in love.`"

[.offset]
"`To present you holy, unblamable, unreprovable, in his sight.`"

[.offset]
"`If any man defile the temple of God, him shall God destroy,
for the temple of God is holy, which temple you are.`"

[.offset]
"`So be holy in all manner of conversation, because it is written, be holy,
for I am holy.`"

[.offset]
"`What manner of persons ought you to be in all holy conversation and godliness.`"

[.offset]
"`You shall be perfect with the Lord your God.`"

[.offset]
"`The Lord said, Job was perfect and upright.`"

[.offset]
"`Be therefore perfect;`" the words of Christ.

[.offset]
"`I in them, and you in me, that they may be made perfect in one.`"

[.offset]
"`Howbeit we speak wisdom among them who are perfect.`"

[.offset]
"`Finally, brethren, be perfect, be of one mind.`"

[.offset]
"`That we may present every man perfect in Christ Jesus:
that you may stand perfect and complete in all the will of God.`"

[.offset]
"`Now the God of peace, etc., make you perfect in every good work.`"

[.offset]
"`That you may be perfect and entire, lacking nothing.`"

[.offset]
"`Having therefore these promises, dearly beloved,
let us cleanse ourselves from all filthiness of flesh and spirit,
perfecting holiness in the fear of God.`"

[.offset]
"`Unto a perfect man, unto the measure of the stature of the fulness of Christ.`"

[.offset]
"`This we wish, even your perfection.`"

[.offset]
"`Let us go on to perfection.`"

[.offset]
"`Be not overcome of evil, but overcome evil with good.`"

[.offset]
"`You have overcome the wicked one;`" (this is twice repeated in one chapter).

[.offset]
"`You are of God, and have overcome.`"

[.offset]
"`Whatsoever is born of God, overcomes the world,`" etc.

[.offset]
"`To him that overcomes, will I give to eat of the tree of life.`"

[.offset]
"`He that overcomes, shall not be hurt of the second death.`"

[.offset]
"`To him that overcomes, will I give to eat of the hidden manna.`"

[.offset]
"`To him that overcomes, will I give power over the nations.`"

[.offset]
"`He that overcomes, the same shall be clothed in white raiment.`"

[.offset]
"`Him that overcomes, will I make a pillar in the temple of my God,
and he shall go no more out.`"

[.offset]
"`To him that overcomes, will I grant to sit with me in my throne.`"

[.offset]
"`He that overcomes, shall inherit all things.`"

Consider then, courteous reader, I pray you,
for what are all this language of the spirit, all these words of God,
and all these commands, exhortations, and glorious promises?
What is the end and tendency of them?

If the Almighty commands things that cannot be done, what will that make of him?
If his servants labour and exhort us to things not to be done,
where will those absurdities land?
Surely it must centre in the mouth of the unprofitable servant,
and such as charge God foolishly.
And are all those glorious promises made to put us on to fight against sin and Satan,
without a possibility of overcoming?
God forbid; and may he, Christian reader,
forbid also that you should believe such a gross and palpable error.

Oh! that the Almighty Lord may send forth more and more his holy light and truth,
and thereby lead and guide the inhabitants of the earth;
so that they may not give up the cause of Christ, but manfully resist, even to death,
that at last they may have a crown of life.

[.signed-section-signature]
Thomas Chalkley.

In the Christian world, it is too generally believed,
that on this side the grave people cannot be free from sin.
This principle, or belief, is a great hinderance to the glorious work of reformation,
and mightily obstructs people in their way to eternal glory.
It tends to uphold the kingdom of Satan, which every good Christian, with St. Paul,
should be for pulling down; and in order to do this,
should make use of the weapons which he did, that is, the armour of light,
the preparation of the gospel of peace, the girdle of truth, the helmet of salvation,
the breastplate of righteousness, the shield of faith, and the sword of the spirit,
which is the word of God.
This is indeed a holy war, to war against sin and Satan;
and the armour of light is also heavenly armour;
and this holy apostle was a valiant soldier, who was also victorious in this war.
Oh! who would not enlist themselves under Christ`'s banner,
and fight this fight of faith, with courage and true Christian valour.
Then would they witness the truth of that saying of the apostle,
"`That the weapons of this warfare are not carnal, but mighty, through God,
to the pulling down of the strong holds of sin and Satan.`"
Oh! down with those strong holds: let every lover of Jesus Christ,
pray that the kingdom of God and his Christ, may be exalted forever.
Sin is the chief support of Satan`'s kingdom,
which Christ came to destroy and put an end to,
and to bring in everlasting righteousness.
He came to save his people from their sins;
as his doctrine in his excellent sermon on the mount,
and his many other divine expressions, do plainly and abundantly manifest.

Now considering the great evil of this dangerous principle,
I have been deeply affected on account of poor mankind,
to whose utter ruin and eternal destruction it most certainly tends.
If we were to reason as rational beings,
with what spirit and courage should we undertake any business, or concern,
if beforehand we were grounded in a belief that we could not perform our undertaking?
Or what nation or people in the world,
would have any courage to oppose their common enemies,
if at the same time they did believe they should never overcome them?
Would not this abundantly dispirit and discourage them; let any rational soul judge!
This belief of sinning to the end of our days,
is a mighty engine of Satan to support his kingdom.
Pray, what signify all the preaching and writing in the world against sin,
though ever so elegantly or scholastically written
or delivered by the greatest orators or ministers,
if at the same time, this doctrine be upheld and maintained in pulpits, prints,
and otherwise, and received and believed by the people?
Let truth and right reason in this matter bear rule and be judge,
and the cause will be determined against sin and Satan:
but the "`Kingdom of Christ is an everlasting kingdom,
and of his dominion there shall never be an end.`"
This is a word of encouragement to the followers of Christ to be faithful to his commands.

Though the devil is king over all the children of pride and disobedience,
and prince of the power of the air;
yet "`the Lamb and his followers will have the victory`" over sin and him,
although sometimes it may fare with them as with their Lord,
who obtained it through sufferings; and let it be remembered by them,
that they shall in the end reign with him.
"`Fear not little flock, says Christ,
for it is your Father`'s good pleasure to give you the kingdom.`"
By which words, when received in faith,
the soul is inspired with courage and holy boldness, to resist the tempter;
though we may have the disadvantage of being but few, and Satan and his followers many,
who support his kingdom with this sinful principle and doctrine above mentioned.
One wily way which he uses to uphold his kingdom,
is to wrest and abuse the holy Scriptures, and strain them to his evil purposes,
as he served our Lord, the Captain of our salvation, as will be shown hereafter.
When he makes use of any of the words of God, it is for an evil end,
and that end must needs be wicked which is to keep people in sin,
or to create a belief that we cannot live without it in this world; which,
if he can obtain, and cause people to believe,
he knows he has a great advantage over them.
For how should dust and ashes overcome sin, who confess they are,
and believe they always shall be, sinners?
Therefore let us examine and see what use he makes of those Scriptures,
which he brings to support people in sin,
and by which he makes them believe they can never live without it;
some of which are as follows:

[.numbered-group]
====

[.numbered]
_First,_ beginning with that saying of our Lord Jesus Christ, to a young man who asked him,
"`What good thing he should do to inherit eternal life,`" calling him good master.
Our Saviour replies, "`Why do you call me good, there is none who is good, but one,
that is God.`"
The young man thought he was speaking to a mortal man;
and it seems to have been the will of Christ, by this remark,
both to caution his disciples against the use of vain compliments,
and to let them know that the young man had not true faith in him,
as he was the Son of God.
It is most certainly true, that in fulness and perfection, there is no man good,
compared with God; but comparing men with men, there are good men, women and children,
who fear God and do truly love Christ, and there have been a few such in all ages,
and will be some such, to the end of the world.
To construe Christ`'s words otherwise, would be to abuse the holy Scriptures,
which Satan makes a common practice of doing.

[.numbered]
_Second;_ Another is that expression of Solomon, "`There is no man that sins not.`"
The learned say this should be interpreted, and who may not sin.
But though it may truly be said of men, in one part of their lives or other,
or in the state of man in the fall, or degeneration, there is no man that sins not;
yet in the regeneration or new birth, the apostle John,
in the third chapter of his first epistle, and ninth verse, says,
that "`Whosoever is born of God, does not commit sin, for his seed remains in him:
and he cannot sin, because he is born of God.`"
It is this seed which would beget this new and living birth,
which makes us children of God, and heirs of the kingdom of heaven; and this,
Satan would destroy, for he knows he shall have an enemy of every such soul,
and therefore it is the devil`'s interest and endeavour to destroy every such birth,
and the belief that Christians can live without sin in the world.

[.numbered]
_Third;_ "`Who can say, I have made my heart clean, I am pure from sin.`"
David prayed to the Almighty in his psalms; "`Create in me a clean heart,
and renew a right, or pure spirit within me;`" which prayer was no doubt answered:
but this is the work of God, and to him all things are possible,
even that which looks impossible to men; for "`He can make a man more pure than gold.`"
So it being the work of God, no man can say, he has done it,
that he has purified himself, or made himself clean.
Can the Almighty make a man pure?
It might with much truth be answered, he can;
and it is supposed no good Christian will deny it:
and then what will become of that absurd, antichristian and antiscriptural tenet,
that we cannot be clean or pure from sin, in this world?

It may be said, if there are any who live without sin, they are but very few:
a sorrowful truth indeed!
But is it not every one`'s interest to strive to be one of those few,
as it is also his indispensable duty: our Lord also says, that the way to his kingdom,
is straight and narrow, and that there are but few that find it.
Must we therefore give up the cause, and not seek the kingdom,
and because of the difficulty of Christ`'s cross here in this world, go in the broad way,
where there is much room and company.
May every true Christian say, the Lord forbid it, and I humbly pray, not only say,
but do that which is right in the sight of God.

[.numbered]
_Fourth;_ The next is an expression of Solomon`'s,
"`There is not a just man upon earth that does good, and sins not.`"
This should be interpreted as the former, and who may not sin:
he speaks of a man in the state of vanity and sin, before a reformation;
for divine wisdom and the fear of the Lord, which he taught, keeps the heart clean,
and preserves from the snares of sin, death, and the devil:
so that this state of sin that he here speaks of,
must be before man attains to the wisdom of God,
and before he comes truly to live in his fear.
He must certainly do good, who lives in the fear of God,
"`Which,`" as the same Solomon says, "`is the beginning of wisdom;
and to depart from iniquity, is a good understanding.`"
So that he shows man his state of vanity and sin, and teaches people how to avoid it,
by fearing the Lord and walking in the counsel of wisdom, i. e., Christ`'s counsel,
who is the wisdom of God to salvation.
That all men are sinners before the work of conversion, is true,
and that the devil intends to keep them there to their lives end, is as true;
and no likelier way can he do it,
than by keeping them in a belief that they must live in sin,
and cannot live without it while they live in this world; and when they come to die,
then fear surprises the hypocrite, and terror takes hold of the ungodly: and many times,
when too late, they see the snares which the devil and sin have brought them into.

Oh! what pity it is, that this veil of darkness is not done away, in time of youth,
strength and health, when the bones are full of marrow, and the veins are full of blood:
but the design of Satan is to lead people on in this pernicious principle till death,
and then before they are aware, they may drop into eternal woe and misery,
where the wicked and the ungodly must be turned, with all them that forget God;
for in heaven, where Christ is, "`If we die in our sins, we cannot come.`"

[.numbered]
_Fifth;_ The apostle John writes thus, "`If we say we have no sin, we deceive ourselves,
and the truth is not in us.
If we confess our sins, he is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness.
If we say we have not sinned, we make him a liar,
and his word is not in us;`" which answers to the eighth verse,
"`If we say we have no sin, we deceive ourselves.`"
The ninth verse fully lets us into the meaning of the eighth verse, i. e.,
if we confess our sins, for all ought to confess, and also`' to forsake their sins,
all having sinned, and being by nature children of wrath;
otherwise we have no assurance of mercy from the holy Scriptures:
then the Almighty "`is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness.`"
And pray what sin is there, when we are cleansed from all unrighteousness?
And then in the tenth verse, he says, "`If we say we have not sinned,
we make him a liar.`"
There is no doubt that we have sinned,
which is what the apostle plainly points at in the eighth verse.
And if any man sin, "`We have an advocate with the Father, even Jesus Christ,
the righteous: and God is faithful and just to forgive us our sins.`"
But then we must repent and forsake, if we expect to find mercy; though we have sin,
or have had sin, we must not always have it, for if we have it always, woe will be to us,
according to the words of God and Christ.
"`Let no man,`" nor the devil either, "`deceive you: he that does righteousness,
is righteous: he that commits sin, is of the devil.`"
This is plain and naked truth, let who will like, or dislike it.
Further, in the ninth and tenth verses, he again repeats to the same purpose, saying,
"`In this the children of God are manifest, and the children of the devil:
whosoever does not righteousness, is not of God.`"
Ergo, then he must be of the devil, while he is in unrighteousness.

====

There are various other places in the holy Scriptures, which he abuses in like manner,
and which he and his children wrest to uphold him and his kingdom of sin and unrighteousness,
and themselves therein.
By the grace of God, we may see his wiles and delusions, and the rottenness of his cause,
as also the unsafe and dangerous foundation of his building,
though endeavouring to support the same,
by that which was always designed to destroy him and his kingdom, i. e.,
the holy Scriptures.

May all men judge in this matter, whether that is a right spirit,
which would pick and cull out a few verses, and sometimes a few words out of a verse,
in order to make them speak contrary to the whole scope and tenor,
or tendency of the holy Scriptures,
and to plant a belief that we shall never overcome sin and unrighteousness in this world,
though the holy Scriptures all along exhort, and teach us,
to avoid sin and unrighteousness, and live a holy righteous life in this present world.
I say, may all judge whether such a spirit can be of God, or whether it be not of,
and from the father of lies.
If it be plainly proved, that there have been those who have overcome sin and Satan,
and that Christ and his holy apostles,
repeatedly exhorted to fight against sin and the devil, who is the author of all sin;
and Christ faithfully promises most sweet and gracious rewards to those who shall overcome,
in order to encourage the spiritual warrior to a faithful perseverance,
and resisting of sin and Satan, then it is hoped that Satan will be wounded,
his kingdom shaken, and this evil and destructive principle, in some measure laid waste,
in some poor souls, into whose hands these may come.

[.numbered-group]
====

[.numbered]
_First;_ Beginning with the great apostle of the gentiles,
a notable soldier in the Lamb`'s spiritual war, "`I have,`" says he,
"`fought a good fight, I have finished my course, I have kept the faith.
Henceforth there is laid up for me a crown of righteousness, which the Lord,
the righteous Judge, will give me at that day: and not to me only,
but unto all those that love his appearing.`"
And if this be not encouragement, what is?
He also says, "`Be followers of me, even as I also am of Christ.`"
Here is example, exhortation and encouragement, with experience.

[.numbered]
_Second;_ Another of the apostles, John, in his first epistle,
is positive that those young men he writes to, had already overcome the wicked one.
"`I write unto you,`" says he, "`young men, because you have overcome the wicked one.`"
And in the fourteenth verse he repeats it again,
as though he would doubly and deeply imprint it in their minds,
"`I have written unto you young men, because you are strong,
and the word of God abides in you, and you have overcome the wicked one.`"
Here were young men, who were truly valiant and noble, to wage war with the wicked one.
If it was possible for them, why is it not possible for us also?
Oh! that our young men of this generation, would take those young men for their examples,
to make war with the wicked one, and truly endeavour to pull down his kingdom.
It is worth our notice, that those young men had the word of God abiding in them;
by the sword of the Spirit they overcame, by it they were cleansed,
by taking heed to walk according to its directions, as it is written,
"`How can a young man cleanse his ways?
By taking heed according to your word.`"
The great reason why young men are overcome, instead of overcoming,
is their heedlessness to, and of the word;
for notwithstanding their bones be full of marrow, and their veins full of blood,
and nature strong, having many temptations to sin and evil; yet,
by taking heed to the word, they might be reformed:
and through the immediate power and strength thereof, may overcome the wicked one.
Here were young men who actually overcame sin and Satan,
to whom this holy servant of Jesus wrote, by way of encouragement.
Is the arm of the Lord shortened?
Surely no.
It is true mortals are short in their duty, but not the Almighty in his holy power,
nor his dear Son, in his unparalleled love, and most pure doctrine;
whose doctrine shall be set down, as the Spirit indited it to the seven churches in Asia.

====

[.numbered-group]
====

[.numbered]
_First;_ To the church of Ephesus.
"`He that has an ear to hear, let him hear what the Spirit says to the churches:
To him that overcomes, will I give to eat of the tree of life,
which is in the midst of the paradise of God.`"
Here is an excellent promise and blessed encouragement to such as believe,
and are faithful, and are desirous to fight in the Lamb`'s war against sin and Satan.
The same apostle gives a description of this tree of life,
"`That it bears twelve manner of fruits, and bears its fruits every month,
and its leaves are for the healing of the nations;`" which mystically points at Christ,
who is faithful in his precious promises and doctrine, and has virtue in him,
which through faith, will heal the nations of the wounds which sin has given them.
Those who continually eat of the tree of life, shall live forever;
but a flaming sword will turn every way, to keep the unbelieving sinner from it:
none in a state of sin and disobedience can come to enjoy the paradise of God.
The above is an excellent promise to all those who overcome sin and the devil,
who is the author of it.

[.numbered]
_Secondly;_ To the church of Smyrna: "`He that has an ear to hear,
let him hear what the Spirit says to the churches:
He that overcomes shall not be hurt of the second death:`"
which is that eternal death which is in hell,
or that lake of fire which burns forever, where the worm never dies,
and the fire never goes out.
This holy warfare is certainly a fighting for life, against eternal death and hell;
which is of much greater consequence than natural life and death.
Oh! fight for your lives against sin and Satan, against pride and vanity,
and all manner of wickedness; put on the whole armour of light; look unto God,
through Christ the victorious Lamb, that you may be saved from the lake of fire,
and not be hurt of the second death.
Oh! may we know a dying daily to sin, to the world, the flesh and the devil,
that we may live unto God, through faith in his dear Son Jesus Christ.

[.numbered]
_Thirdly;_ To the church of Pergamos: "`He that has an ear to hear,
let him hear what the Spirit says to the churches: To him that overcomes,
will I give to eat of the hidden manna; and I will give a white stone,
and in the stone a new name written, which no man knows, saving he that receives it.`"
Here are four excellent promises to him that overcomes;
the Lord opens his treasury of life and of wisdom,
in order to invite souls to the mighty battle of the Lamb,
who is not like the princes of this world,
who sometimes promise great things to their soldiers or followers, and do not perform;
but God`'s promises are all yes and amen forever.

====

[.numbered-group]
====

[.numbered]
The _first_ promise is,
"`To eat of the hidden manna:`" the children of Israel did eat manna, outwardly,
as it is written, in the wilderness, and are dead;
but those who eat of this hidden manna, this angel`'s food,
who are hid with Christ in God, these shall never die, i. e., spiritually,
for his hidden manna is the flesh and blood of the Son of God, who said,
"`Except you eat my flesh, and drink my blood, you have no life in you.`"

[.numbered]
The _second_ promise is, "`To have a white stone;`" this stone is Christ,
who is the chief corner stone of God`'s building or church, the New Jerusalem,
which the wise letter-learned master-builders set at naught;
but he is the head of the saint`'s building or corner, and a holy precious stone,
the elect or chosen of God, the gift of God, to all those who truly believe,
and overcome sin, as he did; and as it is written, "`If he give us his Son,
shall he not with him freely give us all things?`"
This stone will certainly do miracles for them that have it,
through the virtue of its power, it will procure joy in tribulation,
patience in afflictions, health in sickness, riches in poverty, strength in weakness,
liberty in bonds, and to sum up all, which indeed is a great sum, life in death.

[.numbered]
_Third_ promise,
"`And in the stone a new name:`" how many gay sparks
and beaus would do abundance to gain honour,
or a name among men?
Nothing is dear to them in this world, neither their estates,
nor the nearest relation they have in the world, so that they may gain a name here below;
no, not even their own lives.
But, Oh! did mortals know the virtue of this new name, and were they in love with it,
then the world and all its fading beauty and vanity,
would be nothing to them in comparison of it,
which is better than the names of sons of worldly glory, and daughters of honour;
for those outward names are fading.
Today a king, a prince, a duke, an earl, a lord, a knight, and as has been,
and may be again, tomorrow on the scaffold: but this name which the King of kings,
gives those who overcome sin and Satan, is a name which will outlast time,
and endure to eternity.

[.numbered]
_Fourth_ promise is, that it should be secret, only to the world,
but surely known to him that has it.
Great men, when their acts and titles of honour are blazoned abroad in the world,
have many enemies who envy them;
and yet some are so vain as to love grandeur and popularity notwithstanding;
but he that has a name which Christ gives, so long as he is sensible of it in himself,
is therewith satisfied.

====

Now as this is the portion, and more which is hereafter mentioned,
of those who overcome the wicked one, then, on the contrary,
what will become of those who live and delight in sin, and are daily overcome with it?
For the holy Scriptures are positive "`That the wicked, with all those that forget God,
shall be turned into hell.`"
This is the determinate will of God; and that we may take the more notice of it,
to observe and do his will,
he has caused it to be written down in the language of the holy Spirit,
in the holy Scriptures of truth, which are of no private interpretation,
but naked and open to mean capacities.
The holy Scriptures are not to be interpreted to the private
interest of any particular person or set of persons only;
but are a general benefit unto all the faithful believers and followers of Christ,
through the whole world.

[.numbered-group]
====

[.numbered]
_Fourthly;_ To the church at Thyatira: "`And he that overcomes,
and keeps my works unto the end, to him will I give power over the nations,
and I will give him the morning star.
He that has an ear to hear, let him hear what the Spirit says unto the churches.`"
The Spirit still continues promising his gracious privileges upon condition of overcoming:
therefore, if it had been impossible to have overcome sin and Satan,
then all these promises would have been in vain, and the holy Scriptures deceiving,
which would be to make Christ and the apostles deceivers: but Christ, his apostles,
and the holy Scriptures, are true, and every one who contradicts God, is a liar.

Let it be observed, that there must be a keeping the works of God to the end;
for many have run well for a time, and overcome many sins,
through the help and goodness of God, and yet afterwards have run into sin again,
whereby they have grieved the good spirit of God,
by which they should have been sealed to the day of redemption,
and so the Lord has taken his good spirit and gift of light and grace from them,
and left them to themselves, and their own hearts`' lusts.
But such as hold out in well doing to the end, the same shall be saved,
and "`Those shall have power over the nations:`" the laws of men,
or powers of earth or hell, cannot hurt them;
but they will be as kings and priests unto God, ruling over their own spirits;
and such a one is greater than one that rules a city, and cannot govern himself.
Another excellent gift is promised here to the victorious Christian warrior:
"`I will give him the morning star:`" it is indeed a very comfortable gift,
to behold the morning star, after a long, tedious, stormy night,
earnestly waiting for the morning.
This morning star the writer of these lines has witnessed,
both as to his natural and spiritual travels;
but especially in his inward condition as a Christian.
Those that have a true sight and sense of this divine star, are made to rejoice;
for then they do infallibly know, that the day of the Most High is at hand,
and that his kingdom draws near unto them.
Amen, holy Lord Jesus!

As the day star is the forerunner of the natural day, so,
is the heavenly morning star a forerunner of the day of the Most High to the soul.

[.numbered]
_Fifthly;_ To the church of Sardis: "`He that overcomes shall be clothed in white raiment,
and I will not blot his name out of the book of life;
but I will confess him before my Father, and before his angels.
He that has an ear to hear, let him hear what the Spirit says unto the churches.`"
These promises of God, through his spirit,
and through his servant to the church of Sardis, are,
that those who overcome shall be clothed in white raiment;
and he says in the fourth verse of the same chapter, that that church had a few in her,
who had not defiled their garments, who should walk with him in white, for, says he,
they are worthy.
So that there were a few undefiled ones, who had overcome;
although others were blameable, whom the spirit reproved sharply.
But those who overcame were to be clothed in white raiment;
which raiment is that clean linen called the righteousness of the saints, or elsewhere,
the wedding garment, and the garment unspotted of the world, without having which,
we may expect to be asked,
how we dare presume to approach the holy presence of a just and righteous God,
who is of purer eyes than to behold iniquity with allowance or approbation,
as it is written, "`Friend, how did you come in here without a wedding garment?`"
And by the promise to the church, that those who overcome,
"`shall not be blotted out of the book of life,`" it plainly
appears that the names of those who fight the Lamb`'s battle,
and overcome sin and Satan, are upon record in heaven, in the Lamb`'s book of life;
and that though we may have done well or valiantly in some things,
yet if we allow ourselves to be overcome of sin,
there is danger that we may have our names blotted out of the book of life.

The third promise is very excellent and glorious:
"`But I will confess him before my Father, and before his angels.`"
Oh! wonderful honour! to have Christ confess that we are his and belong to him,
and have been men of courage in this holy war, and overcome the enemy,
and been victorious in this fight of faith; to confess us before God and his angels,
must needs be unspeakable honour done to us before the armies in heaven.
He expressed again his often repeated advice to those who have ears, saying,
"`He that has an ear,
let him hear what the Spirit says to the churches;`" which is much lacking among men,
and also a believing heart.
Is not God, Christ and the Holy Spirit, stronger than the world, the flesh and the devil?
But is not this belief of its being impossible to overcome sin, and saying,
that we cannot do it while we are in this world; as much as to believe and say,
that Satan and nature are stronger than grace.

[.numbered]
_Sixthly:_ To the church at Philadelphia, the Spirit says:
"`Him that overcomes will I make a pillar in the temple of my God,
and he shall go no more out: and I will write upon him the name of my God,
and the name of the city of my God, etc.
He that has an ear to hear, let him hear what the Spirit says unto the churches.`"
Here is promise upon promise,
all to persuade and invite people to fight the fight of faith,
believing they shall obtain the victory, and to destroy the principle of unbelief.
The overcomer, through grace, is to be made a pillar in the temple of God; that is,
one of his church, who helps to support the credit of it,
through a true Christian reputation in his conduct.
Such a one is a pillar in the church militant here on earth, and will,
if he is faithful to the end, be of the church triumphant in heaven also;
and he will not go out any more, but will abide in, and with Christ forever.
Here are gospel promises and privileges, happy are they who through faith attain thereto;
how much have Christians need to be concerned before God,
for the excellent gift of faith, since, "`Without faith it is impossible to please God.`"
Our Saviour says, "`If you had faith as a grain of mustard seed,
you might say to this mountain, be removed, and cast into the sea, and it should be so.`"
Now though sin indeed has grown a very great mountain, in this generation,
yet through true faith it is removed, according to the doctrine of Christ,
blessed be his holy name.
Upon those overcomers, the Lord has also promised, to "`Write the name of God,
and the name of the city of God, which is New Jerusalem,
which comes down from heaven,`" which is the mother of all saints.

Here is a train of glorious expressions and promises,
enough to inspire the tender soul with strong desires after God and Christ,
and his kingdom.
My heart is deeply affected at this time,
in the sense of the love of our heavenly Father;
and my spirit is greatly concerned for the welfare of the children of men,
my fellow mortals.
Oh! that they might believe, and that believing they might have life,
through the name of Christ.
It is observable, that to overcome,
is the condition of obtaining all these great and glorious promises;
and overcoming is repeated seven times; once to every church.
And after all those glorious and fair promises,
is not the consequence of saying or believing that sin and Satan cannot be overcome,
to make Christ a deceiver?
which is absurd and antichristian doctrine.

[.numbered]
_Seventhly;_ To the church of Laodicea:
"`To him that overcomes will I grant to sit with me in my throne,
even as I also overcame and am set down with my Father in his throne.
He that has an ear to hear, let him hear what the Spirit says unto the churches.`"
What greater promise could Christ make to his church than this,
to take her into his throne, and into his Father`'s kingdom, into his bosom of love?
This is wonderful indeed.
But then, Oh, Christian! the condition is to overcome, as Christ overcame.

====

Now since it may be beneficial to Christians to understand, and to consider duly,
this great fight or battle, and how this great conqueror overcame;
because we are to follow him, and to take him for our example,
let us have a description of it, it being the greatest encounter or battle,
that ever was in the world, between the Prince of life,
and the king of the bottomless pit.
The history of which, is worth the reading of the greatest prince or monarch on earth,
since they must leave this low world,
and lay down all their crowns when death calls them.
To fight this battle, and to follow this monarch,
who has all divine power in heaven and earth, and to take his direction,
is every man`'s duty and interest, both noble and ignoble.
The holy evangelists, Matthew and Luke, give us an account of this great fight,
in the fourth chapter of Matthew, and fourth chapter of Luke,
and agree in the most weighty matters, though they did not exactly word it alike,
yet the substance is the same, and the temptation, conflict, or battle, all one.
First, Satan bids Christ, as Matthew and Luke have it, "`Command the stones,
or stone to become bread.`"
Secondly, "`To cast himself down from the pinnacle of the temple.`"
Thirdly, "`To worship the devil, or fall down to him,`"

"`Then was Jesus led up of the spirit into the wilderness, to be tempted of the devil.`"
And when he had fasted forty days and forty nights, he was afterwards hungry.
And when the tempter came to him, he said, "`If you be the Son of God,
command that these stones be made bread.`"
But he, i. e., Christ, answered and said, it is written, man shall, or does,
not live by bread alone, but by every word that proceeds out of the mouth of God.
Then the devil takes him up into the holy city, and sets him on a pinnacle of the temple,
and says unto him, "`If you be the Son of God, cast yourself down: for it is written,
he shall give his angels charge concerning you;
and in their hands they shall bear you up,
lest at any time you dash your foot against a stone.`"
Jesus said unto him, it is written again, "`You shall not tempt the Lord your God.`"
"`Again, the devil takes him up into an exceeding high mountain,
and shows him all the kingdoms of the world, and the glory of them; and says unto him.
All these things will I give you, if you will fall down and worship me.
Then says Jesus unto him, Get behind me Satan; for it is written,
You shall worship the Lord your God, and him only you shall serve.
Then the devil leaves him, and behold, angels came and ministered unto him.`"

Behold how the Saviour of the world overcame the devil and his temptations.
As he did, so ought all Christians to resist the tempter, as it is written,
"`Resist the devil, and he will flee from you.`"
Here we may see he is a conquered enemy; and we are told,
"`By Christ`'s spirit we must overcome, as he also overcame.`"
After our Lord had fasted forty days and forty nights, he was hungry,
at which time the devil urged him, if he was the Son of God,
to make the stone or stones bread.
After the same manner he tempts us poor mortals,
by laying his snares and bating his hooks,
according to the nature and propensity of the person he is engaged with.
If a man, woman, or child, be addicted to passion, pride, swearing, lying, drunkenness,
taking the sacred name in vain, idle or vain discourses to steal away our precious time;
let the sin be what it will, which we are most naturally addicted to,
there will he lay his temptations, for he preys upon our weakness,
and plies the weakest part in us most.
For this reason we have need to keep a strict watch; as Christ advised,
"`Watch and pray continually, lest you enter into temptation.`"
It is no sin to be tempted, but the sin is to entertain, and enter into the temptation;
if we overcome, as Christ did, it is an honour to be tempted,
and a secret joy springs in the soul, in a sense of its victory,
in sore conflicts between the enemy and the soul;
the Lord manifesting his divine grace for our assistance and help.
Here we can take the advice of the apostle, when he says,
"`Count it all joy when you fall into various trials,`" and overcome them as Christ did,
by resistance.

If it be objected, though Christ overcame, yet I am a poor sinful creature,
and have no power; but he had and has all power, both in heaven and earth,
committed into his hands, so that he might well overcome.
It is well if you see you have no power, and if you also see that Christ has all power;
then since we have no power of ourselves, we must by prayer and humble supplication,
apply to him for it in the time of need;
believing that he who has made so many encouraging promises as are before recited,
has also grace, and will give grace and glory, and power,
to those who will diligently seek him;
else why did he make so many excellent promises to the spiritual warriors?
It is worthy the notice of all, that Satan is a conquered and limited adversary.

It is a sweet portion of gospel tidings, and good news,
that the devil cannot force anyone, whether he will or not, into sin; for if he could,
no flesh could be saved.
If a man, woman, or child, is tempted by Satan to tell a lie,
he cannot force them to it against their will;
so that there must be a cowardly giving way and falling from the Lamb`'s standard,
or ensign, and going over to Satan, if man is overcome of sin and wickedness.
For if we stand stiffly against him, although we may be weak of ourselves,
our great Master, who sees us in secret, if we cry to him for help,
will come to our assistance, even he whom Satan could never conquer.
Therefore it is safe for all professing the name of Jesus Christ, to keep near to him,
through faith in his name and power, which ever was and will be,
a strong tower to those who fly thereto.
Christ did not do as the devil tempted, or persuaded him to do;
but he withstood the temptation, with this reply, "`It is written,
that man lives not by bread alone,
but by every word that proceeds out of the mouth
of God:`" for there is life in every word of God.
Thus our Lord overcame him; for Satan cannot resist, so as to make void,
or lay waste the words of God in the holy Scriptures of truth,
when they are brought into our minds by his spirit,
to uphold and promote the kingdom of God and Christ,
and to destroy the kingdom of sin and Satan; though he, i. e., the devil,
makes use of those Sacred Writings, often wresting them,
and bringing them for evil uses and wrong purposes, as most certainly he does,
when he alleges from them, that people cannot live otherwise than in sin.

"`Then, as Matthew has it, he took our Lord to the pinnacle of the temple,
and bid him cast himself down; for, says Satan, it is written,
he shall give his angels charge concerning you,
lest at any time you dash your foot against a stone.`"
Though he was once overcome, yet he has boldness to tempt again:
as Christ overcame him by his power, making use of the holy Scriptures,
he now tries what he can do with the Scriptures; he tempts Christ with them,
that he might tempt his Father; and so he tempts poor mortals by the Scriptures,
to keep them in sin, by making a wrong use of them, and misapplying them;
and if he can hold them in sin,
he knows it is a ready way to cause the Almighty to be angry with them;
and if they hold out in it to the end, to turn them at last into hell,
where the wicked must be turned.
He begins his temptations with an "`If you be the Son of
God,`" though he knew very well that he was the Son of God;
yet like some of his evil seed, or seed of evil doers, he tempted him to show a sign;
but our Lord did not gratify either him or them, but rebuked them both,
as they well deserved; and so by denial and resistance he overcame;
and we also must in the same way.

After this our Lord makes a right use of the Scriptures, saying, "`It is written again,
you shall not tempt the Lord your God.`"
And truly, those who read the holy Scriptures, and know how much they speak against sin,
and for righteousness, and who notwithstanding, live in sin and ungodliness,
and plead for it, even from these Sacred Writings,
which were written on purpose to destroy sin, should seriously consider,
whether they are not guilty of tempting God,
which Christ says it is written you shall not do.
Oh! that people would turn away from sin and Satan,
and break off from their sins by repentance, and their iniquities by amendment of life,
which is the way to have the days of their tranquillity lengthened out in this world,
and to be happy in that which is without end; for it is written,
"`The wicked do not live out half their days;`" which, according to my observation,
is a true general rule.
How many have been taken off in their prime and strength,
and in the flower of their years, who might, according to the course of nature,
have lived many years, had they been sober and temperate, and lived in the fear of God?
If it be asked, do not pious young people die also?
Yes; but not so frequently as intemperate ones;
I have had occasion to observe it in various parts of the world; and besides,
if pious young people leave this world, their change is glorious:
whereas the wicked and ungodly make a sad and bitter exchange.

Since life is so uncertain, and death so sure and certain to all,
what care and fear ought there to be on all, of offending so merciful a God,
and so sweet a Saviour; who overcame, to show us the way to overcome also;
and died for sin, that we might die to the world and the sinful part of it,
and live to him, exhorting us to overcome, as he also did,
and then promises to take us for his companions, with himself and his Father,
in his heavenly kingdom.

Satan repeats his temptation a third time; for he is an unwearied enemy,
and will tempt poor mortals over and over, many times;
but he is to be resisted as often as he tempts,
if we will follow the counsel and example of Christ:
"`He takes him up into an exceeding high mountain,
and shows him all the kingdoms of the world, and the glory of it.`"
A temptation which takes with abundance of souls: the glory, riches,
and greatness of this world, ruin many; they having it,
and being swelled with pride therein.
Some are destroying themselves to get it, and cannot attain it;
and many would endeavour to create a belief that they are greater, richer,
and more noble than they really are; which is a temptation of the evil one;
for we ought to think meanly of ourselves; and if we will follow Christ`'s example,
make ourselves of no reputation.
When Satan would tempt us to be proud, or high of mind, we should resist, as Christ did,
who said to the devil, "`Get behind me, Satan, for it is written,
you shall worship the Lord your God, and him only shall you serve.`"
If this holy rule was followed, as Christ instituted it,
then we should overcome sin and Satan: Christ`'s institution is, that "`The hour comes,
and now is, that those that worship the Father,
must worship him in spirit and in truth.`"
The duty of every Christian is to worship the Lord God of heaven and earth,
and he only we should serve and worship; and that not in a formal way,
but with hearts truly devoted to his will.
We are to worship the Father in spirit and in truth, into which the devil can never come;
though he may get into the form of it, he cannot overcome us,
where the power of Christ is lived in; for by the power of God, which dwells in Christ,
who overcame by the same power, Christians shall overcome.
The devil was forced to fly when Christ resisted him,
and so he will be when Christians resist him in Christ: and when Christ had overcome,
then the angels came and ministered unto him;
likewise the guardian angel of God`'s presence,
will administer sweet comfort and pleasure to every soul,
who stands truly for the cause of God and Christ against sin and Satan,
sincerely endeavouring to pull down Satan`'s kingdom, and sin which upholds it,
and faithfully desire to exalt the kingdom of God and his dear Son.

He or she that believes and overcomes, for without belief, it is impossible to overcome,
is truly entitled to all the above precious promises and privileges.
But the wrath of God will be revealed from heaven
against all ungodliness and unrighteousness of men,
and against all those who hold the truth in self-righteousness, or unrighteousness.
Again, "`Tribulation and anguish upon every soul of man that does evil, of the Jew first,
and also of the Gentile; but glory, honour and peace, to every man that works good,
to the Jew first, and also to the Gentile; for there is no respect of persons with God.`"
The ways of God are equal, but the ways of man and Satan are unequal; sin,
iniquity and transgression, are of the devil, and of man in the fall; but righteousness,
holiness and truth, are of God, to which man is restored,
through regeneration and reformation.
Glory over all be given to God and the Lamb, forever.
Amen.

[.asterism]
'''
