== A Letter to Cotton Mather, in New England.^
footnote:[Having received a courteous letter from Cotton Mather,
one of the greatest preachers among the people of New England;
he being in community with the national church there,
and having preached a sermon concerning the power and excellence of Christ within,
recommending the people thereunto, and commending our Society therein;
but differing from us in some particulars, which particulars I was concerned to answer.]

Frankford, 20th of Third month, 1726.

Courteous friend, C. M.,

Yours, dated November 30th, 1725, I received a few days ago,
having been visiting the people along the seashore in the Jerseys, in the love of Christ,
hoping to bring some to him, among whom, in a general way,
the gospel which I had to preach in his name, found acceptance,
for which I was truly thankful.
And though I had no earthly consideration for so doing, yet I had an inward satisfaction,
that I thought I would not exchange or part with,
for the bishop of Rome or Canterbury`'s revenue:
and at my return I received your friendly letter, of which I was glad,
and that mine to you found that acceptance, so as to answer my request.

And whereas you say your aim and hope have been to persuade us who call ourselves Friends,
we professing ourselves friends to all people,
that our superior stress should be upon the grand point of Christ inward;
we having found, by living and blessed experience,
the great benefit and comfort of his sweet and glorious presence,
by the manifestation of his power, spirit and grace, in and to our souls,
we cannot do otherwise than lay the greatest stress thereon, our benefit thereby,
being not easily expressed, so as to be understood by the carnal mind,
or those who are in a state of degeneration.
Christ within was, is, and ever will be the hope of the sanctified soul`'s glory,
though a mystery hid from ages of the unregenerate people,
or from those who are in the reprobation; "`Do you not know your own selves,
that Jesus Christ is in you?--unless indeed you are
disqualified;`" as says the apostle Paul.

From the above I would not be understood as though
I believed Christ is no where but in the people;
neither did I ever understand any of our Friends so,
though we have been often misrepresented on that head.

And as to the ceremony of the hat, and the plural language to single persons,
I thus answer you, that many of us left that way of salutation and speaking,
through strong conviction, accompanied with these reasons:

First; It being a respect we pay to Almighty God, he being our head,
is honoured by uncovering our heads, as says the apostle Paul; we think, for that reason,
it is not right to uncover our heads to men, but that to give one another our hands,
in an inward and hearty respect, is better.

Second; We read in the holy Scriptures,
that Mordecai could not bow to Haman for conscience sake,
and I think it may be safely concluded, that he did not take off his hat,
or uncover his head, though he was in danger of suffering for it.
And,
Third; The three children of God walked in the presence of the great king of Babylon,
and those present with him, with their hats on;
and they stood the king`'s fury and the fire, though seven times hotter than usual,
with their hats on.

I beseech you, my good friend, to consider the tenor of the holy Scriptures maturely,
and then I hope you will not think the hat,
and the language of you and thou to a single person,
to be needless ceremonies and encumbrances, according to our principle and practice.
I do not write thus to you for contention, nor in a contentious spirit,
but in the innocent love of our dear Lord Jesus, and for edification; or, if need be,
for information.

Also, as to thee and thou to a single person, I answer, that the holy Scriptures,
or the words of God therein recorded, are by Protestant professors of Christ,
acknowledged a rule to us all, next to the holy Spirit, from where they came,
or the Holy Spirit, who our Saviour promised, "`shall lead into all truth,
and abide with the true believers anyone;`" and that God and Christ`'s spirit,
does not contradict the holy Scriptures, which have proceeded from there:
this general proposition we all agree to, if we rightly understand one another.
Then, according to this rule, our plain language is right,
otherwise I should be obliged to you to show us wherein we err from that good rule.
Now, the Most High thought good to teach and use that
language in the beginning to our first parents,
so that is our mother tongue, and is the language of the Bible, or holy Scriptures,
from Genesis to the Revelation 1 suppose I need not tell you,
that you to a single person, had its rise from pride and flattery; and you yourself know,
that you to a single person is neither good English, nor good grammar.
And if I am rightly informed, your forefathers, as well as ours,
made use of this plain Scripture language of thee and thou to a single person,
in their first separation from the common sinners of their times.

Though I thus apologize for the plain Scripture language,
yet in respect of faith or grace, and principles to be believed,
which are absolutely necessary to salvation, I call these but small things,
but we are not to despise the day of small things.
If we are faithful in the little, we have the promise of more, or greater things.

I pray you excuse this long letter;
for it seems fitting that we should render a reason for our disuse of
those things used by some of most societies professing the Christian faith.

In respect of water baptism, and the bread and wine.
First; As to water baptism, I have this to answer,
the which I hope you will charitably construe.

The first account that we have of it, is from John the Baptist, who first practised it,
according to the account the evangelists give concerning it, and he said,
"`I indeed baptize you with water, but he,`" Christ,
"`shall baptize you with the Holy Spirit and with
fire;`" plainly distinguishing between the two baptisms,
and the two natures of them; adding, "`He must increase,
but I must decrease;`" he spoke not of their persons; but of their dispensations.

William Dell, a learned man in his day,
wrote an excellent piece on the subject of baptism, which be pleased to peruse:
it is very evangelical, and well worth reading.
I shall take care to procure you one of his books.
I am the more concerned about this subject,
because you are positive about our coming to it, if we improve in wisdom:
but I would hope to be, in some measure, instrumental to convince you,
that there is no absolute need, in order to salvation,
to go into or unto the water or element;
but that it is absolutely necessary for us to go unto and into Christ,
that being the way to be new creatures, as it is written,
"`He that is in Christ is a new creature.`"

Our dear Lord says on this subject, "`John truly baptized with water,
but you shall be baptized with the Holy Spirit.`"
Here our Saviour, as well as John, distinguished between the two dispensations.
John`'s was indeed a glorious dispensation in its time;
but Christ`'s far exceeds it in glory, and is to endure anyone.

The apostle Peter remembered this doctrine of Christ`'s,
when the holy Spirit`'s baptism was come; "`Then,`" says he,
"`I remembered the word of the Lord, John baptized with water,
but you shall be baptized with the Holy Spirit.`"
Paul, the great apostle of the Gentiles, says, "`He was not sent to baptize,
but to preach the gospel;`" which, when truly preached,
has a spiritual baptizing power attending it;
and if we come rightly to be baptized with the holy Spirit and fire of the divine word,
we shall witness a renovation,
and the work of reformation and regeneration will go forward more and more,
both without and within, in body and spirit,
for which every true Christian and minister of Christ,
longs and prays with fervent desires.
The apostle says, and pray be pleased to judge for what reason, "`That the kingdom,
of heaven is not food nor drink, but righteousness, peace and joy in the Holy Spirit.`"
Oh! may the Most High inspire your soul when you read these lines, is my tender desire.

I know I am writing to one who in many things is far before me; so that I write in fear,
mixed with Christian love; and if it meet with the same love in you,
that will cover a multitude of faults.

As to the supper or ceremony of bread and wine, which is called the sacrament,
which word we find not in the Bible,
we do not understand that our Lord laid it as an injunction
on his followers to observe this practice to perpetuity;
or that the observation thereof is absolutely necessary to salvation,
or that his church should be in the practice of the elements of either water to dip in,
or sprinkle with, or bread and wine to eat and drink,
as a lasting ordinance to be observed by believers.

Christ said, "`This do, as often as you drink it,
in remembrance of me;`" which to me seems to leave it indifferent:
also from the debates and contentions of Christians about it,
and the blood that has been spilt in this controversy,
and the many doubts arising concerning it,
I think it is evident that Christ was not positive that
his followers should be found to perpetuity therein;
and where he says, "`Take, eat, this is my body which is broken for you, or for many;
and drink,
this is my blood which is shed for many;`" I believe it is not to be doubted
but that he pointed at his flesh and blood rather than the bread and wine,
as in a figure, and that also he had an eye to his spiritual flesh and blood or body,
as where he says, "`Except you eat my flesh, and drink my blood,
you have no life in you;`" the which every true Christian should daily feed upon,
and without which we have no divine life in us; and as himself also said,
"`My flesh is food indeed, and my blood is drink indeed.`"

It is worthy of note, that much of his holy words and heavenly doctrine,
was to be understood spiritually; "`My words,`" says he, "`are spirit and life.`"
A glorious speech to such as truly witness and understand it,
which is much better felt by a true believing Christian than expressed.
Oh! may we so open our hearts to our beloved Jesus, that he may come in unto us,
and that we may sup with him and he with us, and that he may not only sup with us,
but take up his abode with us, and we with him, anyone; and not only in us twain,
but in all those who truly love, believe in, and follow him, throughout the world;
so wishes and prays, in sincerity, your real friend,

Thomas Chalkley.

P+++.+++ S. I hope you will excuse this long letter,
your "`Vital Christianity`" being instrumental towards
our corresponding together by way of epistle,
at which, if it proves any way to your satisfaction, I shall rejoice.
In reading several of your latter tracts, I have had love in my heart towards you,
which was yet more renewed in perusing your "`Vital
Christianity,`" and your friendly letter to me.

[.asterism]
'''
