[short="Free Thoughts Communicated to Freethinkers"]
== Free Thoughts Communicated to Freethinkers, in Order to Promote Thinking on the Name and Works of God; With a Relation of a Remarkable Providence, Which Fell Out at Port Royal, in Jamaica.

=== TO THE READER.

The author having been much pressed in spirit to write the following considerations,
begs they may be read with attention, and examined without prejudice.
He hopes the learned and ingenuous reader will excuse any faults in style or method,
having respect to the sincerity of intention,
which he professes to have had in this undertaking;
and humbly prays that a divine blessing may attend it,
to the satisfaction and eternal advantage of all whom it may concern.

[.asterism]
'''

Having had some discourse with a young man of bright natural parts,
concerning another world, and of leaping out of this into that, in the dark,
which must needs be very dangerous;
and fearing that many take that great leap in that manner,
I have been induced to write these lines.

Upon which I cannot forbear asking,
what man in his senses will venture to leap in the dark, he knows not where?
or into a pit, of which he knows not the bottom?
To think of it is terrifying, and must needs shock any considerate thinker.

Though a man, having a bright genius, and a large share of natural parts,
may acquire much literal and natural knowledge; yet,
for lack of a spiritual understanding, which is derived from the divine Spirit,
he may greatly err concerning true faith and religion,
and have no just apprehension of the eternal kingdom and judgment of God,
or of another world; which it might be well for the ungodly, were never to be at all:
though even if this were to be supposed, yet to live virtuously,
as the bishop of Sarum observed to that great libertine.
Lord Rochester, would be an advantage to men, even in this world.

But if there should he an eternal righteous kingdom,
of which we may internally and spiritually be sensible,
and a state of life therein to come; then.
Oh, then! what will become of the wicked,
and all who forget God! and what perturbation of soul must attend such, when,
under the convictions thereof, they shall be ready to launch into eternity.
I beseech you, Oh, soul! seriously to consider, before it be too late.

The great Saviour of the world says, "`The kingdom of God is within you.`"
That is, inwardly and spiritually, to be known and perceived.
He also says, "`I am the light of the world.`"
He, by this divine and supernatural light,
lights us through this dark world to his spiritual and glorious kingdom,
where he rules and reigns in transcendent majesty and brightness;
of which his faithful subjects are in some measure sensible;
glory to the King of kings forever.

And that eminently wise apostle Paul says,
"`He was sent to turn men from darkness to light.`"
Darkness he calls the power of Satan, and light the power of God.
Now as a man walking in outward darkness is in continual danger of falling,
not knowing where he goes; so also a man living and walking in spiritual darkness,
which is the power of Satan,
where the wonderful power and works of God cannot be seen or understood,
must needs be in the greatest danger of falling into the bottomless pit of perdition,
where horrible darkness and unutterable misery prevail anyone.

The many bitter cries, dreadful shrieks, and heavy groans,
which my ears have heard from such dark souls, ready to depart the body,
have been enough to convince me of the judgment of another world,
though there had been no other demonstration of it to me.
May our fine wits and sprightly youths repent in time.
Oh! my heart is pained for them;
and my soul mourns in secret for many of my former and latter acquaintance,
and I have also tender desires for the well-doing and well-being of mankind in general.

If any, by duly thinking of these things,
should be awakened and convinced of their state,
and their former lives and wicked practices;
and have so much light as to see the danger of living without God in the world;
but be ready to conclude, that if there be indeed a righteous God,
who will reward every man according to his works, there can then be no hope for them,
they are such wretched sinners.
Oh, if this be the case of any, look not at such thoughts, which,
in the midst of your just apprehensions, Satan, taking advantage,
may thus suggest to you; who having got you deep already in the mire of sin,
would by such infusions plunge you deeper both into sin and despair.

Be it remembered that Christ died for sinners, even the chief, as Paul says,
and he can make a chief saint of a chief sinner, as appears in the case of that apostle,
by his own testimony.
God has done and can do it, though it be wonderful!

Therefore abide not in darkness,
but repent and turn to the light of life! strive and struggle for life,
the life of God in the soul of man! turn to the divine light; turn to God who is light,
and in him is no darkness at all; live and walk in the light of God,
which is far above the light of human reason;
therein shall we have fellowship with the Father of lights, and his son Jesus Christ;
whose religion is spiritual: "`God is a spirit, and they that worship him,
must worship him in spirit and in truth.`"

God must be worshipped in thought, word and deed; that is,
in all things we ought to expressa humble reverence and adoration to the Sovereign Being,
frequently meditating on his great name.
But all evil and sinful thinking we must refrain from with abhorrence,
as displeasing to him, being of the devil, that wicked spirit;
and indeed it is contrary to the nature and end of free-thinking;
which is a sincere exercise of the rational faculty,
in order to distinguish between good and evil, truth and falsehood,
that we may choose and acknowledge the one, and avoid and reject the other.
And here it may not be unfit to recommend the care of all our thoughts,
from where proceed our words and actions,
as naturally as good and evil fruit from the different seeds sown in the earth.

And as the truest and most sublime end of thinking,
which is the reasonable service of every intelligent being, is the contemplation, fear,
and adoration of the Almighty Creator;
so are we thereto greatly encouraged by that Scripture of Malachi,
which I am concerned here to transcribe and recommend: "`Then they that feared the Lord,
spoke often one to another, and the Lord hearkened and heard it,
and a book of remembrance was written before him for them that feared the Lord,
and that thought upon his name.
And they shall be mine, says the Lord of hosts, in that day when I make up my jewels,
and I will spare them as a man spares his own son that serves him.
Then you shall return and discern between the righteous and the wicked,
between him that serves God, and him that serves him not.`"

In which Scripture we may observe how great and glorious a reward
is promised to those who sanctify the name of the Lord;
the consideration of which must needs raise their love and admiration,
and add to their present delight in such holy thoughts.

But, on the contrary, it is to be feared, that evil thinkers and actors,
when the divine spirit and light would inspire them with good thoughts,
or convince them of their sins, endeavour to stifle or overcome such thoughts or motions,
as would awaken them to righteousness, or restrain them from sin;
and strive by their natural wit, to reason the good spirit out of their souls;
at the same time opening their hearts to the evil spirit and his suggestions,
which they hug, to their own destruction.

But to judge rightly of these things,
if a man have ever so much natural wit and strength of reason,
it must be sanctified through his faithful subjection to the divine will,
and raised by divine inspiration;
which as far surpasses human reason as heaven is above the earth.
May our men of bright natural thought think clearly and seriously of this.
This is evident in the case of the great apostle Paul,
who was educated at the feet of Gamaliel, in the perfect manner of the law, yet,
by all his knowledge could not justly distinguish concerning religion,
but was a persecutor of the church of Christ.
But when his knowledge and spirit came to be sanctified
by the grace and spirit of our Lord Jesus Christ,
then, and not till then, he became of great and good use to his Maker and mankind.
Then his reason and religion became spiritual,
"`who had not conferred with flesh and blood,
but had been obedient to the heavenly vision.`"
And he says, "`If in this life only we have hope in Christ,
we are of all men the most miserable.`"
His hope and expectation, as well as of all faithful believers,
must have been of another life, and the kingdom of God hereafter: "`For here,`" says he,
"`we have no continuing city, but seek one to come.`"
And though the condition of such, in this life,
be often exposed to much persecution and trouble for their faith`'s sake,
towards the name of God and testimony against this
world and the evil spirit ruling therein;
yet, blessed be the Most High, he gives them strength and the assurance of his favour,
whereby they endure to the end,
as well as that he refreshes them with his outward blessings and comforts;
so that they may well say with his ancient servant Job,
"`Shall we receive good at the hand of the Lord, and not evil?`"
Thus afflictions have been indeed usually called, but they often, in the hand of God,
are means of redeeming the soul, and raising up many excellent virtues,
when they are rightly submitted to.

I would inquire what subject we can possibly choose so worthy of our meditation,
or from where so great a benefit can redound both to spirit and body?
The fear and thoughts of Almighty God,
which are inspired by his grace sanctifying our hearts,
thereby render us more fit to receive his favours both to spirit and body,
which he multiplies according to his wisdom and good pleasure;
and all our faculties and passions being redeemed and governed by the spirit of faith,
we shall possess and enjoy all things in a more regular and excellent manner.
But who is there that has not been so great a partaker of the many blessings,
with which the infinite Creator fills the world,
and in an especial manner encompasses mankind,
as not to be obliged to a continual acknowledgment thereof,
and remembrance of the great and bountiful Author?
The state therefore of the wicked and rebellious, is stigmatized in holy Scripture,
with this character, in particular, that "`God is not in all their thoughts.`"
And indeed for this came his judgment upon the old world of the ungodly,
who cannot be supposed ever to have thought of the adorable Lord,
since every imagination and thought of their hearts was only evil continually,
as the Almighty himself has complained.

But instead of the returns of faith and love, how sad a consideration is it,
that there should among men be found any so vile and foolish,
as even to deny the divine existence,
and the effects of his infinite power in the external creation,
and to affirm that all things have come by nature, without God,
or any supernatural power; which evil tenet,
some have endeavoured to justify and support by natural reason;
"`Wherein the name thereof may indeed be abused; but reason itself,
which concludes nothing without evidence, can never declare in favour of a proposition,
for which, not only none can appear, but against which the whole world is full of it.
But let this be disposed for the judgment of reason.
When therefore it is said, that all things have come by nature;
if thereby we are to understand that natural things are severally self productive,
this will be disproved by daily experience; for we may observe,
that they depend one upon another,
and upon various causes for production and subsistence, without which neither,
in a state of nature, could possibly be.
But if it be meant of the universal system of natural things collectively,
this will less be allowed of many, than of any particular of them;
because that would destroy the nature of a self-productive power,
which cannot be limited from being infinite, and therefore can be but one:
one infinite supreme nature therefore only can have self-existed
and must have been the supernatural author and power,
by whom all other beings have existed: which refutes the above error,
and rationally proves and establishes the great truth in the question.`"

And this the Christian religion teaches in the greatest perfection,
that the Creator of all things is God, an infinite eternal Spirit, who fills all things;
who having been pleased to manifest his eternal power
and godhead in the visible frame of the universe,
bears witness of himself therein, by his providence and judgments;
and in every soul of man by his inward inspirations; especially the sincere believer,
in whom his spirit dwells and operates.

Oh! that men therefore would lift up their minds and open their hearts to him,
when by his holy Spirit he reproves them for sin,
and brings a damp upon their spirits for evil; from which they would, perhaps,
if they could, run, or divert themselves from the sense of it.
But, alas! there is no fleeing from his presence, who is everywhere;
nor avoiding his judgment, whose kingdom comprehends all things:
but woe is especially to them with whom his spirit ceases striving.
Holy David certainly was very sensible of this,
when he wrote that admirable description of the Divine Omnipresence,
"`Where shall I go from your spirit, or where shall I flee from your presence?
If I ascend up to heaven, you are there: If I make my bed in hell, behold you are there.
If I take the wings of the morning, and dwell in the uttermost parts of the sea,
even there shall your hand lead me, and your right hand shall hold me.
If I say, surely the darkness shall cover me, even the night shall he light about me,
yes, the darkness hides not from you; but the night shines as the day:
the darkness and the light are both alike to you.`"
With these views of the infinite power and presence of the Almighty,
I shall pass to the relation promised, which may here be properly inserted.

My author was Jonathan Dickenson, merchant in Philadelphia,
who was present with the young men whom this extraordinary providence befell,
at Port Royal, in Jamaica: he gave me the following account:

Two ingenious young men, who were lately arrived at Jamaica, from London,
discoursing about earthquakes, asserted that all things came by nature:
and so argued thereupon, that it brought terror upon the company, who were many,
at dinner, in an upper room.
While this lasted, to the great astonishment of all present,
the earth began to move and tremble, which put most of them to flight in such haste,
that they ran one almost over another, some downstairs, others leaping over the balcony.
But my author said he considered there was no running from Divine Providence,
and that the same hand which moved the earth, was able to preserve him;
in which he trusted, and was preserved.

As he continued with the young men in the same room, Oh! terrible to relate,
and my heart and hand tremble in the writing thereof,
the mighty hand of an offended God struck these young men with death, and they fell down,
and never rose any more, being in all appearance unprepared for so sudden a change.
And how many other gay, witty young people have been suddenly snatched away by death,
though perhaps not so immediately, nor in so extraordinary a manner,
seems worthy of reflection.
The author of this account added, that he took up the young men,
and laid one of them upon a bed, and the other upon a couch;
but that they never spoke again after their blasphemy against God and his works.
Upon which I think it very natural, as well as necessary to remark,
that this was indeed an eminent instance of the just judgment of God against
such as deny his wonderful power and providence in the creation;
with this terrible circumstance,
that these unhappy persons were cut off in the midst
of their ungodly discourse and corrupt reasoning,
without so much time afforded them as to ask pardon and crave mercy of a provoked Lord;
which is very dreadful to consider.
I especially recommend it to the serious reflection
of all such as affect the name of free-thinkers,
as they are commonly distinguished, that they may no longer, under such a pretence,
abuse their understanding with a latitude of profane and evil thinking: who,
as they must be sensible that they have not conferred
the excellent faculty of reason upon themselves,
so they may as certainly conclude that they never received it to exclude his existence,
power and providence, out of the world, who gave it them;
nor to employ it to their own destruction, by such a perversion thereof,
which must inevitably be the consequence, without timely and due repentance;
but that they may apply themselves to him for true wisdom,
who is the eternal fountain of it, who would direct all their thoughts aright therein.
Then would they find a substantial and enduring happiness and satisfaction,
in the honourable thoughts and practice of true religion and virtue;
and that all vain and evil thoughts directly tended
to the misery and destruction of mankind.

Lastly, if any expression in this short tract should prove successful to promote,
in any measure, the contemplation of the Divine Being;
the consideration of man`'s duty to him, his Almighty Creator,
or to convince but one soul of the error of his thoughts and ways;
the author will think himself richly rewarded for his endeavours,
and reverently ascribe the glory and praise to God,
the prime Author and mover of every good thing, who is worthy forever.
