[quote.epigraph, , Ps. 1:1-2]
____
Blessed is the man who walketh not in the counsel of the ungodly,
nor standeth in the way of sinners, nor sitteth in the seat of the scornful;
but his delight is in the law of the Lord,
and in his law doth he meditate both day and night.
____

== Chapter I

Having great cause to acknowledge the regard and protection
of divine Providence in the several stages of my life,
I think it may be of service to others,
to leave behind me the following account of my life and travels.

I was born on the 3rd day of the third month, 1675, in Southwark,
and descended of honest and religious parents, who were very careful of me,
and brought me up in the fear of the Lord; and oftentimes counselled me to sobriety,
and reproved me for wantonness; and that light spirit which is incident to youth,
they were careful to nip in the bud: so that I have cause to bless God, through Christ,
on the behalf of my tender parents.

I may not forget the dealings of God with me in my very tender years.
When between eight and ten years of age,
my father and mother sent me nearly two miles to school, to Richard Scoryer,
in the suburbs of London.
I went mostly by myself, and many and various were the exercises I went through,
by beatings and stonings along the streets,
being distinguished to the people by the badge of plainness which my parents put upon me,
of what profession I was: divers telling me,
"`it was no more sin to kill me than it was to kill a dog.`"

About this time the Lord began to work strongly on my mind by his grace,
insomuch that I could not forbear reproving those lads,
who would take the name of the Lord God in their mouths in vain,
reminding them of the third commandment,
"`Thou shalt not take the name of the Lord thy God in vain,
for the Lord will not hold him guiltless that taketh
his name in vain;`" and of Christ`'s saying,
"`every idle word that men shall speak,
they shall give an account thereof in the day of judgment;`"
for which I was mocked and derided by some,
and others would sometimes refrain from such bad words when I reproved them.

One time I remember being amongst some men, one of whom I had reproved,
and he told the rest of it, and turned to me, and said,
"`that I was no Christian,`" and asked me, "`when I said the Lord`'s prayer?`"
I asked him, if he said it.
He replied yes.
I then asked him, how he could call God Father,
and be so wicked as to swear and take God`'s name in vain;
which I had heard him often do; and I told him what Christ said to the Jews,
"`ye are of your father the devil,
because his works ye do;`" and that those that did
the devil`'s work could not truly call God father,
according to Christ`'s doctrine.
Being convicted in their consciences that what I said was true, they were all silent,
and wondered that I, being so young, should speak in such a manner;
in which I remember I had great peace and good satisfaction;
and from thenceforth these men let me alone.

Notwithstanding I hated to hear wicked words, I loved play exceedingly,
being persuaded that there was no harm in that, if we used no bad words.
One time I was at play at a neighbour`'s house with the children,
and in the midst of my sport I was reached with strong conviction,
insomuch that I could not forbear weeping.
The children`'s mother observing that I wept, said, "`why do you weep?`"
I told her I could not tell, except it was because I was a naughty boy.
"`Oh!`" said she, "`don`'t believe him, for that`'s the devil tells you so,
for you are the best boy in all our street.`"
But I knew I was told the truth by conviction, and that she was mistaken:
for I plainly understood by clear conviction, and by the holy Scriptures,
which I had been trained up in the reading of, that I was too vain and wanton;
for I loved music, dancing and playing at cards, and too much delighted therein,
and was followed with the judgments of God therefor in the secret of my soul.
What I did in those sports and games, I always took care to do out of the sight,
and without the knowledge, of my tender parents;
for I was afraid of their reproofs and corrections, the which I was sure to have,
if they had any intelligence of it.

I remember that, unknown to my parents, I had bought a pack of cards,
with intent to make use of them when I went to see my relations in the country,
where there was liberty in the family so to do, at a place called Woodford,
about seven miles from London, where I got leave sometimes to go.
At the time called Christmas, I went to see them,
and five miles on my way went to a meeting, at a town called Wanstead; at which meeting,
a minister of Christ declared against the evil of gaming, and particularly of cards;
and that the time which people pretend to keep holy, for Christ`'s sake,
many of them spend mostly in wickedness, sports and games;
even some pretending to be religious; and generally speaking,
more sin and evil is committed in this time,
than in the like space of time in all the year besides;
so that the devil is served instead of honouring Christ.

From this meeting at Wanstead, I went to the house of my relations,
where the parson of the next parish lodged that night,
who used to play cards with them sometimes.
The time drawing near that we were to go to our games, my uncle called to the doctor,
as he styled him, to me and to my cousin, to come and take a game at cards;
at which motion I had strong convictions upon me not to do it, as being evil;
and I secretly cried to the Lord to keep me faithful to him; and lifting up my eyes,
I saw a Bible lie in the window, at the sight of which I was glad.
I took it, and sat down, and read to myself,
greatly rejoicing that I was preserved out of the snare.
Then my uncle called again, and said, "`Come, doctor, you and I, my wife and daughter,
will have a game at cards, for I see my cousin is better disposed.`"
Then he looked upon me, and said, "`He was better disposed also.`"
So their sport for that time was spoiled, and mine in that practice forever;
for I never, as I remember, played with them more, but as soon as I came home,
offered my new and untouched pack of cards to the fire.
I am certain the use of them is of evil consequence,
and draws away the mind from heaven and heavenly things;
for which reason all Christians ought to shun them as engines of Satan;
and music and dancing having generally the same tendency,
ought therefore to be refrained from.
The sentiments of the Waldenses, a people in great esteem among Protestants,
are worthy the consideration of all Christians; which were, "`That as many paces,
or steps, as a man or woman takes in the dance,
so many paces or steps they take towards hell.`"

I very well remember the work of God upon my soul, when I was about ten years of age;
and particularly at a certain time when I had been rebelling against God and my parents,
in vanity and lightness: and as I had offended both, so I was corrected by both:
for I had not only felt the anger of my parents, but the Lord frowned upon me, insomuch,
that I trembled exceedingly, and was as though I heard a voice say to me,
"`What will become of thee this night, if I should take thy life from thee?`"
At which I was amazed, and in great fear.
Then I covenanted with God, that if he would be pleased to spare my life,
for I thought God would have taken it from me that very moment, I would be more sober,
and mind his fear more than I had done before.

Nevertheless, I broke covenant with God my Maker, my adversary tempting me so to do,
telling me I was but a child, and it was natural for children to be brisk and play,
and that God would wink at my childhood and youth,
and it was time enough for me when a man, to become religious.
But still God followed me with his chastising rod,
and often put me in mind of my covenant which I made with him in my distress;
and that he had granted the request I then made to him;
and unless I would take up a cross to my own corrupt will and inclinations,
he should take me out of the world.
Then, Oh, then!
I cried.
Lord help, or I die!
Save me, or I perish forever!
I cannot keep thy covenant, nor do thy will, without thy help and assistance!
And indeed, if the Lord had not helped, I had been undone forever.

I continued bowed down in my mind, calling on the Lord;
thinking and meditating on heaven and heavenly things:
but as I am sensible I had an inward enemy that always sought my hurt and overthrow,
I have cause to bless God, who by his grace, as mine eye was turned to it,
helped me to do his will, as he was pleased to manifest it to me,
so that thereby some change was wrought on me both inwardly and outwardly.

I then began to delight in reading and sobriety, which before were irksome to me:
and when I read the holy Scriptures,
I desired that God would open them to my understanding,
which he did many times to my edification.
I also begged earnestly of the Lord, that he would be pleased to be with me,
and make me like his children and servants, of whom I read in the holy Scriptures,
who faithfully served him all their days.
And when I read of the crucifixion of our blessed Lord and Saviour Jesus Christ,
it would break my soul into tenderness.
I thought it was enough to awaken and humble any soul that was well meaning,
and had any sense of the power, love and grace of Christ.
Thus I went on for several years, feeling that peace which passeth natural understanding,
which many times accompanied my poor and needy soul:
and being advanced to about fourteen or fifteen years of age,
I remember that I used to shun the cross of speaking in the plain language,
which I always read in the holy Scriptures, to those whom I conversed with,
except my father and mother, who would not allow me to speak otherwise.
I was convicted in my conscience that it was not
right to play the hypocrite after that manner;
and on a certain time I had occasion to speak with an officer,
a great man in our neighbourhood,
and my heart moved within me for fear I should shun the cross of Christ;
for it was Christ`'s language to all, as we may read in the New Testament;
and all the Scriptures, from Genesis to the Revelations, speak thee and thou,
to a single person.

So I took up the cross, and said thee to him; and he was much affronted, and said,
"`Thee! what dost thou thee me for?`"
I soberly asked him if he did not say thee to his Maker in his prayers?
and whether he was too good, or too great,
to be spoken to in the same language in which he addressed the Almighty?
To this he made no reply, but seemed to fall from his passion into admiration,
as one smitten in himself.
He bore me respect ever after; and I greatly rejoiced that I was preserved faithful.
Though it may look a little thing to some, yet I found it good, as the Scripture saith,
not to despise the day of small things.

About the twentieth year of my age,
I was pressed and carried on board of a vessel belonging to a man of war.
I was put down into the hold in the dark, not having any thing to lie upon but casks;
and what made it worse to me, I was among wicked, debauched men;
and as we were shut up in darkness, so was their conversation dark and hellish.
In the morning, for which I longed more than the watchman,
the lieutenant called us up on deck, and examined us,
whether we were willing to serve the king?
He called me to him, and asked me, if I was willing to serve his majesty?
I answered, that I was willing to serve him in my business,
and according to my conscience; but as for war or fighting,
Christ had forbidden it in his excellent sermon on the mount;
and for that reason I could not bear arms, or be instrumental to destroy or kill men.
Then the lieutenant looked on me and on the people, and said, "`Gentlemen,
what shall we do with this fellow?
he swears he will not fight.`"
The commander of the vessel made answer, "`No, no, he will neither swear nor fight.`"
Upon which they turned me on shore.
I was thankful that I was delivered out of their hands;
and my tender parents were glad to see me again.

As I grew in years, the world began to take too much root in me;
and my unwearied enemy would tell me that it was lawful enough,
and indeed I see that he hurts many with lawful things,
with whom he knoweth unlawful things will not take;
and here I had been lost if God had not been gracious to me.
But he, in whose presence I delighted, withdrew,
and deprived me of that enjoyment which was grateful
and comfortable above all things to my soul.
Then did I pray with tears, Oh,
that it might be with me as it was at other times
before! and I was willing to let the world go,
rather than grace and God`'s glory.
The Psalmist saith, "`no good thing will he withhold from them that walk uprightly.`"

About this time there was a great concern on my mind,
rightly to distinguish between the voice of Christ, and the whisperings of Satan;
and thus it opened to me: that Christ, the truth,
always speaketh good and for a good end,
and that there is divine life to the soul in this speaking;
but the devil never speaks good, unless sometimes for a bad end,
and then not good in reality, only coloured with good or a fair shew.

Keeping under this exercise, the Lord appeared to me again,
and many times refreshed my heart with his goodness.
When I was in my business amongst men, I witnessed the Holy Ghost, the Comforter,
to be near me; which was more to me than all the world, or the riches,
glory and beauty of it.
The love of God being so sweet to my soul and spirit; my breathings,
prayers and supplications, were to the Lord, that my neighbours, acquaintance,
and relations, might also partake of the like precious faith and love which I enjoyed;
and that the children of men might answer that great
and good end for which the Lord created them;
which is, that glory, honour, and praise, might ascend and be given to Him.

I had such a sense and fear of dishonouring God, that I often, with tears, cried,
Never let me live to dishonour thee.
Oh! it had been better for me that I had never been
born than that I should live to dishonour thee,
or willfully reproach the name of Christ, who, with the Father,
is only worthy of divine honour.

In this concern I felt the gospel power of our Lord Jesus Christ to work, upon my soul,
and the word of God was as a seed in my heart, growing and opening in me, speaking to me,
and making my understanding fruitful in the things of his kingdom;
and in that ability which was given me of God, through his grace and holy Spirit,
I exhorted people to repentance and amendment of life;
and I always humbly desired the help and divine influence of God`'s eternal Word therein.
Oh!
I did fervently pray that I might minister the gospel in the power of Jesus;
for I clearly discerned, in the light of the Son of God,
that all ministering out of Christ`'s power was neither
edifying nor efficacious unto souls:
therefore I did earnestly beseech God for the continuance of the gift of his Spirit,
that I might be enabled to preach the gospel in the power of Christ Jesus.
The concern that was upon me on this account at that time,
is hard to be expressed in words.

The latter end of the year 1695, my father sent me into Essex on some business,
and when I had accomplished it, I visited some meetings of Friends there,
and my mind being much affected with the apprehensions of an impending storm,
the nation being about this time threatened with an invasion from France,
in favour of the late king James,
so that there was expectation of much blood-shed and confusion in the land,
I wrote a letter to my parents, and another to Friends of the evening meeting,
kept weekly at my father`'s house, expressing my thankfulness to the Almighty,
in the remembrance of the many precious visitations
of divine love and favour we had been partakers of,
uniting our hearts to him, and to one another; and my earnest prayers and supplications,
that we might be preserved in true love, and the unity of the spirit,
which is the bond of everlasting peace;
and that the world might be made sensible of this true peace,
which abounds in those who love and fear the Lord,
and truly believe in the name of Jesus.
Oh! surely, they would then depart from sin, and abandon iniquity,
by which they incur the wrath of the Lord, and provoke the just One to anger;
so that the line of confusion seems to be stretched over the city and nation,
and the eyes of the faithful see it to the grief of their souls.
Yet the mercy of the Lord, even of the just God,
who will render a just reward to every one according to his deeds done in the body,
is still handed forth to the land.
Oh! that the inhabitants thereof would consider their ways, and be wise,
and turn to the Lord with unfeigned repentance, while the day of mercy lasteth,
before it be said, now it is hid from thine eyes; for the Lord,
even the God and Father of spirits, hath said,
"`My spirit shall not always strive with man, for that he also is flesh.`"

On the expiration of my apprenticeship, having served my father faithfully seven years,
I entered more strongly into covenant with my heavenly Father and master,
to serve him all my days, through his assistance; and was soon after drawn forth,
in the spirit and love of Christ, to visit the meetings of Friends westward from London,
viz. through Surry, Sussex, Hampshire, Wiltshire, Devonshire,
and Cornwall to the Lands End; in which journey I was accompanied by William Hornould.
At one of our meetings at Falmouth, in Cornwall,
two men called gentlemen came from the inn to hear the strangers; and after meeting,
they said they could take their oath that I was a Jesuit,
and that they had heard me preach in a Romish chapel in France; which was utterly false;
for I never was in France.
Besides, had I been a papist, or popishly inclined, which I was not,
I was too young to be a Jesuit.

Indeed, I thought I was mean for the work of the ministry,
but the good remembrancer brought those truths to my remembrance,
which strengthened me in the work and service of God.
The spirit breatheth where it listeth;
out of the mouths of babes and sucklings thou hast perfected praise, etc.
We having great peace in our labours in this journey, and being edified therewith,
returned to London, after about four months absence from home.

After I had been two weeks at home, my dear mother departed this life,
in a sweet frame of spirit, praising the Lord.
She was one who lived the life of the righteous, and whose latter end was like theirs,
and left a good report behind her, being well beloved, I think I may safely say,
by all our neighbours; not only by those of our own society, but others also,
to whom she was often very helpful.

I went to my calling and got a little money, a little being enough,
which I was made willing to spend freely, in the work and service of my great master,
Christ Jesus.
About this time I was concerned to travel into the north of England,
and part of Scotland, which I did in that ability God gave me;
and that dispensation which I had freely received, I freely handed forth to the people,
devoting my strength and time to serve him who had done so much for me;
and I had the satisfaction to find divers confessing the truth, as it is in Jesus.
In this journey I was from home about four months,
being mostly alone as to any yokefellow in that work, travelling many hundreds of miles,
as far as Edinburgh, in Scotland, where our meeting was in the street,
we being locked out of our meetinghouse by the then power,
and great numbers of people were there.
This news being carried to the provost of the city, he said,
"`The Quakers would do more hurt out of doors than
within,`" and he ordered Friends their key.
Since which I have understood that Friends in that
city have enjoyed their meetings in the meetinghouse;
and sometimes when the rabble have disturbed Friends,
the magistrates have sent officers to disperse them.

After I had visited the churches of Christ in divers parts of England,
and had many sweet seasons of God`'s love,
and many good opportunities with my Friends and others in this nation;
the word of life being declared in the simplicity of the gospel,
in several places people were very open-hearted,
and received the testimony of it with gladness.
After I had been at my father`'s, and at my calling,
a little after this north country journey,
I found myself engaged in the love of the gospel to visit Friends in America;
and having acquainted my friends and relations of my mind,
they being willing to give me up, in order for the voyage.
Friends of the monthly meeting gave me a certificate,
and I had another from the meeting of the ministers in London.

My father, and several other friends with me, took boat from London,
and accompanied me to Gravesend, on the 21st of the tenth month, 1697.
I went on board the ship Josiah, Thomas Lurting, master,
and sailed that day from Gravesend, and got to the Downs the next day,
where we tarried some days for a fair wind; in which time several others,
who were concerned in the same gospel labour, came on board, viz. Thomas Turner,
William Ellis, and Aaron Atkinson.
In about four days time the wind was fair for us, and we set sail,
and in a little time we got out of sight of the land;
soon after which the wind was contrary,
and we proceeded but a small distance for several weeks;
the weather was rough and the sea boisterous, so that with the motion thereof,
most of the passengers were sick.
In this time we lost a lad,
who fell into the sea as he was drawing a bucket of water and was drowned;
the ship running swiftly, he could not be saved, although it was speedily endeavoured.
Several others died before we got over; but for the most part we were healthful.
The Lord be praised, he was, is,
and will be with those who faithfully serve him to the end.

There were three ships in company, but by the distress of weather,
soon after we came out, we parted.
After we had been at sea about eight weeks, on the 25th of the twelfth month,
we saw two vessels astern of us.
One of them came up with us, and the people hailed us,
and told us they came from Bristol, and had been out ten weeks.
The other came up with us next day.
The people informed us they had been at sea seven weeks,
and had had a dreadful time of it.
She had lost part of her topmast, and her spritsail topmast was gone.
She was a new ship, and never at sea before, belonging to London, and bound for Virginia,
as near as we could understand.
Our ship lost none of her tackling, through the great mercy of God to us,
though the wind and sea were wonderfully high at times; the mate told me,
I might go to sea all my life, and not see the like: he said he had been at, or used to,
the sea for twenty years, and never saw it so rough and high before.
We had meetings twice a week, several of which were comfortable and refreshing,
to which most of the passengers, being in all about sixty, sometimes came;
and several of them were affected with the sense of truth,
and the Lord strengthened our faith and hope in him.

Oh! forever blessed be the living and eternal God,
who kept my soul above the fear of death, hell, and the grave; for my trust was in him,
and he did bear up my spirit above the waves of the sea;
and in the time of tossing with tempests, I was comforted and cheerful,
praising the Lord in my heart, both in the day time, and in the night season.

I was much concerned in my mind for many of the passengers, who, with the second mate,
and several of the seamen, were very sick, and by some were thought near unto death.
I cried to the Lord to heal them, in the name of his dear Son,
and that it might be a means to convince them of the efficacy of love to,
and faith in Christ Jesus, the physician of value; and the Lord was pleased to heal them.
The mate of the ship desired that I would come and pray by him.
I went to him, and prayed in the power and name of the Lord Jesus Christ,
and the Lord helped him, that he said he was fine and easy, and thanked me for my love;
and in a little time he recovered.
Several others of the seamen and passengers I was instrumental to help in their sickness.
The Lord blessed my endeavours in supplicating him on their behalf,
and administering what I had to them.
One of the seamen said, he was bound to pray for me as long as he lived,
and that the Lord would bless me.
Another of the passengers said, that I was the blessed doctor,
for there was not a surgeon, or doctor in the ship.
I was very free to communicate of what I had to any sick person in the ship,
and several blessed the Lord on my behalf.
Indeed I thought I could scarcely do enough for any that were in distress.
I write not thus, that I may seem popular, but with my mind bowed before the Lord.
Many times in this voyage there were consultations in my mind,
whether I had best write a memorandum hereof; but at last,
conceiving in my spirit that it might strengthen and excite love to God,
and faith in his beloved Son, in true believers, I wrote as aforesaid;
and then I was satisfied, and gave the glory to God.

Before we came to the land, we saw a ketch,
which had saved the lives of some who belonged to a ship
that was a little before foundered in the sea;
who said also, that a fleet of New England ships which had been upon that coast,
by stormy weather were forced to Barbados.
Within a few days after, we saw the land of Virginia, and also a New England ship,
which sailed from England three weeks before us.
We arrived within the Capes of Virginia the 31st of the first month 1698,
and overtook the John and Margaret, a ship that came out of the English channel with us,
the master, Thomas Salmon, being dead.
Next day we anchored our ship at the mouth of Patuxent river, in Maryland,
where our boats were hoisted out, and we were rowed up Patuxent river twelve miles,
to Arthur Young`'s house, where we lodged that night;
and for our preservation and safe arrival, we blessed the Lord our God,
and my spirit praised him who lives forever and ever.
Our voyage was above twelve weeks, it being then winter time,
and for the most part the winds so high that the ship could carry but little sail,
which made our voyage the longer.

About four days after we landed, we had a meeting, near Patuxent river;
and a blessed one it was!
When it was ended, we went that night to Daniel Rawling`'s,
and from thence to the Cliffs, to Richard Johns`',
a Friend who came with us from England, at whose house we had a meeting,
wherein God`'s presence was powerfully felt.
We had several meetings on that side the bay, called the Westernshore,
and then we sailed over to the east side of Chesapeak bay, with Thomas Everden,
in his sloop; went to his house and had a meeting, where many people came.
Here we met with our friends, Jonathan Tyler, Henry Payton, and Henry Payton`'s sister.
While I was at this Friend`'s house, one Robert Cathing, being very ill,
sent for Thomas Everden, and he not being very well desired me to visit the sick person.
So I went, and the man was near to death.
Howbeit, he said he was comforted much with the visit,
and that he never had received so much benefit by the parish priest, although, said he,
it cost me dear for what I had; and if ever I live to get over it,
by the assistance of God, I shall have nothing to do with them more.
But, he said, he should not live three days.
And before the end of three days he expired.
He desired if I were not gone that I would be at his funeral.
On notice hereof, about ten Friends went; and there was a great many people,
among whom we had a good opportunity,
and many weighty truths were opened to them in the love of God;
and some of them were tender and wept; and the most, if not all, I think I may say,
were solid and weighty.

From Thomas Everden`'s we went to George Truit`'s, at whose house we had a meeting.

This Friend and I went to an Indian town not far from his house,
because I had a desire to see these people, having never seen any of them before.
When we came to the town they were kind to us, spoke well of Friends,
and said they would not cheat them, as some others did.

From George Truit`'s, in Maryland, we went down to Virginia;
and in Accomack and Northampton counties had large meetings.
I hope they were effectual to many, and I think my hope is not without ground.
In those parts we had several meetings,
where we were informed Friends had not had any before.
And really I cannot but bless the Lord for the opportunities we had with the people;
for the goodness of God, through Christ our Lord, was great, both to us and them,
and with tears they did acknowledge the truth.
Thomas Turner, who had hitherto accompanied me,
went by the seaside the nearest way to Philadelphia,
and afterwards I had a meeting at George Truit`'s brother`'s, and on the first-day,
another near the courthouse, and went to Thomas Everden`'s, and so to Leven Denwood`'s,
and thence to Nanticoke river,
and visited Friends up the bay until I came to the river Choptank,
about which there are many Friends.
I went on and took the meetings till I came to Philadelphia, in and about which place,
and in other parts of the province of Pennsylvania,
I had many large and precious meetings,
the power of the eternal Son of God being wonderful;
in which power we many times blessed his name together.
It was much in my heart to exhort Friends to love God,
and to be at unity one with another,
without which there is no fufilling the law or gospel.
There are many Friends in that province, and many sober young people,
which greatly rejoiced my spirit, so that for their encouragement,
the Lord opened my mouth in a prophetic manner to declare
unto them the blessings which he had in store for them,
on condition of their walking in the truth.
Glory to God on high! untruth decays and the branches of it mightily wither;
the darkness is much past, and the true light shineth gloriously in many souls.
Oh! powerful praises be given to God, who is light forever.

From Philadelphia I went to Burlington and to Crosswicks,
where we had a large meeting under the trees, and some were convinced of the truth.
From hence I went to Shrewsbury and had meetings; then to Woodbridge,
Staten island and Long island, being accompanied by several Friends.
On Long island we had several large and good meetings,
wherein Christ was preached freely; and after we had been two weeks there,
we went on board a sloop bound for Rhode Island,
and by the way we touched at Fisher`'s and Block islands,
and on the first-day morning we set sail from Block island to Rhode Island,
the yearly meeting being just over when we got there.
That evening we sailed over to Connanicut island,
and on the third-day of the week had a meeting there.
From thence we went over to Narraganset and had a meeting, and back to Rhode Island,
where Ruth Fry, a sober young woman, was convinced and remained a Friend till her death.
Here I met with several travelling Friends.

From this island we went to the main,
and had a large meeting on first-day at a place called Greenwich.
It was thought there were about five hundred people present, and many of them were tender.
We went the same night to the island;
and after several open times with Friends and others on Rhode Island,
about twelve Friends of that island went with me to Warwick and Providence yearly meetings.
We set sail about noon, and having but little wind,
it was late in the night before we got there, and very dark,
insomuch that we could neither see nor know one another, only by our speech,
and the darkness occasioned us to run our vessel against the rocks;
but at last we got ashore with our horses, and after going over a very dirty slough,
entered a dismal wilderness.
These difficulties occasioned our not getting to the Friend`'s house till the next day,
which being the last day in the week, we had a meeting;
and on the first-day also we had a very large and satisfactory meeting.
Many of us were so united in the love of God, that it was hard to part one from another.

From Providence I went to Boston and Salem, where I had meetings,
and from thence to Hampton.
In those parts God Almighty hath shortened the power of persecutors,
and brought his righteous judgments upon them for their unrighteousness.
Oh! that New England`'s professors might live in the sense of the same, and repent.
I being a stranger and traveller,
could not but observe the barbarous and unchristian-like welcome I had in Boston,
the metropolis of New England.

Oh! what a pity it was, said one,
that all of your society were not hanged with the other four!^
footnote:[Marmaduke Stevenson, William Robinson, Mary Dyer and William Ledra,
who were put to death in 1659 and 1660.]
In the eastern part of New England God hath a seed left of his people.

From thence I returned in order to get a passage to the isle of Nantucket;
and from a place called Cushnet, we sailed over to the said island in about ten hours,
where we tarried several days and had five meetings.
The people generally acknowledged to the truth, and many of them were tender-hearted.
Some of the ancient people said,
it was never known that so many people were together on the island at once.
After the first meeting was over, one asked the minister, so called,
whether we might have a meeting at his house '`.`' he said, with a good will, we might.
This minister had some discourse with me, and asked.
What induced me to come hither, being such a young man?
I told him I had no other view in coming there than the good of souls,
and that I could say with the apostle, a necessity was laid upon me,
and woe would be to me if I did not preach the gospel.
Then, said he, I wish you would preach at my house in God`'s name.
So next day we had a meeting at his house;
and on first-day we had the largest meeting that we had on the island.
It was thought there were above two hundred people.
The Lord in his power did make his truth known to the praise of his name.
Oh! how was my soul concerned for that people!
The Lord Jesus did open my heart to them, and theirs to him.
They were also loving and kind to us.
The chief magistrate of the island desired that I would have a meeting at his house,
there being no settled meeting of Friends before I came;
and after meeting he disputed with me about religion.
I thought we were both but poor disputants;
and cannot remember all that passed between us,
but that in the close of our dispute he said, I disputed with your friends in Barbados,
and they told me that we must eat the spiritual flesh,
and drink the spiritual blood of Christ: and, said the governor,
did ever any one hear of such flesh and blood; for is it not a contradiction in nature,
that flesh and blood should be spiritual?
Oh! surely, said I, the governor has forgotten himself;
for what flesh and blood was that which Christ said, "`except ye eat my flesh,
and drink my blood, ye have no life in you.`"
Why, said he, I do not think they were to gnaw it from his arms and shoulders.
I then told him he had answered himself; and thus our dispute ended.
From that time forward they have continued a meeting,
and there is now a meetinghouse and a yearly meeting for worship;
it is a growing meeting to this day,
and several public Friends are raised up amongst them,
who preach the gospel of Christ freely.

At this time a Friend was convinced whose name was Starbuck,
who became very serviceable on that island,
and lived and died an eminent minister of Christ.
Several scores of the people accompanied us to the water side;
and when we embarked on board our sloop,
they desired that I would come and visit them again.
I recommended them to the grace of our Lord Jesus,
and we parted in great love and tenderness.
In the evening of the next day we got to the main land, where we were gladly received.
Now it was in my heart again to visit the eastern
parts of New England before I left America;
therefore I went to Boston yearly meeting, thence to Lynn and Salem,
where we had a sweet comfortable time; likewise to the yearly meetings at Dover,
and to Piscataway, where we had several meetings,
which were profitable opportunities to many.

From Piscataway, James Goodbridge and I went over to the isle of Shoals.
We had with us a church member of the Presbyterians,
whose brother invited her over with us to the said island,
to the meeting which was at his house;
and while he was talking with her in the yard or garden,
I saw a bible and took it and read therein.
When she came into the house, she asked me, What I did with that book?
I told her, if she was offended I would lay it down.
No, no, said she, do not think to come off so, for you disown or deny that book.
I told her she was mistaken; and asked who told her so.
Why, said she, our minister in his pulpit.
I replied, that it was a great abuse upon us,
for I had been trained up from my childhood in the reading and belief of the Scriptures,
and my father and mother were Friends, that is Quakers.
She willing to try me further, said,
Did your father and mother suffer you to read the bible when you were a little boy?
Yes, said I,
and gave me correction when I was not so willing to read therein as they would have me.
Then, said she, our minister has belied you; and since you say so, if it please God,
I will go and hear you.

She went with us to meeting; and after it was over,
one asked her how she would answer it to their minister for going to meetings?
She replied, it was truth she had heard, and she would stand by it,
through the grace of Christ, and need not be ashamed of it,
though we are of ourselves but poor weak creatures.
This woman was sober and religious, and one of good report.
By the foregoing we may see how slanders flow from some pulpits:
the more is the shame and pity.
We went on and preached the gospel of our Lord Jesus Christ, in that ability he gave us,
with which the people were affected, and would have had us tarry longer,
but we could not, although they much importuned us,
because we had appointed a meeting at Oyster river.

After having several meetings about Piscataway and Dover, we went to Hampton,
where we had meetings; and at Salisbury we had a large open meeting,
of about three hundred people, as it was supposed,
which was at this time accounted a great concourse of people thereabouts.
At Jamaica and Haverhill also, we had meetings,
and from thence went to Salem and Lynn again, where we had oood service for truth;
and then to Boston, and had a meeting at the meetinghouse,
and another at a Friend`'s house in the evening, at which there were many people.
From Boston I went to visit Friends about Cape Cod, till I came again to Rhode Island.
By the way I met with Aaron Atkinson, who was on a visit to Friends in New England.
I had several good opportunities and powerful meetings in those parts,
and truth wrought a tenderness in divers at Rhode Island.
The presence of Him who said, "`Where two or three are met together in my name,
there am I in the midst of them,`" being sensibly witnessed by many;
for he was with us of a truth.

From thence I went round the Narraganset country, and had meetings at several places,
and was accompanied by John Rodman and William Beackley,
through Connecticut to Long island, which is accounted two hundred miles.
We had one meeting by the way, in which Christ, the Light of the world,
was preached to the people,
at a place where we were told there had never been a Friend`'s meeting before.
I came to Long island about two weeks before the general meeting,
and visited Friends in several places on this island, as at Hempstead, Jerusalem,
Jericho and Bethpage, where there were large meetings,
and much openness among the people, and some were convinced.
We had a meeting at a place called Matinicock,
where I met with some of the people called Ranters, who disturbed our meeting.
I may say as the apostle Paul, only altering Ephesus to Matinicock,
that I fought with beasts there.
I travelled to New York, where we had two meetings; from thence we went to the Jerseys,
and had several serviceable meetings; and so to Pennsylvania,
where there are many very large meetings of Friends, and the Lord is with his people,
and prospereth them spiritually and temporally.
Here I met with my dear friend William Ellis.
From Philadelphia, Richard Gove of that city, and I travelled to Maryland,
and visited Friends on the Western Shore and to Virginia.
In Virginia, near James`' river, I met with an aged Friend whose name was William Porter:
he was ninety-two years of age.^
footnote:[I saw him some years after, and he was weeding Indian corn with a hoe.
He was then about one hundred and six years of age, and had upwards of seventy children,
grandchildren, and great grandchildren.
Divers Friends of us went to see him, and he preached to us a short,
but very affecting sermon, which was, as near as I remember, thus: "`Friends,
you are come to see me in the love of God; God is love, and those that dwell in God,
dwell in love; I thank God I feel his divine life every day and every night.`"
He died, aged one hundred and seven years.]
We had several meetings there amongst Friends and others,
many being well satisfied concerning the truth, and spoke well of it.

After we had had several good and open meetings in Virginia,
we found ourselves clear of America, and! in order for our passage,
agreed with our friend F. Johnson, of the Elizabeth and Mary, to carry us for England.

On the 11th of the first month, 1698-9, we were accompanied on board by several Friends,
who abode with us all night; and the next day being the first-day of the week,
we had a comfortable meeting, and then parted in much love,
having the evidence of the power of the Almighty with us.
We waited for a fair wind until the 20th of the aforesaid month,
and left the Capes of Virginia that day,
and at night got our ship into a sailing posture;
and I was glad in my spirit that I was setting my face towards my native land;
and more glad that I was returning with peace in my bosom.
The power and presence of Him who said, Go, teach all nations,
was sweet to my soul at that time,
and now in some measure I enjoyed the fruits of having
laboured in that ability which God had given to me.
Glory to God, through Christ, who is worthy forever!
The presence of God was with us on the great ocean,
and we were wonderfully strengthened through his goodness.
We had several good meetings on board our ship,
and were very largely opened in the love of God to the poor seamen.

When we launched forth into the deep, there were several ships in company;
but we had been but a little time at sea, before we lost sight of them all.
Several ships passed by us about a week after we sailed;
and about this time we saw a very large whale,
which lifted itself partly out of the water, with its mouth open,
which looked like the entrance of a large cave.
We likewise saw several other large sea-fish, such as grampuses, sharks,
etc. all which show forth the wondrous works of the great Creator of all things.
Elizabeth Webb and Elizabeth Lloyd went over with us in this vessel, both virtuous women.
For about two weeks the winds were mostly fair, in which time we got finely on our way;
but for above a week afterwards the winds were mostly contrary,
and the ship had a great motion, which caused some of us to be seasick,
especially Elizabeth Lloyd,^
footnote:[She was the daughter of Thomas Lloyd, late deputy-governor of Pennsylvania.
She lived and died a virtuous woman; and, I think,
generally beloved by all who were acquainted with her.
When she died she was the wife of Daniel Zachary, a merchant of Boston, New England,
and was well known and much beloved there for her piety and virtue.]
who was but weakly.
One night our sailors thought that an enemy or pirate was near us,
as a vessel fired two guns, and passed by us; but it being night,
we could not certainly know what she was.
I rather judged it might be some ship in distress,
for that evening we saw one of the ships that came out with us,
and the next morning we could see none at all, and there was hardly any wind that night,
so I feared that our companion had sprung a leak and foundered;
and when I told our master my opinion, he said he feared the same likewise.

For nearly two weeks time we beat about the sea, and made little progress.
Howbeit, we had several good meetings, wherein we gave glory to God, our Saviour;
and forever let it ascend to him over all, saith my soul!
Contrary winds are commonly tedious at sea,
but especially to those that know not where to stay their minds;
but there being several Friends of us on board, we had oftentimes good meetings;
and if any of our ship`'s company came to meeting,
they always were sober and sometimes tender;
and truly God`'s love was extended towards them.
When it was not our meeting days, we spent not our time idly,
but for the most part in reading the holy Scriptures, writing, etc.,
in which we were at seasons greatly refreshed, strengthened and comforted.
Oh! my soul! glorify God thy Maker, and Christ thy Saviour forever,
in the sense of his goodness and mercy, both by sea and land, by night and by day!
After we had been almost seven weeks at sea, we thought that we were near the land,
but we sounded several days and found no bottom, although we let out abundance of line,
I think above three hundred yards.

About this time our doctor dreamed a dream, which he related to me, to this effect;
he said "`He dreamed that he went on shore at a great and spacious town,
the buildings whereof were high, and the streets broad;
and as he went up the street he saw a large sign,
on which was written in great golden letters, shame.
At the door of the house to which the sign belonged,
stood a woman with a can in her hand, who said to him, Doctor, will you drink?
He replied, with all my heart, for I have not drank any thing but water a great while,
(our wine and cider being all spent,
having had a long passage) and he drank a hearty draught, which he said made him merry.
He went up the street reeling to and fro, when a grim fellow coming behind him,
clapped him on the shoulder,
and told him that he arrested him in the name of the governor of the place.
He asked him for what; and said.
What have I done?
He answered, for stealing the woman`'s can.
The can he had indeed, and so he was had before the governor,
which was a mighty black dog, the biggest and grimmest that ever he saw in his life;
and witness was brought in against him by an old companion of his,
and he was found guilty, and his sentence was to go to prison, and there lay forever.`"

He told me this dream so punctually, and with such an emphasis,
that it affected me with serious sadness, and caused my heart to move within me;
for to me the dream seemed true, and the interpretation sure.
I then told him he was an ingenious man,
and might clearly see the interpretation of that dream,
which exactly answered to his state and condition, which I thus interpreted to him:
"`This great and spacious place, wherein the buildings were high and the streets broad,
is thy great and high profession.
The sign, on which was written shame, which thou sawest, and the woman at the door,
with the can in her hand, truly represent that great, crying,
and shameful sin of drunkenness, which thou knowest to be thy great weakness,
which the woman with the can did truly represent to thee.
The grim fellow who arrested thee in the devil`'s territories, is death,
who will assuredly arrest all mortals: the governor whom thou sawest,
representing a great black dog, is certainly the devil,
who after his servants have served him to the full,
will torment them eternally in hell.`"
So he got up, as it were in haste, and said, God forbid! it is nothing but a dream.
But I told him it was a very significant one, and a warning to him from the Almighty,
who sometimes speaks to men by dreams.

In seven weeks after we left sight of the land of America, we saw the Scilly islands,
and next day the land of England, which was a comfortable sight to us;
in that God Almighty had preserved us hitherto, and that we were so far on our way.
We drove about the channel`'s mouth for several days for want of wind;
after which the wind came up, and we got as far up the channel as Lime-bay,
and then an easterly wind blew fresh for several days, and we turned to windward,
but rather lost than got on our way, which was tiresome and tedious to some of us.

About this time, being some days after the doctor`'s dream,
a grievous accident happened to us.
Meeting with a Dutch vessel in Limebay, a little above the Start, we hailed her,
and she us.
They said they came from Lisbon, and were bound for Holland.
She was loaded with wine, brandy, fruit, and such like commodities,
and we having little but water to drink,
by reason our passage was longer than we expected,
we sent our boat on board in order to buy a little wine to drink with our water.
Our doctor, and a merchant who was a passenger, and one sailor, went on board,
where they stayed until some of them were overcome with wine,
although they were desired to beware thereof.
When they came back, a rope was handed to them,
but they being filled with wine to excess, were not capable of using it dexterously,
insomuch that they overset the boat and she turned bottom upwards,
having the doctor under her.
The merchant caught hold of a rope called the main-sheet, whereby his life was saved.
The sailor not getting so much drink as the other two,
got nimbly on the bottom of the boat,
and floated on the water till our other boat was hoisted out,
which was done with great speed, and we took him in;
but the doctor was drowned before the boat came.
The seaman who sat upon the boat saw him sink but could not help him.
This was the greatest exercise that we met with in all our voyage; and the more so,
because the doctor was of an evil life and conversation,
and much given to excess in drinking.
When he got on board the aforesaid ship, the master sent for a can of wine, and said,
Doctor, will you drink?
He replied yes, with all my heart, for I have drank no wine a great while.
Upon which he drank a hearty draught, that made him merry, as he said in his dream;
and notwithstanding the admonition which was so clearly
manifested to him but three days before,
and the many promises he had made to Almighty God, some of which I was a witness of,
when strong convictions were upon him, yet now he was unhappily overcome,
and in drink when he was drowned.
This is, I think, a lively representation of the tender mercy,
and just judgment of the Almighty to poor mortals;
and I thought it worthy to be recorded for posterity,
as a warning to all great lovers of wine and strong liquors.
This exercise was so great to me, that I could not for several days get over it;
and one day while I was musing in my mind on those things relating to the doctor,
it was opened to me that God and his servants were clear,
and his blood was on his own head; for he had been faithfully warned of his evil ways.

We were obliged by contrary winds to put into Plymouth harbour,
and from Plymouth I went by coach to London,
where I was gladly received by my relations and friends.
I got to the yearly meeting of Friends in London, in the year 1699, which was large,
and was at divers public meetings for the worship of Almighty God.
'`I may truly say, the Holy Ghost was amongst us, blessed be God our Saviour,
forevermore.
