== Chapter II

In this year I thought it my place to enter into a married state,
and I acquainted my father of my design,
and that I inclined to make choice of Martha Betterton, a religious young woman,
whom I entirely loved for the piety, virtue and modesty, which I beheld in her.
I was in the twenty-fourth year of my age, and she in her twenty-first.
I likewise acquainted her father and mother with my intentions,
to which both our parents consented; her father saying, when I spoke to him,
the Lord bless you together.
And my father said, if I was worth my weight in gold, she deserved me.
The heartiness of both our fathers in this matter,
was more to me than a portion of silver or gold, of which we had but very little;
but our love to each other was very great, and being honourably grounded,
it was not easily shaken.
We proposed our intentions of marriage to the monthly meetings to which we belonged;
and because I had been travelling in America, I had certificates from my brethren there,
not only of my industry and labour in the ministry, with the good effects thereof,
but also of my clearness in relation to marriage.
After having twice published our intentions,
we had liberty of the said meeting to proceed to the solemnization of our marriage,
which was accomplished at Devonshire-house, in London,
at a meeting appointed for that end, on the 28th day of the seventh month,
in the aforesaid year, in the presence of many hundreds of people,
and many worthy brethren and elders.
A day of days it was to my soul! wherein I was made sensible
of the love and goodness of God in a particular manner,
which to me was an earnest of our future well doing.
My dear wife was one who truly loved and feared God,
and had an excellent gift of the ministry given unto her, and was serviceable therein.

+++[+++A paper coming to my hands of her own hand writing and composing, I transcribe it here.
She calls it, An account of the Exercise of Martha Betterton,
viz. "`As I was walking in the city of London, with a concern on my mind,
in beholding the abominable pride of the people; it opened upon my mind in this wise:
Woe, woe! to the crown of pride!
And then I was deeply bowed in my spirit before the Lord, and it was said to me,
I will yet spare a little longer.
I have sheep which I will gather home to me,
and there shall be one Shepherd and one sheepfold.
Then I said in my heart.
Oh!
Lord, shall I be one of the sheep belonging to thy sheepfold of eternal rest?
And again it was answered me, My sheep hear my voice, and they follow me.
Then a cry was raised in me, Cause me to hear thy voice; and not only so,
but enable me to obey the same.
And then this charge was returned to me, Be thou faithful.`"]

Soon after I was married, I had a concern to visit Friends in the counties of Surry,
Sussex and Kent, which I performed in about two weeks time,
and came home and followed my calling, and was industrious therein.
When I had gotten something to bear my expenses,
and settle my wife in some little business,
I found an exercise on my spirit to go over to Ireland,
to visit our friends and brethren on that island,
in which William Townshend accompanied me,
and Friends in that nation were generally satisfied with our service among them.
When we had been from home about ten weeks, and had visited most parts of that nation,
having had many meetings among Friends and others,
we found freedom in our minds to return home, which we did,
being comforted in our service, and blessed the name of the Lord.

After some few months, I acquainted my wife and my father, with her father and mother,
that I thought it my duty to go over and live in America.
To which proposal my father consented, though with tenderness of heart,
considering that I must be so far separated from him.
I also laid it before the monthly meeting of Friends, at Horslydown, in Southwark,
of which meeting I was a member; they consented to it,
though somewhat unwilling to part with us, and gave us their certificate,
to let our brethren know that we were in love and unity with them,
and walked according to our profession.
When we were ready, and in order for going,
we agreed for the freight of our goods and servants, with John Snowden,
and shipped them on board the __Josiah,__ bound for Maryland.
When the ship was at Gravesend, and ready to sail,
several of our dear relations and friends accompanied us to the ship,
on board of which we had a good meeting, and took our solemn leave of one another,
as expecting never to see each other any more in this world.
It was a solemn time indeed!
We prayed for one another, and so parted, our ship sailing that evening,
and we got to Margate-road, where we anchored, and the wind sprung up very fresh,
and blew tempestuously, so that we broke our cable, and lost our best bower anchor,
and drove violently towards the Goodwin Sands.
We let go our sheet anchor and three more, which were all we had,
but they did not stop her;
upon which the master ordered the carpenters to stand by the mainmast,
with their axes upon their shoulders, and when he gave the word,
they were to cut the mast.
The people in the ship, there being many passengers, were in great consternation,
expecting nothing but death: but for my part, being exceedingly sea sick,
and having been in many storms, I was not so much surprised with this,
the sailors sometimes making a great noise when there is but little danger;
but there was more danger than I was aware of, as appeared afterwards.
One of the passengers came weeping, and said our case was very bad.
The doctor also came in the same manner; and cried,
Oh!
Mr. Chalkley, we are all dead men!
I thought with myself, I would go out on deck, and see what the matter was.
I went to the pilot, who had the lead in his hand; he sounded, and cried out.
Lord, have mercy upon us! she is gone, she is gone,
she is gone! by which I perceived that we were very near the Goodwin Sands,
on which many ships have been lost with all their crews.
In this sense of danger, I sent for the passengers into the cabin,
and told them that I thought it would be well for us to sit still together,
and look unto, and wait upon God, to see what he would please to do for us; that,
if death came, we might meet him in as good a frame of mind as we could,
and that we might not be surprised beyond measure.
As we were thus composed in our minds, a concern came upon my dear wife,
and she prayed to God, the Father, in the living power and sense of his Son;
and he heard from his holy habitation, and answered the prayer:
for immediately after the wind abated, and our anchors held us.
This was a great deliverance, which is not to be forgotten.
When we saw the longed for morning,
we were very near the sands and the sea ran prodigiously high,
and broke upon them mightily, so that we were forced to leave our cables and anchors,
and make the best of our way to Deal, as well as we could.

One of the owners being on shore, and seeing us in distress,
sent off a cable and anchor to us;
and we anchored before Deal with our new cable and anchor,
and sent a boat for our other anchors and cables, when it was calm,
which brought them to us.
After we had supplied ourselves with what we wanted, we put to sea again,
and had fair winds till we got as far as the Western islands, where captain Cant,
being in company with us, spoke with our captain in the evening,
and the two captains concluded it would be stormy that night, which happened accordingly.
They took in their sails, and we all but our mainsail; notwithstanding which,
the storm was such, that we lost our main-mast, sprung the head of our fore-mast,
and broke our crossjack-yard, and thus lay rolling upon the sea for about two weeks:
the ship Bristol-merchant coming by in that time, lent us a spare top-mast,
of which we made a main-mast, and a top-mast of our top-gallant-mast,
and so refitted as well as we could, and had a pretty good passage afterwards.
We were about eight weeks from the Land`'s End to the capes of Virginia;
had meetings twice a week on board, and they helped to stay our minds on our Maker,
though our bodies were tossed to and fro on the mighty waters.
We went on shore at Patuxent river, and by land to Herring bay,
where my family tarried that winter; and I with my three servants followed my calling.
In the spring we transported ourselves, our goods and servants,
from Maryland to Pennsylvania, where we intended to settle,
when we came from our native country.

At Philadelphia I bought a lot of ground upon the river Delaware,
and there I followed my calling that summer.
In the fall I had an inward call to visit Friends in Barbados,
which I proposed to our monthly meeting,
and they certified on my behalf that they had unity with me in my proposal,
conversation and ministry.
I took ship at Philadelphia, about the 20th of the seventh month, 1701,
on board the Abraham, Street, commander, and was about a month on the voyage;
Josiah Langdale was with me.
We had several good meetings in the ship to our satisfaction; and were well received,
and had many meetings at Barbados, which were often very large and open,
and some of the people loving and tender.
We had several meetings at Bridge-town, Speight`'s-town, the Spring, the Thickets,
and at Pumpkin-hill; and after being there about six weeks,
we went in a sloop to Bermuda, where we found but very few Friends,
yet had meetings in several places,
and at the houses of some people who were not of our profession.
The longer we tarried, the larger our meetings were;
and many began to be affected and spoke well of us and our devotion,
but some were disturbed, and spoke to the governor to break up our meetings;
which at the desire of one of the inhabitants we had appointed at his house:
upon which he sent orders by one of his colonels to break up our meeting,
which troubled the sober people.
After this I met with the governor at the house of one judge Stafford;
and he being a moderate man, we had the following discourse, viz.

[.discourse-part]
_Governor:_ How do you like our country?
We are but a little spot in the sea.

[.discourse-part]
_T+++.+++ Chalkley:_--I like it well for its moderate climate.
If the people were moderate also, it would be well.

[.discourse-part]
_Governor:_ Doth it answer your end in coming?

[.discourse-part]
_T+++.+++ Chalkley:_ My end in coming, was to visit the people in Christian love.

[.discourse-part]
_Governor:_ Do you think the people will be brought over?

[.discourse-part]
_T+++.+++ Chalkley:_ If they are brought to truth and righteousness, it will be well for them.
That is the end of our coming.

[.discourse-part]
_Governor:_ If you had acquainted me with your design, when you first came,
you had done well.
It was your duty.

[.discourse-part]
_T+++.+++ Chalkley:_ If we had known the governor`'s will herein,
or that thou wouldest have spoken with us, we should have readily answered it:
but knowing nothing of it,
we could not tell but that it might be taken for rudeness in us,
considering our homely way and manner of addressing such men.

[.discourse-part]
_Governor:_ Then your design in coming here was to preach.
Had you no other end?

[.discourse-part]
_T+++.+++ Chalkley:_ Yes.
As we found a concern upon us to preach, and a desire in the people to hear.

[.discourse-part]
_Governor:_ Why do you not tarry with them?
that looks strange.
Here the people are affected with you, and you go away and leave them:
I blame you for that.

[.discourse-part]
_T+++.+++ Chalkley:_ We do not direct them to men, but to the Lord Jesus Christ, their teacher,
and the bishop of their souls.
And why should our leaving them look strange to the governor?
It was the practice of the apostles of our Lord Jesus Christ,
and his own practice and command to his followers.
And further, the apostles (which word signifies ambassadors or messengers) say,
follow us, as we are followers of Christ.
They travelled up and down the world preaching the gospel;
and our great Lord himself had not whereon to lay his head.

[.discourse-part]
_Governor:_ The apostles were inspired men;
inspired by the Holy Spirit to preach the gospel.
I suppose you do not pretend to be inspired.

[.discourse-part]
_T+++.+++ Chalkley:_
Every true Christian ought to pray for the pouring
out of the Holy Spirit or Holy Ghost upon him.
The church of England^
footnote:[Of which church the governor was a member.]
also prays for it, the receiving of which is inspiration.

[.discourse-part]
_Governor:_ Your reasons being grounded on Scripture, you are well grounded;
for no man can deny the Scriptures.
Then you say you are inspired?

[.discourse-part]
_T+++.+++ Chalkley:_ I hope I am.
I pray for it with great earnestness.

[.discourse-part]
_Governor:_ Then it is but ask, and have, you think.

[.discourse-part]
_T+++.+++ Chalkley:_ If we ask in faith, without wavering, we shall receive,
according to the doctrine of Christ and his apostles in the New Testament.

[.discourse-part]
_Governor:_ Well, if any have a desire to hear you, you may preach and welcome.

[.small-break]
'''

After I had this discourse with the governor, it was reported on the island,
that he had given us a license to preach, which report was not true,
further than the aforesaid discourse, and then we had larger meetings than before.
We had a meeting at judge Stafford`'s house, and one at a house not far from his.

It is observable, that this island hath formerly been a very healthy and fruitful place.
Red-cedar, or sweet-wood, is all the timber they have,
with which they build their houses, make their household goods,
build their ships and sloops, and make their fires;
so that there is continually a fragrant and pleasant smell,
which we could smell at sea sometime before we saw the land;
and it is yet a pretty healthy and fruitful island, but not so much so as formerly.
In one of the meetings I was concerned to let them know,
that it was the evil of their ways and doings that had caused
the Almighty to withhold from them the fruits of the earth,
and to make their island more unhealthy than it was formerly.
After meeting, the judge told me I had said truly, for that was the cause;
and if I had spoken more on that subject, I had done well.
Several were convinced at this time on the island.

Soon after, an opportunity offered, in a sloop belonging to this island,
bound for Philadelphia, and being clear we embarked in her,
and on our voyage had pretty good weather, only one hard gale of wind,
which caused us to hand our jib.
A mulatto man named Stavo, the master`'s servant,
went out upon the bowsprit to hand the sail, and there came a sea and washed him off;
and the vessel ran over him; and in all probability, he had been drowned,
had he not been a good swimmer; for he swam, as we judged, three quarters of a mile,
before he got to the sloop, it not coming into any one`'s mind to lower the sails,
until I sharply ordered it to be done, which they then did readily;
and the course of the vessel being stopped, he soon got on board,
having stripped himself of his clothes in the sea, and brought them in his mouth.
I was very thankful for the poor fellow`'s life,
and praised the Lord in the secret of my soul for his preservation.
In about two weeks time we arrived at Philadelphia,
and I had great peace in my labours in this visit,
in which I was from home about five months.
The Friends of Barbados were so well satisfied with this labour of love,
that they certified the same by way of certificate,
more than is proper for me to mention.
But though they thought so well of me, yet I had occasion to think very meanly of myself,
for I was emptied at times to exceeding great spiritual poverty.

After I came home from Barbados and Bermuda, I followed my calling,
and kept to meetings diligently; for I was not easy to be idle,
either in my spiritual or temporal calling.
At times I travelled in the work of the ministry in our own province,
in which there are many large meetings of Friends,
and they increase and multiply from time to time.
Since my settling in this province, which is now about a year,
some hundreds of people are come here to reside, and many meeting houses are built;
and I do certainly know from above that this province of Pennsylvania,
and city of Philadelphia, will flourish both spiritually and temporally,
if the inhabitants will love and live in righteousness, and in the fear of God;
otherwise the hand that planted them can soon pluck them up.
After some time, I was drawn forth to visit Friends in Maryland, Virginia,
and North Carolina, and went with the unity of Friends, having their certificate;
according to the good order established among us.
About the 26th of the first month 1703, I went through Maryland,
and visited Friends in Virginia and North Carolina, to the river Pamlico,
where no travelling, public Friends, that ever I heard of, were before,
and we had several meetings there on each side of the river.
One day going out of our canoe through a marsh, I trod on a rattle-snake,
which is accounted one of the most poisonous snakes but it only hissed at me,
and did no harm.
This was one deliverance, among many, which the Lord, by his providence, wrought for me;
and I bless his holy name for all his mercies.

In going to, and coming from this place, we lay two nights in the woods,
and I think I never slept better.
It was the eighth hour in the evening, when I laid down on the ground, one night,
my saddle being my pillow, at the root of a tree,
and it was four o`'clock in the morning when they called me.
When I awoke, I thought of Jacob`'s lodging on his way to Padan Aram,
when he saw the holy vision of angels, with the ladder, whose top reached to heaven.
Very sweet was the love of God to my soul that morning,
and the dew of the everlasting hills refreshed me.
I went on my way, praising the Lord, and magnifying the God of my salvation.
In this journey I met with another remarkable deliverance;
going over a river eight miles broad, there being eight men and seven horses,
we put the horses into two canoes tied together,
so that they stood with their fore feet in one, and their hind feet in the other.
It was calm when we set out, but when we were about the middle of the river,
the wind rose, and the seas ran high, and split one of the canoes,
so that with our hats we were obliged to cast out the water; and with much difficulty,
at last, all of us, with our horses, got safely on shore,
through the good providence of God.
On our return through North Carolina, we had several large meetings,
and an open time it was; as also at Nancemond and Chuckatuck,
and several other places in Virginia.
When my service was over in those two provinces, I went back to Maryland,
and visited meetings there, and then went home.
As nearly as I can compute, I rode about a thousand miles in this journey;
after which I stayed at home, following my business,
in order to the maintenance of my family, being blessed with a wife, children, servants,
and other things; for which I am truly thankful.

While I was at home I visited the neighbouring meetings, as I found a concern on my mind;
and on the 6th day of the third month, 1704,
I laid before our quarterly meeting of ministers and elders,
an exercise that was upon my mind, to visit our Friends`' meetings on Long island,
Rhode Island, in New England, and the places adjacent.
They gave me a good certificate, which I thought it my duty to endeavour to live up to;
and being accompanied by several Friends to Burlington and Crosswicks,
and Joseph Glaister being my fellow-labourer in the work of the gospel;
at the two aforesaid places we had meetings,
and then travelled to New York and Long island, where we had divers meetings;
as at Flushing, Westbury, Jerusalem, Jericho, Bethpage, Matinicock,
and also at West Chester, on the main.
From thence we travelled to Rhode Island yearly meeting,
which was large and serviceable to many.
Joseph Glaister then went towards Boston, the inland way, and I went by the seaside;
and we met together, after I had been at meetings at Dartmouth and Nantucket island,
at which island there are large meetings, the people being mostly Friends,
and sober and growing in the best things.
Though not of our society when they first received the truth,
yet they received it with gladness;
and although the people called Presbyterians were very cruel in their expressions,
and bitter in their spirits against us, yet there were others who went under that name,
who were more open and charitable towards us, and received us gladly with tenderness;
and at some places we had meetings at their houses to our mutual satisfaction.
We likewise had meetings at Suckanuset, Scituate, and Sandwich.

About this time the Indians were very barbarous in the destruction of the English inhabitants,
scalping some, and knocking out the brains of others, men, women, and children,
by which the country was greatly alarmed, both night and day;
but the great Lord of all was pleased wonderfully to preserve our friends,
especially those who kept faithful to their peaceable principle,
according to the doctrine of Christ in the holy Scriptures,
in his excellent sermon which he preached on the mount, recorded in the 5th, 6th,
and 7th chapters of Matthew, which is quite opposite to killing, revenge,
and destruction, even of our enemies.
Because Friends could not join with those of fighting principles and practices,
some were put into prison; divers people railing,
and speaking very bitterly against their peaceable neighbours,
and wishing the Quakers might be cut off.

Some of the New England priests and professors were so bitter against Friends,
that instead of being humbled, under the mighty hand of God upon them,
in suffering the Indians to destroy them,
they expressed their enmity against the poor Quakers,
on a day appointed for humiliation and a fast;
and particularly in a sermon preached by one of their priests,
which he divided into three heads, viz. First, That the judgments of God were upon them,
in letting loose the savage Indians to destroy them.
Secondly, In that he withheld the fruits of the earth from them,
for there was a great scarcity.
Thirdly, That the Quakers prevailed, and were suffered to increase so much among them;
which he said, was worse than the Indians destroying them,
and gave this absurd reason for it; the Indians destroy our bodies,
but the Quakers destroy the soul.^
footnote:[This priest was soon after killed by the Indians, as I was told by a minister.]
This is an abominable falsehood; for it is sin that destroys the soul;
and those who preach to the people that there is no freedom from it in this world,
contradict Christ`'s doctrine, "`Be ye perfect,`" etc. and that of the apostle,
"`He that is born of God cannot sin.`"
And thus their blind guides mistake light for darkness, and darkness for light.
Among the many hundreds that were slain, I heard but of three Friends being killed,
whose destruction was very remarkable, as I was informed; one was a woman,
the other two were men.
The men used to go to their labour without any weapons, and trusted to the Almighty,
and depended on his providence to protect them,
it being their principle not to use weapons of war, to offend others,
or to defend themselves.
But a spirit of distrust taking place in their minds,
they took weapons of war to defend themselves; and the Indians,
who had seen them several times without them, and let them alone, saying,
"`They were peaceable men, and hurt nobody,
therefore they would not hurt them;`" now seeing them have guns,
and supposing they designed to kill the Indians, shot the men dead.
The woman had remained in her habitation,
and could not be free to go to a fortified place for preservation, neither she, her son,
nor daughter, nor to take thither the little ones;
but the poor woman after some time began to let in a slavish fear,
and advised her children to go with her to a fort not far from their dwelling.
Her daughter being one who trusted in the name of the Lord,
the mighty tower to which the righteous flee and find safety,
could not consent to go with her;
and having left a particular account in a letter to her children of her and their preservation,
I think it worthy to be inserted here in her own words; viz.

[.embedded-content-document.letter]
--

When the cruel Indians were suffered to kill and destroy, it was shewn me,
that I must stand in a testimony for truth, and trust in the name of the Lord,
who is a strong tower, and that we should wait upon him.
I often desired my mother and husband to sit down and wait upon the Lord,
and he would show us what we should do.
I could not prevail with him, but he would say it was too late now,
and was in great haste to be gone; but I could not go with him,
because I was afraid of offending the Lord.
Still he would say I was deluded by the devil, so that my mother would often say,
"`a house divided could not stand;`" and she could not tell what to do.

Although she had most peace in staying, yet she had thoughts of moving, and said to me,
"`Child, canst thou certainly say it is revealed to thee that we should stay; if it be,
I would willingly stay, if I was sure it was the mind of God.`"
But I being young, was afraid to speak so high, and said, mother,
I can say it is thus with me,
that when I think of staying and trusting in the name of the Lord,
I find great peace and comfort, more than I can utter,
with a belief that we shall be preserved; but when I think of going,
Oh! the trouble and heaviness I feel, with a fear some of us should fall by them!
And my dear mother sighed, and said, "`She could not tell what to do.`"
I said to them, if they would go, I would be willing to stay alone;
if they found freedom, I was very willing, for I was afraid of offending the Lord.
But still my poor husband would say, "`I took a wrong spirit for the right.`"
And he would say, "`How should I know?
For if I was right, I would be willing to condescend to him.`"
Then I said, in condescension to him I would move;
but I hoped the Lord would not lay it to my charge, for was it not to condescend to him,
I would not move for the world, and after I had given away my strength,
in a little time there came men from the garrison, with their guns, and told us,
"`They came for us,`" and said, "`The Indians they thought,
might be near;`" and then away we went, and my mother went in with my brother-in-law,
although I persuaded her not to do it.
But she said, "`Why, my child is there; and may not I be with her as well as thee?`"
And so we went along to Hampton, to my husband`'s brother`'s. But,
Oh! the fear and trouble I felt! and I told my husband it
seemed as if we were going into the mouths of the Indians.
The next day was the first of the week; and our dear friend, Lydia Norton,
came with my dear mother; and in her testimony,
she said there was there that was very near to her life, who was very near to death.
Oh! then I was ready to think it would be me,
because I believed we had done amiss in moving, and great trouble was I in,
and told dear Lydia of it; but she comforted me as much as she could, and said,
"`She did not think it would be me.`"

My dear mother went to my sister`'s again, to the garrison,
where she found herself not easy; but as she often said to many,
she felt herself in a beclouded condition,
and more shut from counsel than ever she had been since she knew the truth.
Being uneasy, she went to move to a friend`'s house who lived in the neighbourhood;
and as she was moving, the bloody cruel Indians lay by the way, and killed her.
Oh! then how did I lament moving;
and promised if the Lord would be pleased to spare my life, and husband, and children,
and carry us home again, I would never do so more.
But, Oh! the fear, and trouble, and darkness, that fell upon me,
and many more at that time! and three or four of us kept our meeting:
but although we sat and waited as well as we could,
yet we sat in a poor beclouded condition, until we returned home again,
then did the Lord please to lift up the light of his love upon our poor souls.
Then I told my husband, although he had built a little house by the garrison,
I could not move again.
So he was willing to stay while the winter season lasted,
but told me he could not stay when summer came, for then the Indians would be about;
and told me, that if I could not go to the garrison,
I might go to a friend`'s house near it.
I was willing to please him, if the Lord was willing;
and applied my heart to know the mind of truth, and it was showed me,
that if I moved again, I should lose the sense of truth,
and should never hold up my head again.
Then I told my husband, he must never ask me to move again for I durst not do it.
Still he would say it was a notion, till our dear friend Thomas Story came, and told him,
"`He did not see that I could have a greater revelation than I had.`"
He satisfied my husband so well, that he never again asked me to go,
but was very well contented to stay during all the wars;
and then things were made more easy,
and we saw the wonderful works and the mighty power of the Lord,
in keeping and preserving us, when the Indians were at our doors and windows,
and at other times.
And the Lord put courage in you, my dear children; do not you forget it,
and do not think that you were young, and because you knew little, so you feared nothing,
but often consider how you stayed at home alone, when we went to meetings,
and how the Lord preserved you, and kept you, so that no hurt came upon you.
I leave this charge upon you, live in the fear of the Lord,
and see you set him always before your eyes, lest you sin against him.
If I had not feared the Lord, and felt the comforts of his holy Spirit,
I could never have stood so great a trial, when so many judged,
and said that I was deluded, and that the blood of my husband and children,
would be required at my hands; but the Lord was near to me,
and gave me strength and courage, and faith to trust in him,
for I know his name to be a strong tower, yea, and stronger than any in the world;
for I have oftentimes fled there for safety.
Oh! blessing, and honour, and everlasting high praises, be given to the Lord,
and to his dear Son, our Saviour and mediator, Christ Jesus.
Amen.

[.signed-section-signature]
Mary Doe.

--

A neighbour of the aforesaid people told me, that as he was at work in his field,
the Indians saw and called him, and he went to them.
They told him, they had no quarrel with the Quakers, for they were a quiet,
peaceable people, and hurt no body, and that therefore none should hurt them.
But they said, that the Presbyterians in these parts had taken away their lands,
and some of their lives, and would now, if they could, destroy all the Indians.

Those Indians began about this time to shoot people down as they went along the road,
and to knock them in the head in their beds, and very barbarously murdered many.
We travelled the country, and had large meetings,
and the good presence of God was with us abundantly,
and we had great inward joy in the Holy Ghost in our outward jeopardy and travels.
The people generally rode and went to their worship armed,
but Friends went to their meetings without either sword or gun,
having their trust and confidence in God.

After having had divers good meetings in those eastern parts of New England,
I returned to Salem, Lynn, Boston, and so towards Rhode Island, and at adjacent places,
as in the Narraganset country; we had meetings also, at Dartmouth, Sandwich,
and Scituate.
As I was entering into the town of Boston, in company with many others,
a man rode up to me, and asked in a scoffing manner,
"`Whether I saw or met with any Quakers on the road?`"
I pleasantly told him, we should not tell the Presbyterians, lest they should hang them.
He not thinking of such an answer, went sneakingly away.

Having thoroughly visited Friends in those parts, in company with my friend Thomas Story,
I travelled through Connecticut government, and had several meetings in that colony;
and came to Long island,
where we had meetings to the satisfaction of ourselves and Friends.
From Long island,
after we were clear of the service and exercise of the work of the ministry,
and had visited Friends`' meetings as we travelled,
and in many places found openness among the people who were not of our profession,
who sometimes came in great numbers to our meetings,
and several were convinced in a good degree, and many comforted,
strengthened and edified, in Christ our Lord, we came to Philadelphia,
the place of our habitation.
Let his name, saith my soul, have the praise of all his works forever.

After being at home some time, I visited Friends`' meetings in our county,
and several parts of New Jersey, Maryland, and the lower counties on Delaware.
At Jones`' I appointed a meeting at a public house near the courthouse.
General notice being given thereof, there came one +++______+++ Crawford, a priest,
with many of his hearers, and in the beginning of the meeting he read a sermon,
as they called it, which was a transcript of the works of some of our adversaries,
which we desired to have from them to answer.
They said, "`If I would answer it myself I should have it.`"
I told them I should, if they would let me have it; but though they promised it,
they did not perform, but were worse than their word.
We heard them read it patiently; and after they had done, had our meeting.

The auditory was large, and most of the magistrates were at it.
The priest`'s reading, and my testimony, occasioned this meeting to hold long;
after which, as we were getting on horseback, the priest cried out among the people,
"`That he did not think we would go away so sneakingly.`"
We having twenty miles to ride that night, and he near his home,
and having the advantage in that respect, some thought it made him the bolder,
for he let me get on horseback before he uttered that expression.
I told him to challenge was enough to set a coward to work, and we were no cowards;
for he knew we could venture our lives for our religion,
which I questioned whether he would do for his.
I dismounted, and he having the Bible open in his hand, I being near him, chanced,
against my will and knowledge, to touch it with my foot.
"`Look you, gentlemen,`" says he, "`he tramples the word of God under his feet.`"
For which gross abuse, his own hearers openly rebuked him, and put him to shame.
Then he said, "`He would prove us no ministers of Christ.`"
I bid him prove himself one, and he would do the business, "`Well,`" says he,
"`how shall we know who are Christ`'s ministers?`"
Why, said I, art thou willing to be tried by Christ`'s rule,
for he hath given us a plain rule to know them by.
"`What is that rule?
let us hear it,`" says he.
It is short, but full, namely, "`By their fruits you shall know them;
for men do not gather grapes of thorns,
nor figs of thistles:`" wherefore by their fruits they are known.
"`I deny it,`" says priest Crawford, for that was the name he went by here,
he going by another elsewhere, "`that they are known by their fruits.`"
I answered, then thou deniest the plain and naked truth of Christ.
So I called aloud to the people to take notice what a blind guide they had;
and indeed he was wicked, as well as blind, and his fruits not good;
which may make one suppose that he was not willing to be tried by his fruits.
For soon after news came that he had a wife in England, and as he had another here,
his fruits were wicked with a witness; and according to Christ`'s doctrine,
no good could spring from his ministry, therefore he proved himself by his evil deeds,
to be no minister of Jesus Christ.
Near the aforesaid place we got a meeting settled, which is called Little-creek meeting;
and about the same time a meeting was established,
and a meetinghouse built at Duck-creek.
The people in those parts about this time began mightily to see
through the formal preaching of such as preach for money,
who love the hire, though they do not love to be called hirelings.

In the year 1706, having some concerns in the province of Maryland,
I had divers meetings as I travelled on the road, as at Nottingham, Elk river,
North-east, Susquehanna, Bush and Gun-powder rivers;
at some of which places I do not know that there had been any meeting before.
At one of these meetings were one Edwards a priest, and a lawyer, the attorney-general,
and several justices of the peace.
The priest was angry, and said, "`It was an unlawful assembly,
the house not being licensed by law,`" The justices told him,
"`That he and his people being there to hear,
if any unwarrantable or false doctrine was preached,
he had a fair opportunity to lay it open before all the people.`"
So they desired him to hear patiently and quietly.
He seemed to like the proposition, and sat down by me.
We had not sat down long before I stood up, and spoke to the people a considerable time.
The lawyer sat opposite to me, and took what I said in short hand,
for about half an hour; but growing weary, he laid down his pen,
and took out of his pocket a bottle of liquor, or spirits, and said, "`Come friend,
here is to thee (or you) you have spoken a great while,
you need something to refresh you,`" I made a stop, and said to the people,
here is your minister, and here is some of the fruits of his ministry,
of which he and all sober people may be ashamed.
And then went on again without any opposition till I had done;
but afterwards they were in a rage, and threatened what they would do to me,
if ever I came there again to have a meeting.
But I told them if they had power to take our lives from us,
they were not dear to us for the sake of Christ and his gospel;
and that we did not regard their threatenings.
I desired the lawyer to give me a copy of what he had written; he went about it,
but did not do it; neither was he candid in penning my words;
for several of the people then present bore witness that he had not written it verbatim,
or truly taken the sense of what I spoke.
I charged him to be just, otherwise he had many witnesses against him;
at which the priest bent his fist, and held it up to me, but did not strike me,
and away they went in a fret.
Soon after we had another meeting at the same place, which was large and quiet.
The man of the house being an attorney at law, had got his house licensed,
and though the priest and lawyer threatened hard, they came not.

Aquila Paca, high-sheriff of the county, living at the head of Bush river,
near the main road, built a meetinghouse, at his own charge, and had it licensed,
at which we had many good meetings.
About this time also a meetinghouse was built at a place called Nottingham,
which is a large meeting, and greatly increases.

When I was travelling in those parts,
I had a concern on my mind to visit the Indians living near Susquehanna, at Conestoga,
and I laid it before the elders of Nottingham meeting,
with which they expressed their unity, and promoted my visiting them.
We got an interpreter,
and thirteen or fourteen of us travelled through the woods about fifty miles,
carrying our provisions with us, and on the journey sat down by a river,
and spread our food on the grass, and refreshed ourselves and horses,
and then went on cheerfully, with good will and much love to the poor Indians;
and when we came they received us kindly, treating us civilly in their way.
We treated about having a religious meeting with them, upon which they called a council,
and were very grave, and spoke one after another, without any heat or jarring;
and some of the most esteemed of their women do sometimes speak in their councils.
I asked our interpreter why they permitted the women to speak in their councils?
His answer was, "`That some women are wiser than some men.`"
Our interpreter told me, that they had not done any thing for many years,
without the counsel of an ancient grave woman; who, I observed,
spoke much in their council; for I was permitted to be present at it;
and I asked what it was the woman said?
He told me she was an empress; and they gave much heed to what she said amongst them;
and that she then said, "`She looked upon our coming to be more than natural,
because we did not come to buy, or sell, or get gain,
but came in love and respect to them,`" and desired their well-doing both here and hereafter;
and further continued,
"`That our meetings among them might be very beneficial to their
young people,`" and related a dream which she had three days before,
and interpreted it, viz: "`That she was in London,
and that London was the finest place she ever saw, it was like to Philadelphia,
but much bigger, and she went across six streets,
and in the seventh she saw William Penn preaching to the people,
which was a great multitude, and she and William Penn rejoiced to see one another;
and after meeting she went to him,
and he told her that in a little time he would come over and preach to them also,
of which she was very glad.
And now she said her dream was fulfilled,
for one of his friends was come to preach to them.`"
She advised them to hear us, and entertain us kindly; and accordingly they did.
Here were two nations of them, the Senecas and Shawanese.
We had first a meeting with the Senecas, with which they were much affected;
and they called the other nation, viz., the Shawanese,
and interpreted to them what we spoke in their meeting, and the poor Indians,
particularly some of the young men and women, were under a solid exercise and concern.
We had also a meeting with the other nation, and they were all very kind to us,
and desired more such opportunities; the which,
I hope divine Providence will order for them, if they are worthy thereof.
The gospel of Jesus Christ was preached freely to them, and faith in Christ,
who was put to death at Jerusalem, by the unbelieving Jews;
and that this same Jesus came to save people from their sins,
and by his grace and light in the soul, shows to man his sins,
and convinceth him thereof, delivering him out of them,
and gives inward peace and comfort to the soul for well-doing, and sorrow and trouble,
for evil-doing; to all which, as their manner is, they gave public assents;
and to that of the light in the soul, they gave a double assent,
and seemed much affected with the doctrine of truth;
also the benefit of the Holy Scriptures was largely opened to them.^
footnote:[It is worthy of notice, that at the first settling of Pennsylvania,
William Penn took great care to do justice to the Indians,
and bought his land of them to their satisfaction, and settled a trade with them:
so that whereas the Indians were destructive to the other colonies,
they were helpful to Pennsylvania;
and to this day they love to hear the name of William Penn.]

After this we returned to our respective habitations,
thankful in our hearts to the God and Father of our Lord Jesus Christ.
Several of the Friends that went with me, expressed their satisfaction in this visit,
and offered themselves freely to go again on the like service.

I also was concerned soon after to visit the people about Egg-harbour and Cape-May,
and had meetings amongst them, and several meetings were settled in those parts,
and the people somewhat reformed from what they had
been before they were visited by Friends.
They told me, after a meeting we had with them,
that they used to spend the sabbath days in sporting and vanity,
until Friends came among them,
and now they meet together to worship God and his Son Jesus Christ.
At our coming amongst them, some backsliders and apostates were displeased.
One, in a very bitter spirit, called us cursed and cruel devils.
Another wrote against us.
To him I sent an answer, for which he scandalized me in one of his almanacs,
and publicly belied me in print;
which lies I swept away with [.book-title]#A Small Broom,# printed in this year, 1706,
to which I never understood that he returned any answer,
nor that he wrote against Friends afterwards,
though he had made it his practice for several years.

At Little Egg-harbour lived a Friend whose name was Edward Andrews, who,
as himself told me, had been a leader of the people into vanity and folly, as music,
dancing, etc., but the good hand of the Lord being upon him,
wrought a wonderful reformation in him,
and made him an instrument to lead people into truth and righteousness,
and gave him an excellent gift in the ministry of the gospel of Christ;
so that he was made instrumental in gathering a large and growing meeting,
most of the people thereabouts being convinced,
and a great reformation and change wrought in their conversations.
This Friend told me that when he was very rude and wild, he was mightily reached to,
at the meeting we had under the trees at Crosswicks,
so that he could not go on with his vanity as before;
after which he had strong convictions on him,
which wrought conversion in the Lord`'s time,
after he had gone through many deep inward exercises.

After these journeys were over, and I had cleared myself, I was some time at home,
and followed my business with diligence and industry,
and throve in the things of the world, the Lord adding a blessing to my labour.
Some people would tell me that I got money for preaching, and grew rich by it;
which being a common calumny cast upon our public Friends that are travellers,
I shall take a little notice of it, and leave it to posterity.
It is against our principle,
and contrary to our known practice and rule to take
money for preaching the gospel of Christ,
and publishing salvation through his name unto the people;
for according to Christ`'s command, we, receiving it freely, are to give it forth freely.
I can say, without vanity or boasting, I have spent many pounds in that service,
besides my time, which is as precious to me as to other people; rising early,
and laying down late; many days riding forty, fifty, and sixty miles a day,
which was very laborious and hard for my flesh to endure,
being corpulent and heavy from the twenty-seventh year of my age.
I can truly say,
that I never received any money or consideration on account of these services,
either directly or indirectly; and yet, if any of our ministers are necessitous or poor,
we relieve them freely, not because they are preachers, but because they are needy;
and when we have done those things, we have done but our duty:
and well will it be for those that have discharged themselves faithfully therein.
Such will, besides the earnest of peace in their own souls in this world,
have a blessed reward in the glorious kingdom of the Lord
and his Christ in that world which is to come.
It is well known that I have spent much of my time,
since I have been free from my apprenticeship, in travelling and preaching the gospel,
being out often many months, and sometimes a whole year, and more;
and at intervals I have been apt to think the time long,
till I got to my business and family;
and have at times made more haste than I should have done,
which has brought trouble on my mind, and is a trouble to me unto this day.
This may be a caution to those who travel in the work of the ministry hereafter,
not to make too much haste from the work of Christ;
and yet there ought to be discretion used; for a minister may stay too long,
as well as return too soon,
which may be perceived as we keep the eye of our mind to our divine guide.
