== Chapter III

After I had stayed at and about home for a considerable time,
a weighty concern came upon me to visit Friends in the West Indies,
and some parts of Europe, as it might please the Almighty to open my way;
and as it was to be a long travel, both by sea and land, and hazardous,
by reason that it was war time, and many privateers at sea, I settled my affairs by will,
and otherwise, that if I should not live to come home again,
things relating to my outward affairs might be done honourably and well:
for at this time, as at many others,
I can truly say I gave up my life freely for my holy Master`'s sake, and in his cause,
who said,
Go teach all nations, etc.

On the 29th of the sixth month, 1707,
I had a certificate from the monthly meeting of Friends at Philadelphia,
signifying their unity with my undertaking, and desires for my welfare;
and a tender concern was on my mind that I might live according
to what my brethren had certified concerning me.
I likewise laid my exercise before the general meeting of ministers and elders,
held for the provinces of Pennsylvania and New Jersey, on the 22nd of the seventh month,
who also signified their fellowship with my intended journey,
and recommended me to the grace of God,
and in much love and tenderness I parted with my dear and loving wife,
and my near and affectionate friends and brethren.

I had for my companion and fellow-labourer in the work of the gospel, my dear friend,
Richard Gove,
who also had the approbation and unity of Friends in this journey and undertaking.
We went on board a sloop at Philadelphia, bound for Barbados, John Knight, master,
about the 27th of the eighth month, in the aforesaid year.

After a few days sailing down the river Delaware, we put to sea,
and in about a month`'s time we came within sight of Barbados,
where we met with a privateer, which chased, and had like to have taken us;
but the good providence of God preserved us out of the hands of those enemies;
forever blessed be his name!
In this chase the seamen were uneasy, and belched out wicked oaths,
and cursed the Quakers, wishing all their vessels might be taken by the enemy,
because they did not carry guns in them; at which +++[+++evil conduct]
I was grieved, and thus expostulated with them: Do you know the worth of a man`'s life?
guns being made on purpose to destroy men`'s lives.
Were this ship and cargo mine, so far as I know my heart, I do ingenuously declare,
I had rather lose it all, than that one of you should lose his life:
for I certainly knew they were unfit to die.
Lives! say they, we had rather lose our lives than go to France.
But, said I, that is not the matter; had you rather go to hell, than go to France?
They being guilty of great sins and wickedness, and convicted in their own consciences,
held their peace, and said no more about the poor Quakers;
and when we got within gun-shot of a fort on Barbados, the enemy left chasing us.

Next morning early we safely arrived at Bridgetown, in Barbados,
where our friends gladly received us;
amongst whom we laboured in the work of the gospel for about two months.
After having had divers good and edifying meetings for the worship of God,
we sailed for Antigua, and stayed some days there,
having meetings and visiting our brethren.

From Antigua we sailed for Nevis, but the wind being contrary, we put in at Montserrat,
an isle that has a great mountain in it, on the top of which is a hot spring of water,
which boils up, and the mire of it is clear brimstone;
some of which we carried on board our vessel; which is admirable,
and shows the wonderful works of God.
They say that the spring is hot enough to boil an egg.
From this island we sailed to Nevis, and had meetings with the few Friends there,
with whom we parted at the sea shore in great love and tenderness.
We sailed to an island called Anguilla,
and were civilly treated there by the generality of the people; as also by the governor,
George Leonard, at whose house we had meetings.
I remember that after one meeting the governor went into his porch,
and took the Bible and opened it, and said, "`By this book,
if people believe the holy Scriptures, I am able to convince the world, and prove,
that the people called Quakers, are the people of God,
and that they follow the example and doctrine of Christ,
and the practices of the apostles and primitive Christians,
nearer than any people in the world;`" i. e., generally speaking.

At this island several people were heartily convinced, and confessed to the truth,
among whom a meeting was settled.
Here was never any Friend before, as the inhabitants said.
I entreat the Lord Jehovah to preserve the sincere-hearted
among them in his holy fear whilst they remain in this world;
and not them only, but all that love and fear him, in all kindreds and nations,
and amongst people of all professions whatsoever.
This, in the universal spirit of God`'s love, is the desire of my soul.
From Anguilla we went to Nevis, and to Antigua;
and notwithstanding our sloop was a dull sailer, yet we were preserved from the enemy,
to the admiration of ourselves, friends and others,
our course being in the very road of the privateers.
Just as we got into the harbour and were landed, a privateer came by with a prize,
as we supposed, which excited our thankfulness to the Lord for our preservation.
Here we met with the packet-boat bound for Jamaica, and thence for England.
We stayed a little at the island called St. Christopher`'s. In our way to Jamaica,
we saw a small privateer that gave us chase, and it being calm, she rowed up towards us.
The master prepared the vessel to light, hoisting up his mainsail,
and putting out our colours.
In the interim some were bold and some sorrowful.
One came to me, and asked, "`What I thought of it?
and of the Quakers`' principles now?`"
I told him I thought I was as willing to go to heaven, as himself;
to which he said nothing, but turned away from me.
Another asked me, "`What I would do now?`"
I told him, I would pray that they might be made better,
and that they might be made fit to die.
In the midst of their noise and hurry, I begged in secret of the Almighty, in the name,
and for the sake of his dear Son,
that he would be pleased to cause a fresh gale of M`'ind to spring up,
that we might be delivered from the enemy without shedding blood,
well knowing that few of them were fit to die.
Whilst I was thus concerned, the Lord answered my desire and prayer,
for in a few minutes the wind sprung up, and we soon left them out of sight,
our vessel sailing extraordinarily well, and the next day we got to Jamaica,
and had meetings at Port-royal, Kingston, Spanish-town, etc.

At a meeting at Spanish-town, there were some Jews, to whom my heart was very open,
and I felt great love to them, for the sake of their fathers, Abraham, Isaac and Jacob;
and they were so affected with the meeting, that they sent us some unleavened cakes,
made with fine flour and sweet oil, it being a festival time with them.
We had a meeting at Port-royal,
in a place where the earthquake had destroyed a large building,
in which meeting I had occasion to remind them of the righteous judgments of God,
which had been justly inflicted on them for their wickedness.
Some wept, and some were rude.
The people here, as I was informed, were generally very wicked.
After having had divers meetings, the packet in which we had taken our passage,
being obliged to stay but ten days,
we went off sooner than we otherwise should have done,
and solemnly taking leave of those Friends that were there, we went on board our vessel,
in order for England, by God`'s permission.
We got readily through the windward passage,
which is between the islands of Cuba and Hispaniola;
and several times after we left Jamaica, we were chased by ships,
but they could not come up with us.

One ship of twenty-eight guns gave us chase after a great storm,
and was almost up with us before we could well make sail; they being eager of their prey,
sent their hands aloft to let their reefs out of the topsails,
in order to make more speed, and came running towards us, and gained much upon us.
We feared to make sail by reason of the storm, and the sea running very high,
and our masts being in danger,
we were some time in doubt whether we should escape or not:
but whilst we were in this consternation,
down came the French ship`'s three topmasts at once; so we escaped, and left her,
and went rejoicing on our way, that we were thus delivered.
This was one of the great and remarkable deliverances among many I met with,
by the good hand and providence of the Lord, my great and good Master,
whom I hope to serve all my days.

After having been at sea about six weeks, we began to look out for land,
and in two or three days we sounded, and found ground at about ninety fathoms;
after which we saw two French privateers, who gave us chase, and pursued us vigorously;
but sailing better than they, we run them out of sight, and in about two hours after,
we saw the land of Ireland.
It being misty weather, with rain and wind,
our master thought it best to lay by and forbear sailing,
that coast being rocky and dangerous,
by which means the two ships that gave us chase came up with us,
and found us not in sailing order,
and were within gun-shot of us before we were aware of it.
What to do now we could not tell, until they began to fire at us;
but in this emergency and strait,
our master resolved he would rather run the vessel on shore than they should have her,
she being richly laden with indigo, silver and gold,
reckoned to the value of fifty thousand pounds.
In this strait, we must either fall into the hands of the French, who were our enemies,
or run among the rocks; and we thought it best to fall into the hands of the Almighty,
and trust to his providence; so towards the rocks we went, which had a terrible aspect.
The native Irish seeing us, came down in great numbers, and ran on the rocks,
and called to us, saying, "`That if we came any nearer we should be dashed in pieces.`"
Our master ordered the anchor to be let go, which brought the ship up before she struck;
and with much ado, he put his boat out into the sea, and put in all the passengers,
in order to set them on shore, the waves running very high,
so that it looked as if every wave would have swallowed us up;
and it was a great favour of Providence that we got to land in safety.
The privateers not daring to come so near the shore as we did, after firing at us,
went away, and our master carried the ship into the harbour of Kinsale, in Ireland.
Thus through many perils and dangers we were preserved,
and got safely on the Irish shore, for which,
and all other the mercies and favours of the Most High,
my soul and spirit did give God glory and praise!
In this voyage we were about seven weeks at sea.

When I came from my home at Philadelphia, I intended, the Lord permitting,
to visit Friends in Ireland, and being accidentally cast on shore there,
I thought it my place first to go through that nation.
I had been in Ireland about nine years before, and then being but young,
and now being more grown in body,
my old acquaintance and friends did not at first know me;
but we were kindly and lovingly received by our friends and brethren in that nation,
where there is a numerous people that serve and worship
the Father in spirit and in truth,
and who have good and wholesome order established amongst them,
in the unity and fellowship of the gospel.
In this nation we had many and large meetings after our landing,
visiting Friends`' meetings along to the north, many not of our Society coming to them,
among whom we often had good service, to our and their satisfaction,
as they often declared, Richard Gove being still with me.
Friends from their national meeting, certified to our brethren in America,
of our service and labour of love among them,
after we had travelled several hundred miles, and visited Friends`' meetings generally,
and some other places where it was not usual.
While I was in Ireland, under a concern for the prosperity of truth and religion,
I wrote an exhortation to the youth and others, which was afterwards printed there.

We took ship in the north of Ireland, at a town called Donaghadee,
being accompanied by divers brethren, who brought us on our way after a godly sort.
We got to Port Patrick, in Scotland, after about five hours gail,
in order to visit the few Friends that were scattered about in that part of the nation.
People in those parts looked very shy on us,
and did not care to discourse with us on matters civil or religious,
which I thought unreasonable.

The first town or city we came to, in which we had a meeting, was Glasgow,
accounted the second city in North Britain, where,
in our meeting for the worship of the Almighty, we were shamefully treated by the people,
who threw dirt, stones, coal, etc., amongst us, and by other actions unbecoming men,
though heathens or infidels, much more people professing Christianity.
I was constrained to tell them, that though I had preached the gospel to many heathens,
and to divers Jews, as also to Indians and Negroes,
and had travelled in many countries and nations in the world,
in several quarters thereof, and many thousands of miles,
yet I never met with the like incivilities and such scurrilous treatment,
not in all my travels.
I also told them,
that I had preached the gospel of Christ among their brethren in New England,
and in Boston, where they formerly hanged the Quakers,
and cruelly persecuted them for their religion,
and yet they did not treat us so brutishly even there.
And further I told them that I lived in those parts of America,
and what account I should have to carry home to their aforesaid brethren,
of our treatment in Glasgow, the second city in Scotland.
I desired them to consider of it, and be ashamed, if they had any shame.
This a little abashed them for the present, but afterwards they were as bad as ever.
There were at this meeting some collegians, who were very rude.
I asked if that was their way of treating strangers?
and that I believed their teachers in the university did not allow of such ill manners,
by which they scandalized themselves, their city and country.
From this city we went to Hamilton and Gershore, where they were more civil.
At Gershore a man of letters and sober conversation,
begged that I would pray to the Almighty,
that he would establish him in the doctrine which he had heard that day.
This being rare in those parts, I minute it here.
We went on towards the north of Scotland, to Aberdeen, and thereabouts,
where there is a tender-hearted people, among whom we had several large gatherings,
and some that were not of us, expressed their satisfaction.

In the north I met with a gentleman, who coming from a nobleman`'s house, joined me,
and asked me, "`If I knew Robert Barclay?`"
I said, not personally, but by his writings I knew him well.
He told me, "`That he (Barclay) had not left his fellow in Scotland.`"
We afterwards travelled southward, where there were but few Friends and small meetings;
yet we may say, that the goodness, love, and presence of Him, who said,
where two or three are gathered in my name, there am I in the midst of them,
was oftentimes witnessed to be with us, blessed be his holy name.
Oh! that the children of men would praise him in thought, word, and deed,
for he is worthy.
In great reverence and holy fear, we travelled along towards South Britain,
had several meetings at Edinburgh, and divers other places; also at Berwick upon Tweed,
where there were many soldiers, who were very rude.
The devil hath had many battles with us, ever since we were a people,
in order to hinder us in our worship, but we generally came off with victory,
as we did here also, through faith in his name who hath loved us,
and manifested himself to us.
Those rude soldiers throwed their hats into the congregation, in order to disturb us,
and hinder us in our service, but were at last ashamed and disappointed.

At this place my dear friend and fellow traveller, Richard Gove, and I parted.
I was going by the east seacoast up to London, and he inclined towards Cumberland.
We had travelled about a year in the work of the ministry,
in great love and true friendship, in which work we were true helpers one of another;
and as we had laboured together in the work of Christ, so we parted in his love.

From Berwick I travelled to Newcastle; had one meeting by the way,
and good meetings at Newcastle, Sunderland, Shoten, and Durham,
and several other places in the bishopric of Durham.
The winter coming on apace, it began to be bad travelling;
and I being already much spent by it, designed to go speedily up to London;
and taking some meetings in my way, as at Stockton, Whitby, Scarborough, Burlington,
Hull, and Brigg, and so on through Lincolnshire,
where I went to visit a Friend who was prisoner in the castle of Lincoln,
because for conscience-sake, he could not pay an ungodly priest the tithes of his labour.
From Lincoln I proceeded to Huntingdon, about which place we had several large meetings,
then to Baldock, where I met with my father and John Gopsil,
who came from London to meet me, which was a joyful meeting,
for I had not seen my father for about nine years.
The love and tenderness between us, and our gladness in seeing each other again,
cannot well be expressed,
but I believe it was somewhat like Jacob and Joseph`'s meeting in Egypt;
it was affecting and melting;
blessed be the Almighty that gave me once more to see my tender and aged parent!
From Baldock we went to Hitchin, and had a meeting there, as also at Hertford,
from whence, with several Friends, I went to Enfield,
where I met with my dear and only brother, George,
and several of my relations and our friends;
and we were heartily glad to see one another.
From Enfield we went to London,
and by the way we met with several Friends of the meeting of Horslydown,
to which I belonged from my childhood, who came to meet me, and accompanied us to London.

I stayed in and about the city most of the winter, visiting meetings when I was in health;
for through often changing climates, I got a severe cold, and was ill for several weeks,
so that I was not at any meeting, which time was very tedious to me;
not so much because of my illness,
as that I was deprived of the opportunities and meetings
which occur in that city every day of the week,
except the last.
When I had a little gotten over this illness,
I went into Hertfordshire and some parts adjacent, and had meetings at Staines, Langford,
Uxbridge, Walford, Hempstead, Bendish, Albans, Market street, Hitchin, Hertford, Hodgdon,
and then returned again to London.

After I had been in London a while, I visited several other country meetings,
as Winchmore-hill, Tottenham, Wansworth, Plaistow, Deptford and Epping,
and then stayed about London some weeks, waiting for a passage for Holland,
which I intended to visit before I left my own habitation.

On the 14th of the first month, 1708-9, my companion, John Bell, and I,
after having acquainted our friends and relations, and having their consent,
took our solemn leave of them and went down to Gravesend,
where we stayed two or three days for a fair wind.
We then went on board the ship _Ann,_ John Duck, master, bound for Rotterdam,
in company with a fleet of vessels waiting for wind, etc.
When the wind was fair we sailed for the coast of Holland, and when we arrived,
the wind was contrary, and blew very hard,
so that some of the ships in company lost their anchors,
but in a day or two we all arrived safely at Rotterdam, in Holland;
being but two days on the passage.
On first-day morning we went to meeting at Rotterdam, where Friends have a meetinghouse;
and we stayed at this city seven or eight days, and had six or seven meetings,
and were comforted with our brethren and sisters,
and greatly refreshed in the Lord Almighty, At this city we spoke without an interpreter,
because most in the meeting understood English.
From Rotterdam we travelled by the Trekskuyt, a boat drawn by horses,
which is a pleasant easy way of travelling, to a large town called Harlem,
where we had a meeting, and spoke by an interpreter;
to which meeting came divers of those people called Menonists:
they were very sober and attentive; stayed all the time of the meeting,
and spoke well of it.
From Harlem we went to Amsterdam, the metropolis of Holland,
where Friends have a meetinghouse.

Here we had several meetings, and stayed about a week.
On the first day we had a large meeting,
to which came many people of divers persuasions and religions, as Jews, Papists,
and others; and we had a good opportunity among them, and several were tender.
A Jew came next day to speak with us, and acknowledged,
"`That Christ was the minister of that sanctuary and tabernacle that God had pitched,
and not man; and that he was sensible of the ministry of Christ in his soul; and,
(said he) my heart was broken while that subject was spoken of in the meeting.`"
I was glad to see the man tender and reached; but too generally speaking, the poor Jews,
the seed of good Jacob, are very dark and unbelieving.
I have met with but very few of them in my travels who have been tender;
but I do love them for Abraham`'s, Isaac`'s, and Jacob`'s sake.
At this meeting, William Sewel,
the author of the [.book-title]#History of the Rise and Progress of the People Called Quakers,#
a tender-spirited, upright man, interpreted for me.

From Amsterdam we went to North Holland,
and John Claus and Peter Reyard went with us to interpret for us;
so by boat we travelled to a town called Twisk, where we had two meetings,
Friends having a meetinghouse there.
We went back again to Amsterdam, and had two large meetings on first-day;
and on second-day in the evening, we went on ship-board,
in order to cross the South Sea to Harlingen, at which place we had two meetings,
and we and Friends were glad to see one another; and, indeed,
we being as one family all the world over, are generally glad to see each other.
From this place we travelled eastward, through East Friesland,
and went through several great towns and cities, until we came to Embden,
the chief city in East Friesland,
where we had a comfortable meeting by the bedside of one of our friends who lay sick;
and several of her neighbours came in and stayed till the meeting ended;
some of them were very tender and loving, and wished us well, and were well satisfied.
After meeting we set forward for Hamburgh, it being four days journey by wagon,
and passed along through divers towns and cities:
we also travelled through the city of Oldenburg,
and a place of great commerce called Bremen.
A magistrate of this city took notice of us, joined himself to us,
and went with us to the inn, and then very lovingly took leave of us,
and desired God to bless us.
The people at our inns were generally very loving and kind to us,
and some would admire at my coming so far only to visit my friends,
without any view of advantage or profit outwardly.
When we got to Hamburgh we had a meeting at Jacob Hagen`'s, and those who were there,
were well satisfied with the doctrine of truth; blessed be God, who, I may say,
was with us at that time and place!
At Hamburgh there was at meeting one who had preached before the king of Denmark; who,
as I understood by our interpreter,
was turned out of his place for declaring the same truths that we had preached that day;
at which meeting were Papists, Lutherans, Calvinists, Menonists, Jews, etc.
All of them were sober, and generally expressed their satisfaction.
I had so much comfort in that meeting,
that I thought it was worth my labour in coming from my habitation;
the answer of peace was so sweet to my soul,
that I greatly rejoiced in my labour in the work of Christ.
From hence I travelled to Frederickstadt, it being two days journey,
where Friends have a meetinghouse.
We stayed about ten days, and had nine meetings in this city.
Some of the meetings were very large, and the longer we stayed, the larger they were.
Frederickstadt is a city in the dominions of the duke of Holstein,
and was the furthest place to which we travelled eastward;
and from thence I wrote a small piece, called,
"`A loving invitation unto young and old in Holland and elsewhere;`"
which was translated into the German and Low Dutch languages:
and divers impressions of it were also printed in England.

We travelled in this journey through some parts of the emperor of Germany`'s dominions,
as also of the kings of Denmark and Swedeland, and of the duke of Oldenburg,
and prince of East Friesland`'s territories,
besides some parts of the seven provinces of the United States.
We parted with our friends of Frederickstadt in much love and tenderness,
with our hearts full of good will one towards another,
and went back to the city of Embden, a nearer way by two days journey,
than to go by Hamburgh.
We crossed the rivers Eider, Elfe, and Weiser;
over which last we were rowed by three women.
The women in these parts of the world are strong and robust, and used to hard labour.
I have seen them do not only the work of men, but of horses;
it being common with them to do the most laborious,
and the men the lightest and easiest work.
I remember that I once saw near Hamburgh, a fair, well dressed woman, who,
by her dress and appearance, was a woman of some note,
and a man whom I took to be her husband, walking by her, and the way difficult,
being up a very steep hill, and he did not so much as offer his hand,
or give any assistance to her; which, however it might look to a man of that country,
seemed very strange to me, being a Briton.
For my part, I thought it unmanly, as well as unmannerly; on which I observe,
that I never in any other part of the world,
saw women so tenderly dealt by as our English women are,
which they ought to prize highly,
and therefore to be the more loving and obedient to their husbands;
which indulgence I blame not, but commend,
so far as it is a motive to stir them up to love and faithfulness.

In this journey between Frederickstadt and Embden, we had four days hard travelling,
and were twice overturned out of our wagons, but we received no harm,
which was admirable to us; for once we fell, wagon and all, over a great bank,
just by the side of a large ditch, and did but just save ourselves out of the ditch.
The next time we overset upon stones: we wondered that none of us were hurt,
particularly myself, I being much heavier than any of the rest;
but through the mercy of God, we got well to Embden the second time,
and had a meeting upon a first-day, and immediately after we took ship for Delfzeel,
which was from Embden about nine or ten English miles, by water,
and with a fair gale of wind, got there in less than two hours.
We spoke by interpreters all along,
and were divinely helped to preach the gospel to the satisfaction of others,
and our own comfort; and the Friend who interpreted for us,
was sensible of the same divine assistance, to his admiration,
for which we were all truly thankful.
But notwithstanding we were so opened, to the satisfaction of ourselves,
our friends and the people,
yet we were sometimes emptied to exceeding great spiritual poverty,
and in the sense of our want and need,
we did many times pour out our souls in humble prayer and supplication to the Most High,
for his help and strength, that it might be made manifest to us in our weakness;
and we found him a God near at hand, and often a present help in the needful time,
and had a sweet answer to our prayers.
O that my soul, with all the faithful, may dwell near to him,
in whom alone is the help and strength of all his faithful servants and ministers!
Amen.

From Delfzeel we went to Groeningen, the chief city in Groeningland,
and to a town named Goradick,
where we had a meeting with a few Friends and some of their neighbours.
It was to us a comfortable meeting, and they were glad of it,
being but seldom visited by Friends.
From this place we travelled by wagon to Hervine, where we lodged that night,
and next day went by wagon to Leuvvarden.
It happened that we had generally very fine weather while in those open wagons,
in which we travelled several hundred miles, so that Jacob Glaus,
our companion and interpreter, though he had travelled much,
said he never had observed the like before; which observation I thought good to make,
with thanks to the Almighty.

From the city of Leuwarden, we came by water to Harlingen,
where Friends were glad to see us, and we them.
We had a good and comfortable meeting in Friends`' meetinghouse,
blessed be the Lord for it!
From hence we crossed the South Sea, and had a contrary wind,
which made our passage long and tedious.
We were two days and two nights on this water before we got to Amsterdam, in all which,
and the next day, I tasted no food, being three days fasting.
I was willing to keep my body under, and found it for my health,
neither had I any desire for food in those three days, in which time we had two meetings.
We arrived at Amsterdam about the sixth hour on first-day morning,
and had two meetings that day, which were quiet, and many people came to one of them:
but we could not be clear without going again to North Holland.
So from Amsterdam we went to Horn,
where we had a meeting in the collegian`'s meetinghouse, and it was to satisfaction:
the people were very loving, and divers very tender, even more than we have usually seen.
They desired another meeting, but our time would not admit of it,
we having appointed a meeting at Twisk the next day, which we had in the meeting place,
as also another at a Friend`'s house.
Next day we returned to Amsterdam, and had a meeting, which began about the fifth hour,
which was the last meeting we had in this city,
and I hope it will not easily be forgotten by some.
After it we solemnly took our leave of Friends, and departed for Harlem,
where we were well refreshed in the love and life of Christ Jesus,
our dear Lord and good Master.
From Harlem we went with several Friends to Rotterdam, where we had two meetings,
and in the evening visited a Friend who was not well, with whom we had an affecting time,
and the sick Friend was comforted and refreshed,
and said she was much better than before; and we were edified,
and the Lord our God praised and magnified over all, who is blessed forever.

In those parts, viz., Holland, Friesland, Germany, etc.,
we travelled nine hundred and seventy-two English miles, all in wagons and vessels.
We came not on a horse`'s back all the time.
We stayed about nine weeks in those countries,
travelling and getting meetings where we could, which were to the number of forty-five,
thus accounted: at Rotterdam, ten; Harlem, three; Amsterdam, ten; Twisk, four; Harlingen,
three; Horn, one; Hamburgh, one; Embden, two; Frederickstadt, ten; Goradick, one.
All these are large cities, except Twisk and Goradick.

From Rotterdam we took ship for London, and on the 30th of the third month, 1709,
sailed down the river Meuse to the Briel, in the ship _Ann,_ John Duck, master,
but he missing the convoy, we took our passage in the packet;
and from Helvoetsluys sailed over to Harwich, and safely arrived in our native land,
blessing Almighty God for his many preservations and deliverances by sea and land.

About this time, after a long continuance of war, there was great talking of peace;
but the old enemy to peace, truth and righteousness,
broke it off by his evil working in man: neither can there be any lasting peace,
until the nations come to witness the peaceable government
and spirit of our Lord Jesus Christ,
set up and established in themselves.
The Lord bring it to pass, if it be his blessed will, with speed,
for his holy name`'s sake!
Amen.

As I have had great peace and satisfaction in my travels in Holland and Germany, so,
for inciting others under the like exercise, I may truly say,
that there is encouragement for faithful ministers to labour in the work of the gospel.
I know not that I ever met with more tenderness and openness in people,
than in those parts of the world.
There is a great people whom they call Menonists, who are very near to truth,
and the fields are white unto harvest, among divers of them, spiritually speaking.
Oh! that faithful labourers, not a few,
might be sent of God Almighty into the great vineyard of the world,
is what my spirit breathes to him for.

After lodging one night at Harwich, we came to Ipswich, and from thence to Colchester,
where we stayed on first-day and had two meetings;
and had a meeting at Birch and Coggeshall, and then back to Colchester,
where we took coach for London, to the yearly meeting of Friends, which was very large.
I gave a short account of my travels to the said meeting,
with which Friends were satisfied, and made a minute thereof.
I had been about twenty months from my habitation,
and from my dear and affectionate wife, and from any trade or business,
being all that time wholly given up in my mind to
preach the glorious gospel of God our Saviour,
without any outward consideration whatever, taking my great Master`'s counsel;
as I had freely received from him, so I freely gave;
and had that solid peace in my labours which is of more value than golf], yea,
than all the world.

From the yearly meeting I travelled through some parts of most of the counties in England,
and also in Wales: in which service I laboured fervently, and often travelled hard,
in body and mind, until the next yearly meeting, 1710,
having travelled that year about two thousand five hundred miles,
and had nearly three hundred public meetings, in many of which there were much people,
and oftentimes great openness.
Being at so many Friends`' houses and meetings, if I was to be particular,
it would be too voluminous, for which, and some reason beside,
I only give a general account thereof.

In this year, 1710, my dear friend and fellow traveller, Richard Gove,
departed this life at Uxbridge, about fifteen miles from London,
at our friend Richard Richardson`'s house.
He died of a consumption.
We travelled together in great love and unity, and the Lord blessed his work in our hands.
We were in company in the West India islands, Ireland, and North Britain,
till we came to Berwick on Tweed.
We met together again at London,
and he visited some other parts of Britain in the time I was in Holland and Germany.
He was an inoffensive, loving Friend, and had a sound testimony,
which was serviceable and convincing, and was well beloved in Philadelphia,
where he lived.
He left a good savour and report behind him, I think, wherever he travelled.

At this general meeting in London,
I had a good opportunity to take leave of my dear friends and brethren in my native land,
not expecting to see it, or them, any more.
Oh!
I may truly say, it was a solemn parting! a solemn time to me indeed.
After the yearly meeting was over, I took my passage in the _Mary Hope,_ John Annis master,
bound for Philadelphia; and on the 29th of the fourth month, 1710, at Gravesend,
after having taken a solemn leave of our relations, and several of my dear friends,
we set sail and overtook the Russia fleet at Harwich, joined it,
and sailed as far as Shetland, which is northward of the isles of Orkney.
We were with the fleet about two weeks, and then left it,
and sailed to the westward for America.
In this time we had rough seas, which made divers of us sea-sick.
After we left Shetland,
we were seven weeks and four days at sea before we saw the land of America,
and glad we were when we got sight thereof.
In this time we had divers sweet and solemn meetings, on first-days and fifth-days,
wherein we worshipped and praised the great Jehovah,
and many things were opened in the spirit of love and truth,
to our comfort and edification.
We had one meeting with the Germans or Palatines on the ship`'s deck,
and one who understood both languages interpreted for me.
The people were tender and wrought upon, behaved soberly, and were well satisfied:
and I can truly say, I was well satisfied also.

In this voyage we had our health to admiration;
and I shall mention one thing worthy of notice.
Some of my loving and good friends in London, fearing a sickness in the ship,
as she was but small, and considering there were so many souls on board,
being ninety-four in number, for that and other reasons, advised me not to go in her;
for they loved me well, and I took it kindly of them.
But I could not be easy to take their advice,
because I had been long from my habitation and business, and which was yet more,
from my dear and loving wife; and notwithstanding the vessel was so full and crowded,
and also several of the people taken into the ship in the river Thames,
yet they mended on board the vessel apace, and were soon all brave and hearty,
being perfectly recovered at sea, and the ship, through the providence of the Almighty,
brought them all well to Philadelphia, in the seventh month, 1710.
I think I never was in a more healthy vessel,
and I thought this a peculiar favour worthy to be recorded by me.
We had a very pleasant passage up the river Delaware, to our great satisfaction,
the Palatines being wonderfully pleased with the country,
greatly admiring the pleasantness and the fertility of it.
Divers of our people went on shore and brought fruit on board,
which was the largest and finest they had ever seen, as they said, such as apples,
peaches, etc.

I was from my family and habitation in this journey and travel,
for the space of three years, within a few weeks; in which time, and in my return,
I had sweet peace to my soul; glory to God forevermore!
I had meetings every day when on land, except second and seventh-days, when in health,
and nothing extraordinary hindered, and had travelled by sea and land,
fourteen thousand three hundred miles, according to our English account.
I was kindly and tenderly received by my friends, who longed to see me, as I did them,
and our meeting was comfortable and pleasant.

After this long travel and voyage,
I stayed at home and looked after the little family which God had given me,
and kept duly to meetings, except something extraordinary hindered.
Divers people when I came home, raised a false report of me,
and said I had brought home a great deal of money and goods, which I got by preaching.
This was utterly false and base; for I brought neither money nor goods,
so much as to the value of five pounds, except my wearing apparel.
My case was so much the reverse,
that I borrowed money at London to pay for my accommodations home,
which I faithfully remitted back again to my friend who lent it to me;
and if I might have gained a hundred pounds per annum,
it would not have tempted me to undertake that, or another such journey.
Soon after my return home, I visited a few neighbouring meetings,
which were large and edifying,
Friends being glad to see me; and I did, as I had reason to do,
bless the holy name of the Lord,
for his many preservations and deliverances by sea and land.

After some stay at Philadelphia, I went down with my wife and family into Maryland,
to a corn-mill and saw-mill, which I had there,
in order to live there some time and settle my affairs.
While there, my dear wife was taken ill of a sore disease,
and I was desirous of getting her up to Philadelphia.
She was carried as far as Chester in a horse-litter,
where she continued for some months in extreme pain,
at the house of our very kind friends, David and Grace Lloyd,
whose kindness to us in that trying and exercising time, was great,
and is not to be forgotten by me.
From Chester we removed her in a litter, accompanied by our friends, to Philadelphia,
where she continued very ill all that winter, often thinking that death tarried long,
and crying mightily to the Lord, "`Oh! come away, come away!`"
This was her cry day and night, till at last she could speak no more.
As we had lived together in great love and unity, being very affectionate one to another;
so, being now left alone, I was very solitary, and sometimes sorrowful,
and broken into many tears, in the sense of my loss and lonesomeness.
My dear wife was a virtuous young woman, and one who truly feared God,
and loved his dear Son; from whom she had received a good gift of the ministry,
and was serviceable to many therein.
I had five children by her, four sons and one daughter, all of whom I buried before her,
under three years old.
At the yearly meeting before she died,
she was so wonderfully carried forth in her ministry by divine grace,
that divers of her friends believed she was near her end,
she signifying something to that effect in her testimony,
and that she should not live to see another yearly meeting: and so it came to pass;
for she died before another yearly meeting, being aged about thirty-five years,
and a married woman about thirteen years.
Her body was carried to the meetinghouse in Philadelphia,
and buried in Friends`' burying ground,
being accompanied by many hundreds of our friends, in a solemn manner:
and my heart was greatly broken in consideration of my great loss; and being left alone,
as to wife and children, I many times deeply mourned,
though I well knew my loss was her`'s and their gain!
