== Chapter IV

I now gave up my time mostly to travelling, for about the space of two years,
in which I visited the meetings of Friends in the provinces of Pennsylvania,
East and West Jersey, Maryland, Virginia, and North Carolina, back to Philadelphia,
and then to New Jersey again: also to Long island, Rhode Island, Conanicut island,
Nantucket island, and New England, and through those parts on my return to Philadelphia.
In these journeys I travelled some thousands of miles, and had many large meetings,
some in places where there had not been any before, and some were convinced,
and many would acknowledge to the testimony of truth,
which was declared by the help and grace of Christ;
and many times by the assistance of that grace,
my heart was wonderfully opened to the people.

In Virginia I had a meeting at James`' river, where a priest of the church of England,
with some of his hearers, made some opposition after our meeting was over,
and were for disputing about religion; and he openly declared,
"`The spirit was not his guide nor rule; and he hoped, never should be.
But, he said, the Scriptures were his rule, and that there was no need of any other;
and that they were as plain as Gunter`'s line, or as one, two, three.`"
I told him the Scriptures were a good secondary rule,
and that it were well if men would square their lives according to their directions;
which we, as a people, exhorted all to: but that the holy Spirit,
from which the holy Scriptures came, must needs be preferable to the letter,
that came from it.
I also asked him, how he, or any one else,
without the light or influence of the holy Spirit, could understand the Scriptures,
which were parabolically and allegorically expressed, in many places?
And further, to use his own expression, how could any understand Gunter`'s line,
without Gunter`'s knowledge?
or without they were taught by Gunter, or some other?
Neither can we be the sons of God, without the spirit of God.
Which he answered not, but went away.

In New England, one Joseph Metcalf, a Presbyterian teacher, at Falmouth, wrote a book,
entitled, "`Legal forcing a maintenance for a minister of the gospel,
warrantable from Scripture, etc.`"
This book, a Friend of Sandwich gave me,
and desired I would answer it and finding some exercise
on my mind for the cause of truth,
I was willing to undertake it and accordingly wrote an answer thereto, which I called,
"`Forcing a maintenance, not warrantable from the holy Scriptures,
for a minister of the gospel.`" I endeavoured to
set the texts of Scripture in a true light,
which he had darkened and misrepresented, by his chimerical doctrines.

In this year, 1713, I went from Philadelphia, in the _Hope_ galley, John Richmond, master,
to South Carolina.
We were about a month at sea; and when it pleased God that we arrived at Charleston,
in South Carolina, we had a meeting there, and divers others afterwards.
There are but few Friends in this province, yet I had several meetings in the country.
The people were generally loving, and received me kindly.
What I had to declare to them,
I always desired to speak to the witness of God in the soul,
and according to the pure doctrine of truth in the holy Scriptures;
and there was openness in the people in several places.
I was several times to visit the governor, who was courteous and civil to me.
He said I "`deserved encouragement,`" and spoke to several to be generous,
and contribute to my assistance.
He meant an outward maintenance; for he would have me encouraged to stay among them.
But I told him, that though it might be a practice with them to maintain their ministers,
and pay them money for preaching,
it was contrary to our principles to be paid for preaching,
agreeably to the command of our great master, Christ Jesus, who said to his ministers,
"`Freely ye have received, freely give:`" so that we are limited by his words,
whatever others are: and those who take a liberty contrary to his doctrine and command,
I think must be antichrists, according to holy Scripture.
The longer I stayed there, the larger our meetings were;
and when I found myself free and clear of those parts,
I took my passage for Virginia in a sloop, Henry Tucker, master.
I had a comfortable and quick passage to James`' river,
it being about two hundred leagues.
The master of the vessel told me, "`That he believed he was blessed for my sake.`"
I wished him to live so as that he might be blessed for Christ`'s sake.
Some reformation was begun on him in our voyage; which was the goodness of God,
through Christ, to him, and not to be attributed to me,
any further than an instrument in the divine hand;
for of ourselves we cannot do any thing that is good, it being by grace, through faith,
that we are saved, which is God`'s gift to the soul.

After I had been some time in Virginia, I got a passage up the bay of Chesapeake,
and had several meetings in Maryland, Friends being glad to see me;
and we were comforted in Christ our Lord.
I made some little stay at a place I had in that province, called Longbridge,
and then returned to Philadelphia,
where I lodged at the house of my very kind friends Richard and Hannah Hill,
and was oftentimes at divers neighbouring meetings,
and sometimes had good service therein.

About this time I had an inclination to alter my condition to a married state;
and Martha, the widow of Joseph Brown, appearing to be a suitable person for me,
on the 15th of the second month, 1714, we were joined together in marriage,
with the unity of Friends in general.
We had a large meeting at our marriage,
the solemnization thereof being attended with the grace and goodness of God;
and for example sake, we made but little provision for our guests:
for great entertainments at marriages and funerals began to be a growing thing among us,
which was attended with divers inconveniences.

My wife was a sober and religious young woman,
and of a quiet natural temper and disposition;
which is an excellent ornament to the fair sex;
and indeed it is so to both male and female; for, according to the holy Scriptures,
"`A meek and quiet spirit is with the Lord of great price.`"

I was at divers yearly meetings in 1715, viz., at Choptank, in Maryland;
at Shrewsbury and Salem, in New Jersey;
all which meetings were very large and comfortable; many things being opened therein,
tending to convincing and establishing the people in the truth and doctrine of Christ.
I was likewise at divers other meetings in those provinces,
which were large and satisfactory.

At Salem yearly meeting I was sent for to the prison,
where there was a young woman who was to be tried for her life.
She desired that I would pray for her,
and charged me to warn the young people to be careful not to keep bad company;
"`for,`" said he, "`it has been my ruin, and brought me to this shame and reproach.`"
She had been tenderly brought up and educated.
I knew her when she wore a necklace of gold chains, though now she wore iron ones.
Upon which subject I had afterwards a large opportunity
to speak to the people in a very moving manner;
which seemed very much to affect the youth and others in the meeting,
which consisted of many hundreds of people.
I saw this young woman afterwards, the jury acquitting her;
and I told her that her life was given her for a prey; and reminded her,
how it was with her when she was in prison in chains;
and I advised her to walk more circumspectly for the future;
which she said she hoped she should do.

In the year 1716, I had some concerns which drew me to the island of Bermuda,
where I went twice that summer.
My family increasing, I traded a little to sea for their support and maintenance:
and I can truly say, I carried on my affairs and business in the fear of God,
having an eye or regard therein, more to his glory, than to my own interest.
We had a rough passage to this island in the first voyage,
and were forced by distress of weather, to cast some of our goods into the sea;
and the storm being very violent,
some of the seamen thought we should be devoured by the waves.
As for me, they had shut me up in the cabin alone, all in darkness,
and the water came in so that they were forced to take it out in buckets.
When the storm was a little over, the master came to me,
and asked "`How I did all alone in the dark?`"
I told him pretty well; and said to him I was very willing to die, if it so pleased God;
and indeed I expected no other at that time.
After this great storm was over we arrived at Bermuda in a few days;
going into the harbour, the bottom of the vessel struck the rocks, but we got well in;
for which I was thankful to the Almighty.
I stayed on the island about a month, and had several meetings; to some of which,
many came who were not called Friends. They were all sober, and some well satisfied;
and the people of the island generally received me lovingly, and were very kind to me.
Our ancients, who bore the burden and heat of the day, met with very different treatment.
I tenderly desire that we who come after them,
may be truly humble and thankful to the Almighty for all his mercies.

By reason of my outward affairs,
I had opportunities with some persons of great note and business on this island;
and sometimes opened the principles of Friends to their satisfaction;
some of them told me, "`They never understood so much concerning our Friends before;
and if what I said was true, they had been misinformed.`"
Divers such opportunities I had with several on this island,
there being but very few of our Society.

These are called the Summer Islands, or Bermudas,
there being many little islands in the midst of the main island,
in form like a horse-shoe:
they are about two hundred leagues distance from the capes of Delaware.
It is rare to see hail, snow, or ice there.

After I had done my business, and had been for some time on the island,
I had a ready and comfortable passage home, where I was joyfully received.

After some little stay at home, I went a second time that summer to Bermuda,
and then also I had some meetings, and did some business on the island.
It was my constant care,
that my worldly affairs should not hinder me in my
religious concern for the good of souls.
It happened at this time there was a mighty hurricane of wind,
that blew many houses to the ground, and very many trees up by the roots,
and rent rocks asunder, of which I was an eye-witness: though it is to be observed,
that those rocks in the Summer islands,
are not so hard as in some other parts of the world, particularly to the northward;
for here they saw them with saws, and cut them with axes like wood.
I was told there were sixty sail of vessels then at these islands,
and all were driven on shore but three,
and ours was one of the three that rode out the storm; for which I was truly thankful.
In this great storm, or hurricane, several sloops were driven upon dry land,
so that after the storm was over, one might go round them at high water,
and several were blown off the dry land into the water.
One that was ready to be launched,
though fastened on the stocks with two cables and anchors put deep in the ground,
yet the violence of the wind blew her into the water, and dashed her to pieces.

About this time the Bermuda people had got a vast treasure of silver and gold,
out of the Spanish wrecks;
and at a meeting which I had on the first-day of the week before the hurricane,
or storm of wind,
it came weightily on my mind to exhort them not to be lifted up therewith,
nor exalted with pride: for I declared to them,
that the same hand who took it from the Spaniards,
could take it from those who had now got it out of the sea; and if he pleased,
by the same way; which was a storm that cast away the ships going from Spain.
And indeed so it happened the same week;
for it was reckoned by men of experience and judgment, that they lost more by the storm,
than they had gained by the wrecks of the Spaniards.
A sober old man, not of our profession,
told me the next day after the hurricane was over,
that what I spoke in the meeting was soon come to pass: and he added,
I was a true prophet to them.
Many houses that were not blown down were uncovered.
My landlord`'s house being old, several thought it would be down;
but by the good providence of God, it was one of those which stood, I was in my store,
which stood also, though I expected every minute when it would have been blown down.
It was by the mercy of God we were preserved, and not for any merit of ours.
I entreated the Lord in the midst of this great wind,
that he would please to spare the lives of the people;
for many of them being seafaring men, were very unfit to die;
at which time I thought I was sensible of the answer of my prayer,
and he was pleased to be entreated for them: for,
notwithstanding the violence of the storm, and the great destruction it made,
yet not one man, woman, child, or creature was lost, that I heard of, in all the island,
which was to me very admirable.
The Friend of the house came to me after the storm abated, and said,
"`The Lord had heard my prayers for them.`"
Although they could not by any outward knowledge, know that I had prayed for them,
yet they had a sense given them, that I was concerned for them before the Almighty;
which indeed was true.
Oh! that we may never forget the merciful visitations of the high and lofty One,
who inhabits eternity!

While I was on the island I was invited to,
and kindly entertained at the houses of several of the gentry, and at the governor`'s,
who invited me several times to his house.
Once I was with him, and some of his chief officers at dinner,
with divers of the first rank, where I was treated very kindly;
and after dinner the governor`'s practice was to drink the king`'s health,
and he hoped I would drink it with them.
"`Yes,`" said the rest at the table, "`Mr. Chalkley,
(as they called me,) will surely drink the king`'s health with us.`"
So they passed the glass, with the king`'s health, till it came to me;
when they all looked steadfastly to see what I would do;
and I looked as steadfastly to the Almighty, and said to them, I love king George,
and wish him as well as any subject he hath;
and it is known to thousands that we pray for him
in our meetings for the worship of Almighty God;
but as to drinking healths, either the king`'s, or any man`'s else,
it is against my professed principle, I looking on it to be a vain, idle custom.
They replied, "`That they wished the king had more such subjects as I was;
for I had professed a hearty respect for him:`" and the governor and they
all were very kind and friendly to me all the time I was on the island.

After I had finished my concerns, I embarked in the sloop _Dove,_ for Philadelphia,
she being consigned to me in this and the former voyage.
It being often calm and small winds, our provisions grew very scanty.
We were about twelve persons in the vessel, great and small,
and but one piece of beef left in the barrel; and for several days,
the wind being contrary, the people began to murmur,
and told dismal stories about people eating one another for want of provisions.
The wind being still against us, and for aught we could see, likely to continue so,
they murmured more and more, and at last, against me in particular,
because the vessel and cargo was consigned to me, and was under my care,
so that my inward exercise about it was great.
Neither myself, nor any in the vessel,
imagined that we should be half so long as we were on the voyage; but since it was so,
I seriously considered the matter; and to stop their murmuring,
I told them they should not need to cast lots, which was usual in such cases,
which of us should die first, for I would freely offer up my life to do them good.
One said, "`God bless you, I will not eat any of you.`"
Another said, "`He would die before he would eat any of me;`" and so said several.
I can truly say, that at that time my life was not dear to me,
and that I was serious and ingenuous in my proposition:
and as I was leaning over the side of the vessel,
thoughtfully considering my proposal to the company,
and looking in my mind to him who made me,
a very large dolphin came up towards the surface of the water, and looked me in the face.
I called the people to put a hook into the sea and take him,
for here is one come to redeem me, said I to them; and they put out a hook,
and the fish readily took it, and they caught him.
I think he was about six feet long, and the largest that ever I saw.
This plainly showed us that we ought not to distrust the providence of the Almighty.
The people were quieted by this act of providence, and murmured no more.
We caught enough to eat plentifully of till we got into the capes of Delaware.
Thus I saw it was good to depend upon the Almighty, and rely upon his eternal arm; which,
in a particular manner, did preserve us safe to our desired port,
blessed be his great and glorious name, through Christ, forever!

I now stayed at and about home for some time;
after which I was concerned to visit Friends in several places,
and in the adjacent provinces, as Maryland, New Jersey, etc.,
and was at many marriages and funerals, at which,
many times we had good opportunities to open the way, and also the necessity,
to be married to Christ Jesus, the great bridegroom of the soul;
and also to exhort the people to consider and prepare
for their latter end and final change;
which many times was sanctified to divers souls, and the Lord`'s name was glorified,
who is worthy thereof.

In the year 1717, I went into Maryland to look after my affairs in that province;
and as I travelled, I had divers meetings at Nottingham, and at Bush-river,
about which time, at Bush-river, several were convinced.
The meeting I found in a growing condition in that which is good,
several persons meeting together in silence to worship God,
according to Christ`'s institution, which was, and is, and ever will be,
in spirit and in truth.
For the encouragement of all such, Christ hath said,
that the Father seeketh such to worship him; and again,
"`Where two or three are met together in my name, there am I in the midst of them.`"
And if Christ be in the midst, there is no absolute need of vocal teaching,
except it be the will of the Lord to call any to it.
Let the spiritual Christian read and judge.

After my return I had several meetings in the country, near Philadelphia;
and about the latter end of the eighth month I was at several marriages,
one of which was on the third-day of the week, about fifteen miles above Philadelphia,
over Delaware river; the next was over the river again,
about twenty miles below the city;
and the third was about twenty miles further down the river,
and on the opposite side at Salem, on the following days;
so that I crossed the Delaware river three times in three days,
and rode about one hundred miles.
The meetings were all large,
and matter suitable to the occasion freely opened to the people.
These remarks are not intended to set up man, or exalt flesh,
but to stir up others to come up to the work of Christ in their generation.
All the glory and goodliness of man is but as the grass, which soon withers,
without we dwell in the root of true religion, and in the holy life of Christ.
That God may have the glory of all his works,
is the end of all the labours and travels of the
servants and faithful ministers of Christ.

In the tenth month, 1717, divers considerations moving me thereto,
I took a voyage to Barbados, in the _Snow Hope,_ J. Curtis, master,
and from thence to Great Britain and London; partly on account of business,
and hoping once more, if it pleased God, to see my aged father, my brother,
relations and friends; which voyage I undertook in the solid fear of God.
I desired the concurrence of my wife,
and my friends and brethren of the meeting to which I did belong;, in this undertaking,
the which I had in a general way, and the good wishes and prayers of many particulars,
with a certificate from our monthly meeting,
signifying their unity with my conversation and ministry, and present undertaking.
I felt the love and goodness of God therein,
but in many respects it was a great cross to me,
especially leaving my beloved wife and children, and many of my dear friends,
whom I loved well in Christ; and crossing the seas was always troublesome to me,
being sickly, especially in windy or stormy weather.
The confinement was worse to me for the time than a prison;
for it would be much easier to me to be in prison on land, upon a good account,
than in prison at sea, I always looking on a ship to be a perilous prison,
though it was my lot to be much therein.
As for my natural life, I always gave it up whenever I went to sea;
and I thought that was the least part of the hardship, never putting much value thereon.
But to sea I went, for the reasons mentioned,
and got from Philadelphia to Newcastle the first night in said vessel,
and to Elsingburgh next day, where we lay for a fair wind about two days,
then sailed to Bombay-hook, where we met with two other vessels bound to sea,
who waited also for the wind.
We lay there two nights, and on a first-day morning set sail,
the weather being very cold, and the ice thick on the sides of our vessel,
and on our ropes.
The day that we left Bombay-hook we got out to sea, took in our boat and went on our way;
and in four or five days we got into warmer weather.

In this voyage I wrote something on the common prayer,
used by some of the church of England whose conversations were very loose and corrupt,
which I entitled, "`A truly tender scruple of conscience, about that form of prayer,
called the common prayer, used by the church of England and her members,`" etc.

In this voyage we saw several ships, but spoke with none;
and in twenty-seven days from our capes we arrived at Barbados,
and came to anchor in Carlisle bay.

I had been twice in Barbados before, but this was the quickest passage by one day.
Here I was lovingly and tenderly received by my friends.
I took my good friend Joseph Gamble`'s house for my quarters,
most of the time whilst I stayed on the island,
and visited Friends`' meetings several times over,
there being five of Friends`' meeting houses in the island,
and our meetings were sometimes large and open.

Our stay was longer than we at first expected, by reason of a great drought,
they having no rain for more than a quarter of a year,
which was a great hindrance to trade on the island.
While I was here, our ancient Friend, George Gray, died.
I was at his funeral, at which there were many people;
and on this occasion we had a large meeting at our meetinghouse at Speights-town,
where I had a seasonable opportunity with the people,
opening to them the necessity of thinking of, and preparing for, their latter end;
and pressed them earnestly thereto.
They were generally attentive and sober, and some were broken into tenderness.
While we were burying the Friend, there appeared a dismal cloud hanging over the island,
such an one as I never saw before.
I thought it was of the colour of the flame of brimstone;
and expected there would have been a great storm, or gust, and much rain,
they having had very little for many weeks, or some months; but it went over,
and there was no rain or wind as I remember.
Soon after, some people came in from sea, and said it rained ashes from that cloud;
and they brought some to the island, some of which ashes I now have before me:
the taste of them seems to me to be a little sulphurous,
and they have some glittering particles in them;
in colour and smell I think they differed little from common ashes.
Herein the Almighty and Infinite Being signally showed
his mercy and favour to poor mortals;
for had not his mercy prevented,
he could as easily have rained down the fire as the ashes.
He rained fire and brimstone on the cities and inhabitants of Sodom and Gomorrah,
for their pride and idleness, much of which abounds among the inhabitants of Barbados,
the people being very luxurious.
Oh! may the inhabitants of that isle, and all others, consider their ways and doings,
and not provoke the great Lord, the Sovereign of heaven and earth,
as many of them do by their evil lives and voluptuous conversations.
May they kiss the Son, though not with a Judas kiss of profession,
or speaking well or fairly of him only,
but with divine love manifested through obedience,
while his wrath is but a little kindled against them,
and before it break out into a flame.

After this funeral I was sent for to Bridgetown, to the burial of a master of a ship,
a young man, who was very fresh and well a few days before.
There was a great appearance of people, and I was pretty largely opened in the meeting,
on the words of the prophet, where he says, "`All flesh is grass,
and all the goodliness thereof is as the flower of the field.
The grass withereth, the flower fadeth, because the spirit of the Lord bloweth upon it:
surely the people are grass.
The grass withereth, the flower fadeth; but the word of our God shall stand forever.`"
I treated of this Word, its wonderfulness, its duration, and its work in man;
also of the fading constitution of mortal man, though young and strong,
as that young man was a few days before, whose corpse was then before us.

I was at several other burials on this island, which proves a grave to many newcomers,
it being a hot climate, and those who are not accustomed to it being very thirsty,
and it is not easy to quench their thirst; so that what is called moderate drinking,
throws many strangers into a violent fever, and oftentimes is the cause of their death.
I note this as a caution to those who may transport themselves there,
that they may shun that danger; which might be avoided by drinking cool drinks,
of which they have many sorts very pleasant, viz., cane, sugar-reed, and white sorrel,
pine, orange, and divers others.
I advise such, as they love their health,
to refrain from drinking much hot drink or spirits.

I saw several natural curiosities on this island,
which among the great numbers of the works of God, do show forth his praise and glory.
One to the leeward part of this island, which is called the spout,
sends up a vast body of water into the air,
occasioned by a great cavity in the rocks under the water,
which may be seen in calm weather, when the sea is low.
When the wind blows, a great body of water being pent in a large hollow place,
it forces it up into the air, sometimes ten, fifteen, or twenty yards high,
according as the strength of the wind is, and makes a report like a cannon, or thunder,
a great way off.
I believe I have seen it ten or twelve miles out at sea.
I was also at a place called Oliver`'s cave, which we got to with some difficulty,
in going down the steep and craggy rocks.
There is on the outward part next the sea, a very large vaulted place,
in the form of a half circle, about one hundred feet high, as near as I could guess.
In this large vault, behind a rock, is the mouth of the cave,
not the height of a man at the first entrance; after going in a few yards,
one may walk upright comfortably,
the bottom being pretty plain and smooth for about a hundred yards,
and then we come into a large cave which is formed archwise,
and about ten or fifteen yards high, as we thought,
being much higher in the middle than at the sides,
but almost as regular as if it had been done by art, which we beheld with admiration,
by the help of wax candles and other lights, that we made and carried for that purpose.

When I had done my business in Barbados,
having been there about thirteen weeks and loaded our vessel,
we sailed the 10th of the second month, 1718, for London.

We had a good passage, being five weeks and two days from Barbados to Great Britain,
in which we saw several vessels at sea, but spoke with none.
After sight of the land, we got in two days to Beachy-head,
which is about fifteen leagues from the Downs or Deal.

We sailed along the shore by Folkstone, where we took in a pilot,
and had a comfortable passage through the Downs, and up the river Thames to London,
where I met with my dear and aged father, and loving brother, sister and cousins,
and many others of my near and dear relations and friends.

In this voyage I wrote some things which opened in my mind at sea,
upon that excellent sermon of Christ`'s upon the mount,
as it is recorded in the holy Scriptures of the New Testament, in the fifth,
sixth and seventh chapters of the evangelist Matthew,
but have since heard that the same is better done by an abler hand;
and therefore it may suffice here to repeat the advice,
which in the course of my travels I have often had occasion to give, viz.,
that the professors of Christianity should frequently read this sermon,
and be careful to practice the same; that they may not only be Christians in name,
but in deed, and in truth.

After visiting my relations and some meetings of Friends in and about London,
having finished my business, and being ready to return homeward,
divers Friends accompanied us from London to Gravesend; and the wind not being fair,
we went to Rochester, and had a meeting there, then back again to Gravesend,
and there took a solemn farewell of our Friends,
recommending one another to the grace of Christ,
having this time made but little stay in Britain.

In the fifth month, 1718, we sailed from the Downs in the aforesaid _Snow Hope,_
divers Friends, viz., John Danson, Isaac Hadwin, John Oxley, Lydia Lancaster,
Elizabeth Rawlinson and Rebecca Turner, being in company with us.
After about nine weeks passage from land to land,
having had meetings on first and fifth-days on board, during the voyage,
we came all safe and well to Philadelphia, through the blessing of God,
where I stayed with my family a few months,
and took another voyage for Barbados and Britain.
I was under more than ordinary concern for the support and accommodation of my family,
the circumstances thereof being a little changed by the increase of children,
remembering the words of the apostle, that those who had not this care and concern,
were worse than infidels; my Lord Jesus, whose servant I profess myself to be,
also saying, "`It is better to give than to receive.`"
An opportunity offering of the consignment of a vessel and cargo, the _Snow Hope,_
Warner Holt, master, to Barbados, and from thence to London,
and so to make returns home again, for Philadelphia, I embraced it;
though with reluctance to leave my very loving wife, children and friends,
all of whom I tenderly loved and respected.
I also had in my eye an hope, through the blessing of God,
to obtain wherewith to accommodate my friends,
who were strangers and pilgrims in this world for Jesus`' sake,
as I also had been myself; and that they might find a place or home,
and refreshment under my roof; not to excess, but to comfort and edification;
which in sincerity, is all the grandeur I covet or desire in this world.
After due consideration, on the 2nd day of the eleventh month, 1718,
we set sail from Philadelphia, many Friends taking their farewell of us for that voyage.
Thus with hearts full of love and good will, we parted with our friends,
and went down the river about five miles, where we ran aground, but got off next tide,
and next day came to an anchor at Chester.

On the 4th day of the month we set sail, and got to Newcastle about the eleventh hour;
it being meeting day, we went to meeting,
where our great Lord was pleased in some good measure to own us with his living presence,
and comfort us with his love; blessed be his holy name!
In the morning we sailed to Reedy island, where we stayed for the tide,
and in the night our cable parted, which we knew not of until morning,
and then we had gone from the place where we anchored, about a league:
but though the vessel drove about the river, yet she did not go aground.
We dropped our other anchor, and sent the boat to seek for that which was parted from us,
but could not find it until the next tide, and then could not get it up,
and were unwilling to go to sea without it;
which occasioned us to stay several tides before we could get it up;
at last with much difficulty we weighed it, our men`'s clothes being much frozen;
for it was very cold, and froze extremely hard.
After this we went down to Bombay-hook, where was another vessel going out to sea.
Next day the wind was against us, and it snowed much, and froze hard;
and that night the river and bay were filled with ice as far as we could see,
and it drove very hard against our vessel, so that we wished for day:
for we thought sometimes it would have torn her bows into pieces;
but our anchor and cable held us, we thought, to a miracle,
for which we were thankful to the great Keeper of all those who put their trust in him.
When the tide turned for us we got up the anchor,
and so let her drive with the ice down the bay: the other vessel did the same.

It was now dangerous moving, go which way we would.
The vessel in company with us attempted to go back again, but seeing that we did not,
as we supposed, came to anchor again, and we both went down the bay together;
and the wind springing up fair, we got clear of the ice in a few hours time.
By this hindrance we could not get to sea that day,
but were obliged to come to anchor near the middle of the great bay of Delaware,
and the night being fair and calm, we rode it out safely,
which if it had been windy weather, would have been dangerous.
Early in the morning of the 9th of the month, we got to sea,
and soon lost sight of the land.
Next day the wind was high, and the weather proved stormy for several days,
insomuch that our main-deck was under water most of the time,
so that we were forced to go before the wind for several days together.
We also shut up our cabin windows, and were tossed exceedingly, and I was very sea-sick:
and we began in this storm to fear falling on the rocks of Bermuda, which we were near,
as we imagined, and the wind set right on the island.

When we had passed the latitude of Bermuda, we met with fair weather and winds,
and all the remaining part of our passage was pleasant and comfortable.
Thus I was led to consider the vicissitudes which
mortals may expect while in this unstable life,
which is full of changes;
and I strongly desired to be rightly prepared for that world which is eternal,
and its joy and felicity permanent; at which blessed port, I hope in God`'s time,
through his grace, safely to arrive.
Through storms, tempests, ice and snow, we left those frozen climes,
and crossed the tropic of Cancer, between which, and that of Capricorn,
there is neither frost nor snow at sea, at any time of the year,
and the wind always nearly one way, viz., easterly,
except in hurricanes and violent storms,
which sometimes occur in those parts of the world.
We arrived at Bridgetown, in Barbados, in twenty-one days,
which was the quickest passage I ever had,
this being the fourth time of my coming hither,
where I was always kindly received by my friends.

About this time war being declared against Spain by the king of Great Britain,
proclamation thereof was made in Bridgetown, which put such a damp on trade,
that there was little business, and the markets low and dull,
which made my stay longer than I would have chosen.
But my friends, among whom I had many opportunities,
seemed rather pleased than otherwise; telling me,
"`That they did not care if I was to stay there always
if it were my place:`" and when I left Barbados,
they gave me better credentials than I thought I deserved.
A friend of mine giving me intelligence that the
market was better at Antigua than at Barbados,
I dispatched my affairs and took part of our cargo there,
and was kindly received by our friends.
We were about three days on our passage, and had fine weather.
At Antigua I had several meetings:
my business at no time hindered me in my more weighty service; for I always,
through divine help, made that give way to my religious duty,
in which I ever found peace and inward satisfaction.
In about five weeks I finished my business in this island,
having no small satisfaction in coming to it; and our vessel being now loaded,
we took our solemn leave, and with the good wishes of many, departed for England.

Our friends there signified to their brethren, that they were glad of my company,
and that I was serviceable to them, though I came upon business.
My hand, when need required, was to my business, but my heart was, and I hope is,
and ever shall be, freely given up to serve the Lord,
in that work whereunto I believe he has called me.
We have liberty from God and his dear Son, lawfully, and for accommodation`'s sake,
to work or seek for food and raiment; though that ought to be a work of indiffercncy,
compared to the great work of salvation.
Our Saviour saith, Labour not for the meat which perisheth,
but for that which endureth forever, or to eternal life: by which we do not understand,
that Christians must neglect their necessary occasions,
and their outward trades and callings; but that their chief labour and greatest concern,
ought to be for their future well-being in his glorious kingdom.
Why did our Lord say to his disciples, Children, have you any meat?
and when they answered, no, bid them cast their nets into the sea,
and they drew to land a net full of great fishes?
Fishing being their trade, no doubt but they sold them,
for it was not likely that they could eat them all themselves.
Also the apostle of Christ says,
He that doth not take care of his family, is worse than an infidel: and the apostle Paul,
the great apostle of the gentiles, wrought with his hands,
even while he was on his travels in the work of the gospel;
and others tasted of the benefit of his labour naturally, as well as spiritually.
It is also written, he that will not work, shall not eat.
By this, and much more, which might be noted,
it appears that we not only have liberty to labour in moderation,
but we are given to understand, that it is our duty so to do.
The farmer, the tradesman, and the merchant, do not understand by our Lord`'s doctrine,
that they must neglect their calling, or grow idle in their business,
but must certainly work, and be industrious in their callings.
We all ought to understand, that our hearts and minds ought to be out of the world,
or above the nature and spirit of it.
It is good and profitable for both soul and body,
rightly to distinguish between earthly and heavenly things,
and to be careful how we mix the one with the other; for it is an eternal truth,
that God and mammon cannot dwell together, or join together in the heart.
If our love is more to God than the creature, or to heaven than earth,
then will he dwell in us, and with us:
but if our love is more to the creature than to Christ, or to earth than heaven,
then will he not dwell with us, but will leave us to ourselves;
for the Lord Omnipotent will not admit of any rival.

On the 11th of the fourth month, 1719, we left Antigua,
stood close to the wind till we again crossed the tropic,
and got into those latitudes where the winds are variable.
Sailing in the great deep, we saw the wonders of the Lord,
particularly in divers kinds of fish, they living upon one another in the sea,
the great fishes on the small ones; and mankind too much resemble them in that respect.
About the latitude of thirty-three degrees north, our master, Warner Holt,
seeing a school of porpoises about the ship,
took his harping-iron and struck one of them,
out of which we got eleven quart bottles of oil;
and most of us eat heartily of this fish, which agreed with our people very well.
They fried the liver for our mess, of which I ate, it was well tasted,
and more like fresh beef than fish.
I make this memorandum, that if any should take them when their provisions are scarce,
they may eat freely without danger, according to our experience.
When we had been at sea about three weeks,
being near the latitude of forty degrees north, and about the longitude of forty-two,
though it was in the midst of summer, we saw an island of ice, at which we all marvelled,
and judged that there had been a severely cold winter
in those latitudes on the land of America.
When we saw this island of ice we judged ourselves not far from the banks of Newfoundland.
Hitherto we had easy gales of wind and many calms, which made our passage seem long to us.
We saw two sail of ships about those latitudes, but spoke with neither,
being willing to shun them, as it was war time.

We had in this voyage, weekly meetings for worshipping the Almighty,
in which the great Lord both of sea and land,
was pleased to manifest his name and truth amongst us,
for which my soul often secretly and openly blessed
and praised his divine and glorious name and truth;
for he bore up my drooping spirit, so that I could truly say with the royal psalmist,
not because he spoke it only, but also from being an experimental witness thereof;
"`The floods have lifted up.
Oh!
Lord, the floods have lifted up their voice: the floods lift up their waves.
The Lord on high is mightier than the noise of many waters, yea,
than the mighty waves of the sea.`"
This the king wrote of his own experience in a spiritual sense; but I may say,
without boasting, I have witnessed the rage and noise of mighty waves and waters,
both natural and spiritual; the one,
as though it would swallow up my reputation among men, and the other,
as though it would swallow up my person in this voyage;
but blessed be the name of Him who is holy and eternal,
who indeed is stronger than the noise of many waters,
or than the mighty waves of the sea, either inwardly or outwardly,
I will through his strength, magnify his name, because he is worthy:
and may I do it forever!

About the 11th of the fifth month, we saw great flocks of birds,
which we judged came from the Azores, or Western Islands,
near which we reckoned ourselves to be.
The 21st day we saw, and came up with a French ship,
which had been fishing on the banks of Newfoundland, and was bound for Havre-de-Graco,
in France, the master of which came on board of us,
and our captain went on board of them.
We exchanged some rum and sugars, of our sea-stores, for French wine and cider,
and some of our provisions for their fish.
The captain was a Protestant, and very courteous to us:
the regent of France at this time being kind to the Protestants,
so that they increased much in that kingdom.
The Frenchman seeming desirous to know what religion I was of,
I told him by an interpreter, that I was one called a Quaker, or trembler,
and that our principle was to do good to all men, and not to hurt any man,
according to Christ`'s doctrine, not to render evil for evil,
but to overcome evil with good.
When they went away and took leave of us, they desired me to pray for them,
the which I remembered with tenderness of spirit.
Having but little wind, we kept company for several days; but the wind springing fair,
we wished them well, and went on our way, our vessel out-sailing most we met with;
and a few days after we met with a New England ship,
which came out six days before us from Antigua.
We were then in latitude about fifty degrees north,
and twenty-nine and a half longitude from the Land`'s End of Great Britain.
The 30th day of the fifth month, we sounded, and found ground at twenty-eight fathom,
and on the 1st day of the sixth month, we saw the Land`'s End of England,
all our company being in health, and well; for which my heart was truly thankful,
to that great and infinite Being,
whose providence is over us poor mortals in all parts of the world,
and who reigns over sea and land, and is worthy of adoration, worship, service,
and living praise forever!

In a few days we came into the English channel, and while going up,
there came one of the king`'s yatchts, and pressed most of our men;
taking from us our best hands and carrying them on board a man of war;
after which we came to anchor at Folkstone, where I left the vessel,
and got a horse to Dover, and there took coach to London.
In the coach were some persons who began to talk about the Quakers,
and spoke against their plain way of living and clothing, and said,
"`they did not understand their unfashionable way of conversation;
neither was it the way to gain proselytes.`"
Upon which I asked them, whether they understood Paul, the great apostle of the gentiles,
who said, Be ye not conformed to this world, i. e., the fashions of it, for this reason,
the world and the fashions thereof, pass away; which is a great truth.
We plainly see how fickle and changeable the world is in its vain fashions and customs,
and to follow it in all its foolish cuts and turns, or changes,
must make a man or woman very foppish and apish.
I told them that our religion was agreeable to the holy Scriptures, which,
if they did not understand, neither could they understand us;
for the doctrine of Christ and his apostles, was generally very plain therein;
and the doctrine in Christ`'s excellent sermon on the mount,
is clear to very low or mean capacities.
They discoursed no more of religion till we came to London.
Here I met once more my loving and aged father, a man fearing God,
and having a gift of the ministry of the gospel of Christ,
and well beloved of his friends and neighbours, who,
with others of my near and dear relations and friends, received me gladly.

After some months stay among my relations and friends in London, we sold our vessel,
the _Snow Hope,_ and bought a ship, which we called the _Trine Hope,_ Warner Holt, master;
and when I had done my business, I sailed in her for Pennsylvania.
We had meetings on board the vessel twice a week,
in which the Almighty was pleased to favour us with his good presence.
Sobriety, and the fear of God, and faith in his beloved Son, Christ,
were often recommended to the youth on board the vessel with us,
of whom there were several going to America, in order to settle there.
At one meeting I was tenderly concerned to remind them of Jacob, who in his youth,
left his country and relations to sojourn in a strange land, and how in that undertaking,
he sought the Lord and his blessing, more than any outward thing;
and that he was greatly blessed with many favours from heaven above,
and also of the earth beneath, and they were advised to take him for their example.
Many other things were tenderly opened to them in the love of God,
and in his fear and counsel they were exhorted from time to time.

It being winter time, we sailed to the southward, and got into warm weather,
and were on our passage seven weeks and some days, in which time we saw several vessels,
and spoke one, whose people said they were chased by a Turk, but got from him,
at which they greatly rejoiced.
We apprehended it was our ship that they saw over night,
for we saw a sail that crowded from us as fast as she could, and it being near night,
we shortened sail, and she left us.
In the morning we came up with her, and being pretty near,
they and we put out our colours, and being both Englishmen, we spoke to each other,
and were glad to meet with some of our own nation upon the great ocean;
but our vessel sailing best, we took our leave of them, wishing them a good voyage.
We met with rough seas and high winds in the latter part of our passage,
till we came to the capes of Delaware, which we all rejoiced to see;
and had a pleasant passage up the bay and river to Philadelphia,
where I had once more a comfortable meeting with my dear wife and family,
which I gratefully acknowledged as a high favour from the hand of the Almighty.

We arrived at Philadelphia the 1st of the second month, 1720;
after which I stayed about home for some time, and was not idle, but kept to my business,
and to meetings, and having a desire to see Friends in the province of Maryland,
at their general meeting at West river,
I was accompanied by Isaac Norris and Thomas Masters, both sober young men.
It had been a time of much rain, and the waters being high,
going over a ford of Brandywine, my mare got among the rocks,
it being a very rocky creek, and fell down.
The stream being very strong, she rolled upon me, and being entangled with the stirrup,
I could not easily clear myself, but I gave a spring, and swam from her.
When I was clear I got to her again, and laid hold of her mane,
and through the good providence of God, got well out on dry land,
which was a remarkable deliverance.
In three days we got to West river, to the yearly meeting, which was large,
and Friends were glad to see me, I having not been there for several years.
I was out on this journey about two weeks, and rode about three hundred miles:
and after coming home, I travelled much in the provinces of Pennsylvania and New Jersey.

In the year 1721, Thomas Lightfoot and I, with William Brown,
went to a meeting at Bush river, and going over Susquehanna ferry,
the people were fiddling and dancing.
When the dance was over, I asked them, believing them to be Protestants,
if they thought Luther to be a good man?
They replied, "`Yes, there was no doubt of it.`"
Well, said I, and so do I; and I will tell you what he says concerning dancing,
"`That as many paces as a man takes in his dance,
so many steps he takes towards hell;`" which spoiled their sport, and they went away,
and we went on ours towards the meeting; and a good meeting it was.
After it we returned by way of Nottingham, and had a meeting there,
and one at New-Garden, and so on to Philadelphia.
I was from home about a week,
and travelled in this journey about one hundred and fifty miles,
and was well satisfied therein.

From Philadelphia I went to the general meeting at Shrewsbury, in East Jersey,
where I heard of J. G.`'s being wounded by a young man, with a sword, of which he died,
lamenting that he did not take the counsel of his friends;
as young men who slight the counsel of those that wish them well, commonly do,
either sooner or later, if the day of their visitation be not over.
Some few days after this meeting at Shrewsbury, I visited Friends on Long island,
and returned home again, having travelled about three hundred miles.
During my stay at and about home, I wrote something concerning Perfection,
in answer to a nameless author; also something concerning Predestination,
or Election and Reprobation.
