== Chapter V

In the year 1722, I went back in the woods to Buckingham, the Great Swamp, Perkioming,
Manatawny, and Oley, where I had meetings, travelling over mountains,
from which we could see many miles.
After staying some time at home and visiting neighbouring meetings,
I went to the yearly meeting of Friends on Long island, which was very large,
many people, not of our persuasion, being there, who were very sober.
Many things were opened in the love of Christ,
and his great love was largely declared to the congregation.
The parable concerning the prodigal son,
came before me to speak of in a very moving manner,
and strongly to invite the youth to lay hold of the love of the Father in his Son,
to poor souls: and indeed it is a wonderful parable,
setting forth the infinite love of the great Lord of all, to his poor creatures.
Many were affected and reached at this meeting,
and the Almighty was praised and glorified, who alone is worthy.

I had a meeting at New York, and then set forward to Woodbridge,
where we had a comfortable meeting.
Naaman, the Assyrian, was the subject of that day`'s work; and that any thing,
loved and esteemed more than Christ, whatever it be, is to be avoided,
and the people were warned to be careful to keep close to the God of spiritual Israel,
and to give up all which is contrary to his nature, and to take up Christ`'s cross,
and follow him; for it is those who follow him in the regeneration,
that are to be heirs of his kingdom.

In this year I was at the burial of our friend Jonathan Dickinson,
at which we had a very large meeting;
he being a man generally well beloved by his friends and neighbours.
In the meeting held on the occasion, a passage which he had often told me in his health,
was brought to my remembrance, and I think it worthy to be recorded, which is as follows:
"`It happened at Port Royal, in Jamaica, that two young men were at dinner with Jonathan,
and several other people of account in the world,
and they were speaking about earthquakes, there having been one in that place formerly,
which was very dreadful, and destroyed many houses and families.
These two young men argued that earthquakes and all other things, came by nature,
and denied a supernatural power, or deity, insomuch that some persons,
surprised at such wicked discourse, and ashamed of their company, left it.
At the same time the earth shook and trembled exceedingly,
as though astonished at such treason against its Sovereign and Creator,
whose footstool it is.
When the earth thus moved, the company which remained were so astonished,
that some run one way and some another,
but these two atheistical young men stayed in the room, and Jonathan with them,
he believing that the providence of Almighty God could preserve him there, if he pleased,
and if not, that it was in vain to fly.
But the hand of God smote these two young men, so that they fell down;
and as Jonathan told me, he laid one?
on a bed, and the other on a couch, and they never spoke more, but died soon after.
This was the amazing end of these young men.`"
A dreadful example to all atheists, and dissolute and wicked livers.
Oh! that young people might be warned, that the hand of God might be upon them for good,
and that they would be tenderly concerned for their salvation!

On the 30th of the fourth month, 1723, my tenth child, named Thomas, died about midnight,
having before buried nine.
It was some exercise to me thus to bury my children one after another;
but this reflection a little mitigated my sorrow, viz.,
I knew that if I could have all things relating to them according to my desire,
could I see them grow up to be sober men and women, well married,
have a competency in the world, etc., yet it was safer and better for them,
and they more out of danger, to be taken away in their infancy and innocency.
I fervently begged the Almighty,
that he would be pleased to take them away while innocent,
rather than that they should live to be vicious or unrighteous men and women,
and to bring scandal on the holy name of Christ, and upon our Christian profession;
which considerations tended to settle and quiet my mind in my sorrowful exercise.
The great Lord of all sanctify the sorrows and afflictions of his people and children,
and grant them the fulfilling of that blessed portion of holy Scripture,
that all things shall work together for the good of them that love and fear him:
even so be it, saith my soul.

In the sixth month of this year I removed from the city into the country,
to a small plantation I had at Frankford, in order to be more retired,
and for health`'s sake, etc., finding some decline in my bodily strength,
which I take to be very much owing to the severe colds and
hardships I have sustained in my long and hard travels,
especially in the wilderness of America.
Without vanity I may say, that I always loved temperance,
and have been sometimes zealously concerned to preach against intemperance;
and though I cannot now take as long journeys as formerly,
my spirit earnestly travels for the welfare of Zion,
and the peace and prosperity of all those who love, fear, and serve God,
and believe in his Son.

On the 6th day of the eighth month, it pleased God to give me another son,
whom I named George, after my father, brother, nephew, and king;
and though this name is now a great name among men,
I considered that no name can preserve life,
so I gave him up to the will of Him who gave him to me, and desire,
if I have no name through children to posterity,
I may have a name in the Lamb`'s book of life,
which I have ever esteemed far above a name amongst men.

After my removal to this place I was not idle, but visited neighbouring meetings,
and in the eighth month I went to Shrewsbury general meeting,
where there were many hundreds of people,
and the truth declared had good impression upon the minds of many; some after meeting,
who were not of our Society, acknowledged to it, and that they were glad they were there.
In this meeting I was concerned for the welfare of mankind,
and the exaltation of the holy name of the Almighty,
to declare the universal love of God to man, from several texts of holy Scripture;
as that passage of Jacob and Esau, and Peter and Cornelius,
and something concerning the objection made against us, the people called Quakers,
that we do not acknowledge the holy Scriptures to be the word of God;
for though we believe that the Scriptures came by divine inspiration,
yet we are clearly convinced by their testimony,
and by the spirit of truth in our hearts, that Christ is the eternal Word of God,
by whom all things were made and created, and do still exist.

From Shrewsbury, with divers other Friends, I rode to Crosswicks, where,
on the fifth-day, we had a very comfortable meeting,
in which the ancient love and goodness of our heavenly Father was with us,
tendering our hearts into tears of joy,
some of us being likewise affected in remembrance of the goodness of the Almighty to us,
in the meeting we had in this place under the trees, about twenty-five years since.
The great subject of faith and works was spoken to; as,
that the Roman Catholics seemed to lay too much stress on works, and the Lutherans,
Calvinists, and others, too little: but our principles led us to join both together;
the Almighty having joined them together, none ought to separate them.
This subject of faith and works having been much in debate amongst professed Christians,
it is on my mind here to mention a few things deduced from the best authority:
The first is, "`Without faith, it is impossible to please God.`"
Second, "`Faith is the gift of God.`"
Third, "`Faith works by love.`"
Fourth, "`Faith is the evidence of things not seen,
and the substance of things hoped for.`"
Fifth, "`Faith without works is dead.`"
Sixth, "`The just live by faith.`"
Seventh, "`Ye believe`" or have faith "`in God, believe also in me.`"
The author to the Hebrews speaks excellently concerning the power of faith,
and the mighty wonders wrought by it.
This living, saving, true and divine faith, must be in the heart,
through and in Jesus Christ, the Son of the living God, who is, and always will be,
the author and finisher of it in every true believer.

After I came from Shrewsbury, I visited neighbouring meetings, and in Chester county,
where I had meetings for nine days successively, some of which were very large,
particularly at Providence and Goshen;
in which I was opened to exhort them to keep to that plain,
honest way of life and conversation which our fathers and elders were found in,
and to remind them of the sufferings they endured
for their testimony to the blessed truth,
in the first breaking forth thereof in the last age.
I was also concerned to show them, that the Almighty,
who had blessed us with plenty of temporal blessings, would continue the same to us,
if we were careful to live in his fear; but that otherwise,
we might expect his judgments for disobedience.

And after my return, I continued about home for some time,
it being the winter season and bad travelling,
and I not so capable of travelling as formerly;
but I had great peace and tranquillity of mind,
in that I had freely given up my youthful days to serve my Creator,
and the same love and zeal was yet fresh and warm in my heart,
for the glory of his great name;
and I still have a full resolution through his strength and grace to serve him,
the great Lord of all, during the remainder of my days,
according to the light and strength given to me.

Our yearly meeting at Philadelphia this year, was large,
in which our friend Benjamin Kid, from England, being with us, had good service.
I cannot forget a concern which was upon me at this meeting,
that the universal love of God, through Christ, might prevail amongst mankind,
and to press Friends to manifest to all people the influence thereof,
by their exemplary lives and conversation.

In the second month, 1724, I went into New Jersey, as far as Shrewsbury, where,
on on a first-day, we had a large meeting to general satisfaction;
and the next day we had another, wherein the love and good will of God, through Christ,
was opened freely to the people, and our duty to forgive one another,
was largely treated of; and it was plainly shown, that without forgiving others,
we could not be forgiven of God, as Christ saith, "`If ye forgive men their trespasses,
your heavenly Father will also forgive you: but if ye forgive not men their trespasses,
neither will your heavenly Father forgive your trespasses,`"
Much more was said to the same effect on that subject;
as also Christ`'s answer to Peter, who asked,
how often a man should forgive his brother if he trespassed against him?
Peter says, till seven times: our Lord Jesus answers, "`I say not unto thee,
until seven times, but until seventy times seven.`"
And again, Christ says, "`If thy brother trespass against thee seven times in a day,
and seven times in a day turn again unto thee, saying, I repent,
thou shalt forgive him.`"
Which hard-hearted people think a great hardship,
but Christ`'s cross must be taken up and borne daily,
if we will be his disciples and followers in deed and in truth, as well as in profession.

After we had reconciled some differences at Shrewsbury,
we went to a place called Manesquan, and had a good, open meeting,
and most of the people of that place were there.
It was a good time, and I hope the opportunity will not soon be forgotten by divers.
From this place we travelled to Crosswicks, and had a good meeting, after which,
a Friend told me some would say, "`I spoke by information,
because I had opened some matters which were exactly to the state
of some there,`" But I knew nothing of their condition,
otherwise than as it was then immediately opened in my mind;
neither had I been told any thing concerning them directly or indirectly.
From thence we travelled to Burlington,
where the monthly meeting of Friends had desired that I would assist
in ending a difference which had happened through mistake,
and continued for about seven years.
Through divine assistance, our hearts being filled with the love of Christ,
we so prevailed upon the differing persons, that they gave each other satisfaction,
with hopes that they should live in love for the future;
and Friends of the place greatly rejoiced at the end of that difference.
As I went along this town,
some Friends told me of a religious people a few miles distant,
with whom they desired I would have a meeting.
I requested them to see if it would be granted, and let me know; which was done,
and we had a meeting, and were kindly received,
and the divine nature of the gospel of Christ was freely opened to them,
and in great love we parted from one another.
I travelled in this journey, about two hundred miles; and when I came home,
my dear wife and family gladly received me with hearts full of love.
And this testimony I think proper, for several solid reasons, to leave behind me,
of my virtuous and loving wife, that since we were married,
she never hindered me in the service my great Master called me to,
in all the time of our living together;
we always parted for the sake of the gospel of Christ, in pure love,
and in the same love met again.

Soon after this time I met with several great losses by sea and land,
and myself and my daughter were dangerously sick, so that our recovery seemed doubtful;
yet, through the mercy of God, we both recovered, for which I praise his name.

After some stay at home, I was moved in the love of Christ,
to visit the general meetings of Duck Creek and Salem.
At Duck Creek we had a large and satisfactory meeting,
and I appointed one at George`'s creek, which was a good meeting.
The next morning we went over to Elsinburgh, and so on to Cohansie,
where I met with two of my fellow-labourers in the work of Christ,
Thomas Lightfoot and Benjamin Kid.
We had a meeting together at Cohansie,
in which the people were exhorted to sobriety and just dealing.
The contrary of both is too obvious at such times as fairs;
there being divers people there from the fair, as well as others:
the nature of Christ`'s work in the heart was somewhat spoken to,
but it was not so open a meeting as some others,
the people thereaway being too slack and dull as to religion.
Next day we had a meeting at Alloway`'s creek,
where we all three had some pretty close work;
and from thence we went to the general meeting at Salem, which was larger than common,
on account of the said Friend Benjamin Kid being there: who, in the love of Christ,
came from England to visit the churches in this part of the world.
There were so many Friends and others here at this time, that some houses were so filled,
there was not room for all who came to lodge.

After this meeting I returned home, and in a few days went into Chester county,
and travelled about a hundred miles; and when I came home,
I understood that some for want of a true sense of the work of Christ,
had been censuring me for my much travelling and hard labour
in the work of the ministry of the gospel of Christ;
though by the same rule of judging, the apostles of Christ and our ancient Friends,
who travelled much, cannot escape their censure; for in all my travels,
I have had an especial regard to the unity of the brethren,
and never knowingly went abroad without it.
Let this caution be recorded for the instruction of all such forward judges;
let them be careful of judging Christ`'s servants, lest their words become their burden:
"`Judge not that ye be not judged,`" saith our great Lord,
for with what judgment ye judge, ye shall be judged.`"

Soon after my return from Chester county, I was at a marriage at Abington,
which was one of the most solemn I have been at; and on the 15th of the third month,
attended the youths`' meeting at Germantown, to my great satisfaction.
On the 23rd of the same month,
I went to the general meeting of ministers and elders at Burlington;
at which meeting several things relating to the gospel ministry were declared;
as its being a free, a clear, and a powerful ministry, reaching to the conscience,
and convincing of the danger of continuing in sin:
and divine charity was much recommended, without which,
all ministry is but as sounding brass, etc.
From this meeting I went with Walter Herbert into Bucks county,
and at Neshaminy we had an open, tender meeting.
From thence I went to Buckingham,
and was at a marriage of a son and daughter-in-law of Thomas Canby.
The meeting was large, and Friends well satisfied; and it was observable,
though I was very hoarse, through a cold I had taken,
and could hardly speak in common conversation, yet it was much taken away in my ministry,
so that I was carried through the service to our admiration,
for which I was truly thankful.
After this meeting I returned home with true satisfaction,
such as is much more valuable than silver and gold, two mighty idols in the world.

After a little stay at home I went on a first-day to North Wales, or Gwynnedd,
where was a pretty large meeting and many young people,
to whom I was concerned to show that Christ is the
way by which we must come into the true church,
through regeneration, and that all who invent other ways, are thieves and robbers.
I rode twenty-five miles that day, and the next day came to Frankford,
and was at the burial of an ancient Friend, Joan Orpwood,
at which was our friend John Salkeld, with whom I was the next day at Philadelphia,
at our third-day meeting, which was a good one.

On the 4th day of the fourth month, intending soon to take a journey to Long island,
and considering the uncertainty of life, I thought it a proper time to alter my will,
as I had kept one by me for divers years before.
On the 5th of the fourth month, I went to Merion to visit an ancient Friend,
John Roberts, who was sick near unto death, where I again met with John Salkeld.
The Friend expressed his satisfaction in this visit,
and we had a reward of peace in the exercise of that Christian duty of visiting the sick,
which is recommended by the apostle to the primitive churches of Christ.
After we had been some time with our said sick friend,
we went to a meeting appointed for us several days before,
which was large and satisfactory,
for which favourable visitation we blessed the great name of the Almighty,
and parted tenderly in Christian love and good will.
The Friend we went to visit, died the next day.
He was a helper of the poor, and a maker of peace in the neighbourhood; of such,
Christ said, "`Blessed are the peace makers,
for they shall be called the children of God.`"

On the 10th of the fourth month, 1724,
I had a concern to write the following epistle to Friends in the island of Barbados.

[.embedded-content-document.epistle]
--

[.signed-section-context-open]
Frankford, 10th of Fourth month, 1724.

[.salutation]
Dear Friends,

In the tender love of God, our heavenly Father, and of our Saviour, Jesus Christ, do I,
your brother, at this time greet you, and wish you health and salvation.
Understanding by a concerned Friend, that of late,
several of our friends are taken away from you by death,
a concern came on me to put you in remembrance of your latter end,
and of the cause of Christ;
and also of the prosperity of his blessed light and truth in your (in that respect poor,
though in some others, rich and luxurious) island.
The posterity of many who have been taken away there, as well as in divers other places,
having gone astray; let a weighty concern come upon you,
that it may not be so with those who are left behind.

Oh! dear Friends! let your practices and expressions manifest to the rising generation,
that the welfare of their souls, more than of their bodies, is at heart with you;
and do not indulge them in that which you were convinced to be of an evil tendency,
when your hearts were first reached by the power of truth.
How many youths have been lost, through the looseness of the example of their elders,
and through an undue indulgence of them in vanity, folly, pride,
and idleness! woful experience doth but too much declare that they are many.
Oh! they are many indeed, who have been lost by so doing! wherefore, dear Friends,
clear yourselves of your children; and if they will obstinately go astray,
faithfully bear your testimony against them, in life, doctrine,
expressions and conversation, which will witness for you when you are dead and gone,
and your heads laid in the silent grave.
Thus will your youth, through the blessing of God and your endeavours,
come up in your places, or at least you will be clear,
and their blood will be upon their own heads.
A pure, strict watch is required of you in conversation, in all those relations.
First, that God may be glorified.
Secondly, that your children may be exampled.
Thirdly, that your neighbours may be edified, or built up in pure religion.
And fourthly, that you may die in peace with Him that created you and died for you;
remembering the blessed doctrine of Christ Jesus, '`Let your light so shine before men,
that others seeing your good works,
may glorify your Father which is in heaven.`' And again;
'`Ye are as a city set on a hill,
which cannot be hid.`' As you thus train up your
children in the way which they should go,
when they are young,
you may have reason to hope they will not depart from it when they are old;
for many have been convinced of the truth, as it is in Jesus Christ,
through the good conversation of his followers.
And how can we expect to die well, if we do not live well?
Or can we expect the answer of '`Well done,`' if
we are not in the practice of doing well?

I do desire and earnestly exhort Friends to read the holy Scriptures,
and wait to feel the power from which they sprung, through the holy writers;
and also to teach them to their children.
And dear Friends, let me prevail with you in the love of God, and his dear Son,
to keep close to your meetings for the worship of Almighty God,
and for the well ordering of your Society; and do it in the meek spirit,
for that is of great price with the Lord; and when in your meetings,
get into a religious exercise and lively concern for God`'s glory,
and your soul`'s peace and prosperity, I pray the holy Lord of sabbath,
to open your hearts to him in the reading of this epistle, as mine is open to you,
my beloved friends, that you and I may be edified, though outwardly separated,
as we were when together; and if we should never meet more in this world,
that we may meet in the kingdom of God, where we may never part more.
Amen.
Hallelujah, saith my soul!

I desire this may be copied and read at the close
of one of each of your particular meetings,
and if it could be readily, in every family of Friends;
to all of whom is my very dear love in Jesus Christ, whose servant I am,
and hope to be to the end, and I am an entire lover of souls,
and a well wisher of Zion`'s prosperity.

[.signed-section-signature]
Thomas Chalkley.

--

On the 11th of the fourth month, I left home on a journey to Long island,
in order to visit Friends`' meetings, and also to negotiate some business I had there.
The first meeting I had was at Burlington,
where I had occasion to advise them to keep in remembrance
that ancient love which first united our Society together,
and in which, in times of cruel persecution,
some freely offered to suffer the imprisonment of their bodies,
to obtain the liberty of their friends in confinement.
From thence we travelled to Amboy, and over to Staten island.
The day being very hot, and the evening cold, I got a severe cold,
which I did not get clear of for about two weeks, notwithstanding which,
I went to meetings, though ill in body.
The first meeting I had on Long island was at Flushing, on a first-day,
and a comfortable meeting it was; in which was closely pressed,
the taking up the cross of Christ, by all who desire to be his disciples,
and that without it we could not be true Christians.

From Flushing we went to Mosquetto cove, and had a meeting there on third-day,
which was large, and to general satisfaction,
and some were there who were newly convinced.
I seeing the openness of the meeting, advised Friends to build a meetinghouse there,
of which they approved.
On fourth-day we had a meeting at Westbury, and fifth-day, at Cow-neck.
From Cow-neck I went to the south side of the island,
and had a meeting at Captain Hicks`'. The neighbours who
were not of our Society came generally to this meeting,
and were pressingly exhorted to come to Christ, and the way opened unto them.
It was a good time, and I thought a day of love to us all.
Before the meeting I was exceedingly shut up in myself,
so that it was very beneficial to me, among the rest,
to see how the Lord could work by his power, and unlock his treasury, as in a moment,
as he did for my poor soul at times.
Oh! may I, with Christ`'s followers and ministers, ever depend upon him, is my petition!
From Rockaway, for so is the place called, we went to Westbury,
and had a very large meeting on a first-day; and, as I was informed, some were convinced.
From hence I went to a place called Foster`'s Meadows,
where we had a large meeting in a barn.
After this I went over to the main land, and had a meeting at a place called Westchester,
From thence we went to Flushing, and had a large meeting on a fifth-day of the week,
in which the right training up of children, and careful education of youth,
was zealously recommended.

From Flushing I went to Huntington,
where some were lately convinced of the principle of truth as it is in Christ Jesus,
some of whom were excommunicated by the Presbyterians,
with whom they had formerly joined.
We had a pretty large meeting in a Friend`'s barn, where a priest opposed me,
as he also had my friend Benjamin Kid, some time before,
of which I gave an account by letter,
to my dear friends Thomas Lightfoot and Benjamin Kid, desiring them,
in their return from New England, to have an evening meeting there.
The ground of this priest`'s cavilling, or dispute, was my declaring,
that it is the light of Christ, or his spirit, which convinceth the world of sin,
and not a natural light, or the light of a natural conscience;
from whence he took occasion to charge me with denying a natural conscience,
the falsehood of which I charged upon him before the auditory, and desired him,
if he had any thing on his mind, to write to me,
to which I promised to return him an answer.

From Huntington I went to the general meeting of Friends held at Newtown,
which was so large that the meetinghouse could not contain the people,
and the weather being extremely hot, some of the people without doors were uneasy,
and went to and fro; but those that were in the house, and so near that they could hear,
were very attentive, and as far as I could learn, generally satisfied.
Our next meeting was at New York, which was the quietest meeting I ever had there;
and the few Friends at New York, and some that were there from Long island,
parted with us in the love of Christ, and in the fellowship of his blessed gospel.
I travelled homewards, having good satisfaction in visiting my friends;
and when I came there, found my dear wife and children in health, for which I bless God.

After this journey I kept to meetings at and about home as usual,
and was at the fifth-day meeting in Philadelphia,
when Samuel Preston was married to Margaret Langdale,
the widow of my dear friend and fellow traveller, Josiah Langdale.
The meeting was large,
and the parable of the virgins and the bridegroom coming at midnight, was opened,
with an exhortation to the people to be ready against that hour,
and that they should take care to have the holy oil of divine grace in their hearts.

After this meeting I had some affairs which called me into Chester county,
and on the road my horse gave a sudden and violent start out of the path,
and threw me down, and before I could gel up again, he struck my face,
and trod on my right eye with his foot, being newly shod,
which stunned me for the present.
As soon as I opened the eye which was unhurt, I perceived that I lay on my back,
under my horse`'s belly, with my head between his fore feet.
Pie stood still, and I got on my hands and knees,
the blood streaming out of my nose and right eye, and while I was bleeding,
a man and woman came by, and stayed till I was done bleeding,
and saw me mounted on my horse again.
I went forward about two miles, to the house I intended to go to,
and after riding about a mile, I met with a Friend who knew me,
and was surprised to see me so bloody, and went with me to Randal Malin`'s, a faithful,
honest Friend, who was upwards of eighty years of age,
and had suffered much for his profession of the truth in his younger years,
where they dressed my wounded eye.
I was truly thankful to the Lord for his providence towards me in this deliverance,
among many others, which he in his goodness hath vouchsafed to me.
I stayed at the Friend`'s house three nights and mended apace,
and he accompanied me to my house at Frankford, where my loving wife, with some surprise,
received me very affectionately; and through her care,
I recovered so that I could see pretty well with spectacles,
which I was obliged to use for some months.
Such accidents plainly show us the necessity of preparing for sudden death,
as we know not when, or how, we may go off the stage of this life.

On the 25th of the fifth month,
I received a letter from a person in the county of Burlington, relating to water baptism,
to which I made answer as follows:

[.embedded-content-document.letter]
--

Thy lines I received last night, in perusing of which,
there was a Christian love in my heart towards thee, though unknown by face,
and I have much freedom of mind to answer thine, according to thy request,
and my small ability.

[.numbered-group]
====

[.numbered]
_First,_ then, we are near in sentiment to each other,
in the grand Christian principle of saving religion,
which is the work of the holy Spirit of Christ upon the soul,
for that is the baptism which is Christ`'s, and is truly saving,
and absolutely necessary to salvation.
Christ`'s baptism is but one, which is with the Holy Ghost,
and with spiritual fire or water; John`'s being the element, or figure;
and Christ`'s being the spirit, power, and divine substance,
is to be with the church of Christ, and with his true ministers, to the end of the world.

[.numbered]
_Secondly,_ in answer to thy query.
Was not water baptism, that is, the element, commanded by Christ himself,
in Matt. 28:19? I answer, I believe not.
My reason is this, because the Holy Ghost, or spirit, is mentioned in the text,
in express words, and water is not; and therefore we omit going into outward water,
and for other reasons as follow:

[.numbered]
_Thirdly,_ that water baptism, which was John`'s, was practised by the apostles, is true;
but it was not practised by Christ, who, no doubt, would have done it,
if it had been absolutely necessary; for he disdained not to wash his disciples feet,
a much more despicable office, than that of the baptismal ceremony:
so because Christ did not himself practise it, nor, as we conceive,
commanded us to go into material water, we therefore, forbear it.

[.numbered]
_Fourthly,_ that the apostles did baptize with water, we deny not;
and that they were circumcised, and did circumcise, is also undeniable.
Now, must we circumcise because the apostles did, and were themselves circumcised?
Consider this carefully, and I hope that will give thee some sight or light,
concerning the dispensation of water baptism, which was John`'s baptism,
and was glorious in its day and dispensation, in pointing at Christ`'s baptism,
until it came, which was the substance, and was with spiritual fire, and spiritual water,
and will continue forever.
To Christ and his baptism, I heartily direct thee for further instruction,
in whom is life, and that life is the light of men.

====

I would write a little further concerning water baptism, on some texts of Scripture,
being Christ`'s own words, viz: '`He that believeth, and is baptized, shall be saved,
and he that believeth not, shall be damned, or condemned.`"
This must needs be understood of the spirit`'s baptism; for it would be absurd to say,
or believe, that all who are baptized with water, are saved,
or that all who are not baptized with water, are damned;
therefore it is the spirit`'s baptism,
that all professing Christianity ought to come unto, in order to witness salvation.
Again, Christ says, '`Except a man be born of water, and of the spirit,
he cannot enter into the kingdom of God.`' Some will
have this to be a mixture of the element water,
and of the spirit; but Christ says, '`It is the spirit that quickeneth,
the flesh profiteth nothing.

The words that I speak unto you, they are spirit,
and they are life.`' '`That which is born of the flesh, is flesh,
and that which is born of the spirit, is spirit,`' According to which doctrine,
I have faith to believe, that outward, fleshly, or elementary water baptism,
profits little or nothing to the soul.
Again, why should water in that place be understood of the element,
any more than fire in the other, viz: To be baptized with the Holy Ghost and with fire,
since Christ said,
'`My words they are spirit and life.`' Remember the well
of water that springs up to eternal life in the believers,
and the water that Christ gave, whosoever drank of which, was never to thirst more.
This is all spiritual, which the carnal mind cannot comprehend or enjoy,
but is witnessed by the spiritual man.
And further, if we consider what confusion there is in the world about water baptism,
it may well put a tender seeking soul upon further search into the nature of holy,
saving baptism.
The Papists have one way; the Lutherans and Calvinists another;
and the Baptists have another; and all differ so widely, that generally speaking,
they will not worship together; neither are they ever likely to be reconciled,
except they come to the holy Spirit and divine power of Jesus,
the good Saviour and precious guide of souls.
That saying of his has often been a comfort to me
in deep exercises and distresses of mind,
when he said to his disciples, '`It is expedient for you that I go away;
for if I go not away, the Comforter will not come; but if I depart,
I will send him unto you.`' I will pray the Father,
and he will give you another Comforter, that he may abide with you forever,
even the Spirit of Truth.
And when he is come, he shall guide you into all truth; he shall take of mine,
and show it unto you, and shall bring all things to your remembrance,
that I have spoken unto you.
He was to convince the world of sin, and to abide with Christ`'s disciples forever.
May the precious gift of the spirit be given to thee, and to all true seekers of God,
his Christ and kingdom, is my real desire and humble prayer to the Most High.
+++[+++See the four Evangelists for this promise, they not wording it alike.]

Having answered most parts of thy letter, I would add a few lines more, viz:
I have known some who could not be satisfied with
words about this point of baptism with water,
until Christ had by his spirit given them satisfaction in themselves;
and as thou comes more and more into close communion
with his grace and spirit in thy own soul,
I hope thou also wilt have better satisfaction than that of words only.
I have known some of the people called Baptists, who have been convinced of the truth,
according to our way and principle, to whom all the writing and disputing, and reading,
and preaching about this point, could never give full satisfaction,
until they had it inwardly and immediately from Christ,
manifested to them by his holy Spirit in their hearts, as aforesaid.
I would not, however,
be understood to be against satisfying one another as much as lieth in our power,
and as we find openness in the love of God and Christ.
And further,
I never understood that our Society were absolutely against those persons practising it,
who could see no further, or did really think in their conscience,
that it was their duty so to do; but we believe, that we see beyond the figure or shadow,
and are come to the substance, for the reasons mentioned,
and many more which might be given.

Several treatises have been published upon this subject, one of which is very full,
written before we were a people, by William Dell, a wise and learned man,
and one who had a large sense of the power of God: and among us, Barclay`'s Apology,
and a treatise by John Gratton, who had been a Baptist preacher, and one by Joseph Pike,
There is also a little book of Thomas Upsher`'s,
who was a Baptist preacher before he came to join with us, which I send thee,
with whom I was well acquainted, as also with those men who subscribed it.
If thou applies thyself to Richard Smith, of Burlington,
he is as likely as any person I know, to help thee to those books,
all which are larger on the subject, and have given satisfaction to thousands about it;
though some, as I have said, could never be satisfied with words.
In reading the latter part of thy letter I was tenderly affected,
and my prayers to the Almighty were,
that he would please to direct thee by his power and spirit,
and the grace of his dear Son, who hath said, '`He that Cometh unto me,
I will in no wise cast off.`' Now, tender friend, Christ is the true light,
that lighteth every man that cometh into the world,
by which light thou must walk to the kingdom and city of God.
He is the door into the true sheepfold: he is the truth, in whom thou must believe:
he is the divine life and light of the soul: he is the true Christian`'s all in all.
And as the kingdom is within, as said Christ, so the king is within, and without also.
He is God, omnipotent, omniscient, omnipresent, the immortal Jehovah,
and is God over all, blessed forever.
And, as a servant of his, I recommend thee, with my own soul,
unto him for preservation and direction;
for it is the great work of Christ`'s true ministers and servants, to direct the seeking,
travelling souls to him; to whom with the Father, and the eternal spirit, be glory,
now and evermore.
Amen.

[.signed-section-closing]
From thy assured friend in Christ,

[.signed-section-signature]
Thomas Chalkley.

--

The person to whom I wrote this letter, some time after informed me,
that it gave him great satisfaction.

After I had stayed at home some time,
and pretty well recovered of the hurt I received by my fall,
I visited some meetings about home, as Philadelphia, Abington, and Germantown.
In several of those meetings I was concerned to exhort Friends,
as our meetings and worship in this province of Pennsylvania,
were a kind of national worship,
to beware that they did not indulge themselves in the sins of the nations,
but to be careful to keep to the holy, self-denying life of Jesus.

On the 5th of the sixth month, between the hours of nine and ten at night,
there was an earthquake, of which many people were sensible;
and about this time many were taken off with a violent fever,
I was concerned in several meetings to put the people in mind of their mortality,
and the shortness and uncertainty of time;
and of the necessity of speedy preparation for their final change and future well-being.
In the aforesaid month I was at our youths`' meeting in Philadelphia,
where I was concerned to advise parents to do justly to their children,
in the divers relations of a child`'s state; to be just in correction,
and to be sure to give them learning, and train them up in reading the holy Scriptures,
they being able, through faith in Christ, to make us wise unto salvation.
I also was earnest in exhortation to the youth, to obey and honour their parents,
and to have a care not to be disobedient to their fathers and mothers.
I had a concern also to remind that large congregation,
that the Almighty had stretched out his arm, with his rod,
and had given the people of this land three strokes therewith,
as a gentle admonition towards heart preparation to meet him,
and to be ready for their latter end: which were first, a sickness,
or pestilential fever, which carried off many of the people.
Secondly, an earthquake, of which divers in town and country were sensible.
Thirdly, a terrible whirlwind, such as we never before heard of in this land,
that I remember.
They were admonished to take particular and special
notice of these gentle strokes of the divine hand,
for if he pleased, he could as soon take away many by sickness, as a few,
and could make us a desolation, as well as the country about mount Aetna, or Port Royal,
in Jamaica, not very far from us;
and he could also blow us away with the whirlwind of his wrath,
and could as easily have blown down all our city, as those few houses in the country.

Next day after this meeting I went with John Rodman to the
quarterly general meeting of worship in the county of Chester,
which was large and satisfactory.

The 25th of the sixth month I was at the burial of the wife of Richard Wain,
a virtuous and good woman.
Some of her last words were, "`Some men`'s sins go beforehand to judgment,
and some follow after them; and that her sins were gone before,
which was a great comfort to her, now she was going to leave the world.`"
It was a large meeting, and a seasonable opportunity at the funeral.
The people were called upon to work while it is called today, because,
as our Saviour said, the night cometh, wherein no man can work.

In this and the foregoing year, I met with various trials and exercises; as first,
great inward poverty and want.
Secondly, great losses in outward affairs.
And thirdly, the evil spirits of some were stirred up against me,
to report falsehoods concerning me, with many other sore exercises,
both inward and outward.
As to the first, I had often been tried that way, and found by experience,
that I must wait upon God my Saviour, for fresh and renewed visitations from above;
in which exercise, I had always, in the Lord`'s time, received comfort from him,
and by the same exercise I had now the same comfort also; but I thought it very long,
and the enemy did now greatly endeavour to break in upon my patience more than usual:
but my heart still depended in faith and hope upon the Lord, my Redeemer and Saviour,
and in his time he was pleased to help me, blessed be his holy arm and power forever!
Many blessed saints and servants of Jesus were brought to my mind,
who were in the like condition, so that I had a secret joy in their company,
who met with the like in their travels to the holy city.

Secondly, as to my outward losses, I thought with myself,
peradventure it might be best for me: and I remembered that many,
through the increase of outward riches, were exceedingly hurt as to their inward state;
and though I, or any good man, might be concerned for our children,
to get and leave something for them, yet I plainly saw, that generally speaking,
much riches does much hurt to youth.
This was a melancholy observation that I had made in my life and travels,
and I see at this day, that it is an universal distemper, a very few excepted;
wherefore I cried mightily to God that he would give to me and mine,
the gift of his grace and holy Spirit, whatever our circumstances might be in the world.
In this also I saw that patience was an excellent virtue,
and that the meek had the best inheritance of the earth,
if they had ever so little of it;
and that true happiness did not consist in earthly things,
which my experience had largely taught me.

And thirdly, as to the base and evil treatment I met with,
which was more than I had ever met with in all my life before,
great endeavours were used to lessen my reputation, as a man and a Christian;
all which proved false and fruitless, and in due time my innocence was made manifest.
I considered that they could not use me worse than they had done my Lord and Master,
and that the devil was angry with any who endeavoured
to dethrone him and pull down his kingdom,
at the foundation of which, through the help of my Master, I had made many a stroke,
with such weapons as he was pleased to furnish me withal.

The last of the sixth month, and the 1st of the seventh month,
was the quarterly and youths`' meeting at Burlington, at both of which I was present.
At the quarterly meeting I was concerned to open
how the church of God was governed by his spirit,
in the time of the law, and Moses was an instrument therein;
and that when it was too hard, and too much work for Moses,
he was advised to get the assistance of the elders;
and that the same power and spirit of God which was with Moses,
was upon the elders who assisted him in the affairs
of the church and congregation of the Lord`'s people;
so that it was governed by God`'s spirit, and is to be governed by the same still,
and not by the will of man, nor according to the will of man, in his corrupt nature.
And when Israel went from God`'s power and spirit, the Lord left them,
but at last sent to them his only begotten Son, our dear Lord and Saviour Jesus Christ;
and he was, and ever is, to be governor of his church, through his holy Spirit,
of which he told his disciples, that he would pray the Father,
and he should send unto them the Comforter, the Holy Ghost, or holy Spirit,
the spirit of truth, and that he should abide with them forever,
and should lead and guide them into all truth; which sweet and precious promises,
the true believers do witness to be fulfilled at this day.
Glory to his name forever, he is the wonderful Counsellor, mighty Saviour,
and Prince of peace! of whose peace and government there shall never be an end,
and upon whose shoulder the government is to be forever.
Friends were exhorted to pray and wait for his holy power and spirit,
and to be sensible of it in the discipline and government
of the church now in this gospel day,
in which is a brighter manifestation of God`'s love, through his Son,
than in the time of the law.
The youths`' meeting was also large, and divers testimonies were borne,
by way of exhortation and counsel to the youth.
They were with much tenderness advised to take counsel of their elders,
and were shown how it fared with some young men,
who slighted the advice and counsel of the elders; and that one, when on a dying bed,
cried out in the bitterness and agonies of his spirit,
"`Oh! that I had taken the counsel and advice of my friends,
for then I had not been here, nor in this condition.`"
They were advised to beware of keeping bad company,
and spending their precious time in taverns,
which hath undone many fair and promising youths:
and it was shown how a young man might cleanse his ways, by taking heed thereto,
according to the Word of God, which liveth and abideth forever,
and which the holy Scriptures proceeded from;
and they were earnestly exhorted to read and practise what was written therein.
A very tender time we had in prayer to God, through his dear Son,
to preserve us all in his fear, both youth and aged; and so our meeting broke up,
and we parted in the sweet love of God, and his Christ, our holy Saviour.

My troubles in the world, and in the things of it, being many,
and my outward losses great; as also was my inward poverty of spirit, I took my pen,
and wrote one day as follows: "`Oh! if it be right in the sight of God,
how do I long to be unclothed of this frail, mortal body,
that my soul might mount up to the ethereal plains,
and repose itself in the arms of its Maker and most sweet Saviour forever.`"

Being at and near home some time after I came from Burlington,
I visited the meetings of Germantown and Philadelphia, which were large,
and some sense of truth was in the hearts of divers.
I was concerned at that meeting at Philadelphia, to let the people know,
that as God had blessed the people of that city, and the province,
with spiritual and temporal blessings, and made the land fruitful,
enriching many of the inhabitants, he now expected from them fruits of piety and virtue;
and that if there was not a stricter walking with God in Christ Jesus,
they might expect his divine hand, which had visited them with favours from heaven above,
and from the earth beneath, would visit them with a rod,
with which he had already given them some gentle strokes.

Our yearly meeting was this year at Burlington,
for the provinces of New Jersey and Pennsylvania, to attend the service of which,
our quarterly meeting appointed me, with divers others.
It was a large and comfortable meeting,
and many went home thankful to the holy name of God and Christ, that they were there.

I shall here transcribe part of a letter which my dear father wrote to me,
when above eighty years of age, he having been a minister of Christ above forty years;
viz:

[.embedded-content-document.letter]
--

[.salutation]
Loving son, Thomas Chalkley,

Thine dated the 11th of the tenth month, 1723, I received,
and was very glad to hear of your welfare, and that the Lord hath given you children:
and I pray the Almighty God, that he may preserve them with you,
that they may be a comfort to you in your latter days;
and that if the Lord may be pleased to continue them with you, they may,
as they grow in days, grow in grace,
and in the knowledge of our Lord and Saviour Jesus Christ;
and that the Lord may be pleased to preserve us all to the
end of those few days we may have in this world,
that we may lay down our heads in peace,
and in the full assurance of everlasting blessedness, forever and evermore.

I bless the Lord that he hath preserved me sensible of his blessed and holy Spirit,
whereby my understanding is clear and well, considering my age;
and the Lord in his great lovingkindness, I do feel to help me to my great satisfaction,
in my little service for him.

With repeated love to you all, I rest thy aged, and thereby, through pain,
afflicted father,

[.signed-section-signature]
George Chalkley.

[.signed-section-context-close]
Southwark, London, 5th of Sixth month, 1724.

--

To see my dear father`'s handwriting, now he was above four-score years of age,
was very affecting to me; and the more, because I expected it might be his last,
which it was.
The answer I sent to my dear father`'s letter, is as followeth:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Frankford, 22nd of Eighth month, 1724.

[.salutation]
My dear father,

Thine, per James Wilkins, I received with joy,
and was greatly comforted to hear that thou wast yet alive:
and especially that thou art favoured, now in thy old age,
with a sense of the gift of God, through the holy Spirit of his dear Son,
our blessed Lord and Saviour, Jesus Christ.

The reading of thine, did refresh and tender my heart,
not expecting many more such epistles from thee, by reason of thy great age.
But, my very dear and truly honoured father, if we should never hear from,
nor see one another more in mutability, yet are we, while here on earth,
as living epistles in one another`'s hearts, written by the finger of God.
I have hope also, that we shall meet where we shall never part more,
in the glorious kingdom of God and his Christ.

With unspeakable love from self and wife, to thee, my dear and aged father,
and all relations and friends,

[.signed-section-closing]
I remain thy loving and dutiful son,

[.signed-section-signature]
Thomas Chalkley.

--
