== Chapter VI

In this year, 1724, I met with various trials, afflictions and tribulations;
and had not the secret hand of the Lord, which I felt underneath,
borne up my spirit from sinking, I think I could not have waded through them.

I was now removed, as already related, into the country, for retirement,
which I greatly loved and delighted in; but as soon as I was a little settled there,
the enemy of all good endeavoured to disquiet my repose,
by stirring up some bad people against me, who lived near,
and in time past had fawned upon me.
To add to my afflictions, I lost a vessel, in which, I suppose,
I had upwards of five hundred pounds; another vessel came in almost a wreck,
in which I suffered in my interest several hundreds more, and a third I heard of,
in which I had the like loss;
and about the same time I had also a good new barn burned to the ground in a few minutes,
so that I was exceedingly stripped that way.

To add yet more to my exercise, I was sorely afflicted with sickness,
having a swelling in my jaws, mouth, and throat,
that I could neither speak nor swallow for some time, nor eat nor sleep,
for about seven days, as I remember, without great difficulty.
What the distemper was, we could not be certain.
Some supposed it to be the quinsy, others an imposthume;
also my only daughter at the same time was likely to die; and as for my own part,
I was very willing to go, if it so pleased God;
for I saw through the deceit of the world,
and that the friendship of it was not permanent.
And in my sore afflictions of body, mind, and interest, it fared with me as with Job,
for divers of my pretended friends added to my afflictions by undue reflections;
whom I pray the Lord to forgive for his Son`'s sake!
At these times, the remembrance of that saying of Christ,
that the very hairs of your head are numbered,
supported me in hope that all would work together for good.

When I got better, so that I could go to meetings, I went to Germantown, Abington,
Philadelphia, and Darby.
My first going abroad was to Philadelphia, where, on a first-day, we had a large meeting,
and divers things were opened in my mind.
I told them they had Moses and the prophets, and Jesus Christ,
who has arisen from the dead; for neither death, hell,
nor the grave could detain the Lord of life and glory.
And I was opened to declare to them,
that they had a great advantage of the coming of Christ,
not only in his appearance at Jerusalem, but as he came to, and spoke in the heart,
by his inward and spiritual appearance; and that this gospel dispensation was,
by his coming, made more conspicuous, bright, and glorious, than that which went before.
Friends were very glad to see me abroad again,
they having expected daily to hear I was dead, and there was tenderness over the meeting,
and God over all, through his dear Son, our Lord Jesus Christ, was praised and glorified,
who is worthy forever.

In this year two sober young women, Elizabeth Levis and Jane Fenn,
were concerned to visit Friends in the island of Barbados,
and they meeting with some discouragement, in Christian love,
I wrote them the following letter to encourage them in the work of Christ.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Frankford, 1st of Twelfth month, 1724-5.

[.salutation]
My dear friends, Elizabeth Levis and Jane Fenn,

Understanding by our friend, Grace Lloyd,
that you have proposed your intention of visiting the few Friends in the island of Barbados,
and that you meet with some discouragement inwardly and outwardly,
it is in my mind to comfort and strengthen you in so great and good an undertaking,
and honourable work, as is the cause of Christ, who, for our sakes,
crossed himself abundantly beyond expression,
more than is possible for us to do for his sake, or the sake of his people,
whom we may so entirely love, as to lay down our lives for his and their sakes.
But what are our lives to the life of the only begotten Son of God?
And truly, we must give them up often, if we have the cause of souls at heart;
and then he often gives them to us again, glory to his holy name forever!
As Christ said, "`He that will save his life, shall lose it,
and he that will lay down his life for my sake and the gospel, shall find it;`"
which reacheth your case in this undertaking.
And indeed, some of our lives, in our own sense, are hardly worth mentioning,
considering the cause of Christ.

And, dear children of our heavenly Father, I may, through some good experience,
truly inform you, that there is much openness in many people on that island,
and good encouragement I have had from above, in my visiting the people there; though,
true it is, the inhabitants too generally, are luxurious, and much given to vanity:
yet I have this seal in my heart,
that the Lord hath a seed in that place who desire to serve him,
and that seed will surely join with you in your exercise,
and you will be comforted one in another, and in the Lord.
And that there are differences among them, is also true;
but they have the more need of being visited by such, who are,
through their wise conduct and restoring disposition,
likely to heal those breaches which are, or may be among them.
Some, indeed, have gone among them, and have done hurt,
by a rash and turbulent management, and by so doing, have rather made the breaches wider,
than by a meek and loving, as well as lowly disposition,
lessened their differences and healed them.

And, tender friends, though it may seem hard for you in several considerations,
to give up to go to sea, and also to divers who love you, and are nearly related to you,
know ye, and such so concerned, that the Lord is stronger than the noise of many waters,
and than the mighty waves of the sea.
And I really believe that you, as well as my soul, with all the servants of Christ,
will experience it to be so, as David did, whose words they are.

I remember the words of our great Lord and Master, Jesus Christ,
when he sent forth his servants to preach his gospel;
"`I send you forth as lambs among wolves.`" No question but you, like innocent lambs,
before your return, if it please God to give you to us again,
may meet with the wolf`'s spirit, or the spirit of the beast,
in some among whom you may travel; then will the counsel of Christ,
added to his commission, be good for you to keep close to; "`Be ye wise as serpents,
but innocent or harmless as doves.`"

And, dear maidens, as your cross is great, you being two innocent young women,
in giving up your names to cross the sea, which I know is a great trial,
the seamen too generally, being rude, dissolute people; so your crown will be great also.
I have known that by keeping near to Christ, and his truth and power,
there hath been a wonderful reformation sometimes in several of those rude seamen;
and some have been so far convinced, as to be exceedingly kind,
and to speak well of Friends and their conversation,
when it has been coupled with the fear and wisdom of God.
When I have gone to sea, I always found a religious and Christian concern upon me,
for the poor sailors, the good effects of which have been much more than I may speak of;
but give this little hint for your encouragement and information.

Well, dear souls, if you go, I believe the Lord will go with you; and sure I am,
that my spirit will also go along with you, which will not hurt you,
if it do you no good.
And although my exercises and tribulations of late have been very great,
both spiritual and natural, yet my very heart within me affects the cause of Christ,
according to the best of my understanding:
and I heartily wish well to all my fellow-labourers, who are faithful,
painful servants of Christ, and disinterested,
except as to the interest which they desire in Christ and his kingdom,
for the sake of which, they love not their lives unto death.

I must now take leave,
after putting you in mind to remember your poor friend and brother,
when before the throne you are supplicating the Father of mercies in secret,
even as my heart is tenderly bowed and broken into tears on your behalf at this time.
The Lord be with you, and sanctify the present exercise and concern that is upon you,
and you to himself, with all the faithful lovers and followers of the Lamb,
"`through his word, whose word is truth.`" I am your friend and brother,
in the fellowship of the gospel of Christ Jesus, our great Lord and good Master;
and blessed are all those, who, by their fearing to offend him,
manifest him to be their Master, and by their honouring him,
manifest him to be their Lord.

[.signed-section-signature]
Thomas Chalkley.

--

In the twelfth month I went to the quarterly meeting of Friends, held at Providence,
in Chester county, for discipline and worship.

It was large, and a concern came upon Friends to suppress excess in eating and drinking,
and great entertainments at marriages and funerals,
and spending time idly in tippling houses;
also in several other things for the well ordering our Society,
in which there appeared great love and unanimity.
The people were reminded of God`'s love to them, and many favours were recounted to them,
which he had showed the inhabitants of the land, which were very singular,
and that he expected they should bring forth fruits answerable to the labours of love,
which the Lord had bestowed upon them.

About this time I had it in my mind to write to one who
was conscientiously concerned to preach the gospel of Christ,
but was under great exercise on that occasion.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Frankford, 24th of Twelfth month, 1724-5.

[.salutation]
My friend,

Since I last saw thee and conversed with thee, thou hast often been in my mind,
and thy exercise has come before me;
and not having an opportunity to converse with thee personally,
I take this way of communicating my mind, hoping, in Christ,
thou wilt reap some satisfaction and advantage thereby.
I think I know thou art concerned for Christ`'s cause,
as also was that eminent minister Apollos,
who yet was instructed more perfectly by good Aquila and Priscilla.
The subject on which I have it in my mind to write to thee,
is the ministry of the gospel of Christ Jesus,
which I believe to be very different from that which
it is taken for in most parts of the world,
by many professing Christianity.
First, the greatest part of Christendom, so called, calls and elects its ministers,
and will not call them unless they have school learning,
although Christ called and chose unlearned men, as to that sort of learning,
and the apostles were called, "`Not according to the will of man,
but by the revelation of Christ Jesus.`" Christ thanked his Father that "`He had revealed
the mysteries of his kingdom to babes and sucklings.`" The wise Jews,
the scribes and pharisees, admired at the apostles, who so powerfully preached Christ,
and were so wonderfully carried forth in their ministry,
and yet few of them were men of learning.
The call, election, and wages of Christ`'s ministers, are spiritual, and not carnal;
and therefore, their ministry is with divine life and power,
by which they are qualified for this service, without either study or premeditation:
though it is not denied that Christ may show a minister beforehand, what he shall,
or is to speak, at such a time or place, as he may see meet.
But studying, or writing sermons, and afterwards preaching,
or rather reading them to the people, is not the practice of the true minister of Jesus,
our great Lord and Master; of which, I do believe thou hast a real sense.

I shall impart to thee something of my own experience
for thy edification in this great work,
viz. As in the work of conversion or regeneration,
there is a growth and increase from the state of a child to that of a man in Christ,
so in the work of the ministry, or preaching the gospel,
there is also a growth from a babe to an able minister,
in all which the power and grace of the holy Spirit must be our guide,
our help and support.
Keeping close to this, we shall increase in divine wisdom and sound judgment,
and our hearts and understandings will be more and more opened and enlarged.
The apostle Paul said, "`When I was a child, I spake as a child, understood as a child,
and thought as a child;`" and yet he was a child of God and minister of Christ;
and as he grew in his gift, and in Christ`'s grace,
he became an eminently serviceable instrument in the hand of God.
Now a child`'s state in the ministry is too much overlooked by many,
some thinking to be men as soon as they are brought forth into the ministry;
and according to my observation, divers have been at a loss, and some quite lost,
for want of a patient continuing in well-doing;
and not waiting to feel a growth and increase from above,
have gone on in their own strength and will,
perhaps against the advice and instruction of a sound and honest Aquila or Priscilla,
and have been hurt; and some who had received a gift,
have had that same gift taken from them, even by the Lord, who gave it them.

A true minister of Christ is to take no thought what to say,
but in the same hour that which he should speak to the people, will be given him,
that is, in a general way, and if it is not given from above,
I believe he or she ought to be silent; for they receive freely,
if they do receive any thing from Christ, and so they ought freely to administer;
and where little is given, little is required,
all which is plain from Christ`'s own words in the New Testament;
and Christ`'s cross is to be taken up by his ministers in their preaching,
as well as in their conversation.

It is a practice with which the holy Scriptures have not acquainted us,
that the ministers of Christ should take a verse, or a line, out of the holy Scriptures,
and write, or study, beforehand, a discourse on it, and preach it, or rather read it,
to the people.
The holy men of old, as we read both in the Old and New Testament,
spoke as they were moved by the Holy Ghost, and by it they were gifted for convincing,
converting, and reforming the world, and for comforting and edifying the saints,
quite contrary to the latter practice of modern reading divines, who dispute, write,
and preach, against the immediate revelation of the spirit of Christ,
and therefore cannot be his ministers, but must be the ministers of antichrist,
and ministers of the letter, and not of the spirit of Christ, or of his gospel.
And where the apostle says, "`When I was a child,
I spake as a child,`" I take him to point at being
brought newly into the work of the ministry,
as well as the work of conversion,
and that he useth those expressions by way of comparison,
and therefore I compare it thus: a child when it first begins to speak,
speaks but a few words, and those stammeringly sometimes, and its judgment is weak,
and he must be put upon speaking by his father over and over, if he be a backward child;
otherwise, if he be forward, and speaks too much, he is curbed by a wise father.
Thus, according to my observation,
it hath pleased our heavenly Father to instruct his children in the ministry,
and as a child in Christ, I would speak a little of my experience to the children of God.

When I first felt a necessity on me to preach the gospel,
I had but a few sentences to deliver, in great fear and tenderness, with some trembling,
with which my brethren were generally satisfied and edified.
After some time I felt a concern to preach the gospel in other countries,
and to other nations, than that in which I was born, which to me was a very great cross;
but feeling the woe of the Lord to follow me in not giving up to it,
after some time I took that cross up, for Christ`'s sake and the gospel`'s;
and in taking it up, I experienced the truth of the apostle`'s doctrine,
that "`the gospel of Christ is the power of God unto salvation,
to every one that believeth.`" Thus, through a continual labour and spiritual travel,
I witnessed a growth in experience and an enlargement in expression and heavenly doctrine;
and my heart was mightily enlarged to run the ways of God`'s commandments,
and divers were convinced, and some, I hope, thoroughly converted, and many comforted,
and God, through the ministry of his dear Son, glorified,
who only is thereof worthy forever.

In all this I have nothing to boast of or glory in, saving in the cross of Christ;
for what is Paul, or Apollos, or Cephas, but an instrument?
I would not be understood to compare myself with those apostles,
but to endeavour to follow them as they followed Christ.
Christ is all in all: he is the great Teacher of teachers,
and the highest schoolmaster of all: and he says,
"`Whosoever doth not bear his cross and come after me, cannot be my disciple.`"

We do not find any where in the New Testament,
that Christ`'s ministers or messengers were only
to speak or preach to one meeting of people,
or that they were called or hired by men;
for then it would have been necessary that man should pay them; but Christ says,
"`Freely ye have received, freely give; and go forth,`" etc.

And my friend, I find to this day,
that it is safe for me when I am ministering to the people;
when the spring of divine life and power,
from which sound truths and edifying matter spring and flow into the heart, abates,
or stops, to stop with it, and sit down, and not to arise,
or speak publicly to the people, without some spiritual impulse or moving, and openings.

I would have this taken no otherwise,
but as one friend and brother opening his state and condition to another for edification,
and for strengthening each other in Christ.
And as I fear lest I should exceed the bounds of a letter,
therefore shall conclude thy real friend in Jesus Christ;

[.signed-section-signature]
Thomas Chalkley.

--

The 25th of the twelfth month I was at the burial of the wife of Randal Speakman.
It being our fifth-day meeting, divers sober people not of our persuasion, were there,
and I was drawn to speak of the death of Christ and his merits,
and to show them that there is no merit in the works of man, as he is man,
or in a formal righteousness or holiness.

In our yearly meeting at Burlington,
it was agreed that the families of Friends should be visited, and soon after,
our monthly meeting appointed me, with other Friends,
to visit the families of our meeting;
in which visitation many were comforted and edified, both of the youth and aged;
and we could truly say, that the power and grace of God, and the sweet love of Christ,
accompanied us from house to house, to our mutual comfort.
We were so extraordinarily opened and guided to speak
to the states of the people in their families,
who were unknown to us, that some of them were ready to think we spoke by information,
when in truth we were clear of any such thing,
and only spoke from what was immediately given to us,
without any information from man or woman; which to us was sometimes very wonderful,
and caused us to praise the great name of the Lord.

The general meeting held at Philadelphia in the first month, was a solid good meeting,
and ended in a sense of grace and truth, which come by Jesus Christ.
Next day being our week-day meeting, our dear friends Elizabeth Levis and Jane Fenn,
took leave of us, they intending for the island of Barbados;
and it was a parting meeting that will not soon be forgotten by some of us then present.

After this meeting I went to Burlington, to visit one who was sick,
and under some trouble of mind for going astray,
and greatly desired to come into the right way,
with whom I had a good seasonable meeting, to her comfort and my own satisfaction.
Upon this visit I would remark, that it is a great pity that youth,
when in health and strength, should put off the work of their salvation,
and forget the Most High, till either sickness or death overtakes them.
And then, Oh! the bitter piercing cries and groans, and terrible agonies the soul is in;
which, by timely repentance and amendment of life, might be avoided.

I was afterwards at meetings at Philadelphia, Merion, Germantown,
etc., and had some service and satisfaction therein.
On the 2nd of the second month, the Friend whom I visited, as above, was buried,
and the relations of the deceased sent for me to the burial.
The person being well beloved,
there was a large appearance of people of divers persuasions,
and we had an opportunity at this funeral to exhort
the people so to live that they might die well;
and that the way to die in the favour of God, was to live in his fear.
Charity to those who dissent from one another,
was pressingly recommended from the apostle`'s words,
that "`If we had faith to remove mountains, and to give all our goods to the poor,
and our bodies to be burned, yet if we wanted charity, we were but like sounding; brass,
and a tinkling cymbal.`"
And also our belief of the doctrine of the resurrection of the dead, was asserted,
in contradiction to that gross calumny cast on our Society, of denying it.

The latter end of the second month, I was at a marriage at Horsham,
at which was present William Keith, our governor,
and I was concerned to speak of the end of that great ordinance,
and of the happiness of those married persons who
fulfill the covenants they make in marriage,
and what strength and comfort the man is to the woman, and the woman to the man,
when they keep their covenants, and that they are the contrary when they break them,
I also opened the methods prescribed by our discipline, to be observed in marriages,
and our care to prevent any clandestine marriages amongst us.
After this meeting I returned home, without going to the marriage dinner,
as I generally avoided such entertainments as much as I could, having no life in,
or liking to them, being sensible that great companies and preparation at weddings,
were growing inconveniences among us,
which I was conscientiously concerned to discourage.
A few days after my return home, at our meeting at Frankford,
I was concerned particularly to exhort Friends to keep to plainness in language, dress,
etc., according to the examples given us in the holy Scriptures,
particularly that of Daniel and his companions;
and to caution against vain and indecent fashions, which, with concern,
I have observed to prevail too much among some who make profession with us.

In this second month I went to the yearly meeting of Friends at Salem,
and by the way had two meetings at Woodbury creek.
At Salem we had a large meeting, and our gracious Lord was with us,
bowing many hearts before him, and many testimonies were given of the goodness, love,
mercy, and grace of God, and his dear Son, our Lord Jesus Christ.
From Salem we travelled to Alloway`'s creek and Cohansie, and from thence to Elsinburgh,
and ferried over the river Delaware, with our horses to George`'s creek,
and had meetings at all those places.
At George`'s creek, one not a Friend, came to me after meeting,
and said he thanked me for my advice and counsel,
and seemed heartily affected with the doctrine of Christ.
From George`'s creek we travelled to Nottingham, and had a large meeting on a first-day,
and another, very large, on second-day, where were many people of divers persuasions.
The house could not contain us, so that we met in an orchard.
A solid meeting it was; wherein the mighty power of the Creator was declared,
as also the divinity of Christ, and his manhood,
and the people were exhorted to be careful of forming any personal ideas of the Almighty;
for the holy Scriptures do plainly manifest, that God is a wonderful, infinite,
eternal spirit, and therefore is to be worshipped in spirit and in truth,
and outward representations of the Lord Jehovah, border on idolatry.
Much was delivered on that head; and I was told after meeting,
that divers Papists were there, though I knew nothing of it.
From Nottingham I went to Newcastle, had a meeting there, and then visited a sick Friend,
with which he expressed much satisfaction; and then went on to Center, Kennet,
and Marlborough, and so to the monthly meeting at New Garden,
where we had a large open meeting, wherein was shown,
that those who meddled with our discipline, in the will, nature, spirit,
and wisdom of man only, could do but little service, and that our discipline,
as also our worship and ministry, ought to be performed in the wisdom and power of God,
through the grace and spirit of Christ.
From New Garden we went to Birmingham, had a large meeting,
and I was much drawn forth to the youth, of whom many were there.
We then went to the quarterly meeting for discipline and worship at Concord,
in Chester county, which was larger than I had ever seen there before.

In the meeting of discipline.
Friends were exhorted to keep to the cross of Christ,
and to speak to matters in the fear of God, and to avoid and shun as much as in them lay,
self-will, humour, pride, and passion; showing that the rough, crooked, unhewn,
unpolished nature of man, could never work the righteousness of God,
and is contrary to the meek, self-denying life of Jesus.
John Salkeld and Jacob Howell,
then signified that they were going to visit Friends on Long island and Rhode Island.
The sense of the call, labour, and work of the ministry of the gospel,
and of the love of Christ, in the freeness of it, to mankind,
took some good hold on divers in that meeting, and the great name of God,
and his dear Son, through the holy Spirit, was glorified.

From this meeting I came home, having been out on this journey nearly three weeks,
was at twenty meetings, and travelled more than two hundred miles,
and found my wife and children in health, and we rejoiced to see each other;
but my rejoicing was in fear, even almost to trembling,
lest I should be too much lifted up, when things were agreeable to me.

After my return home, I went to several neighbouring meetings,
and on a fifth-day was at Philadelphia,
at the marriage of Richard Smith and Elizabeth Powell.
The meeting was large, and the marriage solemnly celebrated,
and the people were earnestly entreated to love Christ above all,
and to manifest that love by keeping his commandments,
and that not in show or words only, but in the heart and affections.

About the latter end of the third month,
I went to the quarterly meeting of ministers and elders for the county of Burlington;
and from thence to Stony-brook; where, on a first-day,
we had a large meeting in Joseph Worth`'s barn, which was crowded with people,
and was a solid, good time.
From Stonybrook I went to Crosswicks, and was at their youths`' meeting,
which was the largest I had seen in that place.
I told them they might say as the sons of the prophets did,
that "`the place was too straight for them,`" and advised them to enlarge it.
I was glad to see such a large appearance of sober people,
and so great an increase of youth, in this wilderness of America,
and exhorted them to live in the fear of God,
that his blessings might still be continued to them;
and an exercise was on my mind for the welfare of the young people,
to show them the danger of sin and vanity, and of keeping ill company,
and following bad counsel; and that the young king, Rehoboam, Solomon`'s son,
lost the greater part of his father`'s kingdom,
by following the company and counsel of vain young men;
and that many young men in this age had lost and
spent the estates their fathers had left them,
by the like conduct, and brought themselves to ruin,
and their families to poverty and want.
Divers lively testimonies were delivered in this meeting,
and it ended with adoration and praise of Almighty God;
and although the meeting held more than four hours,
the people did not seem willing to go away when it was over; for indeed it was a solid,
good time.
The business of the quarterly meeting was carried on in peace and love,
that being the mark by which the disciples of Jesus were to be known,
and Friends were exhorted with a great deal of tenderness to keep it.

In this journey I travelled about ninety miles, and was at four meetings,
being from home four days, and was much satisfied in my journey;
but met with some exercise when I came home,
hearing of some losses and damage to my estate; so that I found after I had,
according to my best endeavours, done the will of God, I had need of patience,
that I might receive the promise.
I was sensible of the messenger of Satan, the thorn in the flesh,
of which the apostle speaks.

About this time a loving friend of mine informed me,
that one whom I very well knew in Barbados, a minister of our Society,
had gone into an open separation, so as to keep meetings separate from his brethren,
and contrary to their advice.
I was concerned in love to write a few lines to him,
to remind him of the unhappy state and end of such, who,
notwithstanding the brotherly love and kind treatment of Friends, had separated from us,
and losing the sense of truth which had made them serviceable in the church,
were actuated by a rending, dividing spirit,
by which the enemy of our happiness had so far obtained his end,
as to make some disturbance for a time; but few, if any, of these separatists,
have had further power than to promote and maintain
their separate meetings during their own lives;
such meetings having, in every instance I have known, except one,
and that lasted not long, dropped on the death of the founders.
And though we think it our duty to testify against, and disown all such;
yet this disowning is only until the persons offending, from a real sense of,
and sorrow for, their faults, acknowledge and condemn the same;
then the arms of Christ and of his church, are open to receive and embrace them.
I therefore earnestly besought him to consider the
danger of offending any who love and believe in Christ,
though ever so little in their own or other men`'s esteem,
for we cannot have true peace in departing from the pure love of God, his truth,
and people; to which I added the following sentences out of the New Testament:

[.numbered-group]
====

[.numbered]
1+++.+++ "`By this shall all men know that ye are my disciples,
if ye have love one to another.`"
Do not lose this mark.

[.numbered]
2+++.+++ "`We know that we have passed from death unto life, because we love the brethren.
He that loveth not his brother, abideth in death.`"

[.numbered]
3+++.+++ "`He that loveth not, knoweth not God; for God is love.`"

[.numbered]
4+++.+++ "`He that dwelleth in love, dwelleth in God, and God in him.`"

====

About the latter end of the fourth month I was at a meeting at Abington,
occasioned by a burial; and in the beginning of the fifth month,
I was at a marriage in Philadelphia; and was soon after on a first-day,
at two meetings at Germantown,
where I went to visit a Friend who had not for some months been at meeting,
being in a disconsolate condition, I invited her to meeting,
where the love and goodness of Christ to the poor in spirit, was largely manifested,
and the Friend after meeting, said she was better, and afterwards recovered,
and kept to meetings.
I was frequently at the week-day meetings at Philadelphia;
for I thought that week not well spent, in which I could not get to week-day meetings,
if I was in health.

In this month I was at the burial of George Calvert,
who was one of a sober life and just conversation,
and being well beloved by his neighbours, left a good report behind him.
Soon after which I was at Merion meeting, which was large and solid:
the people were tenderly exhorted, that neither outward favours, nor spiritual blessings,
might make them grow forgetful of God;
but that in the sense of the increase and enjoyment thereof,
they might be the more humble;
and forasmuch as the Christian church in former ages
was corrupted by temporal riches and power,
it was intimated, that as we had favour shown us from the government,
and increase of outward things, we should be very careful not to abuse those privileges,
by growing proud and wanton, or envious and quarrelsome; but "`to do justly, love mercy,
and walk humbly with God.`"

In this month I was at Middletown, in Bucks county,
at the burial of my dear and intimate friend, John Rutledge, who died very suddenly,
at which there were above one thousand people: he was well beloved among his neighbours,
and was a serviceable man where he lived.
I admired to see such a number of people collected upon so short a notice,
he dying one day in the afternoon, and being buried the day following;
divers testimonies were borne concerning the wonderful works and ways of God.
It was a solid bowing time, wherein many hearts were broken and melted into tenderness.
After meeting a young man came to me trembling, and begged that I would pray for him,
for he had spent much of his time in vanity, and had strong convictions for it,
and had been greatly affected and wrought upon that day.
I exhorted him to deny himself, and to take up his cross, and to follow Christ,
who hath said, he would in no wise cast off those who came to him in true faith.
He went from me very tender and loving, being broken in his spirit.

From thence I went to Gwynned, or North Wales, and on the first-day of the week,
had a very large meeting.
In the morning of the day a voice awoke me, which cried aloud, saying,
"`Rewards and punishments for well and evil doings are sealed
as an eternal decree in heaven,`" which confirmed me that
mankind are happy or unhappy in that world which is to come,
according to their deeds in this life; if their deeds be good, as Christ said,
their sentence will be, "`Come, ye blessed;`" if their deeds be evil,
"`Depart from me all ye that work iniquity,`" and "`Go, ye cursed,`" etc.
And, "`If thou doest well, shalt thou not be accepted?
And if thou doest not well, sin lieth at the door.`"
And again, "`I have no pleasure in the death of the wicked,
but that the wicked turn from his way, and live.`"
These, with many more texts of the same nature, contained in the holy Scriptures,
are contrary to the doctrine of personal election and reprobation, as some hold it.
We had a meeting in the afternoon of the same day, which was satisfactory to many;
our hearts being filled with the love of God, for which we thankfully praised him.
The next day we had a meeting of ministers,
in which they were exhorted to wait for the gift of the Holy Ghost,
without which there can be no true minister or ministry.
I was concerned to put them in mind to keep close to Christ, their sure guide and bishop;
to be cautious of going before, lest they should miss their way,
and of staying too far behind, for fear we should lose our guide;
and to be careful to keep a conscience void of offence towards God, and also towards man;
that we might say to the people, truly, follow us as we follow Christ;
that our conversation might confirm and not contradict our doctrine,
for our Saviour says, "`By their fruits ye shall know them;
men do not gather grapes of thorns,`" etc.,
and he charged his followers not to be like such as say, and do not.
The next day we had another very large meeting there,
in which many things were opened and declared,
tending to establish and build us up in our faith in Christ.
After this meeting, parting with my friend John Cadwallader, who accompanied me,
I came homeward, lodging that night at Morris Morris`'s, whose wife was very weakly,
with whom we had a tender time.

The 9th of the fifth month, I was at the general meeting at Germantown,
which was a large and good meeting.
Next day I went to visit Jane Breintnall, who was seized with the palsy,
and the Lord was pleased to comfort us together, as she expressed,
to our mutual satisfaction.

On the 30th of the said month, was our quarterly meeting of ministers at Philadelphia,
where humble walking with God was recommended and prayed for,
and it was desired that ministers might be exemplary therein,
having Christ for their pattern.

On the 1st of the sixth month, I was at our meeting at Frankford,
which was dull to me and divers others,
a lively exercise of spirit being much wanting among many,
and close walking with God in conversation.
If we would really enjoy the love and presence of Christ in our religious meetings,
we ought to keep near to him in our daily conversation; and that we might do so,
was humbly desired in supplication and prayer to God.

The young man who came to me under great concern of mind,
after the funeral of John Rutledge, wrote to me,
that he was followed with the judgments of God for his manifold transgressions,
desiring that I would pray for him.
In answer to his letter, I wrote to the following effect.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Frankford, 7th of Sixth month, 1725.

Thine from Burlington, of the 26th of fifth month, I received,
by which I perceive the hand of the Almighty hath
been upon thee for thy vanity and folly.
I desire that thou may be very careful to keep close to that hand,
and do not go from under it,
but mind the light of Christ that hath discovered God to be great and good,
and his dear Son to be thy Saviour, and sin and Satan to be evil, which evil,
if thou follows it, will certainly bring thee to destruction and eternal woe;
but if thou follows Christ,
and walks according to that light by which he hath
manifested sin to be exceedingly sinful;
in his time, as thou waits in patience,
he will bring thee through his righteous judgments unto victory.

Wait, Oh! wait in patience upon God,
if it be all thy days! '`I will bear the indignation of the Lord,
because I have sinned against him.`' Again,
'`All the days of my appointed time will I wait, till my change come.`'

Thou art young in years, and young in experience in the work of grace,
wherefore advise with solid, good men,
if thou meets with inward or outward straits and difficulties,
for the enemy will not easily let go the hold which he hath had of thee;
therefore walk circumspectly, and shun evil company.
As to praying in a form of words, without the spirit helps,
in order to open them according to thy state and condition, that will not avail:
a sigh or groan, through the help of the spirit, is much more acceptable to God,
than any forms without it.

That in the Lord`'s time thou mayest enjoy the reward of peace,
is the desire of thy friend,

[.signed-section-signature]
Thomas Chalkley.

--

The young man took this counsel well, and kept to meetings,
and behaved soberly for a time, but afterwards ran out, kept bad company,
took to drinking to excess, ran himself in debt, and at length into a jail,
which hath been the unhappy case of many unstable youths, who, "`when they knew God,
glorified him not as God, neither were thankful, but became vain in their imaginations,
and their foolish hearts were darkened.`"

In this month I was at Byberry and Abington meetings,
in which we were favoured with the immediate power and presence of Christ,
to our great comfort and edification, the visitation of divine love to the youth,
having a good effect on some of them,
and the latter meeting ended with praise to the Almighty,
after supplications for all men, from our king on the throne,
to the meanest of his subjects.

In my travels I met with a person, who queried of me,
how he should know which society had most of the holy Spirit,
since most of the professors of Christ do believe in the Holy Ghost, or spirit?
to whom I made the following answer.

Let the rule of Christ determine this question: he says,
"`By their fruits ye shall know them; do men gather grapes of thorns,
or figs of thistles?`"
The fruits then of the Spirit of Christ are, love, faith, hope, patience, humility,
temperance, godliness, brotherly kindness, and charity, with all manner of virtues.
Therefore the society of Christians,
which brings forth most of the fruits of the holy Spirit,
consequently have most of Christ`'s grace and spirit.
But some object and say, we will not believe that any society have the Holy Ghost now,
or the immediate revelation or inspiration of the spirit, unless they work miracles.
To which it is answered, that right reformation from sin, and true faith in Christ,
cannot be wrought without a miracle,
neither can we bring forth the fruits of the spirit
without the miraculous power of Christ.
Men by nature bring forth the works of nature,
and that which is contrary to nature is miraculous.
Sin is natural, but divine holiness, or the righteousness of Christ, wrought in man,
is spiritual, supernatural, and miraculous.
And as to natural men, who are in a state of nature, seeing outward miracles,
if they will not,
or do not believe what is written in the holy Scriptures of the Old and New Testament,
neither will they believe, although one were to rise from the dead.
Notwithstanding Christ wrought outward miracles,
and did the works which none other could do; though he cured all manner of diseases,
and fed many thousands with a few loaves, and a few small fishes;
and what remained when all had eaten, was more than there was at first;
though he raised the dead, and himself arose from the dead, yet few, but very few,
believed in him, so as truly to follow him.
His birth, his life, his doctrine, his death, his resurrection, are all miraculous;
and since all this was done in the person of Christ,
and at the first publication of his religion to men, there is now no absolute,
necessity of outward miracles, though his power is the same now as ever;
but he said to his disciples, "`He that believeth on me, the works that I do,
shall he do also, and greater works than these shall he do.`"
Upon which, W. Dell says, "`this must be understood in relation to sin;
for Christ had no sin in himself to overcome,
but we all have sinned,`" and to overcome sin is the greatest of miracles.
This will try the notional or nominal Christian,
who says we can never overcome sin in this world.
Where then is our faith in the Son of God, who for this purpose was manifested,
that he might destroy the works of the devil.

Therefore let not Christians be slow of heart to believe in the glorious gospel of Christ;
and if we truly believe therein, and live in the practice of his doctrine,
we shall see miracles enough to satisfy us forever.

The 16th of the sixth month, I was at the weekly meeting at Frankford, which,
though small, was sweet, reviving, and comfortable to some of us;
so that we had a sufficient reward for leaving our business,
it being the time of our harvest.
Week-day meetings are much neglected by many; more is the pity.
The apostle`'s advice is necessary for men in our age, even of professed Christians,
viz. "`Let us consider one another to provoke unto love and good works,
not forsaking the assembling of yourselves together, as the manner of some is.`"

The 23rd of the sixth month, my cart-wheel, being iron bound, ran over me,
and my horse kicked me on my head; the wheel put my shoulder out,
and the horse wounded my head so that the scull was bare, and my leg was sorely bruised.
The same day Dr. Owen and Dr. Graham, with the help of two of our neighbours,
set my shoulder and dressed my wounds; and the Lord was so merciful to me,
that the next day I was enabled to write this memorandum
of this wonderful deliverance and speedy cure,
for which, added to many others I have received from his gracious hand,
I have occasion to be truly thankful.
I was obliged to keep at home some time, and I thought it long,
because I could not go to meetings as usual; but many Friends came to see me,
which was a comfort to me.
One day upwards of thirty persons came from several
parts of the country to see how I did,
and were glad I was likely to recover.
The day before I was so hurt, being the first of the week,
I was at meeting at Philadelphia, and was concerned to speak of the uncertainty of life,
and the many accidents we are incident to in these frail bodies,
and exhorted Friends to live so,
that they might have a conscience serene and clear of offence towards God and man,
and then they might expect the comforts of the Holy Ghost,
which in such seasons of difficulty, would be a great help and benefit to them.
Of this I had sweet experience the next day, under great extremity of pain;
and though the pain of my body was such that I could
not for several nights take my natural rest,
yet I had comfort, through the sweet influence of the Holy Spirit,
which Christ promised his followers.

On the 18th of the seventh month began our yearly meeting at Philadelphia,
which was large, and our friends John Wanton and William Anthony, from Rhode Island,
and Abigail Bowles, from Ireland, had good service therein.
From this meeting an address was sent to king George,
acknowledging his favour to us as a people,
in giving his assent to a law made in this province,
prescribing the forms of declaration, affirmation, etc.,
instead of those heretofore used.

The beginning of the eighth month, being a little recovered from my hurt,
I had a desire once more to see my friends on the eastern shore of Maryland,
at their general meeting at Choptank, The first day I set out,
I travelled about thirty miles, and at night was very weary, being weak in body,
and I was almost ready to faint in my mind about proceeding further.
Next day George Robinson, at whose house I lodged, offering to accompany me,
we travelled about forty miles to Sassafras river, and though much tired,
we were comforted in each other`'s company and conversation.
On the following day we travelled nearly twenty miles
to the general meeting in Cecil county,
in Maryland; where we met with two Friends from Rhode Island, and two from Pennsylvania,
who were there on the like occasion.
The meeting was large and quiet, many people being there not of our Society,
who were very sober.
It held several days, and the gospel dispensation was set forth,
and the love of God in Christ, exalted.

From Cecil we went to Chester river, and had a meeting there,
at which the people were exhorted to come to Christ,
the eternal rock and true foundation, and to build their religion on him,
against whom the gates of hell can never prevail; and they were so much affected,
that they did not seem forward to leave the house after the meeting was over.
From Chester river we went to Third-haven to the general meeting of Friends for Maryland,
which was very large, some Friends from Pennsylvania and Virginia being there,
and many people of other societies.
Many testimonies were borne to the work of Christ by his spirit in the soul,
and Friends were earnestly desired to be diligent in reading the holy Scriptures,
and to keep up the practice of our wholesome discipline; by the neglect of which,
a door would be open to loose living and undue liberties.

From Third-haven we travelled into the Great Forest,
between the bays of Chesapeak and Delaware, and had a satisfactory meeting.
There was no public meetinghouse in this place,
wherefore I told the people of the house, I was obliged to them for the use of it;
but they tenderly answered, they were more obliged to me for my kind visiting of them;
and truly we had a solid, good meeting there; the people being generally poor,
they had but little notice taken of them by the money loving teachers,
who preach for hire.
From the Forest I went to Little creek, in the territories of Pennsylvania;
where was a general meeting for the counties of Newcastle, Kent, and Sussex.
The meeting was large, and Friends parted in great love and tenderness.
I went forward to Duck creek, where we had a meeting, divers persons of note being there,
and all were quiet and heard with attention.
From Duck creek I went to George`'s creek, and had a meeting;
where a man of a sober conversation said he had never heard things so spoken to before;
but that he could witness to the truth of all that was said.
It was a good meeting before the conclusion;
but I was very low and poor in my spirit in the beginning of it.
From this place we set forward to Newcastle, where we had a meeting;
it was the time of the sitting of the general assembly,
and several members of the house were at meeting.
The governor, who had from our first acquaintance been very respectful to me,
hearing that I was in town, sent to desire me to tarry all night in Newcastle;
but being engaged to a meeting over the rivers Christiana and Brandywine,
and it being near night, I could not stay,
but went away that evening and sent my love to him, desiring to be excused.
That night I lodged at John Richardson`'s, and next day went to George Robinson`'s,
at Newark, where we had a meeting on first-day, and on second-day another at Providence;
and went from thence to Darby, to visit our worthy, aged friend, Thomas Lightfoot,
who lay very weak in body, none expecting his recovery.
I had called as I went from home, and then he was very ill, and told me,
"`He thought that illness would conclude his time in this world,
but said that all was well;
and that he had a great concern upon his mind for
the growth and prosperity of truth in the earth,
and desired with tenderness of spirit,
that I would give his dear love to all Friends;`" and he now said,
"`I thought never to see thee more, but am glad to see thee.`"
I stayed there all night, and in the morning we had a comfortable,
heart-melting time together,
in which was revived the remembrance of the many favourable seasons of God`'s love we
had enjoyed in our travels in the work of the ministry of the gospel of Christ,
and we tenderly prayed, if we never met more in this world,
we might meet in that which is to come, never more to part,
but forever live to sing with all the saints and holy angels,
hallelujah to God and the Lamb.
From Darby I went to Philadelphia third-day meeting, and from thence to my house,
where my dear wife and children with open hearts and arms received me,
and I them with joy;
at which time I had a gracious reward of peace for my labour of love,
which far exceeded silver or gold.
In this journey I travelled above three hundred miles, had nineteen meetings,
and was from home above three weeks,
in which time I recovered of my lameness to admiration,
so that I had with satisfaction to remember the apostle`'s saying;
that "`All things work together for good to them that love God.`"

After my return I was at the general meeting at Frankford;
and in the beginning of the ninth month, I was at meetings at Abington, Germantown,
and divers times at Philadelphia, particularly at the youths`' meeting,
wherein several testimonies were borne, and the youth exhorted to piety and humility.

On the 5th day of this month in the morning,
being under a consideration of the many sore exercises
and trials I had met with from my childhood,
I was much affected;
but the following portions of Scripture being brought to my remembrance,
afforded me some relief, "`Whom the Lord loveth he chasteneth;
if ye be without chastisement, ye are bastards, and not sons.`"
"`In the world ye shall have tribulation, but be of good cheer,
I have overcome the world.`"
So that I patiently bore my affliction and praised God under it.

In this month I was at the funeral of our worthy, ancient Friend, Thomas Lightfoot.
He was buried at Darby; the meeting was the largest that I had ever seen at that place.
Our dear friend was greatly beloved for his piety and virtue,
his sweet disposition and lively ministry: the Lord was with him in his life and death,
and with us at his burial.

I was also about this time at Germantown, and at a general meeting at Plymouth,
to my great satisfaction, being accompanied by my ancient friend Rowland Ellis;
and at the third-day meeting in Philadelphia, at the time of our fall fair;
there were fervent desires and prayers in several of us,
that the youth might be preserved from the evils
prevalent at such times of liberty and profaneness.

About the 20th of the month I went for Long island,
being drawn in true love to make a general visit to Friends there;
and likewise having some business to transact.
On the fifth-day of the week, Thomas Masters and I set out from Frankford,
and in the evening we got to a Friend`'s house, near the falls of Delaware,
where we were kindly entertained, and our horses taken good care of:
to take due care of traveller`'s horses, is a commendable thing,
and more grateful to some travellers than to take care of themselves.

From the falls of Delaware, we travelled next day to Piscataway, and lodged at an inn;
and on the next day we went to Woodbridge, to John Kinsey`'s,
where on the first-day we had a satisfactory meeting with Friends and others.
On the following day John Kinsey went with us to Long island,
and that night got to John Rodman`'s, and next day we rested,
being weary with travelling so far in the cold.
Our dear friends in that island, very lovingly received my visit to them;
so that I had occasion to remember that saying of the holy Scripture,
"`iron sharpcneth iron; so a man sharpeneth the countenance of his friend!`"

The fifth-day of the week we had a large meeting at Flushing,
and another in the evening at Obadiah Lawrence`'s, which was an open, tender time.
From Flushing we went to Cow-neck, to Joseph Latham`'s,
who went with me to Westbury meeting, which, considering the cold,
was much larger than I expected.
From Westbury, Nathaniel Simmons, Samuel Underbill and Phebe Willet,
went with us to Bethpage,
where we had a comfortable evening meeting at the house of Thomas Powell,
who went with us next morning to a town called Setawket;
it was as cold a day`'s travel as ever I went through in all my life;
the wind was in our faces, and northerly.
I do not remember, though I had been a traveller above thirty years,
that ever I endured so much hardship by cold in one day;
my chin and jaws were much affected with the frost for several days;
but we had a good meeting that made up for all.
After which we went ten miles to Amos Willet`'s house,
where we had a serviceable meeting; he invited his neighbours,
who came and received us with hearts full of good will;
and those not of our Society were well satisfied with the meeting;
so that we went on our way rejoicing,
that we were favoured with the good presence of God in our journey.
Amos Willet and his wife went with us to Huntington, where we had a quiet,
peaceable meeting, and the grace of our Lord Jesus Christ was with us,
as many can witness that were there.

From hence we went to Samuel Underbill`'s, and visited his weak brother;
in which visit the Lord mightily refreshed us together, and we blessed his holy name,
for "`he is good to all them who put their trust in him.`"
Next day we had a large meeting at Matinicock,
and had an evening meeting at Thomas Pearsail`'s. The next day being a snowy, stormy day,
and one of the shortest in the year, we went, being eighteen in company, to Cowneck,
where we had a good meeting, and much larger than could be expected.
After meeting we went to Joseph Latham`'s, and had a tender, open evening meeting,
in which we were edified and refreshed in Christ Jesus.

From Cow-neck I went to Flushing, had a large meeting on the first-day of the week,
and on second-day went over the sound which divides Long island from the main continent,
to Horse-neck, and had a meeting where I understood there never had been one before;
the people were sober and attentive, and some expressed their satisfaction.
That evening we had a meeting at an inn near Byram river, where divers people came,
and were attentive; the innkeeper, his father, brother, wife, and several others,
took our visit very kindly; though there was one restless man,
who seemed to be out of order with drink before he came into the house.
When we were sitting in silence, waiting for the gift of Christ,
and worshipping in spirit, as Christ instituted, he sitting by me, jogged me, and said,
"`It is time to begin, for there are as many come,
as will come tonight;`" he was mistaken in that;
but not having patience to watch and pray, he went away;
after which we had a good meeting.
These two meetings were in the government of Connecticut,
where they formerly made a law imposing a fine of five pounds
on those who should entertain any of our Society,
which law I was informed, was repealed in Great Britain.
From thence we travelled into New York government, and had a meeting at Rye,
and another at Mamaroneck; then to West Chester,
and had a meeting there on a sixth-day of the week,
intending to go over the ferry next day to Long island;
but the wind being high and boisterous, so that we could not get over,
we tarried three nights at the house of John Stephenson,
where we were lovingly and generously entertained.
On first-day we were again at West Chester meeting, which ended comfortably,
though I was in a low state both of body and mind in the beginning of it.
On second-day we all got well over the ferry to Long island,
parting with our friends at the ferry in much love and good will.
Joseph Latham having been my fellow traveller on the main, I went to his house;
then to Westbury to a large meeting, and next to Bethpage, and had a meeting there,
and in the evening accompanied by Samuel Bowoe and Joseph Latham, I went to Jerusalem,
and had a large and satisfactory meeting: many of the people of the town who were there,
came the next day to our meeting at Hempstead, which was large.
The great Lord of all was good to us that day,
which I hope many who were there will not forget;
and some convincement was wrought on some who were of account in the world,
at these last mentioned meetings, one who lived at Jerusalem, with tenderness of spirit,
desired my remembrance, whom I pray God to preserve to the end,
with all those who love and fear him, and believe in his Son.

From Hempstead I went to Matinicock, where, on a first-day of the week,
we had a large and good meeting; then to Thomas Townsend`'s, on the Plains,
at whose house we had an evening meeting.
Next morning many Friends from the Plains went with us to the south side of the island,
to a place called Rockaway, where we had a meeting at Hicks`',
the neighbours coming to it pretty generally;
there was great openness to receive the doctrine of truth in those not of our Society,
and they were very kind to us in those parts.
This was the second meeting I had been at in this place,
Benjamin Holme having the first there,
since which they had not been visited by any Friend in the ministry except myself.
From Rockaway we went to Foster`'s meadow, where was a large gathering of people,
and Christ filled our hearts with divine love.
I then went to Peter Titus`'s, and had a meeting at his house,
to which came the neighbours, and were well affected;
and next day we had a meeting in the meetinghouse at Westbury,
which was very large and to our satisfaction.
From Westbury,
in the evening we went to visit a young woman who
had been in a despairing condition for several years.
The family came together, and we put up our prayers to the Almighty,
in the name of his dear Son; it was a good time to us all;
and the young woman and some others, expressed their satisfaction.

This evening we went to see another young woman who was in a deep consumption,
but in a very comfortable state of mind; having a great desire to see me before she died,
she sent for me to come to her, and her desire was answered,
her spirit being revived with a fresh visitation of the love of Jesus Christ,
the holy physician of value, and our supplications were,
that the Lord would be pleased to be with her, and support her to the end,
and grant her an easy passage from this life to his glorious kingdom,
when it should please him to remove her;
which prayer we have cause to hope was answered.

Though the days were short and the weather exceedingly cold,
we rode about fifteen miles and made these two visits,
after that great meeting at Westbury; but our good Master supported us,
and was with us in our exercises and service for his name and truth`'s sake,
I lodged this night at Joseph Rodman`'s, and was next day at Flushing week-day meeting,
which was very large and satisfactory; had a meeting the same evening at Samuel Bowne`'s,
and the next day went to New York, and had a quiet,
good meeting in the evening at Samuel Harrison`'s,
and on the morrow had an evening meeting at a place called the Kills,
at the house of Richard Hallet, and the next day being first-day,
had a large meeting at Newtown, to the edification of Friends and other sober people.

It being now generally known that I was on the island, the people flocked to meetings,
though the weather was extremely cold,
for the Lord in the riches of his love manifested himself
unto us in our meetings for the worship of his holy name.
The next meeting was at James Jackson`'s, at Rocky-hill, where was Judge Hicks,
the high sheriff, and a justice of the peace, with several other persons of note,
with whom, and our friends,
we had a good time to set forth the work of grace and reformation, I think,
to general satisfaction, for which we blessed the holy name of God,
and humble prayer was put up to him for all men, and particularly for our king George,
as also for all in authority under him, and that they might be a terror to evil doers,
and the praise of them that do well.

The next meeting was at Jamaica, which was also large,
and several in authority were there, and were very loving and respectful.
The next first-day we had a large meeting at Cowneck, which was somewhat crowded.
Though my exercises were very great,
I was glad that there was such openness and room in people`'s hearts
to receive the doctrine which I had to dcclare unto them,
in the name and power of Christ;
afterwards we had an evening meeting with the widow Titus,
to which divers Dutch people came, and were very attentive and sober.
On the third-day of the week we had a meeting near the place called Hurlgate,
a narrow passage in the great sound or bay, between Long island and the main land.
Several justices and their wives attended it,
one of whom had disowned his son and turned him out of doors for coming among us;
but beholding his son`'s sober conversation, he grew more moderate,
and after meeting he and his wife invited us to dine with them;
but we were engaged to visit the widow Stephens that evening,
at whose house we had a meeting.

Going thither, it being very cold and stormy, my hands were touched with the frost,
and perceiving it when I came to the fire, I called for a basin of cold water,
which soon cured them: I note this that others may reap benefit thereby.
Next day we went to the week-day meeting at Newtown,
and on fifth-day to Flushing meeting, which was large and to edification,
and in the evening had a meeting at our ancient friend Hugh Cowperthwait`'s,
which was acceptable to him, as he expressed when it was ended; and to us also.
On seventh-day we had a very large evening meeting at Thomas Pearsall`'s,
and likewise a large, good meeting, the day after, being first-day, at Matinicock,
wherein the kingdom of Christ was exalted,
and the deformed state of sin and iniquity represented,
and the example and doctrine of Christ closely recommended,
in order to the overcoming of sin, this being not only possible,
but the duty of Christians, through the power of Christ and true faith in his holy name.
The danger of believing that it is impossible to overcome sin was opened to them,
and that such a belief is contrary to, and against Christ and his doctrine,
and darkens and blinds the hearts of men; but the love of Christ enlightens the soul,
and strengthens it to believe that all things are possible with God;
for this great work cannot be done in the will, wit, and power of man,
but through the power and grace of Christ, which he promised to true believers in him.

I was faint after this meeting, but resting a little, soon grew better,
so that we had an evening meeting at James Cock`'s, where one came and told us,
we must not eat any flesh, and produced Thomas Tryon`'s works for his proof.
I took the Bible and showed him proof to the contrary,
and told him we were resolved to believe our book before his,
and showed him from the apostle, that the kingdom of God is not meat and drink,
nor divers washings, but righteousness, peace and joy, in the Holy Ghost.
Though at the same time, according to the doctrine of Christ and his apostles,
I was for temperance in meats and drinks, as well as moderation in apparel.

The next day we had a very large meeting at Oyster bay,
many being there who were not of our Society,
who steadily gave attention to what was declared; and there being many young people,
they were persuaded to give up their blooming years to do the will of God,
and to remember him their Creator, in their youthful days.
Friends said there had not been such a meeting there a great while,
for which opportunity I was humbly thankful to the Lord.
After meeting we went to Samuel Underbill`'s,
and had an evening meeting with his brother, who through sickness and lameness,
could not get out for a long time.
Next day Samuel Bowne being with me, we went to visit a young woman who was weak in body,
but lay in a comfortable frame of mind; she was thankful for our visit,
and said the visits of her friends were comfortable to her.
Next day being the fourth of the week, we had a meeting at the widow Taylor`'s,
who desired it on account of her father, then in the eighty-eighth year of his age,
and so infirm, that he could not get to meetings;
he was very clear in his understanding and memory,
and was much refreshed with this meeting, as were divers of us also.

Next day we had a meeting at Flushing, which was large and open,
and the grace and power of Christ was with us in the ministration of the gospel.
After this meeting we had an evening meeting with our ancient friend Joseph Thorne,
who by reason of his age and infirmity could not go abroad as far as the meetinghouse:
many of his neighbours and friends came, and we had a solid, good time together.
While at Flushing, I went to visit a young woman who was a most sad spectacle to behold,
an object of great pity: her face, hand, and foot,
being much eaten away by the king`'s evil; our prayers were,
that now in her great misery,
the Almighty would be pleased to support her soul by his grace and spirit,
and sanctify her affliction to her,
that it might work for her a more exceeding weight
of glory in that world which is to come.

The next first-day we had a large meeting at Flushing,
wherein many weighty truths were opened to the satisfaction and edification of the auditory,
and in the evening we had a meeting with the wife of Matthew Farrington,
who was too weakly to go abroad; the neighbours came in,
and we had a seasonable opportunity.
On third-day was the youths`' meeting at Flushing,
in which we were concerned to exhort them to obedience to God and their parents,
and to follow their parents as they follow Christ; for where any leave Christ,
there we are to leave their example, though they were our fathers or mothers;
and the right honouring of our parents was set forth,
and they exhorted not to despise the day of small things;
the happy state of the obedient, and the unhappy state of the disobedient,
with many other weighty truths were delivered to them in that meeting,
by several experienced Friends.
From Flushing I went to the week-day meeting at Newtown,
and in the evening we had a meeting at the widow Way`'s; the neighbours coming in,
we had a good time with them: the parable of the ten virgins was treated of,
and the great disadvantage of wanting the divine oil of grace in our vessels,
was shown to them.

The next day being the fifth of the week, we had a very large,
satisfactory meeting at the widow Alsop`'s, at the Kills;
and from thence with several Friends went to New York,
where we had three meetings to our edification, the weather still remaining very cold,
but we felt the love of Christ to warm our hearts,
and though I think I never felt it colder, I never had my health better.
Several Friends accompanied us to the boat at New York,
the water being open on that side, we took our leave of each other,
and put out for the other shore; but before we got there, we were blocked up in the ice,
and it was a considerable time before we could work our way through,
but at last got well on Long island, where I waited some hours for company,
who through some difficulty got on shore.
We went to the Narrows through a storm of wind and snow, but the wind being high,
we could not get over that night nor the next day,
the ice having come down and filled the bay: when the tide had drove away the ice,
we put out and got well over, and lodged at the ferry-house on Staten island.
Next morning we went to the ferry at the Blazing Star, over against Woodbridge,
but it was all fastened with ice, and we not daring to venture over it,
went to the ferry at Amboy, and got comfortably over, stayed there that night,
and next day went to Trenton and lodged at Captain Gould`'s, who treated me very kindly,
I being much tired with travelling.
Next morning I went over Delaware river on the ice,
as we had done the day before over the Rariton,
and that day being the 5th of twelfth month,
I got safely home to my loving spouse and tender children,
where I found all well and a hearty reception, having travelled six hundred miles,
and attended above sixty meetings.

After having been at home, at our own meeting at Frankford,
I went to the quarterly meeting at Philadelphia, where Friends were glad to see me.

On the next fifth-day I was at the marriage of Thomas Masters and Hannah Dickinson,
where were many sober people not of our Society.

Having been lately among Friends at Long island,
and been comforted in the many opportunities we had together,
it came into my mind to visit them with an epistle at their quarterly meeting at Flushing,
which was as followeth:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Frankford, Twelfth month, 1725.

[.salutation]
My dear and well beloved friends,

Believing it might be acceptable to you to hear that I was got well to my habitation
in such a difficult time of the year as that in which I set out from you;
and also feeling the sweet influence of the love of the heavenly Father,
and his dear Son our Lord Jesus Christ, to arise and spring in my heart,
and flowing towards you,
it came into my mind to write a few lines to the quarterly meeting of Friends at Flushing,
by way of epistle,
well knowing also that many of us are as epistles written
in one another`'s hearts by the finger of the Most High;
and those characters of divine love so written will not easily be erased.
I could willingly have been at your quarterly meeting,
but had been so long from my family, that I was much wanted therein,
and my coming home was seasonable and acceptable, both to them and my friends;
and I humbly thank the Lord, I found all well.
That which is on my mind to your quarterly meeting,
is concerning the government of the church of Christ,
of which he is the holy head and lawgiver;
wherefore we are to seek and wait for counsel and wisdom from him,
in all our monthly and quarterly meetings, for the well ordering of our little Society,
which is growing and increasing in the earth, and also in your island,
notwithstanding the invidious attempts of some men of corrupt minds;
and it will grow and increase more and more, as we keep our places,
our heavenly places in Christ Jesus.

Dear friends, the good order of truth and the government of Christ in his church,
is a great help to us and our children, when carried on in Christ`'s spirit;
+++[+++pray observe or mind that]
for if our order and church government be carried on in the spirit of man,
as he is mere man, though he is ever so crafty or cunning,
it will do more hurt than good in the church of Christ.
Christ`'s spirit must govern Christ`'s church; and when and where that is over all,
then and there Christ`'s church and kingdom are exalted,
of whose kingdom and peace there will be no end; and happy will all those be,
whose end is in it.
Moses, that man of God, governed in the Jewish church in the spirit of God,
and when he found the work too heavy for him, the Lord put his spirit on seventy more,
who were help meets in the government; so that it was God`'s spirit that governed;
and while that ruled, all was well; but when they went from that,
they fell into error and disobedience.
At length the Messiah came, and he governed his own little flock himself;
and when he ascended up on high,
he promised that his spirit should be with and in his church forever,
and be their holy guide into all truth, in which he would also comfort them:
and Christ fulfilled this his promise;
for when his disciples waited at Jerusalem to be endued with power from on high,
according to the advice of their Lord,
they were filled with the gift and grace of the holy Spirit.
And when the brethren and elders met together about
the affairs and government of the church,
they gave forth rules and orders from that general meeting to the particular ones;
and the Holy Ghost presided amongst them, which they signified to the other meetings,
saying, '`It seemed good to the Holy Ghost and to us,
to put you in mind of such and such things.`' And while this Holy Ghost, or spirit,
governed in the primitive Christian church, all was well; God and Christ was glorified,
and his church and people edified; but by going from that the apostacy came in.

Wherefore, dear friends, keep close to the spirit, power, light,
and divine life of Christ Jesus,
in your monthly and quarterly meetings for the government of the church,
as well as in your meetings for the worship of the Almighty;
for if we go from that he will go from us.

And dear friends, the testimony of Jesus, in the spirit of prophecy,
opens in me after this manner,
that if our Society keep and live up to the spirit and truth of Christ,
which hath been manifested to our forefathers, and to us also in this age,
the great Lord of all will prosper his work in our hands,
and bless both us and our children, as we and they keep therein.

And as we have kept close to this our heavenly guide,
how hath the Lord sweetly manifested his love and power
to us in our meetings for the well ordering of our Society?
which many times hath filled our hearts with pure praises and holy thanksgiving,
to the high and lofty One who inhabits eternity, and dwells in the highest heavens,
and is light forever: to whom, with the Lamb of God,
who takes away the sins of the world, I recommend you, my dear and well beloved friends,
brethren and sisters in Christ, with my own soul.

[.signed-section-signature]
Thomas Chalkley.

[.postscript]
====

P+++.+++ S. Since my return I have been thankful to God for the many
favourable visitations and good opportunities he was pleased to
grant me with you and divers sober people on your island,
in which there is an open door among many to receive the testimony of truth.

I commend your nobility in building good houses,
and making room for your sober neighbours to sit with you in your meetings;
this is of good report concerning you, both far and near, and if I apprehend right,
there is more work of that kind for you to do.
I thought often, when among you, and now also, that there would be a large gathering,
if there were a house built at the upper end of the Great Plains,
not far from Foster`'s meadow; but every one may not think or see alike;
though I know some solid Friends among you, thought the same with me,
about the prospect of a large gathering thereaway, if a house were built;
to which Friends and well inclined people might come from Hempstead, Rocky-hill,
Rockaway, Foster`'s meadow, etc.

[.signed-section-signature]
Thomas Chalkley.

====

--
