== Chapter VIII

After I had been at home some time, I visited the meetings at Philadelphia,
Burlington and Germantown; in which places I had service of divers kinds,
and was lovingly received by Friends and others.

In the fifth month,
Joshua Fielding and John Oxley had a large and satisfactory meeting at Frankford.
Joshua came from London on a religious visit to America,
and having been on divers islands, he landed on the main at South Carolina,
and from thence travelled through the wilderness four hundred miles, or more,
where no public Friend had ever travelled before: the journey was perilous,
but the Lord was with him; who may, in his own time,
make way for his servants in those desert places.
John Oxley came on the same account from Barbados,
and had good service among Friends in his public ministry.

In this month we thinking it convenient to send our little children to school,
and not having a schoolmaster of our Society near us,
concluded to put our son and daughter under the care of Nathaniel Walton,
to whom I thought it my duty to write a few lines about the salutations
and language I would have them trained up in,
which were on this wise:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Frankford, 30th of Fifth month, 1727.

[.salutation]
Loving friend, Nathaniel Walton,

I hope thou wilt excuse the freedom which I take with thee,
in writing this on account of my children, in these particulars, viz:
Respecting the compliment of the hat and courtesying,
the practice thereof being against my professed principle: First,
because I lind nothing like it in the Bible; but, as I think, the contrary.
Thou knowest the passage of the three children of God,
who stood covered before a mighty monarch; and Mordecai,
who could not bow to great Haman: Second, I believe those practices derived from vain,
proud man.
And as to language,
I desire my children may not be permitted to use the plural language to a single person;
but I pray thee to learn them to say thee, and thou, and thy, and to speak it properly,
many using it improperly, and the rather I desire it,
because it is all along used in the divine, inspired, holy writings.
I suppose thou art not a stranger to its rise,
being from the grandeur and apostacy of the Romish church; and also, that you,
to a single person, is not consonant to the book of God, or the true rules of grammar.
I know it is generally objected, that the end of speech is to be understood;
but it is understood better in and according to the language of God, Christ,
and the Holy Ghost, in the Bible, and the language of kings, and all people,
as we read it in the holy Scriptures; why then should we be ashamed of it, or shun it,
and bring in and uphold a custom contrary to it?
The same care I would have thee take about the names, of the days and months,
which are derived from the names of the gods of the heathen,
and are not found in the Bible.
I suppose I have the mind of all those of our Society in the above,
it being consonant to our principle and profession,
and I write in a motion of divine love to all.

As to the school learning of my children, I leave it to thy management,
not questioning thy ability therein; and if they want correction, spare not the rod.

I hope thou wilt observe this direction in teaching my children,
in which thou wilt oblige thy assured friend,

[.signed-section-signature]
Thomas Chalkley.

--

The latter end of the fifth, and the beginning of the sixth months,
the weather was exceedingly hot, so that several people died suddenly of the heat,
as it was supposed.

The beginning of the sixth month I was at the youths`' meeting at Abington,
which was large, and open to many; and I not having been there since I came from sea,
divers expressed their gladness to see me;
and we were that day favoured with some showers, both celestial and elementary,
to our comfort.

In the same month I was also at the youths`' meeting in Philadelphia;
it had been a sickly time, but many had recovered.
That passage opened on my mind, to speak of in the meeting,
concerning the lepers whom Christ cleansed and healed, being ten in number,
and that but one came to return thanks to God, for being healed and restored to health.
Friends were exhorted to prize their health,
and to show their thankfulness to God the giver of it, by fearing and serving him,
and taking heed to Christ, the Word, in their hearts.
The meeting was in a good, solid frame, and we praised the Lord together,
and gave him thanks for his merciful visitation.

About this time I heard of the death of our king, George I.,
a prince whom I loved and honoured;
which news was very sorrowful to me on divers accounts;
his love and kindness to our Society was well worthy of our grateful remembrance.

On a third-day, being our week-day meeting at Frankford,
Elizabeth Whartnaby and Mary Smith were there; it was a comfortable opportunity:
they were two nights at my house.
Elizabeth was preparing to leave this land for Barbados and Europe,
intending a religious visit to Friends, The 20th of the sixth month,
going into my closet, I there met with a paper of my son-in-law, Isaac Brown`'s,
and finding the contents were religious, as I had done of several of his late writings,
I found it on my mind to write to him after this manner:

[.embedded-content-document.letter]
--

[.salutation]
My dear son, Isaac,

By several writings of thine, of late,
I perceive that a good thing is at work in thy mind,
the which I pray the all wise and infinite Being to promote in thy heart,
to thy eternal salvation, and his glory.
I now begin to be in some hopes that my prayers and tears for thee, in the Lord`'s time,
may be answered; and I do believe, if thou keepest low in thy mind,
that God will more and more visit thee.
The advice of David to his son Solomon, when he also gave him the kingdom,
comes before my mind to give thee: '`My son, know thou the God of thy father,
and serve him with a perfect heart, and with a willing mind;
for the Lord searcheth all hearts,
and understandeth all the imaginations of the thoughts; if thou seek him,
he will be found of thee: but if thou forsake him,
he will cast thee off forever.`' Dear Isaac,
this was counsel from one of the greatest and best of kings, to a wise young prince,
who petitioned the Almighty for divine wisdom, before riches, or honour, or long life;
which petition so pleased God, that he answered his request, and over and above,
blessed him in an extraordinary manner.

I perceive thou art inclined to read pretty much; I pray thee,
that thy chief study in books may be the holy Scriptures.
Let all other books, though of use, and good in their places, be subservient to them;
for their authority, of all other writings, to the true believers in Christ,
is most divine;
they having a supernatural spring and divine evidence
in them to virtuous and pious readers.
Thou, my son, wilt much comfort the heart of thy tender mother,
and of me thy loving and careful father,
if thou followest and perseverest in the ways of virtue and truth; which,
that thou mayest, is the prayer of thy affectionate father-in-law,

[.signed-section-signature]
Thomas Chalkley.

--

The latter end of the sixth month I went to the general meeting
of ministers and elders for the east part of New Jersey,
and to the quarterly and youths`' meeting at Burlington,
and to a general meeting at Stony-brook,
and to the quarterly meeting of the county of Bucks.
John Oxley, of Barbados, and Joshua Fielding, of London,
were at divers of those meetings; wherein we had open, seasonable opportunities;
and I had a large, affecting account from Joshua,
of his long and difficult travels in the service of truth to the West India isles,
and thence to South Carolina, from whence he came through the wilderness, by land,
through North Carolina, Virginia, etc., to this province.

The 16th of the seventh month began our yearly meeting at Philadelphia,
which was attended with the gracious presence of God,
to the comfort and great satisfaction of many souls.
In this meeting divers young men and young women appeared,
who were lately come forth in the ministry, and as I believe,
had received a measure of the gift of Christ`'s gospel;
which was cause of rejoicing to the faithful among us,
and excited our thanksgiving and praises to the Almighty Lord of heaven and earth.

At this meeting we had the company of four ministers from Great Britain,
and one from Barbados, and many from divers other parts,
it being a very large gathering of some thousands of people, as was believed,
ih which many were strengthened in their faith in Christ,
and comforted through the power of the Holy Ghost, that blessed comforter,
which Christ promised to his church, who should be with them forever,
and guide them into all truth.

Next first-day after the yearly meeting, I, with several of my neighbours,
went over Delaware to a meeting up Pensawken creek;
in which the wonderful love of God was declared, in sending his Son upon earth, who,
as he was man, died for man,
and is now by his spirit present with all those that truly believe in him;
he being the messenger of the covenant of God to mankind.
On second-day, the 25th of the seventh month,
I had the sorrowful tidings of the death of my beloved friend James Lord;
who on his deathbed, desired that I might be sent for to his burial.
In the consideration of that Christian love which was between us,
I think I may truly note, that we were always glad to meet each other;
therefore the thoughts of this so sudden change and final parting,
brought for the present, a sadness and heaviness over my mind;
considering his station in that neighbourhood,
and service in that congregation to which he did belong; for therein he was well beloved,
and very serviceable.

And, Oh! the loss that his dear wife and tender children will have of him,
really affects me with sorrow in penning these notes; but the sorrow, in these things,
is all on our side; for he, without doubt, is at rest with his great Master in heaven.
We had a larger meeting at his funeral than ever was known to be there before,
as an ancient Friend told me, which was solemn and serviceable to many.

Some time after, having been at divers meetings about home, John Oxley and I, in company,
visited Friends on Long island.
At Flushing we were at the burial of Jonathan Dickinson:
many people of divers persuasions, were at the meeting on that occasion,
and were very sober and attentive.
I was at the yearly meeting for the south side of the island,
at a place called Sequetague, which meeting was large,
many Friends and others coming to it over the Plains.
I was afterwards at the yearly meeting at Shrewsbury, in East Jersey,
which held three days, and was very large, and the last day the people were very still.
Joshua Fielding was at this meeting,
and was therein concerned to preach the gospel of Christ with good authority,
and matter suitable to a true gospel minister; John Oxley was ill of a fever,
so that he could not be there; but there were brethren from divers parts,
and the power and presence of the Most High was with and among us; blessed be his name.

I was also at Rahway river, where was a solid, good meeting.
From thence I returned home, having been abroad about a month,
and at above twenty meetings, and travelled above three hundred and fifty miles.

In the eighth month, at Frankford, we had three burials out of one house, at one time;
the mother, daughter, and grand daughter,
of which I had never known the like instance before.
On this occasion we had the company of many neighbours,
and a very solemn meeting at our meetinghouse at Frankford.

About this time I was at meetings at Philadelphia, Abington and Burlington:
we had an evening meeting at Burlington, with Richard Smith, jr.,
who had been so ill that he could not get out to meetings for some months:
it was such a satisfactory meeting, that he and I, and others who were there,
will not easily forget it, our hearts being broken together.

The world still continued to frown upon me; but though this was the case, yet at times,
I had great consolation in Christ; and in the midst of my troubles, when I looked back,
I could truly say that I had not been extravagant, but frugal; not covetous,
but charitable; not idle, but industrious;
not willing to be such an infidel as not to take care for my family.
This was some solid comfort to my mind; and I bless the Almighty,
that I always preferred his work and service to my own, and therein had great peace.
This I can also say, if it were the last I should say, that I never willfully,
or knowingly, wronged any man, woman, or child, since I came to years of discretion;
and yet I have nothing to boast of; it is the Lord`'s grace and mercy which saveth us.

Having occasion to make another voyage to Barbados,
I wrote to the teacher of my children as followeth:

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Frankford, 10th of Tenth month, 1727.

[.salutation]
Loving friend,

Being about to embark for Barbados, I leave the charge of my little children to thy care,
not doubting thy management of them, by their growing in their learning;
please to instruct them to sobriety and the fear of God, and faith in Christ;
and if I should never see them nor thee any more,
our lives being uncertain in this world,
pray let them know that it was their father`'s will and desire,
that they should mind their learning, and above all things,
mind the fear of the Most High.
When my little daughter hath read her testament through, I would have her go to writing;
and George the same, on the same terms.
Please to learn them the use of chapter and verse,
that if any ask them where they are learning, they may tell.
And kind friend, inasmuch as I perceive thou hast followed my former directions,
I look on myself obliged to thee;
therefore am so much the more free to impart my mind to thee, now on my departure; which,
with real love, is from thy loving friend,

[.signed-section-signature]
Thomas Chalkley.

[.postscript]
====

P+++.+++ S. Although my care is great for my children`'s learning their books,
yet it is much more so as to their learning true piety and virtue.

====

--

On the 25th of the tenth month we set sail from Philadelphia in the sloop Dove,
Oswald Peel, master; having taken a solemn farewell of my dear wife,
children and friends, in order for the support of my family, and answering my just debts,
which I had contracted.
On the 27th day of the month, in the evening, we took in our boat and put to sea;
had some rough weather in our passage, but lived comfortably;
we being all loving and obliging one to another.
On the 15th of the eleventh month, we safely arrived at Speight`'s-town, in Barbados;
and the 18th, between the hours of five and six in the morning,
we felt the greatest earthquake that I had ever felt; having been sensible of three,
one at London, one at Jamaica, and one at Frankford, in Pennsylvania.
I was thankful in my heart to the Lord for my safe arrival,
and that we were all preserved safe in our stormy passage, and deeply loaded vessel;
one vessel being lost that came out a little time before us; and another,
which came from our port to this island a few days sooner than we,
lost three men by the violence of the storm, and received much damage otherwise;
one of them being a neighbour of mine, with whom I was well acquainted,
it affected my mind very much.
I visited Friends`' meetings in Barbados, and some divers times over;
and had occasion in some meetings to mention the earthquake,
which I told them I did believe was a visitation from the Almighty,
in order to put people in mind of mortality,
and to reform them from the evil of their ways, and call them to repentance.

While I was in Barbados, Francis Gamble died,
whom I went to visit several times in his sickness:
at his funeral was a large gathering of his neighbours, and others; and divers,
not of our Society, expressed their satisfaction with the meeting.
The people in and about Speight`'s-town, in Barbados, were very loving and kind to me,
more than I ever had observed before; even some vile, profane men,
whom I could not forbear to reprove for their swearing,
and taking the sacred name in vain, yet they showed respect,
notwithstanding I reproved them sharply.
Who can take the sacred name of God into their mouths in vain, and be guiltless?
or who can hear it, and forbear reproving it, without being remiss in their duty?
This great evil is too frequently practised in this rich (poor) island of Barbados;
rich in earthly, but poor in heavenly treasure,
which caused me many times to mourn in secret before the Almighty,
praying him for the reformation of the people, for Christ`'s sake,
and for the glory of his own eternal name.

The 27th of the first month, 1728, having done my business in Barbados,
and seen Friends generally, an opportunity offered for my return home,
in the brigantine Sarah and Mary, Samuel Gallop, master, bound for Burlington,
in company with William Dury and William Callender, both of Barbados.
Our master was exceedingly kind to us in the voyage.
The wind hanging northerly, we could not go to windward, but drove to leeward,
and sailed by the isles of Lucia, Martinico, Dominica, Guadaloupe, Antigua, Montserrat,
Rodondo, Nevis, Christopher`'s, Eustatius, Saba, Martin`'s, Anguilla, Bartholomew`'s,
Sombrero, and four other small islands, which are called the Saints.
It was very pleasant sailing by these islands,
only some of them were so exceedingly high, that in some places we were becalmed,
and the clouds appeared below the tops of the mountains.
At Christopher`'s, which is counted the highest of them,
there being a small river of good fresh water, we sent our boat on shore for some,
having none very good on board: we lay off and on about two hours, but did not come to,
I was thankful for this water, it being my constant drink;
it was also very serviceable to the people on board.
After we left the isle of Sombrero, we saw a sail, which we thought stood after us,
and hearing at Christopher`'s that several Spanish privateers were on that coast,
our master, and some others on board, were a little surprised;
but we soon left her out of sight, and we afterwards went pleasantly on our way,
till we came to the latitude of Bermuda, where the winds blew fresh, and much against us;
and this winter having been very hard, we felt the sharp blasts of the latter end of it.
We had a passage of about thirty days, and came very pleasantly up the bay and river;
and it pleased God that I got home once more to my beloved wife and children,
and was joyfully received by all my family, whom I found in a good degree of health;
for which I did, as I had occasion to do,
bless and praise the great name of the Most High, who is worthy forever.

After I came home I was at many meetings in Pennsylvania and Jersey, viz:
at Philadelphia, Burlington, Bristol, Byberry, Frankford, Germantown.
New Hanover, Crosswicks, etc.,
in all which meetings I had some service to Friends`' satisfaction,
and was comforted with the goodness of God in the midst of my afflictions.
My business lying much at Burlington,
I spent pretty much of my time there for several weeks;
where my friends manifested a tender and hearty respect towards me,
and sympathized with me in my troubles and travels;
and there I prepared for another voyage; for I was fully resolved,
through divine assistance, to pay all my just debts, which I contracted, and lay on me,
through many losses, or else to die in the pursuit of it;
in which resolve I had inward peace and satisfaction; though such labour, travail,
and separation from my family, was a great cross to nature.

On the 14th of the fifth month we went on board the brigantine Sarah and Mary,
Samuel Gallop, master, for Barbados;
and on the 16th we sailed down the bay and put to sea, and I wrote a loving,
tender letter, to my wife and family, and another to my friends at Burlington.
We had fair winds for about two weeks, after which they were contrary for several days,
during which two of our men had a fever, and our vessel proved leaky,
though tight in smooth water, which was some concern to us,
and obliged us to pump every half hour; but the leak being much the same while at sea,
we were the more easy about it: I took care of those two people that were sick,
who soon recovered.
The 3rd and 4th days of the sixth month it was very windy, with lightning,
thunder and rain;
in which rough weather one of our best sailors put his shoulder out of joint,
and they brought him to me to see if I could do him any service.
I was not forward to meddle;
but the man and the people believing if I would undertake for him, I might help him;
I told them that though I did not understand bone setting,
I would instruct them the best I could; then I ordered him to sit down upon the deck,
and to be stripped to the waist, and got a round piece of wood as thick as his arm,
and wrapped a piece of cloth about it, that it might not bruise his flesh,
and put it under his arm, and ordered two men, one at each end of it,
to lift up strongly, and a third man to stretch his arm out, and keep it down withal;
which being done, the bone went into its place;
for which I was thankful in my heart to the Almighty.

About the 10th of the sixth month we safely arrived at Speight`'s-town, in Barbados,
being the first-day of the week.
From whence I had an opportunity, by Alexander Seaton,
master of a vessel bound to Pennsylvania, to send an account of our safe arrival.

I had many meetings in the island, and made several visits to sick persons,
one of which was particularly to the satisfaction of the person visited and his relations:
he died, and was buried at Hethcott`'s bay,
and we had a large meeting at our meetinghouse, where were many people,
and it was a good, seasonable opportunity;
in which I had occasion to remind them of their mortality, and press them to a holy life,
the way to a happy immortality.
I had divers meetings at Bridgetown, Speight`'s-town, and the Spring;
where the testimony of Christ`'s gospel was well received.
After a stay of three weeks, I left Barbados on the 1st of the seventh month,
and took my passage in the Amity, Charles Hargrave, master,
who was very friendly to me in my passage, as were all on board.
We arrived at our port without casting anchor in all our voyage,
and laid the vessel to the wharf at Philadelphia; and on my landing,
I immediately went into the meeting of ministers and elders, it being just meeting time,
where we were much comforted together in Christ; after which I went home,
being lovingly received by my wife and family, having been from home about ten weeks.

After I came home from this voyage, I visited the meetings of Friends at Philadelphia,
Frankford, Germantown, the Falls of Delaware, Burlington, New Hanover, Mount Holly,
Fairhill, etc.

The 2nd of the ninth month I was at the quarterly
meeting of ministers and elders at Philadelphia,
where I met with Joseph Taylor,
a Friend who had visited our meetings pretty generally on the continent of America,
in the ministry of the gospel, and was now on his return homewards,
with whose visit Friends had good unity,
and certified the same to our brethren of the meeting where he lived in Great Britain.

After this I was at divers meetings in Pennsylvania and Jersey;
and the latter end of the ninth month, Sarah, the wife of Jeremiah Elfreth,
died very suddenly; having been the day before walking in her garden:
she was a sober young woman, and her death was much lamented.
Her burial occasioned my stay at Philadelphia, which I had shunned,
because a concern had been on me for some time, to declare to the people of that city,
that the Lord was angry with the legislators of Pennsylvania,
because they were not so much concerned to promote religion and piety, as they ought,
and to make such laws as might prevent the excessive increase of public houses,
which often prove seminaries of Satan; but strove to promote parties more than religion:
and that the Lord was angry with the magistrates,
because they did not so much as they might, and ought,
to put those good and wholesome laws in execution, which were already made,
against vice and immorality;
and that the Lord was angry with some of the better sort of people,
because they seek and mind the things of this world,
more than the things of God and his kingdom.
But I was helped to clear myself in the morning meeting
to the satisfaction of many of the honest-hearted,
and unburden my mind of a great exercise that I had long laid under.

In the afternoon we had a large meeting; at the Bank meetinghouse,
occasioned by the aforesaid burial;
the resurrection of the dead was declared in that meeting,
according to the doctrine of our Saviour, Jesus Christ,
the great author of the Christian religion, and also of the eminent apostle, Paul;
and the old and false calumny, that our Society denied the resurrection of the dead,
was publicly denied and refuted.
The people were exhorted to live well, that they might die well;
and then they need not doubt,
but that they would rise well at the resurrection in the last day.
The meeting concluded with praise to the Almighty for all his mercies,
and prayer to him that he would sanctify that day`'s service to the people.

In the tenth month I prepared for another voyage to the island of Barbados,
and had the ship Bristol Hope consigned to me,
but the winter setting in sooner than common,
caused our stay much longer than we expected,
whereby I had the opportunity to visit divers meetings, as Burlington,
the Falls of Delaware, Neshaminy, Wright`'s town, and Philadelphia.

In this city a concern was on my mind to declare to the people,
that the Almighty had showed me,
that he had often visited those in Philadelphia and Pennsylvania with his own hand,
and with his rod; but if that did not work the designed end for which he visited them,
of which they were told also before it came to pass,
he then would chastise them with the rod of man,
and this was as plainly spoken to me in my own habitation,
as if it had been the voice of a man, though it was not vocal.

The 12th of the eleventh month, being first-day, I was at Horsham meeting,
and had a tender bowing time therein;
and in my way home visited some Friends who were sick,
it being a time of general visitation in those parts;
and the next seventh-day I was at the meeting of ministers and elders at Philadelphia,
where we had a good meeting.
Here I was earnestly desired to be at the funeral of Edmond Orpwood,
the eldest Friend belonging to Frankford meeting; but was in a strait,
this Friend being my neighbour,
and I had before engaged to be at the burial of one
with whom I had been acquainted nearly forty years.
I did my endeavour to be at both, being each of them buried in the afternoon,
and five miles distant; the days being short also, divers told me it was impracticable.
I told them they might be mistaken, as they were; for though we had a large meeting,
and the company of Rowland Wilson, from Britain, who had large and good service therein,
yet after meeting we mounted,
and got to Philadelphia about a quarter of an hour
after the corpse was brought into the meetinghouse,
as I was informed.
We had a large, and as I thought, a good meeting`"; after which I went home,
being weary in my body, but thankful in my heart, that the Almighty had been with us,
and helped us to perform that day`'s service.

On the 20th of the eleventh month, and second-day of the week,
I went into a piece of ground, which I was clearing for meadow,
in order to give directions to the workmen; one of the trees fell contrary to the kerf,
and also to the wind, which was then at northwest, and when I saw it falling towards me,
I ran from it, but before I could get out of the way, it fell upon me, across my back,
from my shoulder to my hips, and struck me down to the earth,
where for some time I lay speechless,
and in all likelihood I should have been immediately killed,
if I had not been providentially preserved by the
body of the falling tree laying on a stump,
which prevented its crushing me, as I lay on the ground.
A Friend who was near me, with a horse, desired the wood-cutters,
when they were recovered from the surprise, and I to the use of my speech,
to help me on his horse, and I rode home, but in extreme misery,
and I was under great concern, lest I should surprise my wife and children suddenly.
We sent to Philadelphia for Dr. Griffith Owen, who came in about two hours,
and let me blood, and ordered several things to be applied and taken,
which through divine favour, proved very serviceable to me; notwithstanding which,
I was in great pain many days, and the nights were long and tedious,
not being able either to feed myself, or to turn in my bed, for a great while.
In this confinement I was at times favoured with
a very comfortable sense of the presence of God,
whose providence is over all his works; and as his love to me was great,
so the love of his people was also, many of whom, and of my neighbours, came to see me,
sympathizing with me in my distress; but among them I had one of Job`'s comforters,
who wickedly abused me in this low state.
I can scarcely forbear mentioning his name, having example for it in holy Writ,
but through the Lord`'s help, I will put on charity.

The 9th of the twelfth month I got abroad the first time to our meeting at Frankford,
with which divers expressed their gladness to see me there again.
In this meeting I exhorted them to think on eternity, and to prepare for it,
by living today, as though they were to die tomorrow;
for I found it by experience to be needful, and then if sudden death comes,
it will not surprise us.

As I now found it my business to go to sea for a livelihood,
I undertook the charge of the ship New Bristol Hope, as master,
though it was a way of living to which I did not incline.
I took care in our vessel that there should be no swearing in my hearing,
nor drunkenness, to my knowledge, without reproof;
and if I could not be instrumental in that way to
break them from swearing and drinking to excess,
my manner was, to put them away, so that we generally had a pretty quiet ship.
We left Philadelphia the 13th of the twelfth month,
but storms and contrary winds detained us in the river and bay,
so that we did not get out to sea till the 21st of said month, when the pilot left us,
by whom I wrote to my wife and family.
And now I thought I felt the benefit of the good
wishes of my beloved friends whom I had left behind,
which did me a great deal of good, as it often hath done on the like occasion;
for faithful friends and good Christians,
are as epistles written in one another`'s hearts.
In our passage we took several dolphins, which were very welcome to us,
we having a long passage, and our fresh provisions being nearly spent.
The 19th of the first month we saw the island of Barbados,
having had several meetings on board the ship in this voyage:
of the good effects I could see but little,
only for that day they would be a little more sober, and some of them,
addicted to swearing, did not swear so often as they did before.
The day following we safely arrived at Speight`'s-town,
where we had the next day a very comfortable meeting for the worship of God.
The fifth-day following I was at Bridgetown, at their week-day meeting;
and next first-day, being the 30th of the month, I was at a meeting at Pumpkin-hill,
where I was enlarged on the doctrine of faith.

After this I went to the Bridge with a Friend from New England; we had two good meetings,
it being the general meeting for the Friends of the island;
and afterwards with several Friends, I went again to Speight`'s-town,
and on the 12th of the second month I was at the Thicket meeting,
at which were Counsellor Weeks, Colonel Charnock, and Justice Sims.
I dined with them at Judge Weeks`',
and they discoursed of what was said in the meeting about dancing,
I quoting Luther`'s words, "`that as many paces as the person takes in the dance,
so many paces or steps they take towards hell.`"
I told them I had heard that several had used that vain exercise in our meetinghouse,
which was appointed for the worship of God;
and said I hoped for the future it would be so no more;
two of those persons who danced in our meetinghouse, were then in the meeting,
though I did not know it.
This testimony so wrought on the colonel,
that he said he could scarcely feel his legs since I spoke it;
and the justice said if these words were true, he had taken many steps towards hell;
and the counsellor and judge said it was home doctrine to some who were there:
divers of them seemed to be touched with the testimony of truth,
though not so solidly as I desired.
Soon after, I went with Joshua Birch to visit the governor of the island.
Colonel Worsley, who treated us with much freedom and civility;
he desired me to sit down by him, and then called for a decanter of wine,
of which he kindly offered me a glass, but I told him I chiefly drank water;
he said water is certainly the best drink in the world,
and told me I was a credit to my drink, as I looked as well, or better,
than most who drank wine.

In the second month I was at meeting on a first-day at Bridgetown,
which was somewhat larger than usual; it was a good open time in the morning,
but more so in the afternoon.
At this meeting there was a merchant of the town, not of our profession,
who sent to know if our friends would make a contribution for me,
in consideration of my losses.
He said he would contribute as much as any, although he had heard me only that one time;
but he was informed that we received no money or pay for our preaching;
yet his good will I acknowledged.

The 4th of the third month I was at meeting at the Spring,
where I met with Joseph Gamble, and John Oxley and his wife,
and several others not belonging to this particular meeting,
and we were edified together in the love and life of Christ,
I was concerned to speak of the divers visitations and speakings
of God to the people since the world began;
quoting the words of holy Writ, that "`God, who at sundry times, and in divers manners,
spoke to the fathers by the prophets, hath in these last days spoken unto us by his Son,
whom he hath appointed heir of all things:`" and that this
dispensation is the last and brightest dispensation of all,
and is the greatest and most glorious manifestation of God`'s love to mankind;
and that beside this vocal speaking of Christ, when in the body on earth,
he now speaks spiritually: which spiritual speaking of Christ,
in and to the true church and true believers, will outlast time,
and endure to all eternity; the great Lord of all, for his unspeakable benefit therein,
was praised and glorified, as being alone worthy.

I had other meetings on the island, which I pass by, not being willing to be prolix.
After a stay of about nine weeks, we proposed sailing.
Judge Gray, a very noted man, and much esteemed among the people, took passage with us;
also Joshua Birch, of Bridgetown, for his health, and William Callender,
and several others, as merchants.
Though I came on account of trade,
our friends gave me a certificate that I had good service among them,
and in my outward affairs had gained esteem among the people,
as well as in my service in preaching Christ;
all which I acknowledge to be the effects of divine grace.
Several friends and acquaintance came to the seashore at Speight`'s-town,
and in a great deal of tender Christian love and good desires, we took leave,
and committed one another to the protection of the Almighty.
We had a comfortable passage, and arrived at Philadelphia,
where I was lovingly received by my wife and friends.

In this voyage a great and weighty concern came on my mind,
on account of the young and rising generation,
desiring that they might be happy in this world, and in that which is to come.
And first, as to this world,
I have taken notice that divers of the youth are too apt to waste their outward substance,
which is given to them, for when they get it themselves,
they are for the most part more saving of it, and this wasting and spending,
they call generosity, liberality, good nature, gentility, fine breeding,
and abundance of other fine names; not considering the labour and industry, frugality,
care and watchings, of their parents or ancestors, to get what they have.
May parents note this well, and not be anxiously concerned to get much wealth,
which may be a means to ruin their posterity; and truly most of these spending, drinking,
company-keeping, gaming, chatting, tippling youngsters,
take a great deal more care how they may get money from others, that they may spend it,
than how to earn it, or faithfully labour for it themselves.
They will beg, or borrow, or run in debt, but take little or no solid thought to pay;
by which means divers of those topping, beggarly beaus and spenders,
have brought both themselves and relations, parents and friends, to shame and disgrace,
and sometimes to poverty, where their relations and parents have been too liberal.
Let all indulgent parents note this also.

And if any concerned person should advise those inconsiderate youths of their evils,
it is much if they gain not their lasting ill will,
and the epithets of niggards and covetous, ill natured, censorious, sour, morose, etc.
However, I shall venture to stand the shock of their displeasure,
and in as moving terms as I can, consistently with the matter on my mind,
entreat them to consider the end of their spending, slothful life, which if continued in,
must needs end in their ruin, and they may repent when it is too late, crying out.
Oh! that I had hearkened to the advice of my father and my indulgent mother!
Oh! that I had taken the counsel of my good friends in time,
then I had not been in this condition, nor in those straits I am now in.
This, or worse, must at last inevitably be the condition of those unthinking,
time wasting, money spending, and evil company-keeping, young people of both sexes.
Some of whom, if they can get it, will spend more in a few hours,
than their parents can get in so many days, which is very unreasonable,
as well as unthinking; for if the indulgent parents do not hold their hands,
truly they must all sink together;
and where the parents have been what these youths call liberal,
whole families have by such liberality been undone, which is a case to be lamented.

I pray our spending youths to consider, how many brave, fine young men and women,
whose parents have left them estates and handsome incomes, have by such extravagances,
soon spent all, and sometimes more than all,
and disgrace and a jail have been their portion; and how many, by living too fast,
have died too soon, much sooner than might be expected,
according to the course of nature.
Wherefore, I would advise them to regard what the wise king Solomon said,
"`Go to the ant, thou sluggard, consider her ways, and be wise;
she gathereth her food in the summer;`" i. e., she prepares against the winter.
Though this may be despicable in the eyes of our fine gentlemen and wits,
yet there appears more wisdom in these little industrious animals,
than in those great spenders, who in the spring and summer of their years,
take so little thought of saving what hath been with so much care gotten for them,
or of getting more against their winter or old age; which, if they live,
will certainly overtake them, when their youth or summer is gone.

But many youths object against this advice, crying out, as I have often heard,
"`The aged give this advice when they are old, but did as we do,
when they were young as we are.`"
Although this may be true in some, yet it will not hold good in the general;
and if it does in some, is not that maxim good, "`Let others harms learn us to beware,
before it be too late, that we fall not into the same snare,
which hath entangled or caught thousands, to their great shame and reproach.`"
Again, those who have been so overtaken in their youth, and are escaped out of the snare,
are more fit to caution or advise how to escape it,
or to show those paths which lead them into that labyrinth of woe and misery.

The author of all evil useth his utmost skill and
power to promote the practice of excessive drinking,
etc., among mankind, it being a mighty support to his kingdom;
for when the nobility of the understanding is clouded thereby, then.
Oh! how many wicked oaths, what corrupt language, what unhandsome,
unbecoming words and actions, are brought forth!
How is the sober, chaste soul, offended, and above all other considerations,
how is God dishonoured, and the end of our creation frustrated, and man condemned!

When people are in those excesses, how do they take the sacred name in vain,
and so bring themselves in guilty before God and man;
for he has positively said he will not hold those guiltless who take his name in vain;
so that let him plead ever so many excuses,
he is pronounced guilty by the Judge of heaven and earth: therefore,
let me persuade the youth to remember what the Lord
by his servants said concerning drinking to excess:
"`Woe to the drunkards;`" and that "`no drunkard shall inherit the kingdom,`" Again,
"`Woe to them that are mighty to drink wine,
and men of strength to mingle strong drink,`" etc.
If it be objected, as it often is, when such poor souls are reproved,
and their sins set in order before them;
we trust in the mercy of God and the merits of Christ;
I say this is a good trust and hope, if upon a good foundation;
but the wicked must forsake their ways, and the unrighteous their evil thoughts;
but what forsaking is that, when strong conviction is upon the soul, to make covenants,
vows and promises, and break them from time to time?
And though Christ hath satisfied the justice of the Almighty for sinners,
it is for those who forsake their sins, not for those who plead for the practice of them,
and endeavour, by many vain excuses, to justify themselves in them.

Since then the salvation of the soul is precious,
and hath cost the precious blood of the Lamb of God,
and is much more precious than health or wealth,
why should any be so cruel and hard-hearted to themselves, as, for a little vanity,
mirth, toys, trifles, vain sports, and evil pastime,
to plunge and sink themselves into the gulf of eternal woe and misery; pray.
Oh! pray consider it, dear youth.

After my return from Barbados in the fourth month,
I visited Friends`' meetings at Burlington, the Falls of Delaware, Abington, Germantown,
and was divers times at Philadelphia and Frankford;
which meetings were much to my satisfaction;
the Lord being pleased to manifest his goodness to many,
as also to my poor exercised soul; for which I was truly thankful unto him.

In the sixth month I was at the general meeting of Friends at Darby, in Chester county,
which was a large and good meeting, divers Friends appearing there in a lively ministry.
About this time, some thousands of people came from Ireland, and also many from Holland;
among whom, it was reported, were Romans, or Papists, several of whom, it was said,
gave out threatening speeches, which caused some consternation among the people.

At this large general meeting, I exhorted them to trust in the Lord,
and not to distrust that hand which had hitherto
preserved us by his providence without outward force;
and that though the people who came among us were many in number,
yet we having the Lord on our side, were more than they, in a mystical sense;
putting them in remembrance of the prophet, who, when his servant was afraid,
prayed to the Almighty to open his eyes, and when they were opened,
he saw the mountain full of chariots of fire, and horses of fire,
and that they were more than their enemies.
I was also concerned to exhort Friends to be good examples
to those strangers who came among us in such great numbers;
and that our lights in our conversations, might so shine,
that those people seeing our good works, might glorify our Father which is in heaven,
according to the doctrine of Christ; and then we should do them good,
and they would do us no hurt, but good also.
But on the other hand, if we keep not our places, and do not live in the fear of God,
nor according to our holy principles and profession,
then it might be just with the Lord God, to make them a scourge to us.
Many were comforted in this meeting, and God was praised, who is worthy.

On the 15th of the sixth month, having loaded the ship New Bristol Hope, a second time,
I sailed in her from Philadelphia,
and having a concern to visit the meeting of Friends at Salem,
I left the ship at Gloucester, under the care of the pilot,
and went by land to the first-day meeting at Salem, and from thence to Elsenborough,
and stayed till the ship came down; and on the 20th of the month we got to sea,
and had a fair wind for several days, and lived very lovingly on board,
being respectfully treated by my sailors.

In this voyage we had several meetings on board,
the first of which was at the request of my second mate,
to call the sailors together in the cabin; I not being forward to propose it to them,
lest they should suspect me of some vanity, in desiring to preach to them;
they not knowing the cross of Christ in that exercise.

On the 24th day of the seventh month, at noon, our ship by observation,
being exactly in the latitude of Barbados, we steered away west for the island,
and on the 26th we saw it, five weeks and one day after leaving sight of Cape Henlopen;
we having, after the first few days, light winds, calms, and head winds,
which made our passage long, and our sea stores almost spent;
but now the sight of land made the people forget all uneasiness, and for this favour,
my heart was thankful to the great Preserver of men.

This time we came to a tolerable market with our provisions, which made our stay short;
yet I was divers times at Bridge meeting of Friends, as also at Speight`'s-town,
where my concerns chiefly lay; and once at Pumpkin-hill meeting,
in which it was observed to the people, that the salvation of the soul is precious,
and that true religion is a solid thing,
a thing of the greatest moment to both body and soul,
and that people ought to be very serious and solidly concerned about it,
taking special care to lay, or build, their religion on a sure foundation.
It was showed them,
that Christ Jesus is the sure rock and foundation of all the righteous, in all ages;
that he was the Rock that followed Israel, which they drank of;
and that any other foundation than him, no man can lay; who is, in the truly religious,
and the true believers, the hope of their glory.
Many other precious truths were manifested to us in that meeting,
for which we praised the Lord.

Soon after I went to Bridgetown to clear out the vessel,
and was at their week-day meeting; the subject matter I had to treat of in that meeting,
was that "`the Lord bringeth low, and he raiseth up again;`" and that in divers respects,
as to kingdoms, families, and particular persons; and as to health, wealth, honour, etc.,
divers in that meeting were appealed to as witnesses of it.
After this meeting I went to visit the governor, who was courteous to me,
and took my visit kindly,
and desired to be remembered to our governor and several others,
and wished me a prosperous voyage, and well back again,
which he hoped would be in about three months; he said, "`Whoever lived to see it,
Pennsylvania would be the metropolis of America, in some hundreds of years.`"
He said "`he loved downright honest men, but he hated deceit and hypocrisy.`"

The 21st of the eighth month, 1729, we having done our business,
weighed anchor and went to sea;
and on the 26th we had a good meeting with the ship`'s company,
for the service and worship of God;
in which the gospel of Christ was declared without partiality,
and the reigning sins of sailors openly exposed, according to the doctrine of the gospel,
and the most high Lord entreated to carry on in the earth the great work of reformation.
Hitherto we have had fine, pleasant weather.

The beginning of the ninth month we had a very blustering, stormy time, for many days,
so that we could not carry sail, but sometimes lay by,
and sometimes went with a reefed mainsail and foresail;
the ship had such a violent motion,
that it broke our glasses and about a dozen bottles of wine, and our earthen ware,
and strained our hogsheads and casks, so that we pumped out molasses into the sea,
and beat us back many leagues, and blew our sails out of the bolt ropes.

After those storms we had a calm, and the wind sprung up westerly;
our course being northwest, or thereabout, we could barely lay it; yet it being moderate,
we had cause to be thankful.

The 12th of the ninth month we found ourselves in the latitude of thirty-six degrees,
seventeen minutes, north; but the wind was ahead,
and our fresh stock of provisions almost expended, and winter coming on apace,
the nights dark and long, made it seem tedious to our people;
the which I was helped to bear with patience.

The 14th day, about eight o`'clock at night, John Flasket,
one of the best of our sailors, through the violent pitching of the ship,
fell into the sea from off the bowsprit; one of the sailors seeing him fall,
nimbly threw a rope to him, which he caught hold of,
and the people helped him into the ship; though in all probability,
he had perished in the sea, if he had missed taking hold of the rope.
I was thankful to the Almighty for this young man`'s life,
and took it as a great favour from heaven.
The next day it was dreadfully stormy, the wind blew violently at southwest,
with lightning, thunder, and much rain; the seas ran so high,
and the ship had such a great motion, that the goods, or casks, shifted in the hold,
and we lay by till next day; our sails also were much torn, and in many places,
blown out of the bolt ropes, so that we were half a day mending them,
and then proceeded on our voyage home, where we arrived the latter end of the month.
