== Chapter IX

After I came home from this voyage, during the small stay I made on shore,
I was divers times at meetings at Philadelphia and Frankford, and also at Germantown,
at the burial of our ancient friend Dennis Conrad,
who was one of the first settlers of this town,
as I understood the first meeting of Friends, for worship, was kept at his house;
he was a man of an inoffensive life, much given to hospitality,
and left a good report behind him.
The meeting was large, and many of the first settlers of the country were there.
I was also at the burial of Catharine, the daughter of Thomas Lightfoot,
and wife of James Miller, a worthy woman, who died soon after their arrival from Ireland,
and was buried from our great meetinghouse in Philadelphia,
in a decent and exemplary manner.

The latter end of the tenth month, Samuel Harrison, of New York, and Obadiah Lawrence,
of Long island, favoured me with their company all night at our house,
where we called the family together, and had a seasonable time to take leave, they of me,
and I of them, and my family also;
and the next day divers very dear friends came with me to the boat, to the river side,
to take leave, and we parted with hearts full of love and good will to each other.

I went on board at Wiccacoe, and had a cold passage down the river and bay,
and left the Capes the 1st of the eleventh month, being the third voyage as master,
and the 17th we passed the tropic of Cancer.
Hitherto we had a comfortable passage, and though we had a crowded ship,
yet we had peace and quietness to a greater degree than I expected;
for men that use the seas,
are too generally inconstant as the winds and waters they pass through.
We had several meetings on board the vessel,
and were at sea about four weeks before we arrived at Barbados,
where the markets were dull, which occasioned our staying about twelve weeks.

During this time I had divers religious and good opportunities,
with those of our own and other societies, I believe to general satisfaction;
having the good wishes of people of all ranks, from the governor to the poor negroes;
all of whom I profess to love for Christ`'s sake.

In our return home we had a full ship and upwards of thirty passengers,
and were on our passage about a month, and had good comfortable weather therein.

Soon after I came home from Barbados in the third month, 1730,
I went to a meeting at Burlington, at which Thomas Evans was married;
Margaret Preston was also there.
It was a good meeting.
I crossed the river Delaware twice, visited a sick person, and rode thirty miles that day.
I also went to the Falls meeting, and after it,
appointed another at Neshaminy the same day.
I went with Joseph Kirkbride to William Paxton`'s, and lodged,
and next morning Joseph Kirkbride rode with me home, and thence to Philadelphia.
I was divers times at Philadelphia, Frankford and Germantown,
and at the general meeting at Frankford, where our friend John Cadwallader was married;
Isaac Norris, Samuel Preston, and Margaret his wife, and John Oxley,
were at this meeting, with many other Friends,
a good share of whose company I had at my house, of which I was glad,
ever loving and coveting the company of good men and women.

I was now preparing for the fourth voyage, as master of the New Bristol Hope,
for Barbados; but it grew harder and harder for me to leave my family, which,
for many considerations, was very exercising; yet I was obliged to continue going to sea,
upon an honourable account; i. e., that no person might suffer by me, if I could help it;
and having got our vessel loaded, we sailed from Philadelphia the 9th of the fifth month.
Next day came to anchor at Chester, and visited my old friend David Lloyd, who,
with his good spouse Grace, treated me with tender, Christian love:
the judge and I being old acquaintances, and both of us in years, and, he not well,
we took leave as if we were not to see one another any more, which happened accordingly,
for he died before I returned.

We weighed anchor at Chester and got down to Elsenborough, and went to Salem meeting,
with some of our passengers and sailors,
it being the first-day of the week and 12th of the month.
The meeting was pretty large, and I was earnestly concerned for their welfare,
as I had often been when I was absent, and was glad I was with them that day.

After this meeting we proceeded on our voyage,
and left the Capes the 15th of the aforesaid month; had small and contrary winds,
and sometimes calms, until the 2nd of the sixth month, and first-day of the week,
when the wind was at south, and a hard gale, the sea high,
and the ship having a great motion, we had not a meeting as usual:
many of the passengers were very sea sick.
For my part, I thought if the Almighty was but with me,
that would make up for all difficulties; for in him was, and is,
my life and chiefest joy; and as an answer of peace in my tossed condition,
I sometimes had comfortable times;
being inwardly refreshed with the love and presence of God; not only in the day,
but also in the night, in my sleep; out of which I was awakened one morning,
with these comfortable words, "`He took me to his banqueting-house,
and his banner over me was love.`"
These expressions were so fresh in my mind for some days,
that I could not forbear but bless the holy name of the living Lord secretly in my soul.

The 16th of the, sixth month we arrived at Barbados.
The 17th there arose about midnight a hard gale of wind,
which the Barbadians call a hurricane, or tornado, and blew more than ten vessels ashore,
great and small, which were wholly lost; and our ship was very near the rocks,
people looking every minute when she would come on shore:
but through divine favour we escaped, with only the boat stove against the rocks.
I would have got on board, but that was impracticable;
but I got on the highest place I could, from which I could see them in the ship,
and they me on shore; but we could not, for the violence of the wind, hear one another;
yet they were so near the fort where I stood, that I could discern them one from another,
and they me from the multitude of people, many being in the fort with me.
I seeing the chief mate look towards me, waved my hat towards him, and he in answer,
his to me; then I made a signal to him to go to sea, which they immediately did,
letting slip their cables and went to sea, without either boat, anchor, or cables,
and came in the next day, and got their cables and anchors again,
to the great joy of many of the inhabitants, whose hearty prayers were for our safety,
as many of them told me.
This among many others,
I put in my calendar of deliverances and preservations from imminent dangers,
by the hand of divine Providence.

We stayed this time in Barbados about five weeks,
leaving the island the 27th of the seventh month; and there I met with Robert Jordan,
my friend and brother in the work and fellowship of the gospel of Christ,
who took his passage with us for Philadelphia,
whose company was pleasant and comfortable.

The 4th of the eighth month we met with a hard gale of wind,
which broke the tiller of our rudder, and split our bowsprit and mainsail,
and overset many of our chests;
Robert Jordan narrowly missed his chest falling on
him from one side of the ship to the other,
which escape we looked upon as a merciful providence, and spoke of it to one another.

In this passage we saw three vessels only; it was a blustering time,
but the shortest from land to land that ever I had,
being but fourteen days and fourteen hours,
from the sight of Barbados to the sight of the main land:
we arrived at Philadelphia the 16th of the eighth month.

In the ninth month I proceeded on a fifth voyage to Barbados, as master,
and went down the river Delaware on a seventh-day,
and on first-day was at Chester meeting, at which time there was a burial of a child,
and a large meeting.
Our friends at Chester were glad to see me, and I them,
and after meeting we set sail and went down the river to Elsenborough,
where we came to and landed Robert Worthington, whose son Ezra, was on board,
and went to Barbados for his health, being in a deep consumption.

We were on our passage about thirty-three days before we arrived at Barbados,
when after doing my business, and visiting Friends`' meetings about five weeks,
we put to sea on the 10th of the twelfth month,
and sailed along to the leeward of several islands, till we came to Anguilla,
where we landed in expectation to get salt,
but at this time there was not any to be had there.
We came to an anchor here in the night, hoping to get to a harbour before it was dark;
but it soon being very dark, and coming into shoal water, we saw a large rock,
and came to by the side of it, in about five or six fathom water, taking it to be a ship,
and when it was day we saw our mistake, and that instead of a vessel,
we were too nigh a rock, and the wind coming about, tailed our ship towards it,
so near that we were sensible of touching twice;
I ordered the men to heave a little further ahead, and so we lay clear till morning.
When morning came, of which we were glad, several boats with a cable, came to us,
and the people advised us to put a spring on our cable and cut it,
that she might cast the right way; which accordingly we did,
and it had the desired effect; so that we soon got into a very fine harbour,
it being about a mile off.
Thanks were given to the Almighty by many of the people, for this deliverance.
George Leonard, the governor of the island, heard in the morning,
that a vessel was on the rocks, and the people were running with saws and axes,
in order to break her up, if she could not be got off: the governor seeing them,
sent a lieutenant with orders that let her belong to what nation soever,
they should help to get her off, if it could be,
and if she was likely to be made a wreck,
he charged them at their peril not to meddle with her, nor any thing belonging to her,
until they had first come to terms with the master; which is worthy to be recorded.

We stayed several days before we could get our anchor; for after we were in the harbour,
it blew very hard for four or five days;
so that with our four oars we could not row our boat ahead,
but watching for a calm one night, our people went out and got it,
and then we went into the principal road or harbour in the island, called Croaker`'s bay.
The name of that we came from was Rendezvous bay, where lived a very kind friend of ours,
named John Rumney, who, with his wife and family, treated us with great love,
and courteously received us into their house, and he went with me to the governor`'s,
who was my old acquaintance and friend, who with much love and tenderness,
when he knew me, took me in his arms and embraced me, saluted me with a kiss of charity,
and thanked God for our deliverance, and that he had lived to see me once more,
I having been there some years before: he was seventy odd years of age, as I remember,
and had more than eighty who called him father;
the people living much on roots and pulse, are very healthy in this island.
I was here nine days, and had seven meetings with the people;
the longer I stayed the larger the meetings were;
so that I had some difficulty to leave them.
Through the grace and gift of God I was helped to preach the gospel of Christ freely,
and they received it both freely and thankfully, divers, if not all;
for their hearts and mine were very open one to another,
the Lord`'s holy name be praised forever.

The 3rd of the first month Ezra Worthington died, and the 4th in the afternoon,
he was buried on the plantation of John Rumney, near his house;
the governor and his son-in-law were at the burial,
where I told them that he was an inoffensive, innocent, sober young man,
and that death was to be the end of us here,
putting them in mind to remember their latter end.
After I had done speaking, the governor said that death was a debt due to nature,
and that we must all pay it, and blessed is the man who in time truly prepares for it.
This was a good expression for a man in his post, and worthy of my notice, as I thought.

I was at one meeting, where were the governor and his daughter,
with divers of the best and soberest people of this island:
it was a satisfactory meeting, which ended in prayer; and when I arose from my knees,
I found the governor on one side and his daughter on the other side of me,
both on their knees;
a posture in which people are too seldom found in this degenerate age of the world.

On the 10th of the first month we departed from the island of Anguilla,
with a pleasant gale, and had fair weather and winds for several days.
I spent some time of this voyage in reading, and met with a passage concerning friendship.
The comfort and beauty of it was set forth therein,
yet most who treat upon that noble subject, place the felicity thereof in humanity;
whereas true and lasting friendship is of a divine nature,
and can never be firmly settled without divine grace.
Christ Jesus is the prime friend of mankind,
from whom all true and lasting friendship flows, as from a living fountain,
himself being the head spring thereof.
"`Henceforth,`" says he, "`I call you not servants, but friends, and ye are my friends,
if ye do whatsoever I command you.`"
And again, "`By this shall all men know that ye are my disciples,
if ye love one another.`"
Oh, holy expressions! much to be admired,
and worthy every man and woman`'s imitation and practice.
Observe that when they had done whatsoever Christ had commanded them,
then they were to be his friends, and they were not only to be his friends,
but one another`'s friends, as he was theirs; and if occasion were, as he died for them,
so they would die for one another.
By this mark and true seal of the truest friendship,
all the world should know they belonged to Christ, that they were united to him,
and in him united to one another.
Nothing but disobedience and sin can ever separate this friendship.

Against this friendship which is in Christ, and grounded and founded upon him,
the gates of hell can never prevail;
but all friendship founded upon any consideration merely human, is brittle and uncertain,
and subject to change or mutability, as experience hath taught in all ages.

If any person has a desire to have a faithful friend,
let that person be sure to make choice of Christ;
for such as choose him have a friend in whom are lasting peace, comfort, and delight,
joy and pleasure, and in him alone are they to be enjoyed forever.

The 20th of the first month being the first of the week,
we had a comfortable meeting for divine worship,
in which the goodness of God was extended to us as we were
rolling on the mighty waters of the great deep,
after which we had pleasant weather and a fair wind, for several days.

On the 26th the wind sprung up at E. N. E., a hard gale, which lasted several days;
for about thirty hours it blew so hard that we could dress no victuals.
I thought on the words of Job, when he spoke to his impatient wife, saying,
"`Shall we receive good at the hand of God, and shall we not receive evil also?`"
or that which is accounted or looks like evil in the eyes of man.
In this time of exercise, the love and heavenly life of God, in his beloved Son,
filled my heart, and caused an overflowing of praises to his holy, glorious,
and blessed name.
Oh! it was exceedingly precious to my soul at that time.

The 1st of the second month we saw land,
being driven to the southward nearly two hundred and fifty miles in this last hard weather;
but we soon after arrived at our desired port.

I visited the meetings of Friends at Philadelphia, Burlington, the Falls, Abington,
Germantown, Bristol and Frankford, and found the people had been,
under a general visitation of the smallpox, insomuch that many hundreds,
especially of children, were taken off the stage of this life,
in the city of Philadelphia;
and I was concerned to exhort Friends in that city to bring their children to meetings,
and to educate them when young, in the way they should go,
that they might not depart from it when old; and that He who had taken many away, could,
if he pleased, take many more; for though he had laid down his rod at present,
the distemper in the city being much abated, yet he could soon take it up again.
It is my belief that the Lord Almighty will still continue to visit the city and people,
if there is not a reformation, with further, if not sorer visitations,
because he hath known them to do them good,
and make them a blessing to many islands and people;
giving them the fatness of the earth, and that which is far more, the dew of heaven;
so that he may justly say to us, as to Israel of old,
"`You have I known of all the families of the earth;
therefore I will visit you for all your iniquities.`"

In the beginning of the fourth month, Robert Jordan was married to Mary,
the widow of Richard Hill, all three worthy Friends.
The meeting on this occasion was large, and the marriage solemnized in the fear of God.
Divers Friends were concerned to speak to the people,
and it was greatly desired that those present, who were then spoken to,
might be married to Christ, the great lover of souls, who laid down his life,
the most precious life that ever was on earth,
and shed his precious blood for our salvation.

A few days after, I again took shipping for the island of Barbados,
being the sixth voyage, in the New Bristol Hope,
and left the Capes of Delaware the 8th day of the fourth month.
The 22nd of the month, being weary, I laid down to rest, and falling asleep,
was awakened with these words, "`Oh,
heart in heaven! it is an excellent thing to have an heart in heaven!`"
These words were comfortable to me, and left a sweetness on my mind all the day after,
for which I was thankful,
and greatly desired that my heart might be set and
fixed more and more on heaven and heavenly things,
and that my treasure might be in heaven, that my heart might be there also,
according to the doctrine of my Saviour; "`Lay up for yourselves treasure in heaven,
for where your treasure is, there will your heart be also.`"

The 27th being the first day of the week, we had a comfortable meeting,
the weather being moderate;
and on the 7th of the fifth month we arrived at Bridgetown in Barbados,
where we unloaded part of our cargo, and from thence we went to Speight`'s-town; where,
after a stay of about five weeks, we accomplished our affairs.
I also visited all our friends`' meetings, and some several times,
in which we were edified and comforted,
and divers of us had occasion to bless the holy name of God for his mercy to us.
Before we left the island, there happened a great storm or hurricane,
which did much damage to the ships and to the island,
blowing down many houses and spoiling much provisions,
destroying almost all the plantain trees on the island,
which is a very wholesome and pleasant fruit, and much used by many instead of bread.

I was clearing out the vessel when this storm happened, and being twelve miles off,
could not hear concerning her,
but thought it altogether unlikely that she should ride out so great a storm,
in so bad a harbour or road, it being open to the sea,
and the storm such as had not been known for many years, and some said, never but once,
to their knowledge, though more damage had at some other times been done to the shipping,
by reason that the hardest of the wind was not that way,
which was most dangerous to them in Carlisle bay, where they mostly lay;
they all got out to sea,
except two or three that were lost by the violence of the weather.
It was indeed a very dismal time, the vessels which rode it out were much damaged,
and one being loaded, ready to sail, sunk down, and was lost in the bay.
When I had cleared our ship, I set forward in order to see what was become of her;
but the floods were so great, and the ways were so bad,
I could not without some danger get to her that night;
but next morning set out from Joseph Gamble`'s, and to my admiration,
from the top of a hill on which a house was blown flat to the ground during the storm,
I saw our ship at anchor, having rode out the storm, with one sloop by her,
for which cause my soul was humbly thankful.

On the 17th of the said month, with some more than ordinary fatigue,
we got up our anchor and took in our boat,
and got our passengers and provisions on board, the sea breaking high on the shore,
so that several of our people and our boat were in jeopardy of being lost;
but at length we set sail, and having sailed slowly about six or seven miles,
we met with a sloop which had lost her mast in the storm,
and next morning met two large London ships, which had put out to sea,
not venturing to ride it out.

We had fine pleasant weather for several days after we left the island,
and on the 22nd of the sixth month, being the first-day of the week,
we had a meeting for the worship of God, which was comfortable and satisfactory to us.
The 4th and 5th of the seventh month,
we had very fresh gales from the northeast to the north, and were near a water-spout,
about a stone throw off, which surprised some on board, on which I came out of my cabin,
and saw the water run up out of the sea into the cloud,
as plainly as ever I saw the water run into the river,
till it filled the cloud with blackness,
and then it would break in great quantities into the sea, which is dangerous,
when falling on vessels.

The 5th of the month being first-day, we had a good religious meeting for divine worship,
wherein our people were earnestly exhorted to a holy life,
and to be earnestly concerned for the true faith, which is in Christ;
that faith which works by love, which is the evidence of things not visibly seen,
and is manifest by works of piety and virtue.
In this voyage we were twenty-two days from the island
of Barbados to the sight of Cape Henry,
in Virginia, and had a pleasant passage, in the main, to Philadelphia, where,
in the seventh month, was held our yearly meeting, at which I had a desire to be,
my watery employment having hindered my being at one for several years.
At this meeting I met with my old acquaintance and dear friends, John Richardson,
of Yorkshire, and Paul Johnson, of Dublin,
both on a gospel visit to the brethren and Friends in America.
The meeting was large, and attended with divine grace and goodness,
and ended with thanksgiving and praise to God and the Lamb.

While our ship was loading, I was at meetings at Abington, Germantown, Fairhill,
and Frankford, in Philadelphia county; and at the Falls of Delaware, Buckingham,
Neshaminy and Bristol, in Bucks county.
I was also at Burlington, at the marriage of William Callender, Jr., of Barbados,
with Catharine Smith, daughter of Daniel and Mary Smith, of Burlington.

On the 16th of the ninth month, I proceeded on the seventh voyage to Barbados,
in the ship New Bristol Hope, having on board several passengers, one of whom,
Elizabeth Martindale, was convinced of the principles of truth on the passage,
and afterwards suffered in divers respects, for making profession with us.

We had a long passage down the river, the wind being high and boisterous.
On the 22nd of the ninth month we left the Capes of Delaware,
and saw the island of Barbados on the 21st of the tenth month, before it was day,
and in the afternoon came to anchor in the bay of Speight`'s-town.
In this voyage I met with a painful and troublesome accident,
which happened in a hard gale of wind: I being to the windward,
and the ship having a large motion, missed my hold,
was canted from my place to the other side of the vessel, against the edge of a chest,
and so bruised my leg that I could not do my business as usual,
which was a great hindrance and disappointment to me.
But in about a month`'s time, with the assistance of some of my friends there,
I got indifferently through it, and also rode to Bridgetown,
and had several meetings there.
I was also at several good and comfortable meetings at Speight`'s-town,
where we had one the day we sailed, being the 21st of the eleventh month;
and on the seashore parted with our friends in great love, and set sail,
the wind being northeast, so that we could weather the island of Martinico;
we therefore sailed along by the islands of Dominico and Guadaloupe,
and had calms under the islands,
and sometimes the eddy winds from the mountains or high lands, would take the sails,
and carry the ship round, which made it tedious.
The 23rd and 24th we passed by several islands,
the winds and weather being fair and pleasant.
The 25th in the evening, it began to be hazy; and in the night we split our maintop-sail,
which cost us a great deal of labour and loss of time,
before we could get it mended and set again.
We had pretty fair weather about twenty days,
until we came on our own coast and into soundings,
when a hard gale of easterly wind springing up and blowing on the shore, was dangerous,
and we had a long night coming on; but through the favour of the Almighty,
we got off from the land.
In the midst of the danger of this storm, my soul sung praises to the Lord.

The 12th of the twelfth month we had another easterly storm,
being in about thirty fathom water; it blew and rained very hard,
and was exceedingly cold, and our coming from a hot climate made it more hard to bear.
In this storm we saw the lights which the sailors call corposants,
one of them was exceedingly bright, and sat about half an hour on our maintop-mast head,
plain to the view of all the ship`'s company,
divers of whom said they never saw the like,
and I think I never heard of or saw the like before.

The storm continued all night till day, when it abated,
and it being the first of the week, we had a comfortable meeting,
in which the people on board were advised to get divine and heavenly learning,
and not to be fools in religion, or in the things of God, nor to hate true knowledge;
for if they had all the natural knowledge and brightest natural parts in the world,
they would be but fools without the true fear of God,
which the wise King Solomon says is the beginning of wisdom.

The 27th of the month we saw Cape Henlopen,
having been twenty-seven days from the island of Barbados: this was a close, foggy day,
we could see but very little before us, and had like to have been aground on the shoals,
which they call the hen and chickens, but went between it and the Cape,
in three fathom water; the wind blowing hard at south we went up the bay by the lead,
for we could not see land; and the gale being so fresh,
we got to Bombay-hook from our Capes, in about six hours,
which is accounted twenty leagues; where we came to anchor,
and met with abundance of ice.
Merciful was the deliverance and preservation we
met with from the hand of the Almighty in this voyage;
may we ever gratefully remember it!
About a league above Bombay-hook, when the fog broke up,
we found ourselves close on the Jersey shore; and the wind sprung up at northwest,
and obliged us to come to an anchor; where the ice came down upon us,
which surprised some of us much.
Coming out of so hot a climate, into one so severely cold,
had a bad effect on most of our ship`'s company.
I had a sore fit of the phthisic, and was at times, almost breathless,
and thought I must die, for I could hardly breathe or speak;
but yet I resolved as long as I was capable of reflection,
I would think of God and my beloved Jesus;
in which thoughts and meditations I found some comfort and consolation.
I sat up for several nights, not being able to lie down for want of breath;
and drank sage tea, which was very helpful to me.

The next day the ice came down more and more upon us, and we feared to put back,
because if we had gotten aground in the bay, the ice might have demolished us;
so we took the most convenient time we could, and got up our anchor with some difficulty,
and stood for Reedy island, one of the best harbours upon Delaware;
but the wind and tide failing us, we could not get in;
and the ebb brought down the ice mightily on us,
so that it took away the head of our vessel, and cut her sides very much.
The next tide we got into the harbour, and lay close to Reedy island,
making the ship fast on shore.
While we lay here, several vessels came to us and fastened on shore as we did.
The ice drove one vessel on us, and broke our spritsail-yard.
Here I went on shore, where the people were very kind to us,
particularly the sheriff of the county, John Gooding, and his wife and family.
I went also to the house of John M`'Cool, who with his wife,
were very tender in their care and love towards me;
bathing my swelled and benumbed limbs until the frost was pretty well out of them.
The good will and tender love and care I here met with,
affect my mind in the noting of it: I pray the Most High, whom I love and serve,
to be their rewarder.

I had two meetings at our meetinghouse at George`'s creek,
where were people of divers persuasions, who gave good attention.
For these meetings I was truly thankful; for though through the extreme cold,
I could hardly speak when on board, I now spoke freely, much to my admiration,
and I believe to the people`'s satisfaction, more than is proper for me to mention;
wherefore I praise God.
When the weather was a little more open and the ice gone,
we sailed up the river to Philadelphia, where I was joyfully received by my friends;
and while the vessel was repairing and fitting for another voyage, I was not idle,
but visited Friends`' meetings at Philadelphia, Burlington, Abington, Germantown,
Byberry, Fairhill and Frankford; being sometimes at four or five meetings a week.
I was also at Haddonfield and Evesham meetings, in West Jersey;
both good and comfortable meetings, which will not easily be forgotten;
for therein God was graciously pleased to visit us with his word; blessed be his name.

The 4th of the third month we again set sail for Speight`'s-town, in Barbados;
and the 6th of the month, about six o`'clock in the morning, left the Capes of Delaware.
From this time until we got sight of Barbados, was twenty-five days,
which was the quickest voyage I ever had in this ship;
in which time we had three meetings for the public worship of Almighty God,
and to me they were beneficial; and for God`'s goodness,
I could do no less than return praise to him, who alone is worthy forever.

After I had done my business at Barbados and visited Friends`' meetings,
on the 5th of the fifth month I sailed for South Carolina,
touched at the island of Christopher`'s, and landed some passengers there.
From thence we went to sea, and the same night had a storm,
though we suffered but little, the wind being for us, so that we went before it,
and after it was over,
we had a pleasant passage of about fourteen days to the coast of Carolina;
and when we saw the land, the wind came against us,
which made some of our passengers very uneasy; but in meditating on the infinite Being,
I was favoured with inward comfort and strong consolation, so that I was humbly thankful,
and praised God.

We were prevented by contrary winds, and a strong current, from getting into Charleston;
and while we were beating about the coast, we met with a vessel which came from thence,
and gave us intelligence that many people died suddenly,
and that they buried ten or twelve in a day.
Hearing such news, and the wind being still against us, our passengers,
who intended for Carolina, concluded to go for Philadelphia: so we tacked about,
and stood for Delaware bay, and then we had a fresh gale ahead again for several days,
and spending so much time on the coast, our water was far expended,
and we agreed to come to an allowance of it, a quart each man, for twenty-four hours,
for several days before we got in.
We were about five weeks on our passage from Barbados to Delaware river.

Soon after our arrival at Philadelphia, we got our ship on the ways,
in order to refit and sheath her, in which time I travelled into several counties,
and had many religious meetings, in which I had good satisfaction;
and my old acquaintance and friends said they rejoiced to see me again,
after my sea voyages.
I was thankful in my heart for the good will of my good Master, and of my friends,
in those journeys, which was, and I hope ever will be,
better to me than choice silver or fine gold.

The winter setting in about a month sooner than usual,
many vessels were detained from going to sea, and frozen up;
and many vessels could not come from sea up the river,
so that a great damp was put on trade, and the frost coming suddenly,
many people were taken with colds and died,
in both the provinces of New Jersey and Pennsylvania.
My dear friend and kind landlord, Paul Preston, died about this time,
who on his dying bed, said "`He had no desire to live but to do good,
and that it had been his care to keep a conscience
void of offence towards God and to ail men,
which now was his comfort.`"
The hard weather continuing,
I found a concern on my mind to visit Friends`' meetings in the county of Bucks,
in Pennsylvania, and the county of Burlington, in West Jersey;
and was at above twenty meetings in about twenty days.
In this journey I was favoured with the grace and goodness of the
divine hand to a greater degree than I was worthy of,
though I was sometimes exceedingly poor in my spirit, and in my own judgment,
very weak for service and labour, both in body and mind; our meetings,
considering the severe season, were large, and I hope they were to general edification.

On the 25th of the tenth month, being the reputed birthday of our Lord Jesus Christ,
at a little town near the Falls, called Bordentown, we had a meeting,
where none had been held before by Friends,
in one of the houses newly built by Joseph Borden, the proprietor of the place:
he entertained us lovingly at his house, and generously offered ground for a graveyard,
and to build a meetinghouse on, and a handsome sum of money towards building it,
though he did not make profession with our Society.
Some that were at this meeting, who did not profess with us,
came over the creek on the ice to Isaac Horner`'s, in the evening,
where we had a satisfactory meeting, in which God through Christ, was glorified.
Daniel Stanton, my wife`'s sister`'s son, accompanied me in this journey,
whose company and ministry were acceptable, both to me and friends,
and we had meetings at the Falls, Bristol, Middletown, Wright`'s-town, Bordentown,
Crosswicks, Mansfield, Upper and Lower Springfield, Mount Holly, Rancocas,
Evesham and Chester, and divers evening meetings at several Friends`' houses.
It being a sickly time, I was often sent for to visit the sick,
in which visits we were comforted, and God`'s holy name was praised.

On the 18th of the eleventh month I was sent for to Bristol, to visit Ennion Williams,
who was dangerously ill, and to Burlington, to the burial of Elizabeth,
the wife of Jonathan Wright, who was buried from the great meetinghouse.
The meeting was very large, she being well beloved by her neighbours and acquaintance,
being a woman much given to hospitality, and indeed many of the Friends of Burlington,
have exceeded in that respect, the most that I have ever observed in my travels.
She was a pattern of piety, a loving, obliging wife, and tender, careful mother,
a kind neighbour, a loving and faithful friend, and so continued to the end;
some of her dying words were,
that she desired her love might be remembered to all her friends,
which was done openly in the said meeting, and tenderly affected many.

After I came home I was at the marriage of William Parker and Elizabeth Gilbert,
at which marriage was our worthy, ancient friend, John Richardson,
with divers other European Friends.
The meeting was large and edifying.

The river still continuing frozen up,
I had a desire to visit my friends and brethren in Chester county,
whom I had not seen for some years; and in order thereto,
in the beginning of the twelfth month, I with my kinsman, Daniel Stanton,
set out from Philadelphia, and went to Newtown, where we had a meeting next day,
being the first of the week,
and afterwards an evening meeting at Evan Lewis`'s. From
thence we went to the monthly meeting at Providence,
on third-day to Middletown, fourth-day to Concord, fifth-day to Birmingham,
sixth-day to London Grove; after which we had an evening meeting at a widow`'s house;
from thence we travelled on seventh-day to Nottingham,
and were at a large meeting there on first-day,
and had an evening meeting at a Friend`'s house, where some persons came,
who had never been at a meeting of Friends before.
On second-day we had a meeting at Susquehanna ferry,
to which divers people came over the ice, and it was a good opportunity to many of them.

Third-day we had a large meeting at West Nottingham,
and in the evening at William Brown`'s, and next we had a large meeting at New Garden,
and at Michael Lightfoot`'s house we met with two Friends from Ireland,
Mungo Bewley and Samuel Stephens,
who were now proceeding on their religious visit to Friends in Maryland, Virginia,
and North Carolina.

From thence I went to visit my old friend and acquaintance, Ellis Lewis,
who had a desire to see me; and we had an evening meeting in his chamber,
to our mutual comfort and refreshment.
Next day had a very large meeting in the meetinghouse at Kennet;
after which we went to Concord to the quarterly meeting for the county of Chester,
and were at three meetings there,
and likewise had three evening meetings at Friends`' houses;
at which meetings we had the company of my kinswoman Alice Alderson,
and her companion Margaret Coupland, who were lately come from the north of England,
to visit Friends in this and the adjacent provinces.

We went on third-day to the general meeting at Providence, which was very large;
Joshua Fielding and Ebenezer Large were there;
and we had an evening meeting at Rebecca Minshall`'s; and next went to Chichester,
where we had a larger meeting than I expected, considering the season;
we lodged at John Salkeld`'s. On fifth-day we had a good, open meeting at Chester,
and in the evening, another at Grace Lloyd`'s; next day had a meeting at Springfield,
which I believe will be remembered by some that were there,
when we do not see one another; afterwards we travelled to Philadelphia.

In the year 1732, arrived Thomas Penn, one of the proprietors of Pennsylvania,
and son of the truly honourable William Penn, governor and proprietor of this province.
A wise man, a good Christian, and a mild governor: a great promoter of piety and virtue,
and of good men.
May this his son walk in his steps!

In the first month was our general spring meeting,
at which were several public Friends from England, viz: John Richardson,
Alice Alderson and Margaret Coupland.
The meeting was large and edifying,
the said Friends having service therein to general satisfaction.

The 2nd of the second month I proceeded on a voyage to Barbados,
it being the first in the Snow Barbados packet, a vessel built on purpose for me.
We got to the Capes on the evening of the 20th of the second month,
and were obliged to come to anchor.
On the 21st we put out to sea, but the wind being against us,
and looking like windy weather, I concluded to come to under our Cape,
and wait for a fair wind: as soon as our Snow came to,
we got our boat out and went to Lewistown; and next day being first-day,
had a meeting in the courthouse; the people were glad of a meeting,
and I had a good opportunity with them.
After meeting I went on board and weighed anchor, and had a fair wind for above a week.
Near the latitude of Bermuda, we had smart gales of wind,
which obliged us to carry our topsail double reefed;
and after having been at sea twenty-seven days and one night,
in which time we had several meetings, we saw the island of Barbados;
though for the most part we had contrary winds, yet all was well, and God blessed,
who is forever worthy.

The 20th of the fourth month, having done my business,
and also visited Friends`' meetings, we sailed for Philadelphia; and on the 25th,
being first-day, we had a seasonable and serviceable meeting,
wherein the Almighty was worshipped and praised,
and the people exhorted to sobriety and temperance.
We were about twenty days from Barbados to Philadelphia.

After having stayed at home about six weeks,
and visited the meetings of Friends in divers places, to mine and their satisfaction,
on the 28th of the sixth month I proceeded on another voyage for the island of Barbados,
and left sight of our Capes on the 31st. The winds were for the most part contrary,
and before we got into the trade wind, we met with two hard gales;
the last of which was a kind of hurricane, in which we could carry no sail at all,
but let the vessel lie to the mercy of the seas,
or rather to the mercy of Him who made the seas and all that is therein,
and in the earth also.
In this storm we lost a square topmast, and divers other things belonging to the vessel;
but all our people were well and safe.
This voyage we had several comfortable religious meetings on board,
in which we were exhorted to prepare for another and better world,
this being so very uncertain and momentary, and full of various exercises,
temptations and afflictions.

I had on board three Whitehaven sailors, William Towerson,
William Trimble and William Atkinson,
and I do not remember that I heard any of them swear an oath during the whole voyage,
which I thought worthy to stand on record, because it is so rare in seafaring men.
About the beginning of the eighth month, being in the latitude of Barbados,
the thoughts of leaving my family and habitation,
and many of my loving relations and near and dear friends, as at divers other times also,
made me pensive and sorrowful; but it being on a principle of justice,
and sometimes meeting with the presence and goodness of God,
I was enabled to do my affairs and business,
and forbore to appear sorrowful as much as I possibly could,
or to be of a sad countenance in the sight of men; but to Him who knows all things,
and sees in secret, I poured out my soul in all my afflictions,
for he only is able to help me.
I met with some who untruly censured me, as covetous of the things of this world,
or to be rich; and that for the sake of these outward things, I might venture my life,
until I might lose it.
As to my life, it hath long been my desire to be ready to resign it, and is so still;
and as to those outward things, so far as I know, my heart is clear.
Food and raiment, and to be clear and even with the world,
having rather to give than receive, is all the grandeur I desire;
and if that be not granted, I hope to be contented without it, and to be thankful.
I look upon crowns and sceptres, and all the fine things of this world, but as trifles,
and diminutive, in comparison of a house and kingdom eternal in the heavens.
In this voyage, as usual, I read in the holy Scriptures,
and met with strong consolation therein, especially in the New Testament;
I also read much in the works of that eminent judge and good Christian, Matthew Hale.

On the 7th of the eighth month we arrived at Barbados, stayed three weeks and one day,
and had several religious meetings.
I hastened to accomplish my affairs before winter,
it being a time of the year when it is dangerous sailing on our coasts.
On the 30th of the eighth month we left the island of Barbados, bound to Philadelphia;
and on the 11th of the ninth month it pleased God to favour
us with a gracious opportunity to worship him;
wherein was declared to the ship`'s company the nature and advantage of good,
and the fountain from whence it flows; also the nature and disadvantage of evil;
the one springing from God, and the other proceeding from Satan, or the devil,
who is the root of all evil: and that men might be left without excuse,
God hath sent the divine and supernatural light of his holy Spirit,
to show to mortals what is good and what is evil;
in order that they might embrace the good and refuse the evil.

The 21st of the ninth month we had a very hard gale of wind at northwest,
which blew so hard that we were obliged to lay the ship to the wind;
for by the violence thereof we could not carry any sail,
and it was so dark that we could neither see stars nor one another, nor hear one another,
without we were very near, the seas rising very high.
Indeed, the long, stormy, and dark nights, were very dismal,
and some of our goods got loose in the hold.
In the beginning of the night, about the seventh hour, Philip Kearney, my apprentice,
fell into the sea and was lost, which was a deep affliction to us.

The 25th we saw land, and next day came to anchor in Delaware bay.
The loss of this lad was a cause that we were not so joyful,
as is usual for people to be when come to the shore.

The latter end of the tenth month I went the third voyage,
commander of the Barbados packet, from Philadelphia, bound to Barbados:
we were towed through the ice by two boats from Thomas Master`'s wharf,
and in two days got to Reedy island; from whence we sailed down Delaware bay,
where we lay two nights, the wind being contrary, and blowing hard.
We left our Capes in the night, it being dangerous lying in the bay;
and after being out several days, had favourable winds and pleasant weather;
but when we got into the trade wind, it blew hard and mostly against us.
The first land we saw was the island of Christopher`'s,
where we arrived in twenty days from our Capes;
and the market for provisions being at that time better than any other of those islands,
and the property of the vessel mostly belonging to me,
and the cargo generally consigned to me, I disposed of part of it.
Here being no meeting of our Society on this island,
I had meetings on board the vessel in the harbour,
and divers from the shore and several masters of vessels came to them,
the Snow having large accommodations for such an occasion;
and so far as I could understand, the people were generally satisfied.

Of late times, and also in this voyage, meeting with many losses and crosses,
and much affliction and various exercises, I was ready to say in my heart, Lord,
why am I thus afflicted, now in my declining years, since, thou knowest,
I love thee above all things, and that I would not willingly or knowingly offend thee,
my great and dear Lord?
It was answered, as though vocally spoken.
My only begotten and beloved Son, who never offended me, suffered much more.
This word being such an evident truth,
I begged patience to go through all my sufferings and afflictions,
so that at last I might live with Christ in the glorious kingdom of God forever,
where I might always bless and praise his holy name.

Five or six days after our arrival at this island,
a vessel that came out five or six days before us, arrived,
she meeting with the same boisterous weather as we did,
yet we made our passage ten or eleven days sooner.
Several other vessels bound to Barbados, put in here, through these '`contrary winds;
and when I saw others in the like circumstances with us,
I was the more thankful for being preserved safe, and so soon to this place;
yet it was a considerable loss and trial not to get to Barbados,
the island I was bound to.

At this island a person whose name was Galloway, a man of a great estate,
hearing that I kept meetings on board the vessel,
kindly invited me to have a meeting at his house,
and said he would give notice of it to divers of the gentlemen, as he called them,
of the island, telling me that I should be welcome to his house,
which was much more convenient than the vessel.
I was not very forward to accept of my friend Galloway`'s kind offer,
being sensible of my own weakness and inward poverty,
so that I made several excuses to evade it; but he obviated them all.
First; I asked him,
"`If he could bear the reproach of having a Quaker`'s meeting at his house?`"
He answered, "`Yes; there are good and bad of all societies.`"
Secondly; I asked, "`If his wife would like it,
or be willing that a meeting should be in the house?`"
He said, "`She desired it, and would be very willing.`"
Thirdly; I asked, "`If he thought he could sit in silence?`"
He told me, "`He believed he could.`"
I then told him, "`I was obliged to him for his kind and friendly offer, and God willing,
I intended to come, and tell my people of the ship`'s company to come also,
and desired him to give notice of it;`" which he did: and there was a large,
satisfactory meeting.
Oh! may the Almighty sanctify it to some souls, is my desire.

He and his wife were very courteous to me,
and invited many of his rich friends and relations.
His wife`'s father was a judge in this island, of good repute.
People of several professions were at this meeting,
and many expressed their being glad of it.
An attorney at law, said "`He was thankful for the words he heard that day,
and if I would stay with them, he would always come to our meetings.`"
One Judge Mills was at this meeting, and very kindly invited me to his house.
Some meeting me next day, said "`They were sorry they were not there.`"
The mistress of the house told some of the people, who were persons of note,
"`That they should remember what they had heard;`" and spoke it with a religious concern,
as it seemed to me.
When I went to this meeting I was very poor, and in much fear,
speaking with a great concern on my mind, for the people`'s salvation, and that God,
through Christ, might be glorified.

After this meeting it was as though a voice said unto me,
"`How dost thou know but for this cause, and for this meeting,
thou art brought to this island, though against thy will?`"
The people told me they did not remember that there
ever was a meeting of Friends before on this island.
The meeting had this effect,
that the people had a better opinion of our Society than they had before.
The subject I spoke of was, the excellency of the gospel dispensation,
above that of the law, in that it brought us to the law, went through the law,
and was above the law, and so far from destroying the law, fulfilled it;
for proof of which, they were referred to Christ`'s most excellent sermon,
which he preached on the mount.

From the island of Christopher`'s, I purposed, God willing, for Barbados;
which I apprehended would be a troublesome voyage,
it being about one hundred leagues to windward, and a strong current against us.
On the 19th of the twelfth month we sailed towards Barbados;
and the wind being ahead and blowing hard, we tarried two nights at the island of Lucia,
where we took in wood and water: the people here are mostly French,
and were very civil to us.

The 21st we put out again to sea; but the wind and current being against us,
obliged us to go into the harbour from whence we came,
and tarry for an opportunity more favourable.
While we were in this harbour, which is a very good one,
several vessels came in on the like occasion;
and a vessel that left Christopher`'s about three hours after us,
came here three days since we did.

We went out again in order to proceed to Barbados; but as before,
the current was so strong against us, and the wind also,
that we could not get forward on our way; wherefore we put back again to Christopher`'s,
and by the way, called at Antigua, where I had an open, satisfactory meeting,
for which I was truly thankful, and so were some not of our Society,
of whom there were divers, and some who had not been at our meetings before.

The next day we arrived again at Christopher`'s,
and there unloaded the remainder of our cargo, though much against my mind.
After having sold the most of our cargo at Basseterre, we went to Sandy point,
and there sold the remainder, and took in our loading for Philadelphia.

In loading our vessel.
Judge Brown was my very good friend, and helpful to me therein,
for which I think myself much obliged to him.

While we lay here I had a meeting on board our vessel,
to which came five masters of vessels.
It was a good meeting, though I spoke to them in much misery and pain, having very angry,
painful sores on my legs, occasioned by a fall in getting out of the boat;
the seas running high through the violence of the waves, I fell across the boat,
and broke both my shins very grievously.

The 31st of the first month, 1734, we had another meeting on board our vessel,
to which came several from other vessels, and some from the shore,
among whom was a young baronet and his host, a tavern keeper,
who at first behaved airily, but after some time, he was more sober,
and seemed respectful at parting.

I was invited to have a meeting next first-day on board the ship King George,
a large vessel; the master told me his cabin was large,
and would accommodate many more than mine;
but we did not stay so long as till the first-day.
After this meeting was over, the master of the large ship came on board,
and said he was sorry he had not come sooner,
so as to have had the opportunity to be at the meeting.

From Christopher`'s we set sail for the island of Anguilla,
and had a meeting at the governor`'s house on a first-day.
We stayed at Anguilla three days, and there took on board some bags of cotton on freight,
and sailed from thence the 10th of the second month.
The governor of this island, whose name was George Leonard,
told me that he should live and die in our principles,
saving that he must defend his people.
But he did not consider that his defence might destroy both him and them,
and that such defence was directly contrary to Christ`'s doctrine and practice.

Not far from Anguilla is an island they call St. John`'s,
the inhabitants of which are Dutch: the negroes there lately rose and took the island,
killed the people, spoiled their plantations and burnt their houses.
I lodged at the house of a person who went to subdue those negroes,
who were too strong for him and his company, and the negroes killed divers of them,
and among them killed this man`'s two sons,
for which their mother and sisters were in bitter mourning, when I was at their house.
The thoughts of the bloodshed and vast destruction, which war makes in the world,
caused me to cry in my heart, "`How long.
Oh Lord! thou holy, just and true God,
will it be till nation lift up the sword no more against nation,
and the people learn war no more.`"
