[short="Testimony of Philadelphia Monthly Meeting"]
== The Testimony of the Monthly Meeting of Friends, in Philadelphia, Concerning our Ancient Worthy Friend, Thomas Chalkley, Deceased.

The christian experiences of the faithful being useful to direct such
as are desirous of following them in the path of true religion and virtue,
and their good examples shining with the greatest clearness, when they have,
with the flesh, put off all human infirmities; justice to their memory,
and a concern for the benefit of their survivors,
demand our grateful remembrance of them,
and the contributing of our endeavours to render their labours useful to posterity.
These considerations engage us to preface the writings
of this our esteemed friend and elder in the truth,
with this testimony concerning him.

He was a member of our monthly meeting above forty years,
so that some of us had opportunities of being intimately acquainted with him,
and of knowing his fidelity and diligence in promoting the
cause of truth and the edification of the church of Christ;
this having been the principal engagement and concern of his mind,
and which he preferred to any other consideration, as will evidently appear to those,
who with an honest and unprejudiced intention,
peruse the journal of his life and travels.

By this it will appear, that he was, in the early part of his life,
sensibly affected with the visitation of divine life and grace, and by adhering thereto,
was preserved from the vanities and follies which often divert and alienate
the minds of youth from a due remembrance and awful regard of their Creator.
Thus he was enabled to bear a testimony of christian
patience and self-denial in his youthful days,
and by keeping under that exercise, as he advanced in years,
attained to further knowledge and experience in the work of religion,
in which he had a sight of the necessity of keeping in a state of humility,
and of bearing the cross of Christ, which mortified him to the world.
The loss which many sustain by the anxious pursuit of the lawful things thereof,
appearing to him, he was concerned to avoid it,
and in obedience to the precept of Christ,
to seek first the kingdom of God and his righteousness, having faith in his promise,
that all things necessary for him should be added.

Thus the love of God influencing his mind, and opening his understanding,
he became concerned for the general good of mankind,
and received a gift of the ministry of the gospel of Christ,
before he had attained the age of twenty-one years; in the public exercise of which,
he soon after travelled through many parts of England, and into Scotland.
In the year 1697 he came to visit Friends in this and the adjacent provinces of America,
where his ministry and conversation were to the comfort and edification of the faithful,
as some of us can with satisfaction declare,
from our knowledge and remembrance of him at that time;
and the near fellowship and union he then had with Friends here,
we believe contributed to his more speedy determination of settling among us,
which he afterwards thought it his duty to do,
though leaving his parents and relations was no small cross to him,
being of a dutiful and affectionate disposition.

After fixing his residence among us,
he persevered in his concern and labour for the edification of the churches,
and gathering people to faith and dependence on the inward teachings of Christ,
and for that purpose only he travelled many long journeys and voyages
through the several English colonies on this continent,
and most of the islands in the West Indies, and in Europe, through England, Wales,
Scotland, Ireland, Holland, Friesland, and several parts of Germany,
and the adjacent northern kingdoms.
In many of these places his ministry and religious
labours were blessed with the desired success,
of which there are yet some witnesses living, and others,
who were convinced of the principles of truth by his means,
became serviceable members of the church,
and continued therein to the end of their lives.

But as the wise king Solomon formerly observed,
that one event cometh to the righteous and to the wicked,
so it happened to this good man,
who met with various losses and disappointments in his temporal estate; after which,
the circumstances of his affairs engaged him to undertake some business,
in the management of which he was obliged to cross the seas frequently.
This however,
did not abate his zeal and religious care to make use of
all opportunities of visiting the meetings of Friends,
when among them, and of calling, at other times,
to such who might be accounted as the outcasts of Israel, and the dispersed of Judah,
or as sheep not yet of the fold of Christ;
and his services of that kind are worthy to be commemorated,
having been often productive of good effects.

His patience was remarkable in disappointments and afflictions,
of which he had a large share; and his meekness, humility and circumspection,
in the general course of his life and conversation were conspicuous and exemplary.
As he frequently exhorted and admonished others to the observation and practice
of the many excellent precepts and rules of Christ our Lord and law-giver;
and more especially those expressed in his sermon on the mount,
which contains the sum of our moral and religious duties,
so he manifested himself to be one of that number,
whom Christ compared to the wise builder, who laid a sure foundation;
so that his building stood unshaken by the various floods
and winds of tribulations and temptations which he met with,
both from within and without.

He was a lover of unity amongst brethren, and careful to promote and maintain it,
showing the example of a meek, courteous, and loving deportment, not only to Friends,
but to all others, with whom he had conversation or dealings;
so that it may be truly said,
few have lived more universally beloved and respected among us.
It was manifest that this did not proceed from a desire of being popular,
or to be seen of man;
for his love and regard to peace did not divert him from the discharge
of his duty in a faithful testimony to those who professed the truth,
that they ought to be careful to maintain good works.
He was often concerned zealously to incite and press
Friends to the exercise of good order and discipline,
established in the wisdom of truth, by admonishing, warning,
and timely treating with such as fell short of their duty therein,
and by testifying against those who, after loving and brotherly care and endeavours,
could not be brought to the sense and practice of their duty;
and thereby he sometimes shared the ill-will and resentment of such persons.

The several essays which he wrote on religious subjects while at sea,
are further proofs that his mind was principally
engaged in the great business and concern of religion;
and as he continued under the same engagement to the end,
we are fully persuaded the words,
with which he concluded his last public testimony in the island of Tortola,
may be truly and properly applied to him, that he had fought a good fight,
and had kept the faith, and we doubt not, he now enjoys a crown of righteousness.

Much more might be truly said of his integrity, faithfulness and worth,
but we do not think it necessary;
our chief intention being to express our respectful remembrance of him,
and our unity with his labours and services, and in order to assure those,
to whom he was not personally known,
of the truth of what he hath himself written of his life and travels.
We believe,
as he was a man signally influenced with the spirit
of universal love and good will to mankind,
this was his chief motive for writing;
and we are sincerely desirous that his good design may be answered,
and that the glory of every good and perfect work
may be attributed to that divine power alone,
which can qualify others to supply the places of
those faithful ministers and servants of Christ,
who have been of late years removed from among us, and are of that number,
of whom it is written, "`Blessed are the dead, which die in the Lord, from henceforth;
yea, saith the spirit, that they may rest from their labours,
and their works do follow them.`"

Signed on behalf, and by appointment of the monthly meeting of Friends in Philadelphia,
the 28th day of the second month, 1749, by

Israel Pemberton.
