[short="Exhortation to Youth and Others"]
== An Exhortation to Youth and Others, Being Part of a Letter From Thomas Chalkley, to a Friend in Dublin.

Let the young men and maidens diligently read the holy Scriptures;
and whenever they come to a passage that affects them,
let them not only turn down that leaf,
but let them be sure that it hath place in their hearts:
and when they read of a good man or woman,
let them earnestly pray and fervently cry to the Lord,
the great God and Father of our Lord Jesus Christ, and God of the righteous in all ages,
that he would please to make them like those his dear children and servants.
Oh! that young people might not forget this great command of God, "`Honour thy parents,
that thy days may be long upon the land which the Lord thy God giveth thee.`"
How many stubborn youths hath the Lord cut off in their prime,
and in the flower of their days; and on the other hand, how hath the Almighty blessed,
prospered, preserved and honoured those who have been obedient to their parents,
and honoured them and their elders?
And let the young men and maidens note this,
that none truly honour their parents and elders, but those who are pious and virtuous;
such were Joseph, Samuel, David and Solomon; as also King Josiah,
who began to reign at eight years old.
God Almighty gives to many a sense of his grace at that age, and thereabouts;
he ordaineth praise many times out of the mouths of babes and sucklings.
Let the youth endeavour to follow those good and great men; and for their instruction,
I shall say something of the above five worthies.

[.numbered-group]
====

[.numbered]
_First,_ in particular, beginning with Joseph. His father sent him to his brethren;
he went willingly, though his brethren hated him;
and when it was in his power to hurt them, he rendered them good for their evil;
a good example for both young and old.
And when tempted to sin by his mistress in Egypt, he said,
"`How can I do this great wickedness, and sin against God?`"
who highly favoured him for his piety, virtue and chastity.

[.numbered]
_Secondly,_ Samuel, for whom his mother prayed earnestly to the Lord;
and when he had given him to her, she gave him to God again:
a good pattern for all mothers.
When he was but a little lad, the Almighty called him, and he thought it had been Eli;
and said, "`Thou calledst me?`"
"`No,`" said the old man, "`I did not call thee; lie down again.`"
He did not grumble, as many of our youth do: when the Lord called again,
he willingly ran to Eli; he did not love his bed so much as obedience, and said,
"`Thou didst call me;`" Eli observing that God had spoken to the child, said to him,
"`when he calleth again, say, Speak, Lord, for thy servant heareth.`"
Let old ones mind this, and encourage their youth to answer the call of God betimes:
God called again, and he answered, "`Speak, Lord, for thy servant heareth.`"
The Lord, by his grace, calls to little ones, many times in the midst of their play,
and sometimes in their beds.
Oh! that our youth may do and say as little Samuel; that they may grow as he did,
and be in favour both with God and man.

[.numbered]
_Thirdly,_ David, his father`'s youngest son, kept his sheep,
and in that innocent employ the Lord was with him.
His father sent him to his brethren; but Eliab, his eldest brother, frowned upon him,
and reviled him.
He only made this soft reply; "`Is there not a cause?`"
He overcame the great Philistine, in the name of the God of Israel;
and God highly exalted him for his uprightness, sincerity and piety,
which were very great; for notwithstanding Saul would have killed him;
yet when David had him in his power, he spared him, insomuch that Saul wept, and said,
"`If a man find his enemy, will he let him go?`"
And there was loving greeting between them: so he overcame the evil of Saul`'s heart,
by the good that was in his, according to those holy expressions of the apostle Paul,
"`Be not overcome with evil, but overcome evil with good.`"
Words worthy to be written in letters of gold,
and more worthy to be observed and practised.

[.numbered]
_Fourthly,_ Solomon, who asked of God wisdom, being in his own eyes but as a little child,
said unto the Lord,
"`Give unto thy servant an understanding heart:`" which request God granted him,
and gave him also riches and honour.
Oh! see the benefit of pleasing God, young men and young women.

[.numbered]
_Fifthly,_ Josiah, a young prince and king.
How zealous was he for God`'s service and worship!
What a wonderful reformation he made in the land, and how was he lamented at his death,
as generally all good, and zealous men and women are, whether old or young.

====

Having touched a little upon the young men, let me remember the young women also:
as for example, Ruth and Abigail, two discreet young women; the first very loving, kind,
and true to Naomi, her mother-in-law: a good pattern for all daughters-in-law:
"`Entreat me not,`" said she, "`to leave thee; for where thou goest, I will go;
and where thou lodgest, I will lodge; and where thou diest, there will I be buried;
thy people shall be my people,
and thy God my God,`" and the Lord abundantly rewarded her for this godly resolution.
Boaz had a sense of her virtue and piety, and said, "`All the city of my people do know,
that thou art a virtuous woman.`"
Which doubtless was a strong motive for him to love her;
and that love commonly lasts till death: whereas when money is a motive,
it often happens that many evils attend.

Consider also wise Abigail, her ingenious speech to David,
and contrivance to hinder him from shedding blood; which he was coming to do,
thinking he had cause, but was prevented by her wisdom.
This was a great motive to him to love her, after Nabal`'s death, and to take her to wife.
She was no proud woman; "`For,`" said she,
"`let thy handmaid serve to wash the feet of the servants of my lord.`"

As there are many good examples in holy Scripture,
whereby young people might be stirred up to virtue;
so also there are examples of the judgments of God on disobedient, impious,
vain and ungodly men and women, even young and old.
Let our youth consider, I beseech them, wicked, disobedient Absalom, and poor Dinah:
also the prince and the Moabitish damsel, whom zealous Phineas slew; for God was angry,
and is angry with the wicked every day.

The before mentioned good men and women were in the time of the law;
and let me add to them,
the holy pattern and good example of our great Lord and blessed master,
who loved righteousness, and hated wickedness, therefore he was highly exalted,
and anointed with the oil of gladness above his fellows:
he had the heathen given him for his inheritance,
and the utmost parts of the earth for his possession: and what is more,
all power in heaven and earth.

Oh! dear young men and maidens! he is our great pattern,
whom we ought to take for our example; walking in all humility and reverence:
Christ saith, "`He that will be my disciple, that is his scholar, must take up his cross,
deny himself, and follow me.`"
Oh! blessed pattern!
Oh! glorious example! let us follow him whilst we have breath;
for it is always well for them that follow him.
What think ye, young men and maidens! had it not been well for that rich young man,
had he left all, and followed dear Jesus: be ye your own judges;
look on your pattern Christ Jesus, when he was but twelve years old;
see what he was doing, forget not that saying which his mother laid up in her heart,
"`Wist ye not that I must be about my Father`'s business?`"
I can say through some experience, it is good business.
Let me tell you for your edification, I have served my master, holy Jesus,
and followed him several years according to the best of my understanding,
and I have always found him a good master; his service is sweet,
and his work is delightful.
I have a great deal more to say for my Lord and Master, but my design is brevity:
"`His yoke is easy, and his burden is light.`"
He hath said it, and I have experienced it.
Wherefore I am the more free to invite you to follow him, and be his scholars.
An eminent servant and scholar of his said, "`Be ye followers of me,
even as I also am of Christ.`"
The apostle Paul exhorts Timothy, a young scholar, and his son in the faith,
to be a good example to others; as also his son Titus.
We are also told of four young women, who were prophetesses, and divers others;
a more particular account of whose exemplary lives and actions
is recorded in the holy Scripture for our learning;
unto which, with the grace of God in the heart, I recommend all young men and women,
and conclude this small token of my very dear love in Christ, our holy Lord and master,
desiring the above may be as so many patterns for them to follow.

[.signed-section-signature]
Thomas Chalkley.
