[short="A Loving Invitation to Young and Old"]
== A Loving Invitation to Young and Old, in Holland and Elsewhere, to Seek and Love Almighty God, and to Prepare in Time for Their Eternal Welfare.

[.centered]
=== Preface.

Having from my childhood been a lover of the Dutch,
and that love being increased by travelling in Holland and Germany,
it came weightily on my mind to invite and persuade this people,
with others into whose hands this may come, and especially the youth, to love, serve,
and fear the Lord, the Almighty, the great Jehovah,
and that they first seek the kingdom of God and his righteousness,
as Christ exhorts or commands.
Those weighty expressions, with the large promise thereto annexed,
are well worth the due notice and consideration of all, both youth and aged;
but seem to be very apt to the condition of those
that are just entering into the affairs of the world.
Oh! that the youth had but faith in the blessed Lord Jesus, and owned his pure doctrine,
now in their tender years; and in the prime of their days.
"`That they would remember their Creator in the days of their youth,
before the evil days come;`" that in their blooming spring time,
they might be like lovely branches, and growing trees of righteousness,
bearing much good fruit of piety and virtue; in which, saith our Lord Jesus Christ,
"`is your heavenly Father glorified.`"
This is the real and hearty desire of my soul, for the youth of this and all generations,
in all nations throughout the world: the universal love of God flows in my soul,
like a living stream, to all my fellow mortals.
The great love of God in Christ Jesus, our Lord and Master,
is abundantly and universally shed abroad to all nations,
through his eternal Spirit and grace in the hearts of the sons and daughters of men,
in order to draw, lead, and guide men and women from earth to heaven.

Being desirous according to my measure, to promote truth and righteousness in the earth,
and having been sensible of the love, mercy and goodness of God,
in '`my very young and tender years, I am willing,
for the sake of well inclined young men and women, to send this loving invitation:
and am desirous that it might be translated into the Dutch language;
hoping it may be beneficial to some well inclined souls, to stir them up to seek, serve,
and love Almighty God.
Amen.

So wisheth and heartily prayeth, a friend to, and lover of all mankind.

[.signed-section-signature]
Thomas Chalkley.

It is a thing truly excellent for mortals to love, serve, and fear him that made them,
and gave unto all life and being: and to begin this work betimes,
is very advantageous to the never dying soul.
It is an indispensable duty, which is incumbent upon every one, male and female;
and whoever is found in the neglect thereof, will certainly have cause to repent it;
and unless they repent before they go hence, and see man no more,
will be miserable to all eternity.
This solid consideration hath often been weighty on my mind, and I could not be clear,
as I thought, in the sight of God, without laying it before men and women.

Truth commands us, reason persuades us, and example is very powerful and inviting,
that the children of men would be wise to salvation,
and embrace the love of God in his dear and well beloved Son, our Lord Jesus Christ,
who himself said, "`I am the way, the truth, and the life.`"
Oh! surely here is a threefold cord, i. e., truth, reason, and example,
which is not easily broken: God Almighty grant, for Christ`'s sake,
that by it poor souls may be drawn to him, even now in their tender years: Today, today,
if any will hear the voice of the Lord, let them not harden their hearts;
for that is provoking to him that made us.
How know we whether he who made the heavens, will be pleased to give us another hour?
How know we, but that after this day we may never open our eyes,
till we open them in eternity?
Oh! eternity, eternity, that boundless ocean! who can fathom those words,
forever and ever?
What will this world and all its glories and vanities signify, or avail to poor souls,
when lying on a dying bed.

It will therefore be well for both old and young to note this:

[.numbered-group]
====

[.numbered]
_First;_ The old, because it is not likely they should have many days,
according to the course of nature and a common proverb, i. e., the young may die,
but the old must die.

[.numbered]
_Second;_ The young, because they know not but that they may die tomorrow.

====

In the great and notable day of the Most High,
heavenly things will be found serious and solid truths, and not toys and trifles,
nor indifferent; when he shall come as in flames of fire, to render vengeance,
which is his only, upon all the workers of iniquity,
and shall come to judge the secrets of all hearts by that great and just Judge,
the Lord Jesus Christ.

Wherefore, let me prevail with some poor souls, now in time, to lay the truth to heart,
and to be found in the work of God in their day; that so for their pains here,
they may receive their penny hereafter; and that enlivening,
that quickening answer of "`well done,`" may be their portion,
and the glorious lot of their inheritance: "`Come, ye blessed; well done,
good and faithful servant: enter thou into the joy of thy Lord.`"
Oh! powerful voice and heart ravishing sentence! enough to make one alive, though dead;
and exceedingly joyful, though sorrowful even to death.

This divine favour and grace,
wherewith the Most High will favour those that love him and faithfully serve him,
in that great and notable day, will far exceed the favour of kings and princes:
for those that get the latter, can only be happy, or so accounted, in this world,
which is but momentary; and those who are living and sensible witnesses of the former,
are certainly happy, even in this world, although men may not see it,
and likewise everlastingly happy in that world which is to come.
To be sensible of God`'s grace in the heart, and to follow the holy teaching of it,
is preferable to all things here below, it will make one more wise and more comely,
than all outward learning, beauty, or parts whatever.
God Almighty grant, I beseech him, that all our young men, our rich men, our wise men,
may glory only in him, according to the language of the spirit in the holy Scriptures,
"`Let not the young or strong man glory in his youth or strength,
nor the rich man in his riches, nor the wise man in his wisdom; but he who glories,
let him glory in the Lord;`" or in this, "`That he knows the Lord.`"
Let the wits of the age consider this well;
let the boaster and disputer rightly note this,
and he will have cause to bow before heaven`'s Majesty.
What becomes of the young man`'s and young woman`'s strength and lovely beauty,
when their heads are laid in the cold gravel What will become of,
or of what service to him will be, the riches of the rich man,
when he shall receive his summons to his long home?
May he not then say.
Oh! that I had been as industrious to get heaven and peace with my Maker,
as I have been to get this world.
Let all worldly-minded men and women remember the expostulation
of Christ Jesus with the rich young man.
This is not to hinder any in their outward concerns:
for the heart of a man may be in heaven, though his hands may be in his employment.

And as to the wise man: pray what will become of his great wit, his acquired parts,
his arguments and criticisms, when pale faced death shall look him in the face,
and strike him with his sharp arrow?
Then he will find, that it had been much better for him, had he lived well,
although he had not talked so much, or so well.
To talk well, is good; but to live well is much better.
To talk finely, and live badly,
is of little worth Oh! that the great Master workman of all, may drive home this nail,
in the heart of him whose eye shall look thereon, by his mighty hammer,
the hammer of his word, his heart breaking, heart melting, and heart piercing word;
according to the doctrine of the Holy Spirit in the holy Scriptures,
"`Is not my word as a fire?
Is not my word as a hammer?
Is not my word as a sword?`" i. e. to burn, to break,
to cut down all manner of sin: not to destroy man,
but sin in man.
Hear further the language of the Holy Spirit; "`Say not in thine heart,
who shall ascend up into heaven, to fetch it down from above?
Or who shall go down into the deep, or beyond the seas, to fetch it from thence?
But what saith it?
The word is nigh thee, in thy heart, and in thy mouth that thou mayest do it.`"
This was, and is, and ever will be, the doctrine of the gospel;
from which people may perceive that Christ Jesus is near to them; near to save,
near to deliver, near to redeem.
The great Jehovah, the blessed Jesus, the holy divine Spirit, is not a God afar off,
but a God near at hand, and a present and sure help in the needful time.
Oh! blessed be his name forever and ever.

I appeal to the consciences of all men, whether they have not,
or do not sensibly witness something of a nature contrary to sin and unrighteousness,
to reprove them and convince them of the evil of their ways and doings,
perhaps sometimes in the midst of their vanity, in the song, in the dance,
or in the game; or sometimes after a debauch, or for their pride,
either in mind or in apparel, for overreaching, or covetousness; all which,
with all manner of evils, are of the devil.
And the King of heaven is lifting up his holy and
righteous spirit as a standard against it,
and against him who is the author of it.
Let this his convincing grace take place in thy heart.

Oh mortal man! for know of a truth, it is the grace of God to thy soul;
for infallible proof of which, besides the experience of the faithful,
take these two texts of holy Scripture, the doctrine of which will stand forever,
notwithstanding all the opposition of man; "`I will pray the Father, says Christ,
and he will send you another comforter, even the Spirit of truth,
that he may abide with you forever; and when he is come,
he shall convince the world of sin.`"
Again, "`The grace of God which brings salvation, hath appeared unto all men,
teaching us, that denying ungodliness and worldly lusts, we should live soberly,
righteously and godly, in this present world.`"
Why should the Almighty show to men the evil of their ways?
Why does he not let them run on in their vanities, without control?
"`Oh! ye children of men! it is his mere grace and mercy to the precious, dear bought,
and never dying souls of poor mortal mankind; for he would have none to perish.
If any perish, their destruction is of themselves, but their help is of the Lord.
Oh! that people would be entreated and persuaded, through loving invitation,
to follow the Lord fully, and do his work faithfully.

I humbly beg of the Lord, the great God, and Father of spirits,
and of our dear Lord Jesus, that this may be instrumental, in his hand,
to draw some poor seeking, travailing soul from earth towards heaven; the which,
if it doth, let the praises be given to God alone, through his well beloved Son.

First, then: As to truth, I would hope few in this generation, who profess Christianity,
need to say.
What is truth?
God Almighty, Christ Jesus, the Holy Spirit, is that infinite, divine truth,
which will endure forever; and he hath said,
"`Thou shalt love the Lord thy God with all thy heart,
with all thy mind and with all thy strength.`"
He is richly worthy thereof: this is his law which is to endure forever;
and he who doth and teacheth it, is to be called great in the kingdom of God;
and that it might not be forgotten, he wrote it on stony tables; which law,
Jacob`'s seed broke and transgressed.
Wherefore, thus saith the Lord, who spoke by the prophet,
"`I will put my law in their inward parts, and write it in their hearts.`"
There it is written in large characters, very plain and legible,
and easy to be read of mankind.
Moses, the man of God, was an instrument to promote the law outwardly,
written on tables of stone, among the children of Israel: so Christ Jesus,
in this gospel-day,
is promoting and proclaiming the power of this law
inwardly engraven in men`'s heart by God`'s finger,
throughout the whole world.
This great law of love, in which all the law and the prophets are contained,
Christ not only lived in, and declared to mortals; but he also died in it,
and for us sealed his holy, glorious testimony and doctrine,
with his most precious blood.

This is he, of whom the voice from the most excellent glory said,
"`This is my beloved Son, in whom I am well pleased, hear ye him.`"
This is he, of whom the former lawgiver said,
"`The Lord your God shall raise up a prophet from amongst your brethren,
him shall ye hear in all things.`"
This is he who said, "`I am the way, the truth, and the life.`"
This is he who said, "`He dwelleth with you, and shall be in you:`" and again,
"`I stand at the door and knock, if any man hear my voice, and open the door,
I will come in to him and sup with him, and he with me.`"
His love is wonderful; he not only commands obedience, but invites to it.
Who can be so hard-hearted, and so cruel to him and themselves also,
as to slight and refuse such heavenly offers of infinite love, grace and mercy?
The spirit and the bride say, come; and all that are athirst may come and drink freely,
and buy heavenly milk and rich wine, without money or any outward price.

Secondly, Touching reason:
it is very reasonable that we should serve and love God Almighty,
in the space of time that we have in this world, and work the works of piety and virtue,
because there is solid peace therein: here none can make afraid,
but the soul is calm and quiet, being anchored in a safe harbour.
Here no law can take hold of us.
If any should imagine that there are no future rewards or punishments,
which no mortal can do without blushing or self-condemnation, as I conceive;
yet a life of holiness is a much better life, even for the body,
for its health and most sweet repose, and for pleasure that is solid, and not flashy;
and for its outward tranquillity in every respect.
I appeal to the reasoning wits of the age,
whether the above be not a great and undeniable truth: besides, all true men and women,
in practising as above, have a living hope and faith, through and in Christ,
of a glorious rest in eternity, which is very reasonable to believe.
Christ wrought such wonderful works and mighty miracles,
which before were never wrought by man on earth;
so that those must needs be self-condemned that believe not in him, his works and grace.

There is no writ nor wit in the whole world, that can, or ever will be able to make void,
or lay waste the mighty and miraculous works of truth,
which were done by the blessed Jesus.
Moses was a mighty man of God, and highly favoured and greatly beloved of him,
and did many mighty works; yet Christ exceeded him, as also did his dispensation.
Moses went through the sea: Christ went upon the sea.
Moses prayed for bread from heaven, and it was given in abundance;
Christ with a few small fishes and seven loaves, fed many thousands,
which was unreasonable to expect, but from a divine hand.
Moses prayed for water for the people: Christ made wine, and admirable wine too,
even of water.
Moses preached the law and judgment to Israel only; but Christ Jesus preached grace,
mercy, peace and truth, not only to Israel, but also to all the world,
through divine faith in God, in and through repentance, and the work of the spirit.
Oh! is not here reason and truth pleading with, and persuading poor creatures to love,
serve and follow, reverence and fear, their Creator.

It is likely some such doctrine as this might better please the sparks of the age,
and the jolly young men and maidens up and down in the world, viz: "`Rejoice,
Oh! young man and young woman, and let thy heart cheer thee in the days of thy youth;
follow the desire of thy heart, and the sight of thine eyes:`" But let them remember,
that for all these things God will bring them to judgment:
they must surely come to judgment.
They will have it inwardly and secretly in their hearts, here in this world,
notwithstanding they may endeavour to hide it from men;
but they cannot hide it from Heaven, from the all-seeing,
heart-piercing eye of the holy One: "`He who inhabits eternity,
whose dwelling is in the light; and whose eye goes through the earth,
beholding the good and the evil;`" sees them at all times,
and without repentance they will have condemnation without end,
in the world that is to come.
Let the youth and aged seriously consider it.

And further,
let them call to mind the great and heavy judgments
that have fallen upon wicked and ungodly men,
many of which were foretold by the messengers of heaven,
and came to pass according to their sayings, viz: the flood of waters,
which destroyed the old world, which the very Indians in America have a notable idea of,
handed down to them by the tradition of their fathers to this day.
The destruction of the land and inhabitants of Sodom and Gomorrah,
and the thousands of thousands that have been destroyed in battles, which will still be,
and continue to the world`'s end, unless people come into the love of God,
which will teach them to love one another,
and into the faith and doctrine of the Prince of Peace, which is, "`To do unto all men,
as we would have them do unto us,`" and to "`do good
for evil;`" which to be sure is not to destroy.
Likewise the destruction of Jerusalem and scattering of the Jews,
the seed of faithful Abraham; and divers terrible earthquakes,
which have happened in these latter ages of the world;
some of the dreadful ruins of which I have seen in my travels.
Surely there is much reason to walk in reverence
and holy fear before the great Lord of all:
he who made the heavens and the earth, the seas and the fountains of water,
and hath given life and breath to all that move therein,
can take it from them at his pleasure, in the twinkling of an eye.

Oh! happy are all those who live and dwell in the holy fear of God,
and in the self-denying life of Jesus: no greater happiness or felicity,
than to be one of these.
Let my soul dwell here, and be in unity and fellowship with all such forever.

As to the third and last part of the argument, viz: example; which, as the proverb says,
is above precept.
Good example is very taking with many,
and often happens to be very affecting to the younger sort more particularly:
for they look out much at others,
and take great notice of the words and conduct of their elders and superiors.
Jacob was a good example to his great family: he was a pious affectionate father,
a loving husband, a faithful servant, and an obedient son:
the history of his life and travels in holy Scripture is affecting.
He sought God betimes; and how humble,
how lowly did he behave himself in his pilgrimage! his father and mother called him,
and bid him go; he does it without any replies to the contrary;
not like some of the youth of this age.

Being benighted on his way, he lays himself down; his pillow was hard, but his bed large,
and the heavens were his curtains; his sleep was sweet, and his dream precious.
In which sleep he sees angels; and when he awakes, he says,
"`Surely this is none other than the house of God and the gate of heaven.`"
The condition of his covenant with his Maker, as to outward things,
was as small as well could be, viz: Bread to eat, and raiment to put on,
and the presence of his Maker, with his blessing.
This was when he was about to set up for himself in the world: his mind was not high,
neither sought he after great things; notwithstanding which,
the Almighty gave him abundance.
So onward he went, and came to Laban, and became his servant.
I could wish that all young people, who are servants,
would follow his steps in faithfulness, then might they be a blessing to their masters,
as he was to his.

I ever observed in my travels, having travelled much in divers nations,
and made many observations, that Almighty God hath greatly blessed obedient,
industrious children and servants; which observation,
I hope will be of good use to the world, if well considered.
And on the other hand, I have taken notice of the contrary,
and have perfectly understood,
that God`'s hand hath been manifestly against those
who have been disobedient and ill natured,
and idle; which may be an useful caution to all.

The Lord blessed the good service and faithful industry of this his servant,
with great increase; as also with many children,
for whom he was concerned even to the very last; and like a pious and godly father,
prayed to the Lord for their preservation,
and was zealously concerned to cleanse his family from superstition and idolatry;
and call them to go up to Bethel, the house of God,
Oh! that all heads of families would be concerned for their posterity,
and seek God and the things of his kingdom, for their children and servants,
more than the things of this world; there being too much care for the one,
and too little for the other, generally speaking; so that there is need of this caution.
This good man was not only concerned for his family in his life,
but even at his death also: waiting for the salvation of God, and being sensible of it,
he very livingly and sensibly blessed his seed,
and was opened in faith to speak exactly to each of their states and conditions.
I refer to the history of it in holy Scripture,
the which I believe will be affecting to pious minds.

What a race he left behind! all his twelve sons were patriarchs,
and fathers of many people, who were highly favoured of God, and had been to this day,
had they walked in the steps of their fathers, Abraham, Isaac, and Jacob;
from whom came many valiant and noble men for God; as Moses, Joshua, Samuel, David,
Solomon, Josiah, Elijah, and Elisha; also the holy blessed Star and Sun of righteousness.
Holy Jesus, whom the degenerate offspring of good old Israel, slew and hanged on a tree.
The holy apostles also, were great examples of virtue; as well as the blessed martyrs,
and many modern good men might be brought in for inviting examples,
to stir up the minds of men and women, to serve, love and follow the Lord,
and to believe in him, and in his dear Son,
and in the appearance of his grace working in the soul,
in order to convince and convert them.

To be particular in all the above instances,
would swell this far beyond what is intended;
and considering the many and large volumes that are in the world,
though a large door is opened before me, yet I am now willing to conclude,
and recommend the work, with the reader, to the grace of God,
in and through his dear Son Christ Jesus, our great example: to whom with the Father,
through the divine Spirit, be glory forever.

[.signed-section-signature]
Thomas Chalkley.

[.signed-section-context-close]
Written at Frederickstadt, in Holstein.
