[short="Tender Scruples About the Common Prayer"]
== Some Truly Tender Scruples of Conscience, About that Form of Prayer, Called the Common Prayer, as Used by the Members of the Church of England.

I AM not against reading the holy Scripture, either privately or openly,
but would encourage it in all Christians and true believers in Christ:
and we ought to excite one another thereto,
and more especially to put in practice what we read to be our duty;
otherwise the holy letter will kill, as said the apostle,
which is to be understood when we practise contrary to what we read therein.
As for example, where our Lord saith, "`Every idle word that men shall speak,
they shall give account thereof, in the day of judgment.`"
Again, "`God will not hold him guiltless, that taketh his name in vain.`"
"`That servant that knew his Lord`'s will, and did it not,
shall be beaten with many stripes.`"
These, and many more portions of holy Scripture,
are condemning and killing to those who live in sin and evil,
which the letter is absolutely against, and without true repentance,
accompanied with amendment of life, though the holy Bible be read every day,
it will but add to our condemnation.
But if people truly repent of the evil of their ways, and awake to righteousness,
and sin not, as the holy Scriptures themselves hold, and Christ taught,
then unto such souls they are as a rich treasure,
and as a cabinet full of precious jewels,
able to make the man of God wise unto salvation, through faith in Christ,
by the influence of the Holy Ghost, or Spirit.

It is not the reading divinely inspired writings, or the Bible, which is scrupled,
but the formal reading of formal composed prayers and songs, at set times,
instituted by such whose principle is that there is now no divine revelation,
and that we cannot live without sinning, while we are in this world,
according to the tenor of the common prayer; holding, that we sin as long as we live,
as if God`'s power were not stronger to preserve out of sin,
than the devil`'s to keep us in sin,
contrary to the work and doctrine of the holy apostles,
who were sent of God to turn people from Satan`'s power, to the power of God;
whose glorious, eternal power, is above the power of sin, death, and the devil.

I wish to write a few words concerning some unsound words,
and also some Scripture expressions perverted to a wrong use, in the common prayer.

First; As to that expression in the common prayer, that "`We are miserable sinners.`"

Second; And that "`We are full of bruises and putrifying sores.`"

Third; And "`From the crown of the head to the sole of the foot,
there is no soundness in us.`"

Fourth; And that "`We have left undone the things which we ought to do,
and do those things which we ought not to do;`" and these to be repeated for life.

First, then.
If people must be miserable sinners all their days,
to what end did Christ come into the world and preach the gospel, and suffer death,
the painful death of the cross?
Did he not come to put an end to sin, and to destroy the works of the devil,
whose works are sin?
Did he not preach against sin, both within and without?
Witness the fifth, sixth, and seventh chapters of the evangelist Matthew.
Yea, his birth, life, preaching, suffering, death and resurrection,
and ascension into glory, were all against sin, the devil, death and darkness,
and all the works and deeds thereof.
Christ died for our sins, and we should die to them, and live to him:
he came to save us from the act of sin, as well as the imputation of it;
and takes away the guilt of sin on condition of true repentance and amendment of life,
as the doctrine of Christ and his apostles largely and plainly demonstrates,
as any who are come to the years of discretion, and who can but read the holy Scriptures,
may plainly discover.

The apostle saith, "`Whatsoever things are holy, whatsoever things are pure, just,
and of good report, seek after those things.`"
And again,
"`No unclean thing can enter the kingdom of heaven;`" but certainly all sin is unclean.
Read over the holy Scriptures, from the beginning to the end,
their nature and tendency is against all sin; and as it is true,
that we all have been sinners,
surely therefore all true Christians and true believers in Christ,
have cause reverently to bow, and to be truly and humbly thankful, that Christ,
our great Lord, by offering himself for us, hath taken away that imputation;
so that now through faith and belief in Christ,
accompanied with true repentance and amendment of life,
the imputation of our former sins is taken away;
for this cause we praise God and adore his eternal majesty forever,

Second; As to the word "`miserable,`" a Christian may indeed be poor;
but since Christ is come to make us happy and comfortable,
through the hope of eternal salvation, in his name and power,
as we are not to think ourselves better than we are,
so we cannot say nor think we are miserable, unless we are without God and Christ;
and then we are miserable indeed; but no mortal can be miserable who hath Christ;
"`For he that hath the Son, hath life (eternal life) abiding in him.`"
To be truly in Christ, is to be truly happy;
this doctrine is as clear as the sun at noonday, or as a morning without clouds.
When the soul comes to see itself undone without a Saviour,
and sees sin to be exceeding sinful, and is ready to cry to the Almighty,
Lord help or I perish! save me, or I am undone forever! then it seeth itself miserable;
but it is for want of Christ: and when Christ is come into the soul,
then its misery vanisheth, or flieth away.
But from day to day and week to week, yea,
all the days of one`'s life to be miserable sinners, is a miserable case indeed,
destroying the very nature of Christianity: wherefore some tender conscientious souls,
cannot join with such miserable sinners and sayers,
who neither say nor do that which they ought.

Third; As to these sayings, "`We are full of bruises and putrifying sores,
from the crown of the head to the sole of the foot, and there is no soundness in us.`"

If a congregation of such people as these say truly, and if they do not say truly,
what will the consequence be, let the wise in heart judge;
can such a people be the church of Christ, or his spouse, or beautiful bride?
Christ saith, "`If the inside be clean, the outside will be clean also;
and he came to cleanse the souls of poor mortals, and to heal them,
and wash them from sin, and he doth it by his spiritual baptism,
and the fire of his word.
The abovesaid church and people, do both "`Promise and vow,
that they will forsake the devil and all his works,
the pomp and vanity of this wicked world, and all the sinful lusts of the flesh,
and walk in God`'s holy will and commandments,
all the days of their lives,`" which is the very highest pitch
of perfection any man or Christian can attain in this life;
and yet contrary to those vows and solemn covenants, they tell the Almighty,
from time to time, that they are unsound, nay, that there is no soundness in them;
but that they are putrified from head to foot, and by their common practice,
intend to tell him so as long as they live in this life: this is unsound work indeed:
and truly those who are tenderly conscientious, may well scruple to join with it,
or with those who are in such ways, words and works.

Those bruised, putrified, sore and unsound souls, are therefore in Christian love,
tenderly advised to come to Christ, the physician of value, and great doctor of the soul,
that he may heal them, and wash their sinful souls and unsound hearts,
"`By the washing of regeneration, and renewing of his word and spirit.`"
"`Ye are clean through the word which I have spoken unto you,`" saith our Saviour.
They were cleansed by putting his word in practice; for, saith Christ,
"`He that heareth these sayings of mine, and doeth them,
I will liken him to a wise man;`" so consequently, he that doeth them not, is foolish,
sinful, and unclean.

Fourth; And further, say they,
"`We have left undone those things which we ought to have done.`"
Doing the truth and that which is right, is what we ought to do; and committing sin,
is that which we ought not to do: certainly any man would think it mockery,
if his children or servants should serve him so from time to time,
and make a common practice of it.
By this confession, if it be genuine,
it appears they must needs know better than they practise,
they knowing what they ought to do, but not doing it;
and our Lord Jesus Christ saith positively, "`He that knoweth his master`'s will,
and doeth it not, shall be beaten with many stripes:`" and again,
"`Be ye not like the scribes and pharisees; for they say, and do not;
therefore be ye not like unto them.`"

But what can be expected from those who say they sin in their best duties?
If so, they sin whenever they read the common prayers; and by the same rule,
the oftener they read them, the oftener they sin; wherefore, how can a sincere,
devout soul, who unfeignedly loves the Lord Jesus Christ, so as to keep his commandments,
for that is to love him truly, and according to his own definition of it;
"`If ye love me, keep my commandments,`" saith Christ; I say,
how can any such sincere soul join with such wrong doers and sayers?
It must needs be an unsafe practice to do what we know should not be done;
the nature of such doings being provoking, either to God or man:
what man in the world would like it, in either son or servant?

Oh! what would become of poor, degenerate man,
if the Lord Almighty were not very indulgent, if he were not a God gracious and merciful,
slow to anger, and of great lovingkindness to poor mortals!

Fifth; And as to their singing David`'s psalms in metre;
how often do they sing that which is not true as to themselves,
and also that which is not according,
but contrary to their states and conditions`'? As when they sing,
"`That they water their couch with their tears,`" and that "`they practise what
they know;`" when they confess they "`Do that which they ought not to do,
and leave undone that which they ought to do.`"

The apostle said he would "`Sing with the spirit, and with the understanding also.`"
And again, "`We know not what we should pray for as we ought,
but the spirit itself maketh intercession for us,
with groanings which cannot be uttered.`"
In the primitive times of Christianity,
they prayed and sung as they were helped by the Holy Ghost, or Spirit, and not by book,
or stinted or set forms; but.
Oh! the primitive soundness of Christianity is too much lost and defaced;
and therefore some who desire to come again to the
primitive soundness and purity of the Christian religion,
scruple to join with such unsound formalities, and that conscientiously,
for the reasons above, and more which might be given.

When such scruples are mentioned, the members of the church of England usually reply,
that the Scriptures vindicate them in their form, which, how well they do so,
let it be freely and fairly examined, not for contention,
but for edification in the pure love of Jesus.

First: "`The Scripture saith,
that there was a people that was full of bruises and putrefying sores,`" etc.

Answer: But that was in the time of the law, when the people had transgressed the law,
and were under the law; for had they done their duty, and kept the law,
they could not truly have said so.
They were then indeed gone astray like the lost sheep,
and that brought them into that sore, putrefied state, and bruised condition,
and "`Their law did not make the comers thereunto perfect; yet, as saith the apostle,
the bringing in of a better hope did,`" which was the hope of the gospel.
The apostle preaches perfection under the gospel dispensation,
though some of our worldly wise men will not allow of it;
and I hope we are not under the law, but under grace; the law of the spirit of life,
in Christ Jesus, doth set the true believers free from the law of sin and death;
so that a true Christian cannot say truly, with the false and rebellious Jews,
of whom the prophet there speaks, "`That he is full of putrefying sores,
and that there is no soundness in him, and say it all the days of his life.`"

Second: Again the Scripture saith, "`I was shapen in iniquity,
and in sin did my mother conceive me.`"

Answer:
The psalmist was at that time under deep convictions for
the sins he had been guilty of in the matter of Uriah;
but by his expressions in the ninth, tenth and eleventh verses of the same psalm,
it is plain he believed a better state attainable.
And surely these expressions cannot be applicable to all men at all times.
No, surely, if we believe Christ and the holy Scriptures, whose doctrine is holy,
and commands holiness, in both Testaments.
And if people would walk in the holy light of Christ,
who enlightens every man that Cometh into the world, as recorded in the holy Scriptures,
they would then be cleansed from their sin, from both the act and the imputation,
as saith the apostle; "`If we walk in the light, as he is in the light,
then have we fellowship one with another, and the blood of Jesus Christ, his Son,
cleanseth us from all sin.`"

Third: "`There is none that doth good, no not one.`"

Answer:
It is beyond all doubt the apostle spoke of the people in their unconverted state;
for if they had been come to the work of conversion and regeneration, they must,
and it is impossible but that they should do some
good and though there was a time that none did good,
it was under the law, and not under grace; and spoken of the unbelievers,
and not of believers: especially since Christ has brought a covenant of grace,
in order to teach and help us to live righteous, virtuous, holy, religious,
and sober lives and conversations.

Fourth: They object the words of our Saviour to the young man in the gospel,
where he calls Christ good master, asking him,
"`What good thing shall I do that I may have eternal life?`"
Christ answered, "`Why callest thou me good?
There is none good but one, that is God.`"

Answer: And true it is, in our Lord`'s sense, for comparing men to Christ, who is God,
there is none good; the young man thought he had been speaking to a man like himself,
and knew not that he was speaking to the good and gracious Son of the most high God.
But if we compare men with men, it must be granted that there is some good men,
women and children, in that sense; and our Lord showeth how we may know these good men,
women and children.
"`By their fruits ye shall know them; men do not gather grapes of thorns,
nor figs of thistles: a good tree cannot bring forth evil fruit,
neither can an evil tree bring forth good fruit;
wherefore by their fruits ye shall know them.`"
How plain is the doctrine of Christ, if people would but lend an obedient ear,
and give him a faithful and sincere heart, and serve him in a pure mind,
without deceit or guile, taking up his holy cross, to the corrupt will of man,
in true self-denial.
The Scripture says, "`If we confess our sins,
he is faithful and just to forgive us our sins,
and to cleanse us from all unrighteousness:`" where then is the sin,
when God has cleansed us from all unrighteousness?
Indeed it is very meet, and our duty to confess our sins; they truly say, that,

Fifth: "`The Scripture in sundry places excites us to confess our sins.`"

Answer: For poor mortals have all sinned, and by this sinful nature,
we are all children of wrath,
and this is a strong and mighty motive for us in truth to confess our sins,
because God is so just and merciful to forgive and pass by our iniquities;
and indeed if the weight of our sins were upon us,
and the true sense of the heinousness of sin and evil,
it would certainly bow us in deep reverence and humility before the throne of grace,
and melt our spirits into tenderness before the Most High.
Then it is that he forgives us, and cleanseth us from all iniquity, and would,
according to the apostle`'s doctrine, "`Purify us to himself a peculiar people,
zealous of good works,`" and against bad works and words, and thoughts also:
and when God hath so cleansed the soul, then, of course, these common,
and often repeated, dry confessions, full of sin and putrefaction, must fall,
and we should fear to offend any more.
Let it be tenderly, and in Christian love, asked,
how often do our common prayer people go into their closets,
or privately retire into some secret place,
and there pour out their cries and tears to the Almighty,
and humbly confess their faults to him alone?
I ask, would not such an exercise be more acceptable to God, than a popular repetition,
daily and formally made?
This I leave to the consideration of all sober Christians,
and to the judgment of the truly pious.
And how like mockery it looks,
that as soon as they come from their prayers and confessions,
many of them will vainly laugh, and be full of idle words and discourse,
and some of them curse and swear,
and take the awful and sacred name which they have been addressing,
or pretending to address, in vain, and profane that holy name of God and Christ,
which they have been using in their devotion.

To this I have been an eye and ear witness, many a time,
to the sorrow and grief of my soul, and which hath, in part, occasioned these lines;
also hoping it may be a motive to stir up some to more holy living,
and that the name of God and Christ might be glorified,
and the precious dear-bought soul saved.
Let us also remember that the holy Scripture doth abundantly
require and command us to forsake our sins;
the text says, "`He that confesseth and forsaketh his sins, shall have mercy.`"

Sixth: And whereas the apostle John, in his first general epistle, writes,
"`If we say we have no sin, we deceive ourselves;`" from whence it is objected,
we ought always to confess our sins.

Answer: Yes, we should do so whenever we commit any, or knowingly do evil;
but when the Almighty hath cleansed us from all unrighteousness,
then our sins are done away by the grace of his Son, our Lord Jesus Christ,
and we are washed by regeneration;
then it cannot be true to say we are miserable and putrefied sinners,
when at the same time also Christ hath purified and sanctified his church and people.

That is true which St. John saith, when opening and explaining the eighth verse,
"`If we say we have not sinned, we make him, (i. e., God) a liar;`" for all have sinned!
So it is plain that he speaks of the state of man before he comes to the work of conversion,
or to be renewed by grace; for when we come truly to know Christ,
and to see and believe in him, we witness a change from our corrupt and evil nature,
and sinful course of life, which is clear, from the same apostle`'s words,
which I shall transcribe for the information and edification of any who may see this.

The first general epistle of John, the beloved disciple of our Lord, says,
"`Whosoever abideth in him (i. e., Christ) sinneth not: whosoever sinneth,
hath not seen him, neither known him.
Little children, let no man deceive you: he who doeth righteousness, is righteous,
even as he is righteous: he who committeth sin, is of the devil;
for the devil sinneth from the beginning.
For this purpose the Son of God was manifested,
that he might destroy the works of the devil.
Whosoever is born of God, doth not commit sin; for his seed remaineth in him,
and he cannot sin, because he is born of God.
In this the children of God are manifest, and the children of the devil;
whosoever doeth not righteousness, is not of God;`" and as above,
"`he who committeth sin, is of the devil.`"

This is naked truth, without any covering,
and the very sum and substance of pure religion.
Oh! that all true Christians would lay it to heart, and ponder it in their minds,
and then resolve whether they will be sinners to the end of their days,
or whether they will repent, and turn from the evil of their ways; the latter of which,
that poor mortals may come to witness for themselves,
is the desire and prayer of my soul.

If it be further objected, "`That our Saviour taught his disciples a form;`" he did so;
and a glorious form it is; and they did as they prayed, and were taught of Christ,
and so they did it truly, and in true faith,
believing they should witness what they said and prayed to be fulfilled.
"`Our Father who art in heaven, hallowed be thy name, thy kingdom come.
Thy will be done in earth, as it is in heaven.
Give us this day our daily bread, and forgive us our trespasses,
as we forgive them who trespass against us.
And lead us not into temptation, but deliver us from evil: for thine is the kingdom,
and the power, and the glory, forever.
Amen.`"

Christ said to some of old, "`Ye are of your father the devil, because his works ye do.`"
And all sin is his work, and by our works we are manifest,
whether we are the children of God, or of the devil.
