[short="The Sad Effects of Intemperance"]
== A Letter to a Friend in Ireland, Containing a Relation of Some Sorrowful Instances of the Sad Effects of Intemperance, as a Warning to Young People.

[.centered]
=== Preface.

[.salutation]
Temperate reader,

The longer we live in the world,
the more we see the danger and many mischiefs, miseries and inconveniences,
intemperance occasions to mankind, not only in eating, clothing, buying and selling,
etc., but particularly in that great sin of drinking to excess.
And though a risk is run of incurring the displeasure
of some ill-natured over-lovers of strong liquors,
the which hath been experienced by the author, through some of the former impressions;
yet they having found such general acceptance, in many parts of the world,
and being serviceable to people of all persuasions,
for the further service of poor mortals, I venture to put forth this tenth edition,
with this additional preface, in order, if possible,
to persuade all rational souls to forsake so destructive and vile an evil.

[.numbered-group]
====

_First;_ Then, in the aged it hath these bad effects, viz:
they are bad examples to the youth, who when reproved, may reply.
My father before me loved strong liquors, as well as I: he loved a glass of wine;
he loved a bowl of punch; he loved good cider and good ale, and would be merry with it,
and why may not I, as well as he?
He was a wise, good man, when he was sober;
and pray where is the harm of loving good liquor, and being merry?

What can we say to the youth of such parents that will avail,
while their parents show them such evil examples?
And as it is in that, so it is in all other evils,
parents`' examples are very hurtful in evil things,
though very helpful in that which is good.
If a man sees a youth to be out of order, and reproves him for being in drink,
evil speaking, pride, covetousness, etc., and he guilty of the same,
his child may answer, Why father, I had not done so, if I had not seen thee, or you,
do it!
And it being an incumbent duty in a father, mother, master, or mistress,
to reprove their youth for evil;
if we are not clear in ourselves of what we reprove in our children or servants,
and our children or servants miscarry through our bad example,
what a melancholy reflection will that be to us,
if rightly considered! which indeed would be this,
I have been instrumental to my poor child`'s ruin and destruction!
A melancholy reflection to any sober Christian.

Also, except there is a large income,
instead of taking care to put the youth in a reputable way to live in the world,
it brings them to poverty: and if there is a large estate,
it puts them in the way to spend it.
And, Oh! how many are spending their precious time in taverns and ordinaries,
and at the same time their wives and children suffering and weeping at home?
And some sober, modest women,
would suffer unspeakable hardships before they would expose their husbands.

[.numbered]
_Second;_ Concerning the youth, it mightily hurts them, as it doth the aged also,
as to their religion, reputation, health and estate, etc.

====

[.numbered-group]
====

[.numbered]
_First;_ As to their religion,
it not only clouds their understanding and darkens the nobility thereof,
but it unfits them for all and every religious duty.

[.numbered]
_Second;_ Some who value a good name, had rather lose their lives,
than lose their reputation through immoderate drinking.
For if the youth be single, and addicted to immoderate drinking,
no wise and virtuous person will tie themselves to them for life, by marriage;
which state of life, to a wise and virtuous pair,
is far exceeding in happiness all other company or conversation whatsoever.
It is better to be one of these than to enjoy a kingdom: and on the other hand,
it is better to be a slave, than to be married to an intemperate person.

[.numbered]
_Third;_ Intemperance destroys the health of the body,
which we generally esteem before wealth.
And if a man were a king, prince, or duke, if he did not enjoy his health,
what good would all his honour, power, and wealth, do him?
Oh! what abundance of young people have destroyed themselves by this sin?
As it is written:
"`The wicked do not live out half their days:`" and
where this sin is growing general in a country,
that country is growing to its ruin and destruction.
It wastes the people, decays trade, and is very destructive to religion,
and an inlet to Atheism.
Good people are afraid to live in such a country; bad people flock to it,
and often make their exit in it.

[.numbered]
_Fourth;_ And many a fair estate has been embezzled and spent through intemperance,
which honest parents, with great labour, care and industry, have got together,
and left to their sons and daughters, who have extravagantly spent it upon their lusts;
and thereby have brought infamy on themselves, their fathers, and their posterity,
whenever it has pleased God that they have left any behind them; besides,
which is worst of all, dishonouring God,
and bringing a scandal on the Christian religion.

====

Some of our wise kings and queens in Great Britain,
being sorrowfully affected with the heinousness of this great sin,
have made strict laws against intemperance:
and where the legislative authority makes little or no provision against it,
or when they do make any, do not take care to put it in practice,
such a state or colony must needs be in a declining condition.
And for particular families and persons,
we may see too much of this evil in our neighbourhoods, almost in all parts of the world,
which causes sober and truly religious Christians to mourn,
and humbly to bow before the most high God, begging of him, for Christ`'s sake, that he,
by his mighty power, would be pleased to reform the unregenerate world.

This is the prayer and fervent desire of an entire lover of mankind, both body and soul,
and who desires their welfare in this, and in the world to come.

[.signed-section-signature]
Thomas Chalkley.

[.asterism]
'''

[.signed-section-context-open]
Barbados, 7th of First month, 1718-19.

[.salutation]
My dear friend.

It is long since I had a line from thee: but not long since I thought of thee, and thine,
with Friends of your nation; where I know that the Lord hath a seed, who love him,
and desire to serve him, and are accounted to him for a chosen generation;
and that this generation may spread and prosper in the earth, is at times,
my earnest travail in spirit both night and day.
There is also an exercise upon my mind for the offspring of this seed,
the children of those men and women, who have confessed the name of Christ before men,
in a holy, self-denying life and sober conversation: and I do certainly know,
that many pious souls join with me in this exercise,
bowing the knee to the Lord of sabbaths, for the peace,
prosperity and eternal welfare of the present, rising generation.
Oh! how exercising it is to good men and women to
see their youth take those ways which lead to destruction,
and go in company with the wicked,
whose ways lead to the utter ruining of both body and soul,
and whose steps take hold on hell.

A great evil, to which many are prone, is keeping vain and idle company,
which has brought many young men and young women to their utter ruin and destruction,
both body and soul.
How many fair estates have been wasted!
How many fine youths have been destroyed by keeping evil company,
and by excess in drinking, it is really lamentable to consider!
It keeps the poor in poverty: it makes the rich many times poor;
and brings both rich and poor into disgrace:
it breaks and destroys the health and natural good constitution of the body,
and instead thereof fills it with misery and pain: and which is yet more,
it destroys the soul, which is the most noble part of man; so that it is a sore,
and three-fold evil; but the last is the worst,
by how much the soul is the more lasting and better part.
Several terrible instances of this nature I have
met with in my travels among the children of men;
three or four of which I may inform thee of; and it may be affecting to thee,
as it hath often been to my mind, when I have thought thereon.

=== The First Instance of a Young Man, Given to Ill Company and Hard Drinking.

The first is of a certain young man, a physician by profession,
who was much addicted to evil company, and to drink hard,
and was sometimes visited with strong convictions;
in one of which visitations he sent for me, and told me his condition,
and made solemn covenants, "`If God would but that once spare him,
he would not do the like evil again.`"
At that time it did please the Almighty to spare him;
but he soon forgot how it had been with him, and fell into the same sin again;
although he had a most notable admonition in a dream, but a little before.
His dream was this, which is very remarkable; we being then at sea,
in sight of Great Britain.
He saw in his dream a great and spacious town, the buildings high and streets broad;
at which he landed, and going up the street, he espied a large sign,
on which was written in great golden letters, SHAME, to which he went,
and at the door stood a woman, with a can of drink in her hand, who asked him to drink;
to which he replied, "`with all his heart,
for he said he had drunk nothing but water a great while;`" so he took the can,
and drank a hearty draught, which, as he said, made him merry,
and he went reeling up the street; when behold, on a sudden, a grim fellow met him,
and arrested him in the name of the governor of the place, before whom he brought him.
This governor, he said, was like a great black dog, the largest he ever saw,
who grinned at him, and passed sentence on him; and sent him to prison,
there to live forever.
He told me this dream with such emphasis, as made me to tremble,
which was interpreted to him.
I told him that he was an ingenious young man,
and might easily discern the interpretation of this dream,
which to me seemed to be ominous to him.
"`The great town and high buildings are thy great and high profession;
the sign on which shame was written, with the woman with the can at the door,
show the great shame of the sin of drunkenness, and that is thy weakness;
and that grim fellow that arrested thee, is death, who will arrest all mortals;
and the great black dog, the governor of the place, is the devil; who,
when his servants have served him to the last, will torment them forever.`"
"`God forbid, it is but a dream,`" was his answer to me.
I said it was a very significant one to him.

About three days after the same person went on board a ship,
whose loading was wine and brandy.
The master gave a can of wine to him, and said the same words,
as the woman said to him in his dream, and he answered with the same expressions,
and it had the same effect upon him.
He took such a hearty draught as made him too merry, insomuch that he overset the boat,
and was drowned, much in drink: and I seeing him sink down,
and his dream so punctually fulfilled, I was very heavy in my mind for several days.

Oh! methinks I could wish that the many righteous judgments of the Most High,
might effectually work on the hearts of those people, who are in the flower of their age,
to their conversion and salvation.

=== The Second Instance of a Merchant, Addicted to the Like Destructive Practices.

The second is of a merchant, about thirty-five years of age,
whom I saw take leave of this world:
he was one who had spent much time in keeping unprofitable company and over drinking,
which practice wasted his strength and flesh, as it did his time and money,
and brought him into a deep consumption; as it has many to my certain knowledge;
besides bringing the racking painful distemper of the gout, and many other miseries;
so that at last it brought him to his chamber, and then to his bed.
In his sickness he several times sent for me and made serious
acknowledgments of his "`former mispent time,
and hoped, if the Lord would spare him, to be more careful for the time to come.`"
But he was no longer to be trusted in this world;
for he went not out until he was carried in his coffin: he held my hand fast in his,
until he died, and was sensible to the last.

One day, as he lay on his deathbed, he called me to him, into his chamber,
and charged me to caution the young people to be careful how they keep,
and spend their time in, evil company, for it had been his ruin,
and now lay as a great and heavy burden on his conscience.
"`Oh!`" said he, "`if they did but feel one quarter of an hour, what I feel,
they never would keep such company any more: tell this to my former companions.`"

And indeed there is a great deal of hurt done by
young men getting together to drink wine,
or other strong drink.
I wish the woe, mentioned in the holy Scriptures, may not be the portion of many of them;
"`Who are mighty to drink wine,
and men of strength to mingle strong drink;`" and sit late at it,
which many times brings suffering on parents, wife, children and servants,
as well as themselves; and is a very disorderly practice,
being a reproach to all Christian societies and families, wherever such things are.

There is a great concern upon me against this growing evil in our young generation;
and I hope, in Christ our Lord,
that heads of families will come under the like exercise in themselves: and then,
if our youth will neither hear nor fear the Lord, nor us, we shall be clear,
and their blood will be on their own heads, as a worthy and honourable elder,
and man of God, of your nation, said;
one of whose offspring is the third subject that I shall mention to thee,
of the many I have been acquainted with, in my pilgrimage here.

=== The Third Instance of Another Young Man, Who Much Embraced the Same Destroying Delights.

The 5th of the first month, at Bridgetown, in Barbados, S. E., son of W. E., died.
His death was sudden; and as was reasonably supposed,
he destroyed himself by drinking and undue company keeping, and sitting long at it.
A person, to whom he himself had told it, told me, "`That he and four more,
at one sitting, drank above twenty quarts of double-distilled rum punch;
which put him in a violent fever: so that he ran about the streets, with a naked sword,
and talked of killing one of the neighbours, in this drunken fit.`"
The next day he came to me, and asked me, "`Whose door the blood would have lain at,
if he had, in that fit of disorder, killed any body?`"
By which query, I thought he was not yet rightly come to himself:
because there were some ordinary reports about the town concerning him,
he reckoned those who broached and spread those reports, would have been culpable,
and must have answered for the murder, if he had committed any:
but this was but covering his sin.

He seemed to fall out with religion too; for he said, "`He would come no more to worship,
till he should have justice done him, as to the reports:`" though poor soul,
he had the more need to present himself before his Maker,
and bow before the most high God, and repent in great humiliation.
The same day in which he neglected his duty, he was taken sick,
and that day week was buried.
He sent for me, and I went to him: he had but little sense of his end,
that I could perceive, and remained so till the night he died.
I was by him when he died, and saw him fetch his last breath.
A few minutes before he gave up the ghost, he trembled and shook exceedingly,
and shrieked out, to the astonishment of all those present,
which pierced my very soul within me:
for he seemed to go out of the world in an extreme great agony.

I never saw any depart the world like him; and indeed it was amazing,
and greatly affected my mind with sorrow; for I thought he was very unfit to die.
Oh! methinks I could heartily wish, that such objects might be as so many strong motives,
to stir up and awaken the offspring of good men and virtuous women,
and all professing Christianity, to fear the Lord and walk in his ways,
which lead to life, where the sting of death is taken away.

The children of godly parents have much to answer for,
in slighting or neglecting the wholesome counsel and faithful admonition,
of their faithful and careful parents; whom they disgrace and dishonour,
contrary to the command of God, who says, "`Honour thy parents,
that thy days may be long in the land,
which the Lord thy God giveth thee:`" and none can truly honour their parents,
who dishonour God their Maker.

=== The Fourth Instance of a Young Woman, Who Often Absented Herself From Meetings, for the Sake of Bad Company.

The fourth instance which I shall give thee,
is concerning a young woman of about twenty-five years of age;
who was brought up very tenderly and delicately, with her lockets and chains of gold,
and waiting maid: but her parents living too high for their income,
broke in people`'s debt; and their children as they grew up, were put to their shifts.
What pity it is, that youth are not brought up to some business,
whereby they may get a livelihood in the world, if their parents should die before them!
And though parents may have a handsome interest in this world,
yet it has been thought by great, as well as wise men,
that to put out youth to trades and business, is both profitable and honourable:
instances of the evil consequences of the contrary, have been very many,
as woful experience doth daily teach us.
This young woman was one: for falling into evil company, she ran into debt,
and was put into prison; where was a murderer, whom, it was said,
she was accessary to loose from his chains; and for so doing, was put in chains herself,
along with him, when he was taken again.
Now, instead of her gold chain, she must take up with an iron one;
and in a little time be tried for her life.
In expectation of death, being in great distress, she sent for me,
and entreated me to come and see her die, and much lamented her condition:
"`Oh!`" said she, "`that I might be a warning to all young people,
to be careful that they keep not evil company,
and spend their time which should be spent in worship, in airy company,
and other vain diversions, when they should be doing their duty to God.`"
And then she would weep bitterly; she being very penitent, it very much affected me;
and I told her, "`That I did believe, if she in her heart was clear,
and no ways consenting to the murder, her life would be given her;
but then woe and misery would be her portion, if she did not amend her ways.`"
And as I was leaving her, she charged me,
"`To warn young people that they might be careful
that they spend not their time in vanity,
and to keep out of vain and wicked company,`" which
she said had brought her to that misery and shame:
"`And that they should take the counsel and advice of good friends,
which if I had done,`" said she, "`I had not brought reproach on my friends,
and on my parents.`"

In a little time after, she was brought to a trial, and acquitted by the jury.
I saw her once since, and reminded her of her duty; which, she said,
"`She hoped to perform; and that it should be a warning to her,
while she lived in this world:`" and that such examples may be a warning to all people,
is the earnest desire of a lover of souls, and servant of Jesus.

[.signed-section-signature]
Thomas Chalkley.

[.asterism]
'''

Since I wrote the foregoing, there being a person in this place,
who would be sometimes overtaken in drink, I sent it to him to copy over,
hoping it might have some good effect on him.
Before he had copied the relation of the first person,
he was so smitten with the sense of the judgment of the Almighty, that he cried out,
and said, "`He was a condemned person, and that he felt the fire of hell.`"
He sent for me and several others, and begged of us to pray for him: he was told,
"`That the hand of God was upon him for sin, and desired to take warning in time,
and repent, lest the Lord should cut him off in his iniquity.`"

The Lord did accordingly cut off this person, he dying suddenly, by hard drinking,
as I was informed by a letter from Barbados; though he promised,
"`If the Lord would spare him then, to be more faithful for the time to come;
and was then under deep inward exercise of mind.`"
I mention this as a corroboration of the above instances, for further admonition.
This person was in a considerable post in that government: his name I forbear to mention,
for divers reasons.
If thou and Friends see meet, I could desire, from the exercise that is on my mind,
that this might be spread; peradventure it might have place with some, for their good.
