[short="Letter to the High Sheriff of Baltimore County"]
== A Letter to Aquila Paca, High Sheriff of Baltimore County, in the Province of Maryland, and to Other Friends There.

[.signed-section-context-open]
Barbados, 1st of Twelfth month, 1718.

[.salutation]
Loving friend Aquila Paca,

Meeting here with Captain Swaddle, bound for your river,
I found a concern on my mind to send a few lines,
remembering the good opportunities I had at your meeting in that neighbourhood,
together with those few poor honest souls that I met with there;
and I desire thee to give my dear love in Christ to them.

Dear friend, I am tenderly concerned in the love of God and his dear Son, to beg of thee,
that thou let not the world, nor any thing therein, either the riches, pleasures,
or friendship thereof,
draw thy mind from that measure of grace which hath been manifested to thee;
for God hath visited thee in his tender love and mercy, as thou well knowest,
and hath begotten good desires in thee, and convinced thee of the holy truth,
as it is in Jesus.
Oh! saith my soul, that thou mayest more and more grow therein,
to thy bringing forth much good fruit, to the glory of God,
and the eternal good of that part in thee, which will never die.

Salute me to thy wife and children, and the neighbours, and their children also,
all of whom I wish well in this world, and also in that which is to come,
the same I wish to all those who love Christ, so as to keep his commandments.

If thou seest meet,
thou mayest read what follows at the close of your meeting on a first-day,
which meeting I hope you keep up in order to worship God in Christ`'s name;
for to such as meet in his name, he hath promised to be in the midst of them,
wherever they so meet; which he hath graciously fulfilled at many times.

Dear friends, it is in my mind to visit you with the salutation of brotherly love,
in our holy Lord Jesus Christ, and may let you know,
that though I have been long absent from you in body,
yet have I been often present in spirit with you, and you have been often in my mind,
with prayers to the Lord for your growth in the holy truth,
which he hath been pleased to make known to you,
and many times I have desired the Almighty,
that he would be pleased to preserve a seed in your parts that should serve him,
and be accounted to him for a generation.
I have also desired that the Lord would visit your young ones,
and bring them to the knowledge of his truth: and I pray God,
that the tender visitation that was on divers of them, when I was present with you,
may never be forgotten by them, but that they may be plants of righteousness,
of God`'s own right hand planting.

And, dear friends, forsake not the assembling of yourselves together,
in the name of Christ,
remembering how you have been visited with the heart melting power,
and the sweet presence of the Most High, in your silent waiting on,
and worshipping him in his holy Spirit and truth,
as well as when you have been vocally visited by the ministers of Jesus.

Such worshippers, as our Lord said to the woman of Samaria,
the heavenly Father seeketh to worship him; and those whom God finds under such exercise,
such find him to be unto them all in all; he is unto them wisdom, righteousness,
justification, sanctification and redemption.

Oh! dear souls, look to him who is invisible to the outward eye, who is God over all,
and is blessed forever: and may you, if this comes to you,
feel the divine life and spirit of Christ,
in the reading of this little epistle of brotherly love.

Live in love, for God is love, and all those who dwell in divine love, dwell in God;
wherefore love one another, that thereby ye may be known to be Christ`'s disciples:
"`For, says he, by this shall all men know that ye are my disciples,
if ye have love one to another;`" or,
"`if you love one another;`" as one of the evangelists hath it.

Keep low in mind and humble in spirit; for the humble, God will teach of his ways,
and the meek he will guide in judgment, and those whom he teaches,
are taught the mysteries of his kingdom,
which mysteries he teaches to spiritual babes and sucklings, glory to his holy name!
He often hides those holy mysteries from the wise and prudent,
and reveals them unto such men, women and children, as are little in their own eyes,
and despised by the wise in natural wisdom, or the wisdom of this vain world.

Oh! mind your heavenly guide, dear friends, let me entreat you;
for he leads out of all sin, and out of all vanity and evil, of what kind soever;
and as our Saviour saith, into all truth.
When Christ comes by his grace and spirit into the heart,
he opens the soul and enlightens the understanding, even in our common conversation;
and much more, at times, in our solemn meetings,
when we meet together to worship and serve him; so that it is good to wait upon the Lord,
and to seek him with the whole heart.

Dear friends, though my heart is full of love and good will to you at this time,
as at many other times also, I must now conclude,
and commit you into the holy arms of Him who is love,
begging the God of love and peace to keep you, and preserve you to his heavenly kingdom;
to whom be all glory and praise, might, majesty and divine dominion,
through his dear Son and the holy Spirit, forevermore.

[.asterism]
'''
