[short="The Call, Work and Wages of the Ministers of Christ"]
== Some Considerations on the Call, Work and Wages of the Ministers of Christ.

It hath been on my mind to write something concerning
the work of the ministry of the gospel of Christ,
with a design of instruction to ministers in particular,
and also for the benefit of others.

It is an unspeakable benefit to mankind, to be favoured with a powerful living ministry,
which edifies the church of God, and builds up the true believers in the most holy faith,
according to the word of God, in Christ Jesus,
who is the great minister of the sanctuary and true tabernacle,
which God hath pitched and not man.
This great minister sent forth his ministers and servants, saying,
"`I send you forth as sheep among wolves, be ye therefore wise as serpents,
and harmless as doves.`"
He did not send them forth as lords over his heritage, nor as persecuting priests,
or mercenary hirelings; but said to them, "`Freely we have received, freely give.`"
No compulsion or force is enjoined by Christ; but it is plain,
from his own doctrine and example, that his ministry is a free ministry,
blessed be his holy name and truth forever:
nor do we read or understand of any alteration thereof by Christ.
The ministers of antichrist have made an alteration in their ministry;
but the holy apostles, who, after Christ,
were the first planters of Christianity in the earth,
when it shone in its primitive beauty and glory,
followed the counsel of their Lord and Master, and ministered freely.
Then was the power of Christ`'s ministry and gospel
through his ministers and servants great,
and the glory and beauty thereof ravishing to pious souls.
Oh! may every true minister and every sensible soul, bow before the Most High,
and bless the holy name of him that lives and reigns forever,
for this unspeakable gift of Christ`'s holy ministry, which always was, now is,
and ever will be, convincing and converting to souls,
who are not slow in heart to believe in God, and in his dear Son, the Lord Jesus Christ,
who is our great high priest and the bishop of souls;
he saw the need that his church had of his ministry,
and therefore he established it among his followers to the end of time.

In order to this great work, he told his disciples,
when he was going into his glory and to the kingdom of his Father,
"`That he would pray to the Father, and he would send them another comforter,
the Spirit of truth, and that he should abide with them forever.`"
He also told them, that when he is come, he shall reprove or convince the world of sin,
because they believe not in him; for if they believed truly in Christ,
they would love his spiritual appearance.
But how many are there in the world, who slight this high favour,
the grace of God and Christ, calling this wonderful gift the light of nature;
whereas Christ says it is the Holy Ghost; and the apostle Paul says,
It is God`'s grace that teaches us to deny ungodliness, and hath appeared unto all men.
O! that the children of men might love Him who appears to them,
and convinceth them of their sins;
and surely it is a great sin not to believe in the spirit and light of Christ:
such unbelieving souls are in darkness, and not yet turned from darkness to light,
and from the power of Satan, to the power of God,
which is the very work Christ`'s ministers are sent of God to do.

Second; He convinceth or reproveth the world of righteousness,
because "`I go to the Father and ye see me no more.`"
When their righteousness is only wrought in the wisdom of man,
and not by the power of God, whether it be in preaching or worship, when only the form,
and not the power, is witnessed,
he then convinceth them that they have been building their religion upon a wrong bottom,
and a sandy foundation; and showeth the formal minister,
that he is only a minister of the letter, and not of the spirit;
and the formal worshipper, that he has not yet come to worship in spirit and truth;
and the professor of Christ in words, that he denieth him in works and inward faith;
because "`Faith without works is dead,`" as works
without this spiritual faith are dead also.

"`Because I go to the Father,`" is the reason given by Christ,
for it is Christ`'s righteousness that must save the soul,
and Christ being gone to the Father, the soul must go there to him,
for all his gifts and favours, mercies and blessings,
and must witness him in spirit to be with them and in them, as he is in the Father.
When Christ was personally on earth, he taught us by words vocally expressed;
but "`Henceforth know we him so no more.`"
Now he teacheth us by his spirit, light and life,
which convinceth us of form without power, letter without spirit, religion without life,
righteousness without grace,
and light and imputative righteousness without actual righteousness,
and formal righteousness in our own wills only; all this, and much more,
it convinceth us, not to be effectual to salvation,
and showeth us that the spiritual power and presence of Christ,
is absolutely necessary for the work of the ministry and the conversion of souls.

Third; He convinceth the world of judgment, because the prince of this world is judged.
He, the Comforter, the Spirit of truth, when he is come, showeth us our wrong judgment,
and convinceth us of the evil of being too censorious, rash and uncharitable in judging,
and plainly giveth us to understand, that such judgment is from the prince of this world,
who is king over all the children of pride, and that this prince or evil spirit,
is judged by the righteous and just Judge of heaven and earth, Christ Jesus.
He also convinceth us of the everlasting truth, as it is in Jesus,
and is our sure comforter, while we keep therein, in doctrine, worship and conversation.

Fourth; "`He shall bring all things to your remembrance,
whatsoever I have spoken unto you.`"
Wherefore this gift is absolutely necessary for a minister of Christ;
and every true believer in him wants this remembrancer,
which must be a great comfort to us,
to have his excellent speeches and divine doctrine
brought by his own spirit to our remembrance,
if we love him in sincerity.

Fifth; "`He shall take of mine, and shall show it unto you,`" says Christ.
Take of his light, his life, his grace, his wisdom, his mercy, peace and truth,
and show it unto you.
Oh, infinite love from a tender Saviour!
Well may we admire his goodness, and entirely love him above all things in the world.

Sixth;
Christ speaks in divers places concerning this wonderful
and extraordinary gift of the holy Spirit;
and in the fourteenth chapter of John, he says, "`I will pray the Father,
and he shall give you another Comforter, that he may abide with you forever;
even the Spirit of truth, whom the world cannot receive, because it seeth him not,
neither knoweth him: but ye know him, for he dwelleth with you, and shall be in you.`"
Oh! ye ministers of the Lord Jesus Christ, in this his gift is your strength,
your comfort, and your exceeding great reward, both here and hereafter, forever;
far exceeding silver and gold, or the diadems of princes.
The whole world, wanting this, lieth in wickedness, and must lie there unavoidably,
if they have not the sense of this unspeakable gift.
There cannot be salvation, nor any saving ministry without it;
it being absolutely needful, to the being and well being of a minister of Christ.
And indeed the holy text is plain and positive,
that he that hath not the Spirit of Christ is none of his; none of his minister,
none of his believer.

But if it should be objected,
how shall we know the minister or the man who hath this divine gift, or Spirit of Christ,
since it may be pretended to both by the ministers and people,
and yet they may not have it in reality?
This indeed is a great point, and highly necessary to be searched into,
which is to be known by our Lord`'s rule, prescribed for that end.
"`Do men,`" saith he, "`gather grapes of thorns, or figs of thistles V Surely no.
The grape is gathered from the vine, and the fig from the fig tree.
"`Wherefore by their fruits ye shall know them.`"
Now those who have the Spirit, or Holy Ghost, bring forth the fruits of it:
which fruits are love, charity, meekness, temperance, patience, experience, hope,
faith and wisdom from above, which is pure and peaceable, gentle,
and easy to be entreated, to all and everything that is good.
And those who have the holy Spirit,
bring forth the fruits of it as naturally as the vine doth the grape,
or the fig tree the fig.
Also, whatsoever things are holy, just, honest, pure, and of good report,
or tend to piety or virtue: in a word, everything that is good,
is the fruit of the Spirit of God and Christ:
and they are brought forth with divine life and power in that minister and people,
who through true faith in the blessed Jesus, have received the gift of the Holy Ghost,
or Spirit of Christ.

The minister of the gospel being thus fitly furnished to every good word and work,
is ready to answer the call of his great Lord and Master, who is in heaven;
he wants not the call of man, nor authority from man, nor wages of man.
But those who bring forth fruits contrary to the above, can neither be true ministers,
nor Christians, according to the doctrine of our holy Lord.
Being thus qualified by the Most High,
those ministers are freely given up to serve the Lord,
and go wheresoever he is pleased to send them, though he send them as sheep among wolves:
and it is worth noting,
that Christ`'s messengers and ministers are called and sent of him;
they do not run of themselves, nor in their will; which if they did,
their end would be like the forward false prophets of old,
who did not profit the people at all.

Our Lord seeing what need the world had of true teaching, and true teachers,
sends his ministers forth into it, saying,
"`All power is given unto me in heaven and in earth,
go ye therefore and teach all nations, baptizing them in the name of the Father,
and of the Son, and of the Holy Ghost:
teaching them to observe all things whatsoever I have commanded you: and lo,
I am with you always, even unto the end of the world.`"

Here Christ shows his ministers his power, and sends them forth in his own name,
for there is none other given under heaven for salvation;
and Christ comforts his ministers with a glorious promise,
of being with them to the end of the world.
Oh, the sweetness of this gracious promise! and such are all his promises,
for they are yea, and amen, forever.
Wherefore Christ`'s ministers may well go forth without doubting,
having their authority from the King of kings.
Again he saith, "`Go ye into all the world, and preach the gospel unto every creature.
He that believeth, and is baptized, shall be saved; but he that believeth not,
shall be damned.`"
Christ says, go; but the world, the flesh and the devil, say, stay;
for the spirit of sin and Satan is for obstructing the work of Christ,
and hindering the free gospel ministry,
and the motions of the word and testimony of Jesus;
and is for quenching it in those in whom it may appear.
It is a new mode or fashion, contrary to the primitive order of Christ,
for ministers to be tied to an outward benefit, or a particular meeting or congregation;
which way of preaching, or reading, reading being much in practice now,
is quite contrary to the call and practice of Christ and his ministers,
and of the martyrs, and confessors of Jesus;
as also of many of the most noted reformers in religion.
But it is objected, if ministers should always go about among the nations,
what would become of their families, or how must they live, and be maintained?
to which it may be answered,
that when the ministers of our Lord returned to their Master, he asked them,
"`If they lacked any thing?`"
they answered, "`No.`" But instead of lacking any thing, the devils were subject to them.
Pray, let the serious Christian consider, here is now a wonderful change.
Is it in Christ, or in the hireling, money-loving priest?
It is certainly in the man and not in Christ Jesus; for he is the same today, yesterday,
and forever.
Where the power of Christ rules,
there the devil and his power must of necessity be subject.

But some object, that people are not so free now;
were there not a law to maintain ministers,
the ministers might starve and perish in this generation; if so,
then their ministry must starve the people`'s souls.
But this thought of starving, is for want of the gift of God and power of Christ;
which power in the ministry would wonderfully open people`'s hearts towards God,
and those who are his true servants; who said, "`Freely ye have received, freely give.`"
Oh! faithless generation! what, shall we mistrust him who provides for all his creatures,
even the ravens and sparrows,
and will he not much more provide for his servants and ministers?
How shall we receive power from on high, if we want faith,
and cannot depend on the providential hand of God?

Christ sends his ministers into the world, in order to propagate his gospel of salvation,
and to let the world know that he is come to put
an end to sin and bring life and peace to the soul,
according to the angel`'s testimony of him,
that "`His name shall be called Jesus,`" which is a Saviour,
"`for he shall save his people from their sins.`"
The apostles of Christ also, according to their holy commission, declared,
that "`God hath sent his Son to bless us, in turning us from the evil of our ways.`"
But that doctrine must certainly be opposite to this
of the angels of Christ and of his disciples,
which teacheth that we must live in sin while on this side the grave,
and that there is no being free from it while we are in the world;
though Christ himself came for that very purpose, to put an end to it,
to save us from it, and to bring into the world everlasting righteousness;
as is that doctrine which maintains that no perfection can be attained to in this life;
though Christ says, "`Be ye perfect,
as your Father who is in heaven is perfect;`" as he is perfect in fulness,
so are we to be perfect, according to the measure of grace received.
This faith and belief is much wanting in this unbelieving generation,
which is the reason that people remain in their sins,
and their leaders cause them to err, and their ministers minister in their sin,
and minister sin to the people.

Oh! that the great Lord of all may grant the faith which purifies the heart,
unto the children of men, and especially to his ministers,
that they might be instrumental to convince and convert souls to Christ,
and his "`Gospel, which is the power of God to salvation, to all them that believe.`"
And as without believing and being baptized, we can neither be saved,
nor truly preach the gospel, how do we believe in Christ if we remain in our sins?
For Christ saith, "`If ye believe not that I am he, ye shall die in your sins.`"
So it is plain, that the true faith and belief in Christ taketh away our sins,
and that if we remain in our sins, we have not the true faith of Christ.

It is not enough to have a notional or historical
faith or belief that Christ is the Son of God,
but we must also believe, as the angel declared,
"`This is he that shall save his people from their sins.`"
This was before he was born of the holy Virgin;
and those people mightily mistake the doctrine of Christ in the holy Scriptures,
who think or believe they shall be saved in their sins;
and those ministers must needs be antichristian, who preach and write,
that there can be no living in this world without sin,
which is also contrary to their own doctrine at other times,
and to their solemn covenant in water baptism, or sprinkling,
in which they promise for their children,
"`To forsake the devil and all his works;`" and no
Christian can pretend to greater or higher perfection,
than to forsake the devil and all his works, "`the pomp and vanity of this wicked world,
and all the sinful lusts of the flesh, and to keep God`'s holy will and commandments,
and to walk in the same all the days of our lives.`"
According to this solemn covenant, there is no day for sin;
yet those covenanters at other times will say,
that the best saints cannot live without sin, and that people sin in their best duties.
If any think to mock the Almighty after that manner,
they will be much mistaken in the day of the righteous judgment of God:
for "`Christ came to put an end to sin, and to finish transgression,
and to destroy the works of the devil,`" which all sin most certainly is.
It is plain, that John, the beloved disciple of Christ, believed this,
from his own words; "`I write unto you, young men,
because ye have overcome the wicked one.
I have written unto you, young men, because ye are strong,
and the word of God abideth in you, and ye have overcome the wicked one.`"

To the church of Ephesus, he writes, "`He that hath an ear,
let him hear what the Spirit saith unto the churches: to him that overcometh,
will I give to eat of the tree of life, which is in the midst of the paradise of God.`"

To the church of Smyrna.
"`He that hath an ear, let him hear what the Spirit saith unto the churches:
he that overcometh shall not be hurt of the second death.`"
To the church of Pergamos.
"`He that hath an ear, let him hear what the Spirit saith unto the churches:
to him that overcometh, will I give to eat of the hidden manna,
and will give him a white stone, and in it a new name written, which no man knoweth,
save him that receiveth it.`"
To the church of Thyatira.
"`He that overcometh and keepeth my works unto the end,
to him will I give power over the nations: and he shall rule them with a rod of iron;
as the vessels of a potter shall they be broken to shivers:
even as I received of my Father.
And I will give him the morning star.
He that hath an ear let him hear what the Spirit saith unto the churches.`"
To the church of Sardis, "`He that overcometh,
the same shall be clothed in white raiment;
and I will not blot out his name out of the book of life;
but I will confess his name before my Father, and before his angels.`"
To the church of Philadelphia.
"`He that overcometh will I make a pillar in the temple of my God,
and he shall go no more out: and I will write upon him the name of my God,
and the name of the city of my God, which is New Jerusalem,
which cometh down out of heaven from my God: and I will write upon him my new name.`"
To the church of Laodicea.
"`To him that overcometh will I grant to sit with me in my throne,
even as I also overcame, and am set down with my Father in his throne.`"

Surely that soul who cannot by all this see that there is an overcoming,
must certainly be blind, as to a spiritual sight of the doctrine of Christ;
and what is it but to make Christ and the Holy Spirit a deceiver,
to promise all those great things to his churches,
if they cannot perform the condition he prescribes.
If it were true, as it is not, that it is impossible to overcome sin and Satan,
then would Christ be a hard master, which is absurd and wicked to suggest.
But this overcoming cannot be in our own wills, nor in our own time,
nor with our own weapons,
but according to the apostle Paul`'s testimony of the saints`' weapons,
and their warfare, and also of his own fight and victory, viz:
"`The weapons of our warfare are not carnal, but mighty, through God,
to the pulling down of strong holds.`"
Satan`'s holds of sin are strong ones, if never to be overcome.

With these weapons we may overcome: and he bids the Christian put them on,
and calls them the whole armour of light; opposite and contrary to Satan`'s dark power,
and he names them after this manner: "`Stand therefore,
having your loins girt about with truth, and having on the breastplate of righteousness,
and your feet shod with the preparation of the gospel of peace;
above all taking the shield of faith,
wherewith ye shall be able to quench all the fiery darts of the wicked:
and take the helmet of salvation, and the sword of the spirit,
which is the word of God.`"
"`I have fought a good fight, I have finished my course, I have kept the faith,
henceforth there is laid up for me a crown of righteousness; which the Lord,
the righteous Judge, shall give to me at that day, and not to me only,
but to all them who love his appearing.`"

Thus the saints and primitive Christians were victorious
in this Christian and spiritual warfare,
and they encouraged others to follow them, as they did Christ.
The very belief of this doctrine, that we can never overcome sin and Satan,
is contrary to the faith of Christ,
and is a mighty engine of the wicked one to destroy souls.
For what encouragement have any to the work of reformation, or to believe in,
or press after the new birth, if they do not believe in the new birth,
or that they can be created anew in Christ Jesus, unto good works,
and that they must not walk after the flesh, to fulfill the lusts thereof.

Oh! that ministers and people would consider that awful sentence of holy Scripture,
"`If ye live after the flesh, ye shall die; but if ye, through the Spirit,
do mortify the deeds of the body, ye shall live.`"
The want of a lively hope and faith in Christ, the Lord of heaven and earth,
is great indeed.
Oh! that true faith in him might increase in the earth more and more!
Then would he inspire the soul with inward strength and grace to resist the devil,
and overcome him, and actually to do the works of God,
and to forsake the devil and all his works; then, and not until then,
is Christ`'s righteousness imputed to us; so that true Christians are truly righteous,
not only by imputation, but by action also.
Oh! that those who make profession of the name of the holy Jesus, would deny themselves,
and take up their daily cross, and follow him in the regeneration! otherwise,
how can they be his disciples or ministers?
And then would true Christianity flourish in the earth;
then would Christ be exalted over all, who, with the Father and holy Spirit,
is God blessed forever.

To return a little to Christ`'s baptism, viz: "`He that believeth and is baptized,
shall be saved.`"
Here our great baptizer and chief minister, is positive,
that they shall be saved who are baptized with his baptism; from which,
with strong reason, we may conclude,
that the baptism which is absolutely necessary to salvation, is not water baptism,
which was John`'s, but spiritual baptism, which is Christ`'s; and for this reason also,
that most Christians who have any spiritual understanding, do plainly see,
that notwithstanding people are baptized, or sprinkled with elementary water,
many live wicked, ungodly lives, and die in that state.
But quite the contrary effect hath that baptism which
is of the Holy Ghost and spiritual fire,
which is Christ`'s baptism; for that where it is witnessed,
and where people not only talk of it,
but live according to its holy operation on the soul,
saves and cleanses from sin and evil, and washes by regeneration,
and renews the soul by grace, with divine life and power.

The call of a true minister, is from and by Christ; he must come to the school of Christ,
and take his degrees there;
in the universal love of God he must learn and experience patience, humility, faith,
hope, and charity; "`Learn of me,`" saith he, "`for I am meek and lowly in heart.`"
Notwithstanding he was the heir of all things,
and all power in heaven and earth was given unto him,
he humbled himself to the death of the cross, for the sake of mankind;
and as the living Father sent his Son,
so the Son sends his servants contrary to the will of man, as the apostle Paul said;
"`But I certify unto you, brethren, that the gospel which was preached of me,
is not after man; for I neither received it of man,
nor was I taught it but by the revelation of Jesus Christ.`"
Hereby it is plain he thought there was no absolute necessity of outward learning,
or outward call by man.

And as there is no absolute necessity of outward learning to make a minister of Christ,
so there is no need to force an outward maintenance;
for Christ will take care of his servants, and feed and clothe them, when he sends them,
as he did his disciples, who went forth without staff or scrip, yet acknowledged,
after their return, that they lacked nothing.
As Christ said, "`Freely ye have received,
freely give;`" so there is no outward compulsion or force in Christ`'s doctrine or religion.
Some are indeed of another opinion, and have practised the contrary,
and bring those words of Christ to uphold them in the practice of forcing religion,
where he says in the parable of the marriage supper, "`Go,
compel them to come in;`" which was no other compulsion or force but that of love,
which is the greatest power in heaven or earth:
to construe our Saviour`'s words in any other sense, would be absurd,
and contrary to the whole tenor and doctrine of his holy ministry.

Thus then the work of Christ`'s ministers is to bring the people to Christ,
as he is their Redeemer and Saviour from sin,
and as he is their comforter and good remembrancer,
and their spiritual guide into all truth, in the performance of which work,
they will have their reward in this world, and in the world to come, everlasting life.
Amen.

[.asterism]
'''
