== Concerning Personal Election and Reprobation.

A concern came upon me, in Christian love to the honest-hearted of the Presbyterian way,
to show them how their teachers have misled them, and misrepresented the words of God,
in pretending to prove the doctrine they hold of personal election and reprobation,
and in wresting the Scriptures in support of it.

Some of the texts of Scripture whereby they vainly endeavour to defend it,
whereupon they chiefly found their tenet, are these, viz:

Concerning Jacob and Esau, and the Lord`'s hardening Pharaoh`'s heart.
"`He that made them, will not have mercy upon them, and he that formed them,
will show them no favour.`"
"`Hath not the potter power over the clay of the same lump,
to make one vessel to honour and another to dishonour?`"
"`Therefore he hath mercy on whom he will have mercy, and whom he will he hardeneth.`"

Relating to Jacob and Esau, the case was thus: the Almighty showed Rebecca,
the mother of them both, while the children were yet unborn,
that the elder should serve the younger.
Not that the elder should be damned to eternity, and the younger only saved,
as it is hoped will appear clear in the sequel, and the contrary be plainly proved,
both by Scripture and right reason.
Jacob and Esau, were the sons of godly Isaac, to whom, with faithful Abraham,
was the promise of God, and to their seed,
and both Jacob and Esau were blessed in the name of God, and in his faith also:
"`For,`" saith the author of the Hebrews, "`Isaac blessed Jacob and Esau by faith.`"
This he wrote when he was illustrating the power of faith,
by many wonderful works which had been done thereby;
and doubtless the faith there spoken of, is the true faith;
and whatever is foretold through true faith will most certainly be fulfilled,
as this significant blessing of Isaac to his sons was.
The good old man calls his eldest son to him, being disposed to bless him,
and bids him seek venison, and make him savoury meat, such as he knew his father loved,
"`that my soul may bless thee before I die;`" and Rebecca, their mother, knowing,
from what God had shown her before they were born,
that the elder should serve the younger, for whom she had the greatest love;
she calls Jacob and opens the matter to him,
and bids him get savoury meat for his father, which, through her importunity he did.
After he had prepared it, he brought it to his father before his brother came,
and his father blessed him in faith, but he did it against his natural inclination;
for he would have had his son Esau to have had the blessing of preference,
because he was the eldest son, and by nature it was his birth-right; but he,
in his profane state and condition,
had despised it and sold it to his brother Jacob for a thing of little value;
so that Jacob, having, by his brother`'s consent, bought it of him,
had a right to it on a double account, both by the promise of God before he was born,
and by purchase from his brother.
But let it be observed, this was the blessing of preference only,
that blessing which Esau sought with tears, but could not find;
nevertheless he had a blessing pronounced upon him by his father, through faith,
though he does not seem to have had a right sense thereof,
for he was at times in a profane spirit,
and in enmity and malice against his brother Jacob, as appears by that murdering,
persecuting mind, that then was unmortified in him; "`For,`" says he,
"`the days of mourning for my father are at hand,
and then I will slay my brother Jacob.`"
But as his wickedness was great, his conversion must be so much the more glorious.
It would be well if all murdering persecutors would, in his conversion,
take him for an example; for instead of killing his brother,
when he met him on his return to his father`'s house, from whence he had fled,
he fell on his neck and kissed him, and wept.

It is hoped that no Christian will be offended to hear of
the conversion and great change of this profane person,
who, though he was not favoured with the blessing of preference,
or the natural blessing of birth-right, which he sought with tears, and could not find,
yet the blessing of God`'s grace and favour, being the free gift of the Almighty to him,
with the fatness of the earth, he had,
and it was delivered to him by his father by faith, as saith the apostle,
in the afore-cited epistle to the Hebrews,
which blessing was by their father Isaac thus expressed to each of them.
First, to Jacob,
"`That the purpose of God according to election might stand;`" which choice or election,
before they were born, or had done good or evil, was,
"`that the elder should serve the younger,`" or the
younger be preferred before the elder;
not that one should be damned, and the other saved; there is no damnation to eternity,
that we read of concerning Esau, but a choice blessing of God,
of a quite different nature.
Unto Jacob he said thus; "`God give thee of the dew of heaven,
and the fatness of the earth, and plenty of corn and wine, be lord over thy brethren,
and let thy mother`'s sons bow down to thee,`" etc.
And unto Esau he says, "`Behold thy dwelling shall be of the fatness of the earth,
and of the dew of heaven from above, and by thy sword shalt thou live,
and shalt serve thy brother; and it shall come to pass,
when thou shalt have the dominion, that thou shalt break his yoke from off thy neck.`"

These blessings have not only respect to their own proper persons,
but also to their posterity; but are far from pre-ordaining them,
or any of them to damnation; and we have good ground from what is above,
together with the reformation wrought in Esau himself,
to believe much better things of him; for it is written,
"`When the wicked man turneth away from his wickedness which he hath committed,
and doth that which is lawful and right, he shall save his soul alive.
So when a righteous man turneth away from his righteousness, and committeth iniquity,
and dieth in it, for his iniquity which he hath done shall he die.`"

Having thus far taken notice of the purport of the blessings of Jacob and Esau,
relating to their persons; who were both blessed with the dew of heaven,
and the fatness of the earth, I would add this remark,
"`Let none curse him or them whom God hath blessed.`"

And whereas the apostle, reciting the words of the prophet Malachi, saith,
"`Jacob have I loved,
but Esau have I hated;`" this was not said of them before they were born,
or had done either good or evil;
but was justly denounced by the Almighty for the cruelty
and hatred of the children of Esau to the children of Israel,
as is fully and clearly expressed by the prophets, David, Ezekiel, Amos, and Obadiah;
and was written many ages after.

[.numbered-group]
====

[.numbered]
_Second;_ The next text under consideration is,
"`That the Lord hardened the heart of Pharaoh.`"
But it should be observed, he had first hardened himself against God and his people,
and then God hardened him yet harder, in order to show his great power to mortals,
which well consisted with his justice to the wicked and unmerciful;
for as God is merciful to the righteous, so is he just in his judgment to the ungodly.

So that God was clear of that evil heart of unbelief in him, and it is but just,
and also reasonable, that when man, having been often visited,
refuseth the offers of God`'s love, he should visit such with his righteous judgment,
who have slighted his mercy and grace.
And then, according to the holy Scripture, "`His destruction is of himself,
but his help is in the Lord.`"
So that "`God is true, and every man contradicting him is a bar.`"

Wherefore may all have a care of hardening their hearts as Pharaoh did,
for that is provoking the Almighty,
and then he justly gives them over to an evil heart of unbelief, and to a reprobate mind,
in departing from the living God.
The Lord saith unto Pharaoh, "`Let my people go,`" over and over,
and it was the mind of God he should have done it:
without those men who hold the contrary,
would make the Almighty such an one as themselves, to say one thing, and mean another.
What is that but to charge the Almighty with hypocrisy?
a thing hated of him, and his dear Son, Christ Jesus.
Pharaoh might have obeyed the Lord in a day of visitation: but he refused, and said,
"`Who is the Lord, that I should obey his voice, to let Israel go?
I know not the Lord, neither will I let Israel go.`"
And he continued to harden himself against God and his people, cruelly persecuting them,
and forcing them to make bricks without straw,
before we read that the Lord hardened his heart.
Oh! that all hard-hearted, persecuting, unbelieving people, might take warning by him,
before it be too late.

It is clear, he might have let the people go; because God by Moses commanded him so to do.
And who can deny, that what God did, was more proper to soften, than to harden his heart,
by letting him see the miracles wrought in his name,
and the ceasing of the plagues he had inflicted.
It was possible for him to do what God required of him;
he was not predestinated to that obduration, but he hardened his own heart;
and then it was, is, and always will be, just with God to suffer his,
or any other man`'s heart to become hardened, and give them up to a reprobate mind.

[.numbered]
_Third;_ The following Scripture is wrested, and falsely made use of, viz:
"`He that made them, will not have mercy on them; and he that formed them,
will show them no favour.`"
This text hath, in some of the writings of those that espouse the aforesaid doctrine,
been brought to vindicate that despairing, destructive, evil principle,
of the pre-ordination of particular persons to destruction and damnation: but this text,
with the rest brought for that end, is grossly perverted;
for in the same place the case is fairly stated, and the reason clearly shown,
why God will show them no favour, viz: "`Because they were withered branches,
and people of no understanding; therefore he that made them,
would not have mercy upon them, and he that formed them, would show them no favour.`"
From whence it appears they might have been fruitful, but would not, and had been green,
but were withered from their greenness; much like those whom Christ expostulates with,
when he says,
"`How often would I have gathered you as a hen gathereth her chickens under her wings,
and ye would not.`"
"`If thou hadst known, in this thy day, the things which belong to thy peace,
but now they are hid from thine eyes.`"
Which shows the great and fervent desire of Christ to save souls,
and his tender love to poor mortals, and that they had a day of visitation,
in which they might have been gathered,
which is far from ordaining them to destruction from all eternity.

God is fully clear of all men, and their blood is on their own heads,
and their destruction is of themselves;
whereas they might have help in the Lord and his Christ, through faith,
which he offers to man freely; but man will not receive or embrace it.
And further, it should be observed, that if the whole texts of the prophecy of Isaiah,
in his thirty-seventh chapter be considered, it will plainly appear,
that he is so far from uttering an express or positive decree of their final destruction,
that he clearly and fully foretells their recovery and restoration out of that state.

[.numbered]
_Fourth;_ They argue from the words of the apostle,
"`Hath not the potter power over the clay, to make of the same lump one vessel to honour,
and another to dishonour?`"
Yes, doubtless he hath; but the potter doth not make vessels with design to destroy them,
or to break them to pieces, but for use and service;
and it is contrary to his will and interest, when a vessel is marred under his hand.
And it is very plainly expressed by the prophet Jeremiah,
after mentioning his beholding the work of the potter, "`Oh, house of Israel,
cannot I do with you as this potter?
saith the Lord.
Behold as the clay is in the potter`'s hand, so are ye in my hand.
Oh, house of Israel!
At what instant I shall speak concerning a nation, and concerning a kingdom,
to pluck up and to pull down, and to destroy it;
if that nation against whom I have pronounced, turn from their evil,
I will repent of the evil that I thought to do unto them.`"
All which is contrary to the doctrine of an absolute and unconditional predestination.
The Lord in his wisdom, and to show his power, doth make souls more or less honourable,
as he pleaseth; but it is very plain, from Scripture and right reason,
that he makes none with a design to destroy them,
nor hath he ordained any to eternal damnation.
Though he hath ordained damnation for wicked and ungodly men,
yet he never ordained that men should be wicked and ungodly.

[.numbered]
_Fifth;_ They urge the apostle`'s words, but to as little purpose as the former,
"`He will have mercy on whom he will have mercy, and whom he will he hardeneth.`"
It is true, that God hath abundantly shown us, in the holy Scriptures,
on whom he will have mercy, viz: He hath mercy on the poor in spirit;
the humble he teaches of his ways; the meek he guides in judgment;
he clothes the meek with salvation; he hath the righteous in everlasting remembrance;
he loveth them who love him; he saveth them who love his dear Son, and believe in him;
he giveth to them eternal life, and Christ loveth them,
and manifesteth himself unto them.
And his beloved disciple John declared, "`If any man sin,
we have an advocate with the Father, Jesus Christ, the righteous;
and he is the propitiation for our sins, and not for ours only,
but also for the sins of the whole world.`"
And the author of the Epistle to the Hebrews, saith, "`But we see Jesus,
who was made a little lower than the angels, for the suffering of death,
crowned with glory and honour, that he, by the grace of God,
should taste death for every man.`"
And all who believe in, and obey him,
will partake of the benefit of his death and suffering;
"`But the wicked is snared in the work of his own hands.`"

====

It has been in my mind for some years,
to show the weakness of some of what are called the proofs, for this, as I take it,
corrupt and dangerous doctrine, and the misapplication of those texts of Scripture,
which are advanced to maintain this absurd notion,
of souls being fore-ordained to damnation eternally, whether they do good or evil,
and that it is so determined before we are born into the world.

Oh! that people might come to true repentance,
and lay hold of the universal love of God to eternal life,
through the living faith of Jesus Christ our Lord, in whose tender love to all,
are these lines written,
and in great good will they are invited to search the Scriptures,
and to see whether the whole scope of them do not show the contrary
to what they hold in relation to personal reprobation to destruction,
fore-ordained before we are born, or have done either good or evil;
there not being one text to be found to prove that doctrine.
But there are abundance which set forth the love, mercy, and goodness of God to mankind;
only two of which I shall add hereunto, viz:
"`And God saw that the wickedness of man was great in the earth,
and that every imagination of the thoughts of his heart, was only evil continually.
And it repented the Lord that he had made man on the earth,
and it grieved him at his heart.`"
"`And Jonah arose, and went unto Nineveh, according to the word of the Lord,
and entered and said, Yet forty days, and Nineveh shall be overthrown.
So the people of Nineveh believed God, and proclaimed a fast, and put on sackcloth,
from the greatest of them, even to the least of them.
And God saw their works, that they returned from their evil way,
and God repented of the evil that he had said he would do unto them, and he did it not.`"
I heartily desire that these two texts may be duly considered and weighed;
therein the mercy, lovingkindness, and long forbearance of God,
being so clearly and fully manifested,
that I think it may be sufficient to convince every unprejudiced mind
of the error of believing the absolute predestination by the Almighty,
of any part of mankind to destruction.

[.signed-section-signature]
Thomas Chalkley.

[.asterism]
'''
